### ISSUE TITLE
external Display Connection randomly Disconnect

### ISSUE THREAD

**Issue by Delikt** [ValveSoftware/SteamOS#1009]
#### Your system information

* Steam client version:
* 16080827821
* SteamOS version: 
* 3.4.6 Build 20230302.1
* Opted into Steam client beta?: [Yes/No] 
* Yes - Preview Channel
* Opted into SteamOS beta?: [Yes/No] 
* Yes
* Have you checked for updates in Settings > System?: [Yes/No]
Yes - Always Up-to-Date 

#### Please describe your issue in as much detail as possible:
Since i got my SteamDeck i always have Problems with my external Display Connection. The Connection always disconnecting randomly while i playing or/and i cant even establish an Connection after Reboot/Wake on. This seems to me so randomly i cant figure out where the Problem is. I use a USB-C Dock (DockTeck Model DD0008 - https://www.amazon.de/Multiport-60Hz-MacBook-Adapter-Dockteck-Schwarz/dp/B08SM393WB), an not cheap HDMI Cable (1 meter) with Ethernet and have a 4k Resolution Display (This Display shows the Resolution what it get but it cant config a permanently  fixed resolution to Display on its own). This Error is very very very annoying for me! 

#### Steps for reproducing this issue:

1. Reboot/Wake Up Steam Deck -> No Display Connection
2. Disconnect USB-C Adapter from SteamDeck and plug it in again -> Sometimes work
3. Reboot SteamDeck -> Sometimes work 
4. Disconnect HDMI Cable from Dock or from TV and Plug it in again -> Sometimes work
5. Just make sure the Plugs are "good" Connected and play around a bit -> Sometimes work
6. Restart Steam Client -> Sometimes Work
7. Then at one Point (if you have done all try around Things above -> the Connection seems to work for now 
8.  But then after some Time (minutes or sometimes some hours) it starts while playing to randomly Disconnect and Connect again immediately or/and after some short Disconnects the Connection get lost and you can reproduce Step 1-7 to get it to work again 
9.  This behavior starts in 3 from 5 Times i want to play with my SteamDeck -> Rarely it work without Problem.
10.  This behavior is in Steam Gamemode Menue or Ingame (its not just Proton, its everywhere)  

In Step 9 i mentioned, its not always but at the most Time - So i don't think its TV, Cable or USB-C Dock related.

If you need more Information from me, no Problem i watching this Issue carefully cause i finaly hope for a resolution.

**Comment by Delikt** [comment]
Here is a Video: What i need to to every Time to Play on my external Display with the Steam Deck
[Peertube Link](https://tube.tchncs.de/w/21QHkUqhd2QWK7F7zj4hZE)

**Comment by devincurrie** [comment]
> Here is a Video: What i need to to every Time to Play on my external Display with the Steam Deck [Peertube Link](https://tube.tchncs.de/w/21QHkUqhd2QWK7F7zj4hZE)

The Peertube link is broken. Please update your post with a working link? Thanks.

**Comment by Delikt** [comment]
Thanks for reply, this Issue is fixed.. it wasn't related to the Steamdeck, its was all the HDMI females on my TV, which had a bad connection cause  a lack of quality in Manufacturing i think.
