### ISSUE TITLE
Low Battery notification not triggering at 10% or 5% while user is in-game

### ISSUE THREAD

**Issue by s-law** [ValveSoftware/SteamOS#1010]
#### Your system information

* Steam client version: 6 April (beta)
* SteamOS version: 3.4.6
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
**Expected:** When battery level has dropped to 10% a notification should appear, alerting the user that the battery level is at 10%. Another alert should appear when the battery level is at 5%. These alerts should appear whether or not the user is in a game when those battery levels are reached.
**Observed:** No notification appears at 10% or 5% when the Steam Deck has reached the 10% or 5% battery level when the user is in-game.

#### Steps for reproducing this issue:
1. Charge Steam Deck to 100% and unplug charging cable.
2. Launch game.
3. Keep Steam Deck active until battery level has dropped to 10% and 5%.

**Comment by AlexelTech** [comment]
I have exactly the same problem since the last update, it is very annoying and I found no solution until now... except an update correcting this newly introduced bug !

**Comment by s-law** [comment]
Yep, the patch notes for the latest beta specifically calls out the fix for the toasts. I’ll go ahead and close the issue.

**Comment by MrFixite** [comment]
I had it do this to me twice in Subnautica below zero. Was in the zone and lost like 2 hrs progress.
