### ISSUE TITLE
Unable to Change Language in Desktop Mode

### ISSUE THREAD

**Issue by NightHammer1000** [ValveSoftware/SteamOS#1016]
#### Your system information

* Steam client version: 1681864962
* SteamOS version: 3.5 20230420.1000
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
There is still the Huge Issue that SteamOS still does not offer another Language than English for the Desktop Mode, effectively locking out everyone who's English is not up to par from a sometimes Important Half of the Device. A massive Issue, especially in Asian Countries

Changing Regional Settings to Match the Local Area, like Number, Time and Date formats actually causes issues for programs as the locale files are actually missing.
A lot of us do not like being forced to use AM/PM and Inches. Especially since those are rarely taught outside the US.

The Issue here
https://github.com/ValveSoftware/SteamOS/issues/794?notification_referrer_id=NT_kwDOAB4zcrIzNzU2MDE3NjMxOjE5NzkyNTA#issuecomment-1518714635
Is tracked as for "Games Only" so here is the "General Usage" Issue. There it was argued that the locales for the System would use to much space. I am 100% Confident nobody would bat an eye if they loose 500MB if it meant they can use their Device FULLY.

#### Steps for reproducing this issue:

1.  Go to Desktop
2.  Go to Settings
3.  Go to Regional Settings
4.  See that you are actually forced to English.

#### Possible Solution for this issue:
1. Ship the locales outright
2. Give the User the Option to also download, install and generate the locales for their chosen Language while choosing the Language in the First Time Setup OOBE

**Comment by kisak-valve** [comment]
Hello @NightHammer1000, this issue is already being tracked at #816. Closing as a duplicate.
