### ISSUE TITLE
[Feature Request] Use both triggers on single axis

### ISSUE THREAD

**Issue by enTyoiable** [ValveSoftware/SteamOS#1023]
#### Your system information

* Steam client version: 1682708537
* SteamOS version: 3.4.6
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Currently the triggers L2 and R2 are reported in games as two separate axis, both seem to range from 0 to a positive value.

In flight- and space sims the YAW (rudder) and ROLL (aileron) axis are usually bound to a single axis. Where value 0 equals no movement, negative is movement to the left and positive movement to the right (or vice versa/inverted). Because currently the triggers are reconised as seperate axis, only a single trigger can be bound to the yaw and/or roll axis. This results in movement in a single direction only. 

A possibility to bind both triggers to a single axis, where the left trigger produces a value from 0 to -27500 (or whatever needed value) and the right trigger produces 0 to +27500 (or whatever needed value) would solve this. Or perhaps be able for the user to invert a trigger action, so both triggers can be bound to the left trigger output, but one of the triggers reports the negative value, the other the positive.

**Comment by kisak-valve** [comment]
Hello @enTyoiable, this is a feature request for the Steam Input sub-component of the Steam client, not SteamOS as a platform.

It looks like https://github.com/ValveSoftware/steam-for-linux/issues/3495 is already tracking this feature request. Closing as a duplicate.
