### ISSUE TITLE
Sharing non-steam layouts with community broken

### ISSUE THREAD

**Issue by cpelley** [ValveSoftware/SteamOS#1030]
#### Your system information

* Steam client version: 1682708537
* SteamOS version: 3.4.6
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

I create a layout for my non-steam game then share it with the community.  This correctly appears under the 'community' tab for me.
From my wife's steam deck for the same non-steam game with identical name, the community tab doesn't contain my community shared layout.

Appears not limited to just a single game.

#### Steps for reproducing this issue:

1. Create layout for non-steam game from steam deck 1.
2. Share layout with community from steam deck 1.
3. Change layout for the non-steam game from steam deck 2, browsing the community layouts but not finding the layout.

**Comment by kisak-valve** [comment]
Hello @cpelley, managing and sharing of controller layouts is handled by the Steam client. This reads like the issue being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/8583.

Closing as a duplicate.
