### ISSUE TITLE
Unable to "Open Folder" on certain flatpaks

### ISSUE THREAD

**Issue by al12gamer** [ValveSoftware/SteamOS#1052]
#### Your system information

* Steam client version: 1685664179
* SteamOS version: 3.4.8 Stable
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No]
Yes
#### Please describe your issue in as much detail as possible:
Expected functionality: 

1. Turn on Steam Deck
2. Power -> Desktop Mode
3. Open Yuzu
4. File -> Open Yuzu Folder
5. XDG Desktop portal opens up the Yuzu folder

Current functionality:

1. Turn on Deck
2. Power -> Desktop mode
3. Open Yuzu
4. File -> Open Yuzu Folder
5. Nothing happens

**Comment by al12gamer** [comment]
Further information when running the flatpak via Konsole with --debug appended:
```
(deck@gabegear ~)$ flatpak run org.yuzu_emu.yuzu --debug
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
```

**Comment by al12gamer** [comment]
Wonder if a recent flatpak update is having issues with d-bus things...

**Comment by bertogg** [comment]
> kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"

Hi,

some people have reported crashes in UDisks, maybe this is the cause of the problem that you're experiencing.

The next stable version of the OS will ship an updated package, so hopefully this will solve the problem.

**Comment by bertogg** [comment]
There is one thing that you can test. When you have that problem open a terminal and type this:

```
$ cat /proc/$(pgrep -fx /usr/lib/xdg-desktop-portal)/environ | tr '\0' '\n' | grep XAUTHORITY
$ echo $XAUTHORITY 
```
Do both commands show the same value?

**Comment by al12gamer** [comment]
Hmm yes those look similar. Odd.
https://asciinema.org/a/590670

**Comment by al12gamer** [comment]
Some more info
```
(127)(deck@gabegear ~)$ systemctl --user status xdg-desktop-portal.service 
● xdg-desktop-portal.service - Portal service
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal.service; static)
     Active: active (running) since Fri 2023-06-09 13:13:37 MDT; 27min ago
   Main PID: 5641 (xdg-desktop-por)
      Tasks: 6 (limit: 14057)
     Memory: 6.1M
        CPU: 358ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/xdg-desktop-portal.service
             └─5641 /usr/lib/xdg-desktop-portal

Jun 09 13:13:37 gabegear systemd[1092]: Starting Portal service...
Jun 09 13:13:37 gabegear systemd[1092]: Started Portal service.
(deck@gabegear ~)$ pgrep -ax gamescope
(1)(deck@gabegear ~)$ 
```

**Comment by al12gamer** [comment]
I'm no longer experiencing this issue, we can go ahead and close this.
