### ISSUE TITLE
[Feature Request] Nix Packages Support

### ISSUE THREAD

**Issue by vitormmatos** [ValveSoftware/SteamOS#1063]
As an immutable linux distro, a nice way to give users a great number of packages without root access would be supporting nix packages.

VanillaOS also made it possible:
https://vanillaos.org/2023/02/07/apx-now-supports-nix-packages.html

**Comment by kisak-valve** [comment]
Hello @vitormmatos, as a vague and SteamOS specific modification, this doesn't sound particularly interesting to implement and maintain over an extended period of time.

Instead, you should push for upstream Arch to wire up the functionality you're looking for, and after that, come back here with specific adjustments that are required to go along with enabling this, then give me a ping to re-open this feature request for a SteamOS maintainer to evaluate.

**Comment by bertogg** [comment]
Note that you can already install Nix manually using their official installer: https://nixos.org/download.html

**Comment by al12gamer** [comment]
Just to note, no you can not install Nix manually. I ran into some problems running that here https://github.com/al12gamer/deckscript/pull/15#issuecomment-1629776611
Also, any future SteamOS image updates will likely kill the Nix directory, even if you disable steamos read-only for it.

**Comment by bertogg** [comment]
That looks like a project to install a different OS on the Steam Deck and is therefore a bit out of the scope of this issue tracker :slightly_smiling_face:
