### ISSUE TITLE
Formatting drives failing

### ISSUE THREAD

**Issue by Spidy123222** [ValveSoftware/SteamOS#1064]
On 3.5 from main branch, I cannot format my brand new microSD card as if fails. Going into desktop mode and into the kde partitioned and removing everything off drive again and doing a ext4 partition fixes problem. With past versions it was able to format microSD cards to be usable. 

But even then permissions on the microsd card isn't consistent if using dolphin explorer in sub folders. Manually formatting ext4 to microSD had drive be ownership to root and took changing owner and group to fix the permission issue. This permission issue happens on 3.5 when formatting also if it completes.

All you need to do is have a brand new drive and format in settings in system and click format SD card

**Comment by bertogg** [comment]
What is the error that you see when it fails?

(the permission thing is a known issue in the main branch)

**Comment by Spidy123222** [comment]
> What is the error that you see when it fails?
> 
> 
> 
> (the permission thing is a known issue in the main branch)

It only just says it failed to format micro sd card and to try again later. I don't remember what specific number it is. I formatted manually and I'd rather not reformat to just find out. It was a brand new silicon power 512gb. https://www.amazon.com/Silicon-Power-Superior-Compatible-MicroSD/dp/B093H6NXBD/?_encoding=UTF8&pf_rd_p=19b8eca5-5bed-40fc-8d45-24e9a155247a&pd_rd_wg=iFDGg&pf_rd_r=NGPH8PSBGJBC31PNDTNZ&content-id=amzn1.sym.19b8eca5-5bed-40fc-8d45-24e9a155247a&pd_rd_w=Um9Iu&painterId=gwm-asin-tile&pd_rd_r=5260ee52-4d18-4ab3-9bb4-e6bae733e888&ref_=pd_gwm_ci_mcx_mr_hp_atf_m

**Comment by Spidy123222** [comment]
> I did find an issue where the format script is not reliably detecting if an SD card is removable. The format script won't attempt to format a drive that it thinks is fixed, to help protect against formatting the main storage device on a system.
> 
> 
> 
> We can confirm if that's your issue by looking at the output from this:
> 
> 
> 
> ```
> 
> #!/bin/bash
> 
> shopt -s globstar
> 
> cat /sys/devices/**/block/sda/removable
> 
> ```
> 
> 
> 
> If it returns 0, then it means that the 'removable' bit isn't set correctly for your SD card. This seems to be a fairly common problem, about 1/4th of the SD cards I have tested so far don't seem to have this set correctly.

So it doesn't seem like it will even run the script. I'm on the latest version for 3.5. Whenever ran it gives this message. ![image](https://github.com/ValveSoftware/SteamOS/assets/64176728/603a532e-e88a-496b-9f6e-55b49376e14d)

So I decided to try changing ownership manually because it should allow me fine in that sd card and I come to find out my SD card was changed to be read Only file system like the main OS part so I can't really do much of anything. ![image](https://github.com/ValveSoftware/SteamOS/assets/64176728/bb2d2b18-5bf6-4c51-b1be-3c8f3e88ede3)

Seems like the system that manages the read only parts is getting to the micro SD card and changing permissions. Even using root I cannot change it. So I might have to either remove the read only or possibly downgrade my OS which makes stuff I use might not work as well.

**Comment by Spidy123222** [comment]
> You should be able to use the format drive option on the latest 3.5 main image, and it should be able to format your SD card correctly. Could you re-try that mechanism?

Still seems to not format right. This is kinda what was happening before. ![image](https://github.com/ValveSoftware/SteamOS/assets/64176728/11ccbf5a-e122-4cfe-ac95-ccdf6e9df32d)

After my previous manual fix for formatting I added data to sd card. So I backed it up and stuff and seems like it fails to format sd card still and all the data is still there so it doesn't seem like it tried. 

I tried the one line cli command before to check if it's removable it didn't work so I decided to find it myself and I found the removable file and it is set to 0. Is this possible that this also causes my microSD card to not get detected if I remove it and plug back in because it gets detected after a restart then.

**Comment by Spidy123222** [comment]
> @Spidy123222 I've been trying to reproduce this on the latest SteamOS 3.5 "main" image, and haven't been able to, the SD cards I've tried were all formatted successfully.
> 
> 
> 
> Could you please try the format again, and this time after it fails submit a Steam "System Report" ? You can do this under Settings->System->ADVANCED->System Report / Create Report. Post your steam account username here once you've done that so that it can be retrieved.

August 14th update some how fixed my issue. It's no longer even erroring which I find odd as there's no report even nearby about fixing it. Idk if it's something I fixed or what but I'll keep caution. My scaling is different on display so i will likely make a issue on that.

**Comment by bertogg** [comment]
Hello, is this working correctly now?

**Comment by Spidy123222** [comment]
> Hello, is this working correctly now?

Yes though was odd I updated to latest version of the time which has nothing fixed for microSD that it started working. I mentioned it in my last post.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
