### ISSUE TITLE
multiple microSD cards not showing up

### ISSUE THREAD

**Issue by Spidy123222** [ValveSoftware/SteamOS#1065]
I am currently on 3.5 from main branch and I use a dock on my steamdeck which has multiple storage mediums on it for different reasons but usually never shows up on the storage screen in settings but is fine on desktop mode with the kde plasma interface. 

One drive is ntfs and one is ext4 with my previous microsd which is steamdeck formatted which all are supported by Linux but maybe not game mode for them all? Maybe some of this could be solved by having a scan option in storage or supporting more than just ext4 like btrfs, fat32 and ntfs.

All you have to do is connect more than your microsd card on system and I will most likely not show or if you restart it will display any drive inconstantly. I was trying to transfer data from a smaller MicroSD card to my bigger one by having my old one connected via my usb c hub. Does it either way.

**Comment by Spidy123222** [comment]
> I've seen this happen when the drive is not R/W by the `deck` user in SteamOS (same user that runs the Steam UI / games). I suspect this is why you can see them as mounted in KDE but not in the Steam UI... You could verify by showing the permissions on the mounted filesystems for these cards.
> 
> 
> 
> SteamOS 3.4 forced ownership changes on any removable drives so that they were owned by this user. This was changed in 3.5, with the move to using udisks2 for auto-mounting. I think the idea was that forcing permission changes on a filesystem when mounting it isn't very nice, but maybe this decision should be revisited...

Since it was permission based like you said It could of been my new drive that was only allowing Read and requiring root to do anything in it. This was my issue with steam game ui wasn't formatting the card correctly. https://github.com/ValveSoftware/SteamOS/issues/1064

**Comment by w84death** [comment]
I'm on 3.5.1 and have the same problem. How I fixed it:
- put sd in
- sudo chmod 777 /run/media/deck/XXX-YYY-ZZZ
- sudo chmod 777 /run/media/deck/
- while steam settings in background
- out and in sd card
- new card apear in dropdown
- works!

**Comment by w84death** [comment]
@craftyguy  Formatted more than a  year ago on SteamOS. It disapear rescently  on testing 3.5. Then I tried to format it on Linux. Then format once again in SteamOS (3.5). Right now I manage to do:

- detect card in steam desktop
-  install a game on it while in desktop
- now steamOS see the card normally and I see and can play games form sd card
- works for now

the difference is that SteamOS did not see empty formatted card. Desktop version "initialize" it better.

**Comment by bertogg** [comment]
This should be fixed in the 3.6 beta images

**Comment by kisak-valve** [comment]
Closing per the last comment.
