### ISSUE TITLE
Deck randomly crashes to a black screen with the backlight on

### ISSUE THREAD

**Issue by alcroito** [ValveSoftware/SteamOS#1072]
#### Your system information

* Steam client version: 1687386907
* SteamOS version: 3.4.8
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The OS randomly crashes to a black screen with the backlight on. 
There doesn't seem to be any correlation when it happens. 

It happened while idling on the Home screen, it happened in settings, in downloads page, in desktop mode, while downloading a game.
It sometimes crashes with 2-3 minutes between restarts, sometimes after 30-60 minutes.
Happens both with and without power connected. 
Haptics of touchpad still work during black screen,

When it happens, I have to hold power for 3 seconds, and then press power again to power on.
Sometimes it crash reboots back to the OS, and doesn't hand on black screen, but it happens less often.
Often during reboot the file system is verified, but with no error.
In the period of time when it hasn't crashed, a few games I tried seem to run fine.

The deck is brand new, received today, 64GB eMMC edition. No sdcard.
Installed all the updates that were proposed to me. Haven't tried any beta OS yet.

The only changes i did was to enable ssh so i can look at the logs, and created a kdump folder as instructed in this thread https://github.com/ValveSoftware/SteamOS/issues/1015

Logs don't seem to contain anything useful at time of crash, at least from what I can gather.
Any other logs i could potentially enable?

I feel like RMA-ing the unit at this point.

```bash
$ uname -a
Linux piedeck 5.13.0-valve36-1-neptune #1 SMP PREEMPT Mon, 19 Dec 2022 23:39:41 +0000 x86_64 GNU/Linux

$ pacman -Q |grep kdump
kdump-steamos 0.9-2
```
[dmesg.txt](https://github.com/ValveSoftware/SteamOS/files/11984522/dmesg.txt)
[journal.txt](https://github.com/ValveSoftware/SteamOS/files/11984523/journal.txt)

**Comment by guilhermepiccoli** [comment]
Hi, thank you for the report. Just to be 100% clear: did you collect both the dmesg and journal *while* the issue happened? So you had a black screen, but could successfully login through ssh?

Cheers!

**Comment by alcroito** [comment]
Hi!

No, the attached logs were save post-hard-reboot which i saved by running
```
sudo dmesg > dmesg.txt 
sudo journalctl > journal.txt
```
and then scp copying over to my main machine.

But the attached journal.txt has multiple boots. 
If you search for "-- Boot" you can see exactly when the deck dies, it happens a few times.

I also tried ssh-ing and running sudo journalctl -f and then waiting for the deck to crash, but as soon as the deck dies, the ssh connection gets disconnected, and before the disconnect, no new output comes from the journal.
After rebooting  and reconnecting ssh, i see no new output being added to the journal before the new boot.

Since I created the issue, i also tried using the Beta channel and the Preview channel. 
In both cases the issue persists.
I saw some new core dumps in the log related to gamescope, but those didn't occur at the same time as the hard crash, so i am not sure if they are related.

One time when the hard crash occurred, there was a constant high pitched sound coming from the deck, like "piiiiiiiiiii".
It went away after hard reboot.

So now i've flashed the recovery image onto a usb drive, and re-imaged the steam deck.
Will monitor to see if the issue still happens.

**Comment by alcroito** [comment]
> I'm not one of the developers who work on SteamOS. The logs appear to indicate something odd is happening with the audio chip. My guess would be that it's a potential firmware/hardware issue if the SteamOS 3.5 main image didn't make a difference.
> 
> Perhaps Steam support can help?

Steam support proposed updating everything, putting the deck into power conservation mode, and reimaging. I’ve tried all of it, but the crashes persist. I suspect it’s a hardware or fimrware issue given that at the crash time the logs are completely empty. I RMA the device, hopefully getting a working one. I’ll close this issue.

**Comment by rwalle** [comment]
Another data point in case it helps anyone -- I have been running into the same issue, random crash with backlight on with seemingly no correlation, even before finish setting up the device. I am returning the device.
