### ISSUE TITLE
xdg-desktop-portal regression

### ISSUE THREAD

**Issue by parkerlreed** [ValveSoftware/SteamOS#1095]
#### Your system information

* Steam client version: 1689034492
* SteamOS version: VERSION_ID=3.5 BUILD_ID=20230630.1000
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes Main
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Following up from https://github.com/ValveSoftware/SteamOS/issues/775

Portal integration is not working upon launching into desktop. xdg-desktop-portal requires a restart.

Journalctl for the current boot https://gist.github.com/parkerlreed/d2522a08d91012057d2cbf3eeb0aee21

#### Steps for reproducing this issue:

1. Load into Gaming Mode
2. Switch to desktop
3. Notice Flatpak file integrations/link opens not working (And falling back to the default GTK portal for any Flatpaks using that)

**Comment by bertogg** [comment]
Hello, I can reproduce the problem easily with `20230630.1000` (although I need to switch to gaming mode and then back to desktop between steps 2 and 3) and I think that I have identified the problem, I will have a look.

**Comment by parkerlreed** [comment]
This appears to be working in 0807 without any interventions! Thank you.
