### ISSUE TITLE
loop devices do not support trim (or write_zeroes_max_bytes)

### ISSUE THREAD

**Issue by hirak99** [ValveSoftware/SteamOS#1101]
#### Your system information

* Steam client version:
* SteamOS version: Linux steamdeck 5.13.0-valve36-1-neptune #1 SMP PREEMPT Mon, 19 Dec 2022 23:39:41 +0000 x86_64 GNU/Linux
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: [Yes/No]

#### Please describe your issue in as much detail as possible:

Loop devices do not support writing zeros.

Steps to verify -

```sh
cd /home
fallocate -l 10M testfile
losetup /dev/loop0 testfile
cat /sys/block/loop0/queue/write_zeroes_max_bytes  # Shows 0
cat /sys/block/loop0/queue/discard_max_bytes  # Shows 0
```

Expected -
To see nonzero number of bytes for both capabilties as above.

However, on a vanilla Arch this works.

Why this is important -
This prevents efficient trimming on any containers on SSDs, which may be used to set up encryption for example.

Possible reason / solution -

It may be a kernel issue; should be solved with 5.19.4 according to this link: https://bbs.archlinux.org/viewtopic.php?id=267698

Question -

If upgrading the kernel to 5.19.4 fixes this, would you please consider it?

**Comment by kisak-valve** [comment]
Hello @hirak99, the SteamOS 3.5 pre-release is currently using a 6.1 based Linux kernel. When SteamOS 3.5.0 is released, this will be generally available through the regular update channels, but for now you can chose to switch to the `Main` update channel to have access to the pre-release.

To do this:
1) Go to `Settings` -> `System` -> check `Enable Developer Mode`
2) Go to `Settings` -> `Developer` (the bottom of the left sidebar) -> check `Show Advanced Update Channels`
3) Return to `Settings` -> `System` -> Switch `OS Update Channel` to `Main`
4) Apply the update.

If you're able to reproduce this issue with the newer kernel, then give me a ping and I can re-open this issue report for a SteamOS dev to ponder further.
