### ISSUE TITLE
Low FPS on OpenMW when Added as a Non-Steam Shortcut

### ISSUE THREAD

**Issue by d10sfan** [ValveSoftware/SteamOS#1102]
#### Your system information

* Steam client version: 1689034492
* SteamOS version: 3.4.8
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No]  No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

When playing OpenMW (using the binaries here for Linux: https://github.com/OpenMW/openmw/releases/tag/openmw-0.48.0), if I go into desktop mode and launch them directly, I get very high fps (100+). If I take the same binary and add it as a non-steam shortcut, the game drops to 40-50 fps, and barely sometimes 60. The menus will go much higher, but actual gameplay is much worse fps wise. This issue happens in both desktop mode and game mode, when launching this from steam.

#### Steps for reproducing this issue:

1.  Download Morrowind and OpenMW 0.48.0 on the steam deck
2. Launch it as a non-steam shortcut
3. See low fps once  you click New

**Comment by psi29a** [comment]
Does Steam apply game-mode? Could that rate-limit to 60fps?

**Comment by d10sfan** [comment]
The new preview of 3.5 does not fix this issue either.

**Comment by AbduSharif** [comment]
Some users found a workaround here:
https://gitlab.com/OpenMW/openmw/-/issues/7498#note_1582692503

**Comment by d10sfan** [comment]
This is fixed with the workaround, would be nice to have an official answer, but closing.

**Comment by AbduSharif** [comment]
The workaround isn't a fix, best to keep this open so it is noticed.

**Comment by d10sfan** [comment]
True will see if someone from valve respons at some point

**Comment by Fereval** [comment]
I mean, again this isn't fixed nor have they said they won't fix it. Maybe keep it open until Valve notice ?

**Comment by d10sfan** [comment]
> I mean, again this isn't fixed nor have they said they won't fix it. Maybe keep it open until Valve notice ?

This ticket has been created since 2023, with no response from Valve. You're always welcome to create your own ticket, but I'm not holding out hope
