### ISSUE TITLE
Please add missing Gstreamer Plugins

### ISSUE THREAD

**Issue by bezza191** [ValveSoftware/SteamOS#1104]
Less an issue, more a request

Can we please have gst-libav and gst-plugins-good added to the system?

They help with video playback, particularly for emulation frontends such as [Pegasus Frontend](https://pegasus-frontend.org)

Currently, to install them means doing the following
```shell
sudo steamos-readonly disable
sudo pacman --noconfirm -S gst-libav gst-plugins-good
sudo steamos-readonly enable
```
It would of course be better to not have to, as this negates the immutable nature of the OS

**Comment by bertogg** [comment]
Are you installing Pegasus from [Flathub](https://flathub.org/apps/org.pegasus_frontend.Pegasus) or from where ?

**Comment by bezza191** [comment]
> Are you installing Pegasus from [Flathub](https://flathub.org/apps/org.pegasus_frontend.Pegasus) or from where ?

The issue doesn't occur with the Flatpak due to their nature including all dependencies. The standalone executable however does need the libraries installed to the system, with a similar issue also occurring on openSUSE Tumbleweed

I have since submitted instructions for both to the documentation though, so at least it's highlighted - not a huge issue as a result

**Comment by bertogg** [comment]
That's why it's recommended to install additional apps using Flatpak and the like, the base OS cannot possibly ship all libraries and dependencies that third-party apps can potentially need.

**Comment by bezza191** [comment]
I'm aware of that, hence why I've added it to the Pegasus documentation

I didn't know the documentation accepted PRs at the time, so this seemed a logical step

Ill close the issue anyway.
