### ISSUE TITLE
XBox360 controller not fully installed.

### ISSUE THREAD

**Issue by Balderick** [ValveSoftware/SteamOS#111]
The guide button constantly flashes.
Have managed to configure controller in settings when logged in to steam@steamos and appears to be working as expected in BPM.

I know this issue was reported here but i have searched and searched again but can not find the reported issue in open or closed lists.  

From memory this was confirmed as fixed by valve employee who also offered OP of issue the workaround of booting system with out controller connected and plug in once booted/logged into steam@steamos  Pressing the guide button should get the lights to stop flashing.

That workaround does not work and my guide button on xbox360 type controller continues to flash.

`dmesg | grep xpad` returns `[    3.941620] usbcore: registered new interface driver xpad` but no device name has been given indicating the controller is not fully installed.  As does the flashing guide button.

I know installing xboxdrv is one solution to get controller fully installed and is also a solution to my other related query described below.

Most or a lot of games in steam for linux library do not natively support controller and the ones that do sometimes give poor performance and simply do not map according to game settings.  I have used xboxdrv for keyboard and mouse emulation which works well after setting game options to keyboard and mouse and making an appropriate .config for xboxdrv.  Debian Wheezy ships with xboxdrv and do not understand how steamos emulates keyboard and mouse for the steam controller "legacy mode" which is really just using a keyboard and mouse emulator.  Any info regarding this would be appreciated and if it is unacceptable to discuss that here then please consider contributing to http://steamcommunity.com/groups/steamuniverse/discussions/0/864980153266081891/?tscn=1389350846

**Comment by not83** [comment]
Are you still experiencing issues?
