### ISSUE TITLE
[Feature Request] A checkbox before installing a game for shadercache and re-encoded videos

### ISSUE THREAD

**Issue by nicknamenamenick** [ValveSoftware/SteamOS#1120]
With the release of SteamOS 3.5, Graphics Pipeline Library will be in the new graphic drivers.  In my testing in the main channel, many games can run without any stuttering because of this.  My suggestion is adding an option install the pre-cached shaders and/or the re-encoded videos upon clicking "install" for a Steam game.  By default they should be checked and have "(recommended)" next to them.

If the user does not select shaders/re-encoded videos then in the game properties there can be a setting to check it back on, and it can start downloading them as normal.

I think this option can greatly improve the quality of life of 64GB Steam Decks.

**Comment by kisak-valve** [comment]
Hello @nicknamenamenick, the Steam client manages the shader pre-cache, not SteamOS in general as a platform.

This feature request is already being tracked between https://github.com/ValveSoftware/steam-for-linux/issues/6486 and https://github.com/ValveSoftware/steam-for-linux/issues/9132. Closing in favor of the older feature requests.
