### ISSUE TITLE
[Feature Request] Don't let games read native input for controllers managed by Steam Input

### ISSUE THREAD

**Issue by csfalcione** [ValveSoftware/SteamOS#1125]
#### Your system information

* Steam client version: 1691097434
* SteamOS version: 3.4.8
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Expected:
1. Connect xinput controller (in this case, 8bitdo Ultimate via 2.4g receiver)
2. Launch game (something that natively supports xinput controllers, e.g. Duck Game or Vampire Survivors)
3. Only the virtual steam input controller is detected and used by game.

Actual:
3. Games tend to detect both the native controller and the virtual steam input one, making multiplayer either impossible or very difficult.

The user impact is that these controllers are absolutely unusable for many split-screen games. This isn't an issue for DS4/DualSense in my experience. I presume because I haven't tried a local-multiplayer game that natively supports DS4/DualSense. Corroborating this, the issue is present on an 8bitdo Pro 2 in xinput mode but not dinput mode.

This isn't a showstopper for games like many emulators that provide explicit controller mappings, but could be confusing for new users.

As far as I can tell, this is the same class of issue as described in https://kanuan.github.io/DS4WSite/guides/solving-double-input/, but I can't find a linux alternative for HidHide.

In theory, shouldn't it be feasible to prevent the game from even knowing about the native controller's existence, at the wine/proton level?

**Comment by kisak-valve** [comment]
Hello @csfalcione, this is an issue somewhere between Steam Input and Proton. SteamOS as a platform shouldn't be doing anything fancy here.

Looking around a bit, this looks like the same issue as https://github.com/ValveSoftware/steam-for-linux/issues/8132. Feel free to add your findings to that issue report.

Closing as a duplicate.

**Comment by JacobBrownAustin** [comment]
Hi.  I was told that your issue might be the same as mine.  Please try this workaround.  Edit the game properties for games having problems causes by steam input and add this environment variable.
```
'SDL_GAMECONTROLLER_IGNORE_DEVICES="0x054c/0x0268,0x2dc8/0x3106" %command%
```
The device ids can easily be found from `lsusb`.  I don't know what it is for non-usb controllers.
