### ISSUE TITLE
[Steam Deck] Manual GPU Clock Control does not persist for "per-game" profiles.

### ISSUE THREAD

**Issue by Chitan96** [ValveSoftware/SteamOS#1126]
#### Your system information

* Steam client version: 1691097434
* SteamOS version: 3.4.8, Build 20230508.1
* Opted into Steam client beta?: No 
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Enabling "Manual GPU Clock Control" in the quick-menu performance tab allows me to set my GPU clock speed to 200MHz, which works fine and persists when set to the "default" profile. However, when enabling "Use per-game profile", The option works, and sets correctly. but on the next launch of the game, the option is completely disabled and must be re-enabled every time the game is started.

#### Steps for reproducing this issue:
1. Launch an application/game through SteamOS Gaming Mode.
2. Navigate to the "Performance" tab in the quick menu (Three dot button on deck).
3. Enable "Use per-game profile".
4. Enable "Manual GPU Clock Control" and set desired clock speed.
5. Exit the application/game and reopen it.
6. The "Manual GPU Clock Control" setting is automatically disabled.

Update: I have also tried the current (as of 08/29/2023) beta and preview releases and the problem still persists.

**Comment by SQ-sama** [comment]
The same thing also happens with just disabling "Use per-game profile" without exiting the game:

5. Turn off "Use per-game profile" and re-enable it.
6. The "Manual GPU Clock Control" setting is automatically disabled.

**Comment by Chitan96** [comment]
As of SteamOS Version 3.5.1 (Build 20231011.100, Client 1698890449), this issue seems to have been resolved
