### ISSUE TITLE
SteamOS 3.5, DP over USB-C not outputting to HDR display

### ISSUE THREAD

**Issue by AAdmiral56** [ValveSoftware/SteamOS#1140]
#### Your system information

* Steam client version: 1694826162
* SteamOS version: 3.5
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: Yes, preview
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
After updating to SteamOS preview version 3.5, my HDR display (KTC M27T20), which I connect to via a DP Alt-mode type-c cable, does not get a display signal from my Steam Deck nor do my peripherals which are plugged into the monitor activate. Neither does a Silicon Power SU20 type-c dock I have which goes to HDMI and to the display. This is truth for both gamemode and desktop mode ( the latter not even recognizing the display). Curiously the deck still gets charge from the monitor when using the type-c port, which tells me that it's not outputting data for some reason.
Both work on the latest stable versions.

The monitor settings are stock apart from Local Dimming, VRR and HDR being enabled.

#### Steps for reproducing this issue:

1. Steam OS 3.5 Preview
2. Plug the deck into the display

**Comment by AAdmiral56** [comment]
Seems like it, can be archived I guess

**Comment by TTimo** [comment]
Although I guess you are not using a Dock? Direct cable connection between your Deck and the display?

**Comment by AAdmiral56** [comment]
Yes, it's a direct cable connection but from the description sounds like
roughly the same issue

**Comment by TTimo** [comment]
Right, but useful data point that this seems to happen with no dock involved at all.
