### ISSUE TITLE
Steamworks Common Redistributables downloads every time on SD Card Swap

### ISSUE THREAD

**Issue by adham3322** [ValveSoftware/SteamOS#1155]
#### Your system information

* Steam client version: 1695334486
* SteamOS version: 3.6 / 20230918.1000
* Opted into Steam client beta?: [Yes/No]  Yes
* Opted into SteamOS beta?: [Yes/No] Yes, Main Channle
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Every time I switch SD cards the download for the Steamworks Common Redistributables is triggered and I have to download Steamworks common redistibutable again to be able to play any games.

#### Steps for reproducing this issue:

1. Hot Swap SD card

**Comment by kisak-valve** [comment]
Hello @adham3322, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9847. Closing as a duplicate.
