### ISSUE TITLE
sshd_config should contain Include directive

### ISSUE THREAD

**Issue by Mikaela** [ValveSoftware/SteamOS#1159]
#### Your system information

* Steam client version: 1695679261
* SteamOS version: 3.5
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Yes 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

The file `/etc/ssh/sshd_config` doesn't contain `Include` directive and the directory doesn't contain subdirectories.

Modern Fedora and Debian systems ship with the lines:

```sshd_config
# To modify the system-wide sshd configuration, create a  *.conf  file under
#  /etc/ssh/sshd_config.d/  which will be automatically included below
Include /etc/ssh/sshd_config.d/*.conf
```

I would like to place my own configuration under `/etc/ssh/sshd_config.d/`, mainly prohibiting password authentication, without having to worry about OS updates or package management overwriting my changes or them otherwise getting ignored.

#### Steps for reproducing this issue:

1. Switch to desktop mode
2. Open terminal
3. `less /etc/ssh/sshd_config`

-----

Loosely related: https://github.com/ValveSoftware/SteamOS/issues/933

**Comment by bertogg** [comment]
Kiitos bugiraportista!

This makes sense, it was fixed in Arch last month for OpenSSH 9.4p1-2:

https://bugs.archlinux.org/task/79285
https://gitlab.archlinux.org/archlinux/packaging/packages/openssh/-/commit/1d834b1fb688e148797c39cffd95eac3404ef894

I'll let you know if the package is updated before the stable release of SteamOS 3.5.

**Comment by bertogg** [comment]
Hi, this is fixed in the preview branch (SteamOS 3.5.2). Please tell me if you notice anything strange, thanks!

**Comment by Mikaela** [comment]
Thank you and sorry for the long response time, I had somehow missed the issue updates.

The system contains a `/etc/ssh/sshd_config.d` where there is a `99-archlinux.conf` which I presume comes from the Arch package, and the only strange thing with quick testing is that the Include directive was missing from `/etc/ssh/sshd_config`.

I guess that is caused by me editing the file previously and I had just incorrectly assumed that updates would overwrite my changes there, but my changes are now in both places so hopefully even if a future update overwrites the file, nothing unexpected will happen.

**Comment by bertogg** [comment]
> the only strange thing with quick testing is that the Include directive was missing from `/etc/ssh/sshd_config`.

Your guess is correct and this is because you have local changes to that file. If you want to fix this manually, remove `sshd_config` from `/var/lib/overlays/etc/upper/ssh/` and then reboot the system. After that you'll see the original one provided by the OS.

(keep a copy of the file before removing it so you can make sure that you didn't forget any local changes)

**Comment by TheArcaneBrony** [comment]
no such thing in arch land, at least not to my knowledge
regular `pacman` updates usually either move the old config to .pacold or put the new one as .pacnew if you changed it locally

**Comment by bertogg** [comment]
Bear in mind that the SteamOS system update is image-based, not package-based.

If you modify a file in /etc and update the system your local modification will prevail even if the new OS version comes with a new version of that file (this is the general idea, there are exceptions to this).

If you want to get rid of your local version and use the one provided by the system you can remove your local version from the /etc overlay as explained above.
