### ISSUE TITLE
SteamOS 3.5 factory reseting problem

### ISSUE THREAD

**Issue by Spidy123222** [ValveSoftware/SteamOS#1162]
Currently I wanted to remove any variables that could be messing with steamOS 3.5 preview branch so I decided to factory reset as I previously made a GitHub issue about dolphin explorer freezing. Apparently after doing setup it doesn't create a bootable partition. I investigated and went to boot from file and there's 3 different efi sections. Every one of them don't work trying to boot steamOS but the button one which isn't part of the boot priority list. 

Following ifixit they say to trigger an update. I do and seems like it doesn't trigger making a new bootable partition like they claim. https://www.ifixit.com/Troubleshooting/Steam_Deck/Not+Booting/516070#Section_Boot_Partition_Corruption

This is the only way I can boot steamOS currently at the moment so it is installed and is on 3.5 and seems to might of fixed my issue other than some stuff. For the other folders there is steamOS and efi folders but in efi folder is a steam folder and there is a steamctl.efi in first one and other folder the one I booted from has grubx64.efi. Middle efi folder same thing as last one but it doesn't boot at all like the bottom folder. https://cdn.discordapp.com/attachments/967624313974968340/1157550706782371859/IMG_8098.mov?ex=6519049a&is=6517b31a&hm=2cb02c0e98e1950f5f6592d0364a81efce9727a71bd06816309f3de0b212d4dc&

Just wanted to report this issue and maybe get help fix this issue also as using efi file is super unideal and reimage would put me over home internet data cap (Comcast) as updating recently already took a lot of data. I do testing and development stuff but I'm not really fully familiar with Linux to know how to fix this exactly.

One thing to note is the first 2 folders that have steamOS to boot to that don't work. The trackpad seems to work like if you were in gameui so I feel it's booting but there isn't any gameui some reason.

Edit: I realize this is not partition but just boot entries in boot from file section.

**Comment by Spidy123222** [comment]
Currently getting support on boot issue and managed to see the boot process and seems it might be my mistake not sure yet but however during a factory reset it should check for a changed root password and maybe ask for it or just revert to original. For example if I installed power tools it needs sudo perms to add itself.

**Comment by Spidy123222** [comment]
The problem is caused by fsck not understanding steamOS 3.5's file system as during factory reset it also downgraded. I'm guessing this also happens to people downgrading from preview. This is a demonstration from troubleshooting by booting into bash. ![image](https://github.com/ValveSoftware/SteamOS/assets/64176728/e09b2304-e254-4cde-9734-f21637cb15de)

Only way to get system to boot properly was to disable file check for home directory which requires changing from 2 to 0 on right side in /etc/fstab

Here is also an image from booting the current system without temporary fix via QAM boot section. You cannot do anything when this is visible. If you click enter it just repeats which made us go into bash beforehand to investigate. 

![image](https://github.com/ValveSoftware/SteamOS/assets/64176728/5defaa6e-0386-4fcb-b7c6-c81b39b2b61a)

**Comment by Spidy123222** [comment]
Update: so I have data today so I updated to 3.5 and decided to revert the fsck check on /home and it's back to stock. I've also discussed about people's downgrade experiences from preview to stable and seems to be fine so this seems isolated to factory reset.

**Comment by miki223** [comment]
the filesystem feature & thus init system failure  seems to be caused because of the factory reset
resetting formats the home partition which adds new features to the ext4 filesystem the old e2fsck  on stable does not know how to handle a filesystem with these new features
this is my guess at least

**Comment by Spidy123222** [comment]
> Hello,
> 
> 
> 
> the fsck problem that you mention is a known issue with SteamOS 3.5 preview (at least with build ID 20230915.100).
> 
> 
> 
> If you perform a factory reset from there the `/home` and `/var` partitions are formatted with a new feature called `orphan_file`. Without going into too many details, SteamOS 3.4 is not happy with that feature and that's why it fails to boot.
> 
> 
> 
> This will be fixed soon in 3.5. In the meantime, and if you still cannot boot your Deck I recommend that you re-image it using the recovery image: https://help.steampowered.com/en/faqs/view/1B71-EDF2-EB6D-2BB3
> 
> 
> 
> Another possibility is that you boot using a rescue disk (like [System Rescue](https://www.system-rescue.org/) or similar) and you remove those features from all filesystems:
> 
> 
> 
> ```
> 
> $ e2fsck /dev/mmcblk0p6
> 
> $ e2fsck /dev/mmcblk0p7
> 
> $ e2fsck /dev/mmcblk0p8
> 
> $ tune2fs -O ^orphan_file /dev/mmcblk0p6
> 
> $ tune2fs -O ^orphan_file /dev/mmcblk0p7
> 
> $ tune2fs -O ^orphan_file /dev/mmcblk0p8
> 
> ```
> 
> 
> 
> The rescue disk needs to be recent enough to understand this new feature (`e2fsck -V` should be >= 1.47.0)
> 
> 

I was able to fix mine without needing to format. Since you can hold on QAM button on deck and boot and go use a keyboard and get the advanced menu for current and click E you can add init=/bin/bash at the end of steamenv_boot. 
It boots up with the bash terminal and then you can use the command nano /etc/fstab and modify the line for home directory and change the one that's on right side of it from the number 2 to 0 which disables checking it using fsck. You can then after that restart the device after saving and do a update to fix the issue going back to preview then repeating last process but a sudo password putting back the value to 2. Then after that if they want they can downgrade and it be stock like intended. 

This is much better solution than just forcing a reimage especially if it's your only computer like mine currently. I have parts of a old computer so I was able to use a keyboard

**Comment by bertogg** [comment]
Just to be clear, using the recovery image is the easier solution for people who bump into this problem and are not necessarily comfortable with repairing the filesystem themselves.

**Comment by miki223** [comment]
was not sure you could remove the feature with tune2fs

**Comment by bertogg** [comment]
You can as long as tune2fs is recent enough (1.47.0), which is the case in 3.5 but not in 3.4

**Comment by miki223** [comment]
yeah i had a feeling all the core utilities on 3.4 were quite old when were they even updated since release if ever
my guess is the update that brought in the new  plasma

**Comment by bertogg** [comment]
This has been fixed in SteamOS 3.5.1 preview (build id: `20231011.100`), it is safe to do a factory reset now.

**Comment by Spidy123222** [comment]
Someone else will have to retest since I already fixed my install and don't need to factory reset again. But I'm sure it will work. I don't remember seeing something about this being fixed in update changes.

**Comment by bertogg** [comment]
FWIW I tested this a few times with a 20231011.100 build.

**Comment by kisak-valve** [comment]
Closing as resolved.
