### ISSUE TITLE
[Feature Request - Steam Deck] Wake Deck when wireless controller wakes

### ISSUE THREAD

**Issue by Jim-Wright** [ValveSoftware/SteamOS#1164]
#### Your system information

Steam client version: 1694547959
SteamOS version: 3.4.10
Opted into Steam client beta?: No
Opted into SteamOS beta?: No
Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Currently the Steam Deck will only wake when you press the power button on the unit.  It would be great if the Deck would wake when the wireless controller (PS4/XBox, etc) wakes and tries to connect, like other consoles usually do.  Obviously this would mean that Bluetooth would always be checking for activity, so an option to disable this, or disable when not docked would be required for battery life.

#### Steps for reproducing this issue:

1. Turn on controller.
2. Wait
3. Walk across the room to turn on the Deck.

**Comment by kisak-valve** [comment]
Hello @Jim-Wright, this feature request is already being tracked at #913. Closing as a duplicate.
