### ISSUE TITLE
Different display of colour behaviour through In-Home streaming

### ISSUE THREAD

**Issue by kraaijmakers** [ValveSoftware/SteamOS#1166]
#### Your system information

* Steam client version: 1696541351
* SteamOS version: 3.5
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

The games streaming using RemotePlay appear darker than they are since I switched from the Stable to Preview branch, sometimes if I open the quick menu the colours look okay. See attached pictures for an example.
![normally](https://github.com/ValveSoftware/SteamOS/assets/16176800/b1e1496d-ad43-4a98-b776-f2fb85447178)
![in-home streaming](https://github.com/ValveSoftware/SteamOS/assets/16176800/4ac6d4ed-6e6a-4118-9c5f-10880e9b245b)

#### Steps for reproducing this issue:

1. Stream a game through in-home streaming, before and after beta.

**Comment by eth-p** [comment]
Does disabling hardware decoding fix the colors for you? I've been experiencing the same issue and was worried there was something wrong with my deck's h264 decoder.

**Comment by greghanley** [comment]
I'm also having this same issue.  I'm on the latest stable 3.5.5 (build 20231116.2).  I found that launching a remote play game in Desktop Mode while not changing any client settings fixed the darker gamma issue.

I also tested the suggestion of disabling the hardware decoder and remote playing in Game Mode and it looks to have fixed the issue for me as well.  I suspect disabling the hardware decoder means more CPU usage and less battery time, so it's no an ideal fix.

**Comment by Evlos** [comment]
Same here. Additionally, the screenshots under in-home streaming look insane.

![20231119144728_1](https://github.com/ValveSoftware/SteamOS/assets/517862/0216c869-8f25-49cd-a927-85369731a910)

**Comment by matt-mccarthy** [comment]
This issue made me roll back to 3.4. I might be imagining it, but latency felt higher with hardware decoding disabled.

I'll also add that the issue occurs on external displays as well (I'm using the official dock). Disabling hardware decoding fixes it there as well.

**Comment by Evlos** [comment]
> Same here. Additionally, the screenshots under in-home streaming look insane.
> 
> ![20231119144728_1](https://private-user-images.githubusercontent.com/517862/284043616-0216c869-8f25-49cd-a927-85369731a910.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMzYwMzQsIm5iZiI6MTcwMTIzNTczNCwicGF0aCI6Ii81MTc4NjIvMjg0MDQzNjE2LTAyMTZjODY5LThmMjUtNDljZC1hOTI3LTg1MzY5NzMxYTkxMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQwNTI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOWY3YTk0MWIwY2I5NjA0NDk2YWRiMjRmZTM3NzAzMDI2MDAwZWMxZjcwMjE1ZTgyNWQ2YWQ5NGQyODBhNDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-p50L5z09_p8b1KzphmxgcoIJVdg2W3p1qV16v7YUZA)

To supplement, as long as you adjust the settings of remote play during the remote play process, the subsequent screenshots will appear like this.

**Comment by gcaragea** [comment]
Same issue, all games impacted. Disabling hardware decoding fixes it 100% of the time. Steam deck LCD.

**Comment by hamsteriscoming** [comment]
same issue here

**Comment by Chriscrossing** [comment]
Identical issue here, disabling hardware decoding fixes it as does launching in desktop mode, but I do believe the input latency is increased with both fixes sadly :(

**Comment by stesha83** [comment]
Surely this is major functionality, any hint from Valve as to when it might be fixed?

**Comment by Chriscrossing** [comment]
I updated to the preview branch and the issue seems to have been solved. So it's been solved already at some point, just not applied to the stable branch

**Comment by Fiorinol** [comment]
Preview now breaks Remote Play entirely. Beta has the same issue.

**Comment by mpkonmbk** [comment]
> Preview now breaks Remote Play entirely. Beta has the same issue.

Glad I found this comment, I was about to switch to preview channel just to fix the unusable remote play gamma.

**Comment by break11** [comment]
I tested it in desktop mode and game mode on Steam Deck OLED and Steam Deck LCD and everything works fine, after last update on stable version.

**Comment by kraaijmakers** [comment]
Thank you for your time @kisak-valve, I close the issue as it seems to be fixed for me as well.
