### ISSUE TITLE
[Feature Request] Add rumble strength slider

### ISSUE THREAD

**Issue by Spidy123222** [ValveSoftware/SteamOS#1169]
Currently on steamos when you use a game that has rumble. It's usually unprovable sometimes even though it's stronger on other controllers. I suggest a slider to be able to decrease or increase the minimum rumble intensity and have it adapt to increase the rumble throughout so that there's Atleast a difference if a game does slightly stronger.

**Comment by kisak-valve** [comment]
Hello @Spidy123222, this should be controllable at Settings -> Controller -> Calibration & Advanced Settings -> Haptics Settings -> Left / Right Haptics Intensity.

**Comment by Spidy123222** [comment]
> Hello @Spidy123222, this should be controllable at Settings -> Controller -> Calibration & Advanced Settings -> Haptics Settings -> Left / Right Haptics Intensity.

This isn't per game however. As some games might have too strong of rumble while others be too weak.
