### ISSUE TITLE
[Feature request] Filesystem repair tool on gaming mode

### ISSUE THREAD

**Issue by Nyamiou** [ValveSoftware/SteamOS#1170]
#### Your system information

* Steam client version: SteamOS 3.5 Preview channel
* SteamOS version: SteamOS 3.5 Preview channel
* Opted into Steam client beta?: [Yes/No] Preview channel
* Opted into SteamOS beta?: [Yes/No]] Preview channel
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I had an issue with my SD card which I couldn't install a game on. The warning wasn't helpful (I don't remember but something like "can't install game"). On desktop mode using the console I managed to realized it was mounted on read-only because of an issue with the filesystem. I tried the filesystem maintenance button on the system settings in gaming mode but it did nothing. Running a filesystem repair with e2fsck fixed the issue but using Konsole with the on-screen keyboard to do all that was stressful and not easy.

I wish there was at least a warning on gaming mode with something like "Your SD card appear to be mounted as read-only due to a filesystem issue". And ideally, there would be an option to attempt to repair the filesystem there.

It would be even better if there was a way to do this for all filesystem from the system settings (forcing a repair on reboot for filesystem that can't be unmounted) or from desktop mode because I also had the issue on /var.

#### Steps for reproducing this issue:

1. Boot a Steam Deck in gaming mode with a broken filesystem on the SD card (or other filesystems)
2. Try to install a game or anything that require to write on the filesystem
3. The warning isn't helpful at all (I don't remember it but it just say something like "can't install game")
4. Try the filesystem maintenance button on system settings in gaming mode and realize it didn't fix the issue
5. Search for another tool in gaming mode but find nothing
6. Give up and go in desktop mode, search for a tool in desktop mode to do that but find nothing
7. Give up and open Konsole and follow up online tutorials while crossing fingers

**Comment by bertogg** [comment]
This is being worked on, thanks for the report.
