### ISSUE TITLE
Download screen | Currently downloading appearing under completed

### ISSUE THREAD

**Issue by cookiEoverdose** [ValveSoftware/SteamOS#1177]
#### Your system information

* Steam client version: 1697843490 (PC Desktop)
* SteamOS version: 3.5 Preview
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:

Totally confuses me for a long time, the item currently downloading also sometimes appears under "Completed".
I witnessed it both on desktop client and steam deck.
Additionally if you hit "Clear all", the process of the current download item disappears completely.

![2023-10-21 12-26-49](https://github.com/ValveSoftware/SteamOS/assets/19622019/b2a130d4-7284-4bf2-8b42-2987e8f8062c)
![2023-10-21 12-26-51](https://github.com/ValveSoftware/SteamOS/assets/19622019/5b20084f-7402-449e-82b5-aa60609eb531)
![2023-10-21 12-26-52](https://github.com/ValveSoftware/SteamOS/assets/19622019/4ca9e4e0-3a73-49df-91e5-bd3d9f37ec76)

#### Steps for reproducing this issue:

1. Download multiple times, sometimes it happens, usually with shader updates.

**Comment by kisak-valve** [comment]
Hello @cookiEoverdose, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/8527.

Closing as a duplicate.
