### ISSUE TITLE
SteamOS is garbage

### ISSUE THREAD

**Issue by entraide-net** [ValveSoftware/SteamOS#1184]
Archlinux rebase using flatpak, not native packages availlables and delaying updates is stupid, hope that deckbian get decent to move away (unofficial debian for steam deck).

Desktop mode almost endless possibilities are tainted by that and the read-only part of SteamOS.

Wonder why you didn't used window manager quick switch and app launching to make destkop to big picture mode switch seemless like Hydride Linux distribution, apps or small code could do the same.

Would have 2 massively game changer ideas for Valve if implemented well, would hand if paid enough, covered and expected most Valve moves on Linux from the start, reviewed a major innovative indie game by Steam that got a crossover with a major AAA game of another game console maker.

Would have others suggestions and could suggest candidates to hire that could improve things massively.

**Comment by kisak-valve** [comment]
Hello @entraide-net. I'm closing this issue report because it's not actionable feedback and is more suitable for the community forums than this issue tracker.
