### ISSUE TITLE
Cannot boot Version 3.4.11 update 

### ISSUE THREAD

**Issue by simlal** [ValveSoftware/SteamOS#1185]
## System information

* Steam client version: 
* SteamOS version: 3.4.10 -> 3.4.11
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No]  No
* Have you checked for updates in Settings > System?: [Yes/No]

## Issue

Trying to boot up my deck this morning, got stuck on the boot screen. Figured it was an issue with the update so managed to boot to the "previous" SteamOS version from the bootloader. The boot was fine, but in the end it did "corrupt" some of my personal data inside/outside my home. For example:
- Distrobox containers are gone (and the packages installed + .pyenv/ dir that I had with python venvs)
- /nix/ directory is gone (had it using the Determinate Systems guide). Found out because my .nix-profile/ symlinks point to nowhere.
- Some other files in my home/deck/ dir are gone.
- Most of my .config files seem OK, my KDE Plasma custom settings are just the way it was.

I think for now I might just go ahead install a fresh image. I was wondering if this is recurrent with SteamOS updates because it will be hard to use my Deck as my main workstation. I could make a backup of home/deck/ with rsync to keep my configs and port them if future update break the system but I haven't tested if it will work with possible conflicts, empty symlinks etc.

Is this common? Should I abandon the idea of using the Deck as my workstation? Thanks!

**Comment by bertogg** [comment]
Hello, did this happen immediately after you upgraded to 3.4.11? Or were you using 3.4.11 for a time and one day it stopped booting?

**Comment by simlal** [comment]
I cannot say for sure if I was on 3.4.11 or 3.4.10 because it was just the next day after they deployed the update (the 3.4.11). So I cannot say if this happened on 3.4.10 or 3.4.11. I remember at that time being mostly on Desktop mode so I think that I did not trigger the 3.4.11 in Gaming mode (and since I think its impossible as of now to update SteamOS via Desktop mode). But maybe I did I can't remember ;)

Now that I think about it, I think the "previous" in the bootloader referred to the base 3.4.10 build like early October when I bought my Deck (thus fresh image). That's what I reverted to. But maybe the fact that the problematic current state (at the time) was because I messed around with Distrobox and Nix

**Comment by simlal** [comment]
So I went with the fresh image and decided to install/use local packages/software restricted to $HOME only + Flatpaks obviously. I get that now, so I installed python venv/pip (thus a bunch of python libs inside a venv), nvm, and anything that is a prebuilt bin inside ~/.local.

I am backing up my /home/deck/ dir via rsync onto an external drive so if I have a have a problem I can just reload my home back to a working state and without too much data loss
