### ISSUE TITLE
Playing No Man's Sky (275850) prevents launching non-steam games/apps

### ISSUE THREAD

**Issue by greyfade** [ValveSoftware/SteamOS#1188]
#### Your system information

* Steam client version: 1698260427
* SteamOS version: 3.4.11
* Opted into Steam client beta?: No 
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

After playing No Man's Sky for a while (often a few hours at a stretch), I quit and do some other things and then decide to run a Flatpak app (Chrome in this case), which I've added as a non-Steam game. **Chrome does not start.**

After investigation, I find that the log file `/run/user/1000/gamescope-session.log` is 1.5GB in size and has filled the entire 1.5GB tmpfs. In my case, it contains 15,379,037 instances of this line:
```
src/clientdll/controller.cpp (12866) : Assertion Failed: AppID 275850 exceeding analog action limits
```
After deletion of this log file and restarting Steam, or after rebooting, I'm able to launch Chrome and other Flatpak apps again.

[gamescope-session.log.gz](https://github.com/ValveSoftware/SteamOS/files/13196946/gamescope-session.log.gz)

#### Steps for reproducing this issue:

1. Boot Steam Deck in game mode
2. Play No Man's Sky (275850) for a couple hours docked, quit and return to game mode
3. Try to launch Chrome

**Comment by greyfade** [comment]
To be clear, the reason Chrome is failing to run is because Flatpak is unable to create temporary files in `/run/user/1000/`, which is how I discovered the issue.

**Comment by greyfade** [comment]
Oops, didn't mean to close

**Comment by CrazyCritic89** [comment]
Hate when that happens

**Comment by bertogg** [comment]
This should be fixed in SteamOS 3.6 (currently in beta).

**Comment by bertogg** [comment]
3.6 stable is now out, and I think that this can be closed.

**Comment by greyfade** [comment]
Confirmed fixed. There is no longer any log file consuming all available memory! :P
