### ISSUE TITLE
Inconsistent MelonDS performance (Game Mode vs Desktop)

### ISSUE THREAD

**Issue by DoctorGoat** [ValveSoftware/SteamOS#1192]
#### Your system information

* Steam client version: 1698777785
* SteamOS version: 3.4.11
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes, current as of this message.

#### Please describe your issue in as much detail as possible:
Using MelonDS in Game Mode, MelonDS' Retroarch core, and MelonDS in Desktop mode, there is a significant difference in maximum speed for fast forwarding. I have been unable to circumvent the issue with any setting I can find with PowerTools or the system settings. Uncapping the framerate, allowing tearing, turning off turbo limits, and locking the CPU to maximum don't have a real effect on the Game Mode performance limit.

MelonDS for Retroarch has the same speed between Game Mode and Desktop Mode, which makes it particularly interesting as a side test. It caps around 120fps in multithreaded software regardless of swapping the retroarch compositor. 

MelonDS in Game Mode will cap at around 120fps with the multithreaded software renderer. In Desktop mode, it can reach up to 260fps. 

With the OpenGL renderer, it scarcely passes 70fps in Game Mode. In Desktop mode, it easily pushes 90-130fps.

For many NDS JRPGs, being able to go faster than the game originally intended is an enormous boon.

**I apologize if this is the wrong repo.** This may be a compositor issue.

#### Steps for reproducing this issue:

1. Acquire a copy of MelonDS. See https://github.com/melonDS-emu/melonDS. 
2. Acquire any NDS file. Anything public domain should work, I was using a dumped copy of Dragon Quest V. No BIOS is needed. 
3. Add to Steam from Desktop mode. 
4. Launch the NDS game from Game Mode, hold the turbo hotkey, and watch the title bar for the framerate. 
5. Launch the NDS game from Desktop mode, hold the turbo hotkey, and expect at least double the maximum you receive in Game Mode.
6. Retroarch, meanwhile, will not have a meaningful difference. Whatever it's forcing, it's causing worst case rendering.

**Comment by Spidy123222** [comment]
I don't seem to have this issue on 3.5.1 of steamOS.

**Comment by DoctorGoat** [comment]
I apologize if I'm using the wrong terms here. Game Mode refers to the self-contained Steam frontend, while Desktop mode refers to the Arch desktop, right?

I will try to tweak things and see if I can find a solution. It could be something to do with the Game Mode compositor, and I'm really not sure. I need to do a custom build to see if I can dump every conceivable flag to a file and maybe puzzle out what the issue is.

If the renderer is set to OpenGL, the desktop mode has been very noticably faster during turbo than the game mode's turbo, which is difficult to see a speed boost in without inexact tests. Unfortunately, without a custom build or some sort of injection, it's not possible to see real FPS vs. emulated FPS.

I don't see any actual bottleneck, and desktop mode even rarely caps on single core CPU performance.

**Comment by Spidy123222** [comment]
> I'll test 3.5.1.
> 
> 
> 
> Edit: On 3.5.1 I'm getting roughly 200fps (give or take 20) when walking in the church I have a save at in Dragon Quest 4 in Software Mode on both. 3.5.1 seems to have fixed it, but I've no idea how or why. 120fps+ at 16x internal resolution with the OpenGL renderer. 
> 
> 
> 
> I apologize if I'm using the wrong terms here. Game Mode refers to the self-contained Steam frontend, while Desktop mode refers to the Arch desktop, right
> 
> 
> 
> 
> 
> Edit: Does anyone know why 3.4.1 to 3.5.1 would have vastly different performance in this particular use case?

Smt fix is on 3.5 versions which helps emulation on programs. Increasing single thread performance if using smt. Usually you would need to disable smt to get full speed of the single thread performance below 3.5. There's also some mesa updates that changes stuff for the graphics backends.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
