### ISSUE TITLE
Steam Deck HDR breaks some games with Win32 function failure

### ISSUE THREAD

**Issue by nipsy** [ValveSoftware/SteamOS#1201]
#### Your system information

* Steam client version: 1699498641
* SteamOS version: 3.6 20231031.1000
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I recently enabled HDR on my Steam Deck while connected to my Valve dock and my LG OLED.  It looks great!  Having said that, one of my mindless go-to games is Caveblazers which normally works without any trouble.  However, with the HDR display option enabled, the game crashes immediately while starting with an error:

```
Win32 function failed: HRESULT: 0x80004005

Call: pDXGIFactory->CreateSwapChain at line 492
in file \Graphics_DisplayM.cpp
```

I tried a few different Proton versions just for kicks without any change.  Disalbing the HDR option in my SteamOS settings allows the game to run correctly again, albeit not nearly as pretty!  I was successfully running Risk of Rain Returns for the last several days with HDR enabled without any problem.

So at least some older games it seems are going to start having problems with this if it ever becomes the default, which I would assume would be the preferred setting on the new Deck OLED as well as anytime a user has an OLED attached externally (assuming that's detectable anyway).

At the very least, I'm hoping there's a command line switch or some such to be able to toggle this for specific titles maybe?  If not, perhaps some way to twiddle that setting automatically by Steam itself for known broken titles?  I'm not sure if Steam actually does any sort of per title "fix up magic" like that.

Anyway, since this is going to be an issue elsewhere I assume too, I'm opening this issue against SteamOS itself.

#### Steps for reproducing this issue:

1.  Enabled HDR SteamOS display setting.
2. Install and run Caveblazers.
3. Crash with Win32 error above.

**Comment by Joshua-Ashton** [comment]
Was not able to reproduce this issue on Steam Deck OLED.

**Comment by nipsy** [comment]
I can confirm that the latest OS update fixed this issue.

**Comment by nipsy** [comment]
I can confirm this is fixed with the latest OS.
