### ISSUE TITLE
When moving a Proton game between SD and internal SSD fails with "content file locked" error, the game will point to compdata in the new location

### ISSUE THREAD

**Issue by dominalien** [ValveSoftware/SteamOS#1202]
#### Your system information

* Steam client version: 1699498641
* SteamOS version: 3.5.1
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

When I try moving System Shock from SD card to internal SSD the operation fails with "content file locked". Settings->Storage is still showing the game on the SD card.

When I start the game, saves are gone. Looking at the file system, the game is still on the SD card, but now uses the compdata folder on the internal SSD, which was not moved from the SD card during the failed move operation and was created anew when the game started. As far as I can tell, this will also delete save files from the cloud when the sync is next performed.

What I would expect to happen is the game should not be made to point at the new compdata location before the move is fully finished and successful.

The original folder in compdata still exists on the SD, so data is not totally lost, but for someone who's not versed in this stuff it may as well be.

Still, when trying to diagnose this, I did manage to overwrite my saves and this got then synced to the cloud and I lost a ton of progress. I am very unhappy right now. :-(

#### Steps for reproducing this issue:

1. Have a Proton game that will fail to be moved from SD card to the internal SSD with the "content file locked" error.
2. Try and fail to move it.
3. Note in Settings->Storage the game is still listed on the SD card, note on the filesystem the game is still on the SD card.
4. Start the game and witness all saves being gone
5. Look at the filesystem and see there's now a folder in /home/deck/.steam/steam/steamapps/compdata/{gameno} which has no saves and this is the folder that the game now uses
6. Look at the filesystem and see there's still a /run/media/deck/{uuid}/steamapps/compdata/{gameno} folder there and that one includes all the saves, but the game no longer uses it

**Comment by bertogg** [comment]
Hello, this looks like an issue with the Steam client so I think that it belongs here: https://github.com/ValveSoftware/steam-for-linux/issues

**Comment by bertogg** [comment]
I'm not aware that there's a way to move it.

**Comment by dominalien** [comment]
OK, this is now here: https://github.com/ValveSoftware/steam-for-linux/issues/10219
