### ISSUE TITLE
3.5.2 sRGB color space regression

### ISSUE THREAD

**Issue by Originalimoc** [ValveSoftware/SteamOS#1203]
#### Your system information

* Steam client version: 1699498641
* SteamOS version: 3.5.2
* Opted into Steam client beta?: [Yes/No]  Y
* Opted into SteamOS beta?: [Yes/No]  Y
* Have you checked for updates in Settings > System?: [Yes/No] Y

#### Please describe your issue in as much detail as possible:
The color space slider has almost no effect in 3.5.2. Seems like "OLED update" breaks LCD version.

#### Steps for reproducing this issue:

1. Set color to sRGB

It works well from first introduced until 3.5.2

**Comment by wantija** [comment]
This happened to me as well

**Comment by CrazyCritic89** [comment]
Can confirm.

**Comment by Originalimoc** [comment]
3.5.3 Fixed
