### ISSUE TITLE
3.5.2 no more updated fan curve

### ISSUE THREAD

**Issue by Gpinchon** [ValveSoftware/SteamOS#1204]
#### Your system information

* Steam client version: 1699498641
* SteamOS version:  3.5.2 build 20231113.102
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Upon restarting the Deck after latest update I saw the fan was running at a constant ~4000 RPM. I went to the settings to see the "Updated fan curve" was disabled and enabled it to no avail. Upon restarting again I saw this setting has vanished.

#### Steps for reproducing this issue:

1. Update to 3.5.2 and restart

**Comment by ds22x** [comment]
My fan too is running at a constant 4000 RPM, even at idle, after updating to 3.5.2.

**Comment by Originalimoc** [comment]
Partially the same. Even temp 40c. Fan keep spinning at ~4000RPM

**Comment by Originalimoc** [comment]
3.5.3 Fixed

**Comment by ds22x** [comment]
Can confirm, problem is fixed on my end as well.

**Comment by Gpinchon** [comment]
Just installed the update, seems fixed 👍
