### ISSUE TITLE
Microphone does not work with SteamOS 3.5.5

### ISSUE THREAD

**Issue by wendersonp** [ValveSoftware/SteamOS#1207]
#### Your system information

* Steam client version: 1700160213
* SteamOS version: SteamOS 3.5.5
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Microphone just doesn't work anymore, no one can hear me on apps like Discord, it was fully functional with SteamOS 3.4, and it used to work when I tested on Beta before the OLED update, since then, it does not work. I tried the different microphone options and none of them work. Seems like it's a driver related issue, the driver has changed and that broke compatibility. Now the microphone does not work on stable channel. I tried with both internal and external microphone through headphone jack, it does not work

#### Steps for reproducing this issue:

1. Install an app that uses microphone, like Discord
2. Go to Discord settings.
3. Go to voice and video.
4. Run the microphone test, there's no output and you cannot hear your voice.

**Comment by nvkv** [comment]
Exactly the same for me

**Comment by eMPeBeYT** [comment]
same problem. i notice in steam games work. i played mk1 buton chrome on discord not for both desktopcor gaming mode so most probably not working for non-steam apps

**Comment by applejag** [comment]
They released v3.5.6 to the preview channel today, which solved the issue for me: https://steamcommunity.com/app/1675200/eventcomments/7529517132618777843/

**Comment by kisak-valve** [comment]
Closing per the last comment.
