### ISSUE TITLE
Xbox Elite Series II Controller: Unable to rebind Rear Buttons(P1-P4) on SteamOS

### ISSUE THREAD

**Issue by YoreonX** [ValveSoftware/SteamOS#1217]
This is my first time posting to Github, so I may not be entirely verse on how exactly to format my issue(s), but hopefully I'll learn along the way.

# Specs:

_Device: Steam Deck LCD(512GB)_

_OS Build: 20231116.1000_

_OS Version: 3.6 (Occurs on all Versions btw)_

_Kernel Version: 6.1.52-valve6-1-neptune-61_

_Steam Version: 1700533348_

# Problem:

If you plug in your Xbox Elite Series II Controller to a Steam Deck running SteamOS via USB-C or Bluetooth, it will identify it as a Elite Series II Controller but you cannot rebind the rear P1-P4 buttons.

On Desktop Windows(.exe) / Linux (.deb)

You can rebind the P1-P4 buttons, so I want to say this is a bug.. But maybe there's something I'm misunderstanding.

You can apply Community Layouts from Controllers that have rear buttons and apply them to the Elite Series II and the rear buttons work, but cannot be reconfigured.

# Replication

1. Requires: Steam Deck or officially supported SteamOS 3 device

2. Plug-in: Elite Series II Controller via USB-C(or Bluetooth)

3. Go to: Controller Settings(from any game)

 -3(a). You can already see that P1-P4 is not shown

4. Select: "Edit Layout"

5. Enter the: Buttons Tab

6. No option to reconfigure P1-P4 Buttons

**Comment by kisak-valve** [comment]
Hello @YoreonX, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9310.

Closing in favor of the older issue report.
