### ISSUE TITLE
Steam Deck - Performance Overlay only showing either 200MHz, 1040MHz and above

### ISSUE THREAD

**Issue by Kagukara** [ValveSoftware/SteamOS#1241]
#### Your system information

* Steam client version: 
* SteamOS version: 3.5.7 (Build: 20231122.1)
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Anywhere in the Steam Deck's interface the GPU frequency only goes between 200MHz and 1040MHz, with no in between frequencies. Majority of the time the clocks are at 1040MHz and go to 200MHz when moving around the menus. Causing the temperature to slowly rise and more power being drawn.
#### Performance settings used:
- Performance Overlay Level: 4
- Frame limit: 60 FPS
- Disable Frame Limit: Off
- Allow Tearing: Off
- Half Rate Shading: Off
- TDP Limit: Off
- Manual GPU Clock: Off
- Scaling Mode: Auto
- Scaling Filter: Linear
- Show Perf Overlay in Steam: On

Setting the "Manual GPU Clock: Off" to "On" and setting the "GPU Clock Frequency" to "200" causes the frequency to stay at 200MHz, temperature to lower/lowers and less power is used.

In the 3.4 version before 3.5.5 was released the clock speeds would not jump between only 200MHz and 1040MHz.

When in games, if the game can't push the Steam Deck higher than 1040MHz on the GPU Clock Frequency then it will switch between 200MHz and 1040MHz, showing no in between clocks.

This was also not present on an early version of 3.5, but I don't remember which one. When I saw the clocks were only between 200MHz and 1040MHz I just switched to stable without submitting an issue (should have probably submitted that issue).

#### Steps for reproducing this issue:
1. Turn on the Steam Deck
2. Set the Performance Settings to the default
3. Move around the menus/settings/anywhere in the Steam Deck

**Comment by Kagukara** [comment]
Yes, it stays at 1040MHz when idling on the Home screen. Manually setting 200MHz on the GPU Frequency Clock has little to no performance impact but also has the benefit of using less power and keeps the temperature down, in turn keeping the fan speed down. This is also the case in games if not worse, as you want an in between frequency as to keep the temperature, power and fans to a minimum.

**Comment by Kagukara** [comment]
Valve should probably remove the functionality from stable till they fix it.

**Comment by Viexi** [comment]
> Valve should probably remove the functionality from stable till they fix it.

I absolutely agree!

**Comment by Viexi** [comment]
> I feel as though there should be some kind of temporary workaround implemented in soon (Dunno about rollbacks the older steamos versions dont support the newly released oled models), cause it feels like more people are gonna start showing up here pissed feeling like they are being ignored, especially since the original thread talking about the gpu clock bug got closed.

Definitely needs a hotfix. I agree, I think you’re absolutely right about a rollback not working due to the OLED launching, but this needs to be a priority fix with an immediate ETA.

and look valve, I’m a dev myself so I know it sounds like I’m ignorantly saying this is easy - I’m not, this just is not an acceptable issue to release with by any metric.

**Comment by lostgoat** [comment]
Closing this issue as it doesn't refer to any particular performance issue.

**Comment by lostgoat** [comment]
Lets keep the discussion for this topic in the other threads with proper examples for in game performance problems.
