### ISSUE TITLE
External monitor via dock doesn't work / crash

### ISSUE THREAD

**Issue by BryanQuigley** [ValveSoftware/SteamOS#1258]
#### Your system information

* Steam client version (build number or date): Nov 29th
* Distribution (e.g. Ubuntu): Steam Deck OLED 512
* Opted into Steam client beta?: **Yes**
* Have you checked for system updates?: **Yes**
* Steam Logs: monitor doesn't work on Steam or on KDE
* GPU: AMD
* Dock dell_wd19dcs with up-to-date firmware

#### Please describe your issue in as much detail as possible:
https://gist.github.com/BryanQuigley/34feb3c12b68aed158d3c297698658e0

Others have used this dock in the [past](https://www.reddit.com/r/SteamDeck/comments/x6i2kk/the_deck_works_flawlessly_with_the_dell_wd19dcs/).  

Tried with
 * two different monitors
 * using both DisplayPort and HDMI, and two different Display Port cables
 * External Display Safe Mode
 * Battery storage mode

It worked once - only on the initial loading screen for the Steam Deck BIOS...
The external monitor does show up in KDE Display settings, but still blank (tried multiple resolutions)

#### Steps for reproducing this issue:

In Gaming Mode

1. Connect to dock with monitor, or boot with monitor dock attached (or most other combinations I've tried)
2.  Both displays go blank.

In KDE

1, Connect to dock with monitor (or power on with)
2. The steam deck display stays up, but the monitor never displays.  This is the crash I captured.

**Comment by BryanQuigley** [comment]
I have not been able to get it to display the BIOS mode again.

I did test with Fedora 39 (both KDE and Gnome) and they can't seem to get the external monitor to work either.  Maybe firmware difference between OLED and LCD?

**Comment by BryanQuigley** [comment]
I don't quite get it but it's working now.  I did disable Quiet mode in the BIOS which was the "first light" but now it seems to work fine.

**Comment by BryanQuigley** [comment]
It's not working again - and I haven't been able to get it to work again.  I'm confused.

**Comment by merihim** [comment]
Had this same issue occur while updating to the latest version today.  Immediately could not connect via a dock.  Tried a different dock that I use for my work station and same issue. 
I get audio but no video. 

Reverted back to 3.4.6 and everything is working perfectly, so it's definitely an issue in 3.5.5

**Comment by deftdawg** [comment]
My suggestion is to use [Rufus](https://rufus.ie/en/) to create a copy of `Windows 11 To Go` on an SD card, load all the official valve drivers on it and see if your deck can connect to the docks and operate normally, this will double confirm it's a SteamOS issue.   Hold `Vol -` when powering on to get to the boot manager to boot off the SD.

What I've found with the Deck is the Linux / AMD drivers seem to be screwed up/broken in terms of it's bandwidth:

- Under Windows I can run 4k@60 over HDMI **and** a 2K@60 over DP without any issues
- On the deck I can either:
  - Run HDMI at 4K@60 with no DP cable connected
  - **Or** I can run HDMI at 4K@30 and the DP at 1280x720@60, any config higher and both displays either blank or glitch out.

KDE seems to have all kinds of issues getting the resolutions and refresh rates to change with multiple monitors, its weird.

**Comment by deftdawg** [comment]
Following up on this it seem X11 used by SteamOS is notoriously bad at multi-monitor support...

I was however able to get 4k@60 over HDMI **and** a 2K@60 over DP when booted up on **Wayland** + KDE Plasma - distro! 

To test this out, I used WayDroid's live ISO with these steps:
1. Format an SD and install [Ventoy](https://www.ventoy.net/) on it
1. Download a copy of [waydroid live ISO](https://waydro.id/#wdlinux) on the the SD card
1. Shutdown
1. `Power on` while holding `Vol -` (steamdeck), select boot menu, select SD/MMC device
1. Select Waydroid in ventoy, normal boot-up (hit `A` on the steamdeck for enter)
1. Enter `evolution` as the password for `live` account
1. Connect displays in extend mode
1. Alt click on the Desktop to open `Display Settings`
1. Configure as required

All working!

I might see if I can get NixOS-Jovian to start up with Wayland to see if I can fix this my SteamDeck without waiting for value to switch to Wayland for Desktop mode.

**Comment by BryanQuigley** [comment]
I was able to get it to work just be using a different dock. Got the 5-in-1 Docking Station from jsaux and now it works fine.  Thanks all for suggestions!  Wayland didn't help for me...
Closing this issue for now..
