### ISSUE TITLE
Jurassic World Evolution 2 models are "squished" since update 3.5.5

### ISSUE THREAD

**Issue by SiegfredRodriguez** [ValveSoftware/SteamOS#1263]
The models are rendered incorrectly after updating SteamOS to 3.5.5.

Reinstall, Validate Files, use different Proton Version, none worked.

The versions of proton and the game that were known to work properly no longer worked after updating to 3.5.5

![image](https://github.com/ValveSoftware/SteamOS/assets/12148562/242ac6e8-1ff8-42ac-a8c2-5dbefe96dd70)
![image](https://github.com/ValveSoftware/SteamOS/assets/12148562/6335310e-eb3d-488e-94a3-0c1cd9c2ee0b)
![image](https://github.com/ValveSoftware/SteamOS/assets/12148562/36f2531f-71c9-4121-b987-f65d5aee54f5)

**Comment by waspennator** [comment]
Apparently the issue still seems to be around.

**Comment by waspennator** [comment]
Actually checking the community hub and a recent comment from Alasky, this issue might actually be fixed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
