### ISSUE TITLE
OLED WiFi Stops Working / Bricks After Attempting to Connect to 5GHz Network

### ISSUE THREAD

**Issue by mike-zarandona** [ValveSoftware/SteamOS#1280]
#### Your system information

* Steam client version:  `1701289036`
* SteamOS version:  `3.5.7`
* Opted into Steam client beta?: [Yes/No]  `No`
* Opted into SteamOS beta?: [Yes/No]  `No`
* Have you checked for updates in Settings > System?: [Yes/No]  `Yes`
* Router:  `Asus RT-AX88U`

&nbsp;
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

##### Expectation
Steam Deck OLED is able to connect to 5GHz WiFi networks

##### Results
Steam Deck OLED upon attempting to connect to a 5GHz network, will take a very long time and ultimately fail.  Once the failure occurs, the Deck is unable to connect to **any** wireless network nor perform WiFi scans of available networks until the system is rebooted.

&nbsp;
#### Steps for reproducing this issue:

0. This can be tested with a brand new Steam Deck OLED out of the box experience, or at any point after setup + configuration
1. Attempt to connect to a 5GHz network on an Asus RT-AX88U router
2. Observe network join negotiation stall / fail
3. Observe all WiFi networking is now disabled / not working until a full reboot of the Steam Deck

&nbsp;
- - -

#### Edit 1: Tailing Router Logs
On the Steam Deck, I only get _Failed to Connect_.  From my router logs, I get:
```
Dec  2 18:43:48 wlceventd: wlceventd_proc_event(530): eth7: Auth RE:DA:CT:ED:MA:C0, status: Successful (0), rssi:0
Dec  2 18:43:48 wlceventd: wlceventd_proc_event(559): eth7: Assoc RE:DA:CT:ED:MA:C0, status: Successful (0), rssi:-46
Dec  2 18:43:56 wlceventd: wlceventd_proc_event(494): eth7: Deauth_ind RE:DA:CT:ED:MA:C0, status: 0, reason: Deauthenticated because sending station is leaving (or has left) IBSS or ESS (3), rssi:-46
Dec  2 18:43:56 wlceventd: wlceventd_proc_event(494): eth7: Deauth_ind RE:DA:CT:ED:MA:C0, status: 0, reason: Deauthenticated because sending station is leaving (or has left) IBSS or ESS (3), rssi:-46
Dec  2 18:43:56 wlceventd: wlceventd_proc_event(494): eth7: Deauth_ind RE:DA:CT:ED:MA:C0, status: 0, reason: Deauthenticated because sending station is leaving (or has left) IBSS or ESS (3), rssi:-46
Dec  2 18:43:57 wlceventd: wlceventd_proc_event(511): eth7: Disassoc RE:DA:CT:ED:MA:C0, status: 0, reason: Disassociated because sending station is leaving (or has left) BSS (8), rssi:0
```

**Comment by RedAsKetchum** [comment]
This problem has been ignored since release day. Very concerning that there is zero acknowledgement of it. For all we know we got a very expensive OLED brick.

**Comment by australok** [comment]
Same problem here man, like literally same problem as u described it 100%:

https://www.reddit.com/r/SteamDeck/comments/187vgp6/wifi_bug_no_chance_to_connect_to_house_wifi6/

this bug ( i hope is a bug and not a very cringe cheap wifi chip) is not letting me use my deck since day 1

**Comment by Plagman** [comment]
Can you test on the 3.5.12 Preview build if possible?

**Comment by MrToasted** [comment]
I have this same issue. It's persisting even after updating to 3.5.12 Preview.  Failed to Connect error when trying to connect to Netgear Router R6700v3

**Comment by mike-zarandona** [comment]
Resolved in latest public update, closing
