### ISSUE TITLE
Recovery image stuck at console-ex set_state error:3

### ISSUE THREAD

**Issue by Madmorgan007** [ValveSoftware/SteamOS#1290]
![image](https://github.com/ValveSoftware/SteamOS/assets/19917093/d257098c-edde-46b2-b160-3ac8827455fe)

I'm using this image - steamdeck-repair-20231127.10-3.5.7.img

I am using a USB Kingston 8GB connected to a dongle.

Please tell me how to get past this issue.

Thanks

**Comment by RodoMa92** [comment]
Try to switch to XHCI in the BIOS and try to boot it up again. There are quite some issues with DRD on SteamOS lately, and it's the default for the deck right now.
