### ISSUE TITLE
Infinite "Loading User Data" Screen of Death, Cannot Access Library or Update.

### ISSUE THREAD

**Issue by YoreonX** [ValveSoftware/SteamOS#1293]
I'm going to do my best to explain in as much detail as possible.. But I can't really tell you how this happened exactly.

# System Prerequisites

Device: Steam Deck

OS Version: 3.6

OS Update Channel: Main

Steam Client Update Channel: Steam Deck Beta

Steam Version: 1701289036

OS Build: 20231205.1000

# Explaining the Details

So my Steam Deck was with me all day, usually in a mix of sleep/off state(mostly off), it was turned on 3-4 times & WiFi was likely turned off in the settings until I took a short trip home on the 3rd connected to WiFi for 10-20min as it idled.

I turned it off, placed it in the case and it sat in a rather chilled vehicle(not "cold" or "freezing") for another 6hrs.

When I got home, i turned on my Deck and I wasn't completely paying attention.. The Deck either connected instantly, or did not connect to WiF right away but did fast enough for me to not notice.

Steam proceeded to sit on Loading User Data for an extended period of time.. I could not update SteamOS or Steam Client, I could only go to the Steam Store or open settings and change, only WiFi or Bluetooth.

The average person would have to reimage their SteamOS in-order to fix this problem which is extremely unfriendly process to someone who has zero interst in losing all of their data.

I regret to inform that I did not video the incident.

# Reproduction: ???

I feel this post may be a waste, as I really don't know how this happened, but I was infinitely loading user data, and it seemed as if it was refusing to check with Steam, and turning WiFi off + rebooting did not alleviate that problem.

# Workaround / Fix:

- Requires a Dock

- Steam Deck Recovery Image

- Preferably a Fast Drive 

- Preferably a M+KB

**Guide**:

1. Hold the volume (+) button & press the power button(once).

2. Open Boot Menu

3. Select your Drive & Boot into the Recovery Image

4. Open Dolphin (If M+KB, once open Press CTRL + H; Skip to Step 5)

4(a). Open the Dolphin Menu (Deck only)

4(b). Select Show Hidden Files

5. Go to --> `/home/deck/.local/share/Steam/package`

5(a). Open the "beta" file with Kate Text Editor

6. You should see either "steamdeck_stable or steamdeck_beta, rename it to the opposite.

So if you're on Beta rename to Stable, Beta.. Then rename to Stable.

7. Reboot and Steam will begin reupdating Steam & it will load the Library upon Post-Boot.

7(a) you can return to the previous channel, you do not have to stay in either one, this is just to fix the infinite load.

I hope what I provided was useful, because again, someone less technically inclined than me would have had only one recourse, reimage SteamOS & lose all data.

**Comment by kisak-valve** [comment]
Hello @YoreonX, can you check if this is the same issue as https://github.com/ValveSoftware/steam-for-linux/issues/10278?

**Comment by lostgoat** [comment]
Thanks for the report.

This was an intermittent issue in the steam client which could become more common depending on how many non-steam games were present on the system (or other system you could stream from). 

The next update to the SteamDeck Beta and Preview channels will contain a fix.

**Comment by YoreonX** [comment]
> Thanks for the report.
> 
> This was an intermittent issue in the steam client which could become more common depending on how many non-steam games were present on the system (or other system you could stream from). 
> 
> The next update to the SteamDeck Beta and Preview channels will contain a fix.

Thank you, I will mark this issue as closed then.

It might be helpful to add a new script to the recovery image specifically to either reinstall Steam Client or to clear the Steam Beta.

Sometimes the fix might be that small rather than Reinstalling SteamOS or Reimaging!

Thank you for all your work, have a great day.
