### ISSUE TITLE
Are you monitoring ext4 O_DIRECT backported issue?

### ISSUE THREAD

**Issue by hungrymonkey** [ValveSoftware/SteamOS#1301]
#### Your system information

* Steam client version:
* SteamOS version:  3.5
* Opted into Steam client beta?: [Yes/No] 
* Opted into SteamOS beta?: [Yes/No] 
* Have you checked for updates in Settings > System?: [Yes/No]

#### Please describe your issue in as much detail as possible:

I do not know how to reproduce the bug, but it seems related to ext4 and O_DIRECT

https://lwn.net/Articles/954285/
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057843

https://gitlab.com/evlaV/linux-integration/-/commit/91562895f8030cb9a0470b1db49de79346a69f91

https://lore.kernel.org/stable/4118ca20-fb7d-4e49-b08c-68fee0522d3d@roeck-us.net/

#### Steps for reproducing this issue:

1. ??
2.  ??
3. ??

**Comment by kisak-valve** [comment]
Hello @hungrymonkey, reviewing the details of this, Only the upstream 6.1.64 and 6.1.65 linux releases are affected by this issue. The kernel on SteamOS is currently based on 6.1.52 and when a SteamOS dev is ready to bump to a newer patch release, it's highly like they'll bump past 6.1.66 where this has been resolved upstream.
