### ISSUE TITLE
SteamOS | Game Mode: Failure to Upload Screenshots (repeatable bug)

### ISSUE THREAD

**Issue by YoreonX** [ValveSoftware/SteamOS#1302]
# System Prerequisites:

Device: Steam Deck OLED

OS Channel Update: Main

Steam Client Update Channel: Steam Deck Stable

OS Build: 20231206.1000

OS Version: 3.6

Kernel Version: 6.1.52-valve9-1-neptune-61

BIOS Version: F7G0105

Steam Version: 1701289036

# Steps to Reproduce:

1. Be in SteamOS "Game Mode"

(This is Reproducible for all versions of  SteamOS 3.5+)

2. Press the Steam Button --> Go to Media

2(a). Have a screenshot from a Non-Steam Game & Steam Game Present(for testing)

3. Select the Screenshot from the Steam Game & Attempt to upload(Set as unlisted)

3(a). This should complete as normal

5. Repeat Step 3: For the Non-Steam Game

6. You will receive a "failure to upload screenshot" message.

# Video Demonstration

https://github.com/ValveSoftware/SteamOS/assets/128438463/94f93263-7bcd-4faf-aff7-909c13ebace7

# Notes

So it appears when you are in Game Mode, and you attempt to upload screenshots from "Media" that are taken from Non-Steam Games they won't upload.

I would understand if this were intentional, but you could have uploaded them, circa SteamOS 3.4 Update. You can however upload screenshots/photos to your Steam Profile from the Steam Client via Desktop Mode regardless if they're Steam Games, Artwork, etc.

So hopefully this gets the ball rolling, on either a response to why this behavior exists or formal notice of problem. Thanks for the read & I hope this is useful information to help us come to a solution.

**Comment by kisak-valve** [comment]
Hello @YoreonX, you've described an issue with the Steam client instead of SteamOS as a platform.

This issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9335. Closing as a duplicate.
