### ISSUE TITLE
Double UI Sound Effect on Game Launch, Requires Two Back Actions After Quitting a Game

### ISSUE THREAD

**Issue by seanhoyt** [ValveSoftware/SteamOS#1305]
#### Your system information

* Steam client version: 1702079146
* SteamOS version: 3.5.7
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
When launching a game, two sound effects are triggered that I don't believe is intentional (almost like two separate things are happening).

After exiting a game, you need to press B (back) twice to return to the the launch point (e.g. Library).

Admittedly not a super exciting bug, but it is a little annoying.

#### Steps for reproducing this issue:

1. Start a game
2. Return to previous location after quitting game

**Comment by kisak-valve** [comment]
Hello @seanhoyt, this is an issue with the Steam client instead of SteamOS as a platform, and is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/10253.

Closing as a duplicate.
