### ISSUE TITLE
Reduce screen flicker/PWM/Visual Fatigue on Steam Deck OLED

### ISSUE THREAD

**Issue by snipem** [ValveSoftware/SteamOS#1311]
#### Your system information

* Steam client version: 1702079146
* SteamOS version: 3.5.7
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Constant flicker of the screen because of PWM dimming of the screen leads to dry eyes, nausea and blurry vision to those sensitive to PWM.

Steam OS could introduce software measures (DC dimming) to limit the flickering and to reduce the physical effects to those affected. See detailed description of the issue below.

#### Steps for reproducing this issue:

1. Use Steam Deck at 100% brightness
2. Use for random amount of time
3. Eyes get dry and vision gets blurry, some report headaches.
4. Only gets worse with decreasing brightness of the screen.

#### Detailed description of the issue

Disclaimer: This seems plausible to me but I am not in the position to prove that is is scientifically correct. The author gives some hints on how to solve the issue on the software side. Hopefully someone with deeper knowledge can approve and implement a fix.

This is original content of [danisimo1](https://www.reddit.com/user/danisimo1/) over at Reddit:
https://www.reddit.com/r/SteamDeck/comments/1882kys/analysis_of_the_pwmflickervisual_fatigue_of_the/

This is only the conclusion of danisimo1. See the above link for full report and screenshots:

**CITATION STARTS**

**The Samsung OLED anti-glare panel of the Steam Deck OLED has proven to be very bad for the eyes in gaming sessions**, and the damage is particularly pronounced below 45% brightness. Still, the high risk is common at all brightness levels equally. There will be a percentage of people with very low sensitivity to PWM who will not notice negative symptoms in their eyes. However, **another large percentage of people, especially the most sensitive, will notice the symptoms**.

The associated symptoms could include nausea, rapid eye discomfort or fatigue, a sensation of grit in the eyes, migraines, and general fatigue, blurred vision after playing.

It is important to note that each individual reacts differently, and although **the measured values here offer an objective and recommended range for viewing\]**, the response can vary from person to person. If you are especially sensitive, I cannot recommend this screen and this product. Perhaps you try it, and it doesn't go wrong for you, but **\[what my data says is that the risk of it not going well is VERY HIGH**.

In my brief experience with the Steam Deck OLED, I have found that although it is a great product and a significant improvement over the Steam Deck LCD at the same price ranges, I have been really disappointed with the little attention to quality control that Valve has had with certain things. On the one hand, a high percentage of people receiving consoles with different assembly or factory defects (loose buttons, poorly assembled trackpads, sticking or noisy triggers, interference sound in jack headphones, dead pixels on BOE panels, etc.). Still, that is a separate issue. **I want to focus on what Valve CAN change now regarding the PWM of the OLED screen to solve this problem:**

&#x200B;

1. **\[Patch SteamOS by adding an option to enable DC-Dimming\]:** DC-Dimming is an alternative software method of regulating screen brightness that eliminates almost 100% of the flicker of screens of this style where I have tried it or has been implemented. For example, my Xiaomi Mi 9 phone with an Amoled screen and other Xiaomi Oled screens were unusable for me with the default PWM, but once DC dimming, also called "anti-flicker" mode, is activated, the phone is completely usable for hours without tiring. Valve is a company known for listening to and supporting its community and consumers by implementing their requests in software with new updates. \*\*\[With this measure, Valve could reduce a high percentage of people who end up with eye fatigue and worse health playing their OLED steam decks to basically almost, **It is about offering a product that takes care of your customers' eyes.**

2- **A second option by Valve could be instead of implementing a DC Dimming mode, that thescreen still uses PWM, but** **increase its PWM frequency from 360% to 1100%. Look at whathappens when the Hz frequency on the Steam Deck LCD reaches this value, even at itsworst flicker percentage (99%), it manages to enter the yellow or green zone.**

![image](https://github.com/ValveSoftware/SteamOS/assets/985581/7588188e-7bd0-4bb9-a5b1-6771c44c3fcd)

Image of Steam Deck LCD at its worst flicker value, which is mitigated by high frequency; the rest of its values are almost always flicker-free. Steam Deck LCD is the recommended product for people sensitive to this phenomenon, at least for now. 

&#x200B;

Examples of implementations that companies and manufacturers integrate through software on mobile devices such as Huawei, Xiaomi, or Oppo with Oleds PWM displays. From options to activate DC Dimming in normal, adaptive, or hybrid mode, to a software-based increase in the panel's PWM hertz to minimize the perception of flicker, this can be add and parch with software updates.

![image](https://github.com/ValveSoftware/SteamOS/assets/985581/40d92396-c404-4bc0-be6d-00b1d765f5f6)

![image](https://github.com/ValveSoftware/SteamOS/assets/985581/28ac20af-ea31-4302-a126-6b7b198058ae)

*Here is the previous PWM analysis I did of the Steam Deck LCD so that you can compare it with the OLED at each brightness level. The LCD panel is almost flicker-free 100%, entering the green zone at all its brightness levels except at 30%, which stays yellow:*  [(44) Analysis of the PWM of the Steam Deck LCD screen and its level of visual fatigue (and the same style of analysis for Steam Deck OLED next week) : SteamDeck (reddit.com)](https://www.reddit.com/r/SteamDeck/comments/17yf90o/analysis_of_the_pwm_of_the_steam_deck_lcd_screen/)

**While in my use of the Steam Deck LCD Anti-Glare for hours, my eyes have never gotten tired; with Steam Deck OLED, I have already experienced eye strain and a feeling of blurry vision after playing or shortly after starting.**

**CITATION ENDS**

**Comment by snipem** [comment]
The original author of the report will create his own issue with more details on the topic.  Closing this for now.

**Comment by esotericode** [comment]
There's no other post about this issue, so I'm kind of sad to see it closed.

**Comment by andrewcharlton87** [comment]
This is an important issue which should not be ignored, there should be an "eye friendly" option to reduce PWM flicker at the cost of colour accuracy/smoothness. 

People who are PWM sensitive will avoid using a screen this aggressive, and by all accounts it is a relatively simple software fix. I have refunded my SD OLED and will only repurchase once this issue is resolved unfortunately.

**Comment by snipem** [comment]
#1337 is the new issue
