### ISSUE TITLE
[Feature Request] [Steam Deck OLED] Idle Mode / Option to Turn Off Screen While Downloading

### ISSUE THREAD

**Issue by KrisCris** [ValveSoftware/SteamOS#1319]
The Steam Deck's current design, which requires the screen to be on in gamemode during downloads, leads to not only more battery drain, increased risk of accidental interactions, but potential premature wear of the OLED screen. In light of this, I am submitting a feature request for two potential improvements:

1. Idle Mode: This would enable the Steam Deck to continue downloading games with the screen turned off, similar to standard practices in other gaming consoles. It would be a valuable addition to saving battery power and extending the lifespan of the OLED screen.

2. Screen Off with Key Press Activation: As an alternative, introducing a feature that allows the screen to turn off during downloads and reactivate with a key press could be a simpler yet effective solution. This would also help in conserving battery life and reducing screen wear.

Implementing either of these options would significantly enhance the Steam Deck experience, especially in terms of battery efficiency and screen longevity. I believe these features would be a welcome addition for all Steam Deck users.

**Comment by kisak-valve** [comment]
Hello @KrisCris, this request is close enough to #865 that it's not worth discussing separately. Since you've added a couple details to ponder, I've transferred this issue report to https://github.com/ValveSoftware/SteamOS/issues/865#issuecomment-1867730504.

Closing in favor of the older feature request.

**Comment by KrisCris** [comment]
Thank you, @kisak-valve, for referencing issue #865. I'd like to clarify that my feature request addresses a distinct functionality for the Steam Deck. Unlike the referred issue, which focuses on preventing auto-sleep until downloads are complete, my proposal is about enabling the screen to turn off while still keeping the system active for essential services like game downloads, system updates, and soundtrack playback.

Btw, I just came up with an idea, and although I'm not entirely sure about its feasibility, I thought it might be worth considering. The concept is to modify the sleep mode functionality of the Steam Deck. When the user presses the sleep button, the system would not immediately go into full sleep mode. Instead, it would do two things: firstly, turn off the screen, and secondly, pause (potentially using a mechanism like sigstop) all non-essential user processes, such as those launched from gamemode, including applications and games, to preserve battery life. Meanwhile, essential system functions like downloads, updates, and soundtrack playback would continue running in the background. The system would only enter full sleep mode after these essential services have finished.

**Comment by rodion-dolin** [comment]
It is now possible to turn off the internal display through Gamescope while keeping Gaming Mode and background processes running.

Tested on my Steam Deck OLED:

```bash
gamescopectl drm_sleep_internal_screen true
```

To turn it back on:

```bash
gamescopectl drm_sleep_internal_screen false
```

`1` and `0` work as well. The transition is asynchronous and may take several seconds.

The current DRM state can be checked with:

```bash
cat /sys/class/drm/card*-eDP-1/enabled
```

It reports `enabled` when the display is on and `disabled` when it is off.

More details and relevant Gamescope sources:
https://gist.github.com/rodion-dolin/92a6a1ebfadb6b67cdb69f5fcf451020
