### ISSUE TITLE
Beta non-EUFI SteamOS not work on Hyper-V Server 2008 R2 SP1

### ISSUE THREAD

**Issue by CSRedRat** [ValveSoftware/SteamOS#132]
I'm finished installation SteamOS from ISO to Windows Hyper-V Server 2008 R2 SP1 with all updates, reboot and can't boot to SteamOS after login. Gray backgroun and nothing.

**Comment by johnv-valve** [comment]
Hyper-V does not support OpenGL applications

**Comment by DeluSan83** [comment]
Hello johnv-valve, and other folks, sry but that's not correct/ true: 
http://blogs.msdn.com/b/rds/archive/2014/11/05/remotefx-vgpu-updates-in-windows-server-next.aspx

While is was fairly limited before it is not anymore.

------------------------

OpenGL 4.4 and OpenCL 1.1 API Support (2014)

Prior to the Windows Server Technical Preview, running a virtual machine on Hyper-V limited you to OpenGL 1.1 with CPU acceleration and no support for OpenCL regardless of the presence of a capable GPU. This was a limiting factor for delivering a virtual desktop for users with applications such as Adobe Photoshop, Maya, Blender and Houdini which require these APIs. With a capable GPU on a Hyper-V host, RemoteFX vGPU now delivers support for OpenGL up to version 4.4 and OpenCL 1.1 in a Windows virtual machine.

Some OpenGL applications such as Adobe Photoshop include features that use OpenCL for compute/GPGPU tasks. These applications will greatly benefit by the OpenCL capabilities now supported in RemoteFX. OpenCL is of course also available for GPGPU tasks.

------------------------

Just gave Steam OS a try on Windows 10, Hyper-V-Manager Version 10.0.10586.0 and with supported hardware on CPU and GPU side and RemoteFX vGPU enabled I get the same result also mentioned here: https://www.reddit.com/r/SteamOS/comments/1t78ch/steamos_in_hyperv/

namely, a black screen after the setup process.

Please check it out, thx.

**Comment by not83** [comment]
Why's this matter? Think about where SteamOS is going to be used.

**Comment by johnv-valve** [comment]
I should be more specific - Hyper-V does not support OpenGL applications **in Linux guest VMs.**

The key phrase in the blog entry is "in a Windows virtual machine"

**Comment by CSRedRat** [comment]
http://social.technet.microsoft.com/wiki/contents/articles/31771.experience-guide-for-enabling-opengl-support-for-vgpu-in-server-2016.aspx

**Comment by gbraad** [comment]
as @johnv-valve points out, the above link from @CSRedRat states in the requirements: "Guest: Server 2016 or Windows 10 Guest with the November Update". So, only Windows guests have OpenGL support :-s
