### ISSUE TITLE
getsubids command returns error

### ISSUE THREAD

**Issue by kingoftheconnors** [ValveSoftware/SteamOS#1320]
#### Your system information

* Steam client version: 1702079146
* SteamOS version: 3.4.10
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I changed to desktop mode, opened Konsole and tried to use `getsubids deck`. I got the error: `Error fetching ranges`. My guess is that the version of the package (shadow 4.11.1-1) has some problem with it that would be fixed by updating core-rel/shadow to (4.11.1-2), but that's just a guess.

**Comment by kisak-valve** [comment]
Hello @kingoftheconnors, can you reproduce this issue with SteamOS 3.5.7? Shadow was bumped to 4.13-2 for that release series.

**Comment by kingoftheconnors** [comment]
I updated SteamOS and it was fixed! Thank you!
