### ISSUE TITLE
[Feature Request] keychain password management

### ISSUE THREAD

**Issue by mercuriete** [ValveSoftware/SteamOS#1328]
#### Your system information

* Steam client version:
* SteamOS version: latest
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

#### Steps for reproducing this issue:

When an application ask me for a password I have to type It again and again.

Example:

1. Install Assassins creed Black flag.
2. Ubisoft connect ask you for a password
3. You have to type It.

Expected results:

Virtual keyboard should help me remembering the password from a list of password from my keychain.
This keychain could potentially knows which Game I am running and type on few clicks using paste or typing the Keys on the virtual keyboard quickly.

Drawbacks: Valve have to enforce a secure implementation of the storage to avoid reading passwords from an stolen device.

Please close this ticket if you consider this is imposible to archive.

Thanks for your work.

**Comment by kisak-valve** [comment]
Hello @mercuriete, this looks like an issue with running the game and the supporting service with Proton similar to https://github.com/ValveSoftware/Proton/issues/1733#issuecomment-1661113497 instead of an issue with SteamOS as a platform.

Feel free to add a note with the current behavior of the game on the linked compatibility report.

Closing in favor of the Proton compatibility report.

**Comment by mercuriete** [comment]
@kisak-valve 
I understand it seems a game bug but Ubisoft already stated that they will ask a password every time for all old games:
https://steamcommunity.com/app/289650/discussions/1/3192493519716258087/?l=tchinese

This is not a something ubisoft is fixing nor proton because is working as intended.

Apart from that this issue is a feature request not a bug report.
The problem with assasins creed was just an example of use case.

Thanks for your understanding.
