### ISSUE TITLE
Wake on Lan doesnt work if dock is disconnected after sleep 

### ISSUE THREAD

**Issue by Iss-in** [ValveSoftware/SteamOS#1333]
#### Your system information

* Steam client version: 1702079146
* SteamOS version: 3.5.7
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: yes

#### Please describe your issue in as much detail as possible:
Using jsaux dock with deck, 
If dock is connected and i put deck to sleep, I can wake deck via lan successfully  ( if dock is connected all the time ) 

If I put deck to sleep, and then connect or reconnect the dock and then try waking via lan, it doesnt work. 

seems like once the dock cable is removed, device doesnt resume connection anymore 

#### Steps for reproducing this issue:

1. Put deck in docked mode, with a dock which support WOL
2. Make it go to sleep 
3. Disconnect the dock cable once and reconnect it 
4. powering on via wol doesnt work

**Comment by kisak-valve** [comment]
Hello @Iss-in, I don't see any sane way for the Steam Deck to influence this behavior of a third party dock while the hardware is asleep.

Wanting the system firmware to keep track of past seen dock hardware and what's needed to reinitialize an arbitrary NIC and reconfigure the network inferface back to a ready-for-wake-on-lan state is asking too much while the system is sleeping.

Closing as won't fix.
