### ISSUE TITLE
ds-inhibit doesn't properly hook PlayStation controllers on first connect

### ISSUE THREAD

**Issue by Sterophonick** [ValveSoftware/SteamOS#1336]
#### Your system information

* Steam client version: `1704329464`
* SteamOS version: `20240104.1000`
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?:  Yes, `Main`
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
My DualSense controller's touchpad is not inhibited correctly upon its first connection from a clean SteamOS boot. This issue also leads to the controller being called `PS5 Controller` when it has actually been named `Sony DualSense (Cosmic Red)`, as well as the touchpad not being usable in Steam Input, instead reverting to the default X behavior. This issue is fixed when disconnecting and reconnecting the controller.

Fixing one controller will fix all subsequent PlayStation controllers.

This issue was fixed in the Steam Client in the past but has since regressed.

#### Steps for reproducing this issue:

1. Start SteamOS from a clean boot.
2. Connect a DualShock 4 or DualSense controller.
3. Observe as the touchpads are not correctly inhibited by `ds-inhibit`.

### Workaround
1. Disconnect controller.
2. Reconnect controller.

**Comment by kisak-valve** [comment]
Hello @Sterophonick, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9597. Closing in favor of the older issue report.
