### ISSUE TITLE
Audio settings in Big Picture mode won't stick after reboot nor microphone settings

### ISSUE THREAD

**Issue by paulonarciso** [ValveSoftware/SteamOS#135]
Well, I have been testing the new change in Big Picture regarding Audio. It's welcome to see that we now can change to whatever sound card is available, and it works (sort of).

The problem is that SteamOS is configured by default to output sound through HDMI, that's clear in the last four lines in pulseaudio system.pa file.

So, sound settings in BPM don't get saved after reboot, because system.pa file is forcing a specific output.

A change in that especific area of the OS must be made for everything work as intended.

Now let's talk about microphone problems. In my system, which I'm using integrated sound (asus z87 pro) If I set my mic to rear microphone option and set the sound volume, those settings work only in that session, because if I reboot those settings are lost and mic sound volume revert to very low and It change to front microphone.

**Comment by MichaelHeimann** [comment]
@jazz1138 Thanks a million - just saved me from going through audio wizard every time I want to watch a video. (and mostly right after recognizing it's not surroung, stopping the video, leaving xbmc etc. argh).

So: thumbs up for you :+1: 
and shame on steamos devs, audio config is something that should just work. fixit goddamn. no pun intended :)

**Comment by johnv-valve** [comment]
Should be fixed now in brewmaster.
