### ISSUE TITLE
[SteamOS Main] Broken fan control on LCD

### ISSUE THREAD

**Issue by RodoMa92** [ValveSoftware/SteamOS#1359]
#### Please describe your issue in as much detail as possible:
Your latest fan controller changes broke the script for fan control, since it's forcing to parse a parameter called dry_run that is not present in the jupiter-config.yaml file.

The patch below fix this problem.

Marco.

#### Steps for reproducing this issue:

1.  Switch to main on Steam Deck LCD (assuming it's merged, I have no installation of SteamOS to test it against)
2. Fan is using EC controls instead of your script since it's broken.

[fan_fix.tar.gz](https://github.com/ValveSoftware/SteamOS/files/13977326/fan_fix.tar.gz)

**Comment by RodoMa92** [comment]
Thanks for the fix.

**Comment by adamweld** [comment]
Thank you for the catch @RodoMa92
