### ISSUE TITLE
Audio problem lots of people have

### ISSUE THREAD

**Issue by GreatNateDev** [ValveSoftware/SteamOS#1363]
#### Your system information

* Steam client version:
* SteamOS version: newest as of writing
* Opted into Steam client beta?: [Yes/No] no
* Opted into SteamOS beta?: [Yes/No] no
* Have you checked for updates in Settings > System?: [Yes/No] yes

#### Steps for reproducing this issue:

1. Fr turn on steam deck latest ver
2. 
3.

**Comment by kisak-valve** [comment]
Hello @GreatNateDev, this issue is already being tracked at #1360. Closing as a duplicate.
