### ISSUE TITLE
GPU clock jumps between 200/1040 MHz

### ISSUE THREAD

**Issue by Lingviston** [ValveSoftware/SteamOS#1377]
#### Your system information

* Steam client version: 1705108172
* SteamOS version: 3.5.7
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
GPU frequency in certain (perhaps ALL, I didn't test all of my library) jumps between 200/1040 MHz values. Games tested:
- Civilization 6, DirectX 12
- Resident Evil 4 2005
- Vampire Survivors

#### Steps for reproducing this issue:

1. Launch the game
2. Enable performance overlay 4+
3. Observe the behaviour

Also I have a feeling, that the issue began to happen after I changed "Device Name" in the system settings.

**Comment by jvalecillos** [comment]
Same issue as described or related with #1241, #1261 and #1176

**Comment by Kittnz** [comment]
Got the same issue on my LCD deck, i got 3.6 running and nothing has changed. Apparently 3.4 fixes the issue.

**Comment by kisak-valve** [comment]
Hello @Lingviston, @Kittnz, as mentioned in the older issue reports, the change in reclocking behavior from 3.4 to 3.5 is not considered a bug by itself. If you're seeing some kind of performance regression to go along with this symptom, then the information requested at https://github.com/ValveSoftware/SteamOS/issues/1176#issuecomment-1828168044 is needed to make this issue report actionable.

Feel free to add those details if relevant, then give me a ping to reopen.
