### ISSUE TITLE
WiFi often disconnects

### ISSUE THREAD

**Issue by LittleFIve233** [ValveSoftware/SteamOS#1378]
#### Your system information

* Steam client version:1705108172
* SteamOS version: 3.5.14
* Opted into Steam client beta?: yes
* Opted into SteamOS beta?: yes
* Have you checked for updates in Settings > System?: yes

#### Please describe your issue in as much detail as possible:
WiFi disconnects and reconnects for some reason while in use, and it doesn't connect properly every time, resulting in unusability. 

If the Steam client suddenly fails to connect to the server, steamdeck will have unlimited WiFi connections until it can connect to the Steam network.
This bug is available from 3.5.7 to 3.5.14.

#### Steps for reproducing this issue:

1.Connect to the network using WiFi, then hibernate and turn it back on, then make sure that the steamdeck cannot connect to the Steam network, Steam may restart the WiFi indefinitely to try to connect or simply not connect to the Steam network

Just like in the video

**Comment by LittleFIve233** [comment]
The video: 
https://github.com/ValveSoftware/SteamOS/assets/68946023/8c4c886c-ebae-4c96-a369-30df126f4413

**Comment by SimPilotAdamT** [comment]
In your steam deck's gaming mode settings, go to the system section and enable developer mode. Then scroll down to the development settings section and disable WiFi power management.

**Comment by LittleFIve233** [comment]
> In your steam deck's gaming mode settings, go to the system section and enable developer mode. Then scroll down to the development settings section and disable WiFi power management.

Oh, Thanks! I've tried other WiFi these days, and it's probably the only one that has problems with this route to WiFi. I'll close this.
