### ISSUE TITLE
Default storage location keeps changing to the SD card

### ISSUE THREAD

**Issue by ncdaol** [ValveSoftware/SteamOS#1379]
#### Your system information

* Steam client version: 1705108172
* SteamOS version: 3.5.7
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
The default storage location for game installations keeps changing to the SD card. I have to go into storage settings and set the internal storage to default, and it seems to stick a couple of days or so. Haven't found any particular pattern yet to why it changes to the SD card.

#### Steps for reproducing this issue:
Since it's happening seemingly at random, I don't have any steps to reproduce it.

**Comment by kisak-valve** [comment]
Hello @ncdaol, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/10225. Closing as a duplicate.
