### ISSUE TITLE
> Guys, I managed to solve the problem! It's not in the system but in the LPDDR5 RAM memory free frequency I downgraded the bios to FA0116 and unlocked the AMD PBS / CBS menus later I post tutorial I changed the memory frequencies there and everything is ok now it doesn't matter the system version! I live in Brazil RMA and impossible for me who lives abroad and can do the rma do it

### ISSUE THREAD

**Issue by raffa101br** [ValveSoftware/SteamOS#1386]
> Guys, I managed to solve the problem! It's not in the system but in the LPDDR5 RAM memory free frequency I downgraded the bios to FA0116 and unlocked the AMD PBS / CBS menus later I post tutorial I changed the memory frequencies there and everything is ok now it doesn't matter the system version! I live in Brazil RMA and impossible for me who lives abroad and can do the rma do it

I will try if you can tell me more or less how to do it. 
I know how to downgrade BIOS ad how to lock it using the script.

_Originally posted by @tonirevert in https://github.com/ValveSoftware/SteamOS/issues/1257#issuecomment-1939276899_

**Comment by raffa101br** [comment]
you try? the is good

**Comment by kisak-valve** [comment]
Hello @raffa101br, there's no value in fragmenting the discussion of your issue into a separate issue report and that issue title is profoundly terrible.

Closing in favor of #1257.
