### ISSUE TITLE
Steam In-Home Streaming Non-functional

### ISSUE THREAD

**Issue by matt-mccarthy** [ValveSoftware/SteamOS#1387]
#### Your system information

* Steam client version: 1707951391
* SteamOS version: 3.5.15
* Opted into Steam client beta?: [Yes/No]  Yes
* Opted into SteamOS beta?: [Yes/No]  Yes
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When streaming to the Steam Deck in game mode, I should see the game actually stream. However, now when I stream from my PC I'll get an audio stream but no video and no controls. Streaming in desktop mode works correctly, this issue only happens in game mode.

This issue is mentioned [in this issue](https://github.com/ValveSoftware/SteamOS/issues/1166#issuecomment-1925501072) and on the Steam Deck community hub [here](https://steamcommunity.com/app/1675200/discussions/0/4208119923883093652/).

This feature has been broken for at least a week for me and I only went on the preview build because of the gamma issue for in home streaming mentioned above.

#### Steps for reproducing this issue:

1. Attempt to stream a game in game mode. The games I've tested include Cyberpunk 2077, Baldurs Gate 3,  Elden Ring, Octopath Traveler II, among others.

**Comment by kisak-valve** [comment]
Hello @matt-mccarthy, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/10461. Closing as a duplicate.
