### ISSUE TITLE
[regression] Deep Rock Galactic Survivor not rendering on latest main branch update

### ISSUE THREAD

**Issue by K900** [ValveSoftware/SteamOS#1398]
#### Your system information

* Steam client version: 1708479383
* SteamOS version: 20240221.1000
* Opted into Steam client beta?: [Yes/No] yes
* Opted into SteamOS beta?: [Yes/No] yes
* Have you checked for updates in Settings > System?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Deep Rock Galactic Survivor (2321470) does not render anything after today's main branch update, though the sound still plays and the game seems to be running. Updating Mesa from steamos-23.9.9 to steamos-24.1.0 on NixOS also triggers the issue. The game renders and runs fine on 23.9.9.

#### Steps for reproducing this issue:

1. Launch the game
2. ???
3. Black screen

**Comment by Blisto91** [comment]
@K900 Hi there and thank you for the report.
Can you verify that this now works again on Main?

**Comment by K900** [comment]
It does, thanks!
