### ISSUE TITLE
SD Card not working on Gaming Mode and not detected on Desktop Mode (SteamOS 3.5.17)

### ISSUE THREAD

**Issue by manuelpmtsousa** [ValveSoftware/SteamOS#1408]
#### Your system information

* Steam client version: 1709168962
* SteamOS version: SteamOS Holo 3.5.17
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible: I had some games installed on my SD card for quite some time (already a couple of months) and everything was working fine and dandy.

After I turned off the Deck and a half an hour later I turned it on, the Deck stopped recognizing what it was installed on the SD card and asked me to format it (all this happened firstly on Gaming Mode). After verifying there was an issue, I went to the Desktop Mode, and there it didn’t even detect the presence of the SD card. This happened one day after the update of 29th of February, just two hours ago.

The SD Card in question it’s the 512GB Samsung Evo Plus, listed on Amazon.

Some other users reported the same or similar problems on Reddit r/SteamDeck. I’m unsure of what their SD cards are.

#### Steps for reproducing this issue:

1. Have an SD card mounted before the 3.5.17 update.
2. Update it to 3.5.17.
3. Have your Deck restarted or turn it off and on just a handful of times.
4. Once it shows the SD card icon, near the notification top bar with the internet and search icon, then we have a problem Houston.

**Comment by kisak-valve** [comment]
Hello @manuelpmtsousa, can you share the output of:
```
sudo lsblk -d /dev/mmcblk*

sudo blkid /dev/mmcblk*

mount | grep SD032

sudo journalctl -b | grep -E 'mmcblk|steamos-automount'
```

(from https://github.com/ValveSoftware/SteamOS/issues/1339#issuecomment-1883549104)

**Comment by manuelpmtsousa** [comment]
Sure. Here's the results:

`AME      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
mmcblk0   179:0    0 477.5G  0 disk 
mmcblk0p1 179:1    0 477.5G  0 part 
/dev/mmcblk0: PTUUID="a82557fa-2f29-4817-8cc8-35d8aaece2e9" PTTYPE="gpt"
/dev/mmcblk0p1: PARTLABEL="primary" PARTUUID="7a5c44de-cdc2-44c7-bc7e-37c78c16d27b"
mar 03 00:28:31 SDmanuels kernel: mmcblk0: mmc0:59b4 EF8S5 478 GiB 
mar 03 00:28:31 SDmanuels kernel:  mmcblk0: p1
mar 03 00:28:31 SDmanuels systemd[1]: Created slice Slice /system/steamos-automount.
mar 03 00:28:31 SDmanuels systemd[1]: Starting Mount removable drive mmcblk0p1 and notify Steam...
mar 03 00:28:32 SDmanuels steamos-automount.sh[2091]: Error mounting /dev/mmcblk0p1: wrong fstype:  - {
mar 03 00:28:32 SDmanuels steamos-automount.sh[2091]:   "path": "/dev/mmcblk0p1",
mar 03 00:28:32 SDmanuels steamos-automount.sh[2091]:   "label": null,
mar 03 00:28:32 SDmanuels steamos-automount.sh[2091]:   "fstype": null
mar 03 00:28:32 SDmanuels steamos-automount.sh[2091]: }
mar 03 00:28:32 SDmanuels systemd[1]: steamos-automount@mmcblk0p1.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
mar 03 00:28:32 SDmanuels systemd[1]: steamos-automount@mmcblk0p1.service: Failed with result 'exit-code'.
mar 03 00:28:32 SDmanuels systemd[1]: Failed to start Mount removable drive mmcblk0p1 and notify Steam.
mar 03 00:28:56 SDmanuels fwupd[3183]: 00:28:56.139 FuEngine             failed to add device /sys/devices/pci0000:00/0000:00:01.3/0000:02:00.0/mmc_host/mmc0/mmc0:59b4/block/mmcblk0: failed get ffu_capable
mar 03 00:30:04 SDmanuels dbus-daemon[553]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.127' (uid=0 pid=3862 comm="sudo lsblk -d /dev/mmcblk0 /dev/mmcblk0p1")
mar 03 00:30:12 SDmanuels sudo[3862]:     deck : TTY=pts/1 ; PWD=/home/deck ; USER=root ; COMMAND=/usr/bin/lsblk -d /dev/mmcblk0 /dev/mmcblk0p1
mar 03 00:30:12 SDmanuels dbus-daemon[553]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.128' (uid=0 pid=3871 comm="sudo blkid /dev/mmcblk0 /dev/mmcblk0p1")
mar 03 00:30:12 SDmanuels sudo[3871]:     deck : TTY=pts/1 ; PWD=/home/deck ; USER=root ; COMMAND=/usr/bin/blkid /dev/mmcblk0 /dev/mmcblk0p1
mar 03 00:31:53 SDmanuels dbus-daemon[553]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.130' (uid=0 pid=3968 comm="sudo lsblk -d /dev/mmcblk0 /dev/mmcblk0p1")
mar 03 00:32:34 SDmanuels sudo[3968]:     deck : TTY=pts/1 ; PWD=/home/deck ; USER=root ; COMMAND=/usr/bin/lsblk -d /dev/mmcblk0 /dev/mmcblk0p1
mar 03 00:32:34 SDmanuels dbus-daemon[553]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.131' (uid=0 pid=4007 comm="sudo blkid /dev/mmcblk0 /dev/mmcblk0p1")
mar 03 00:32:34 SDmanuels sudo[4007]:     deck : TTY=pts/1 ; PWD=/home/deck ; USER=root ; COMMAND=/usr/bin/blkid /dev/mmcblk0 /dev/mmcblk0p1
`

**Comment by manuelpmtsousa** [comment]
Edit: Wait, I'm a dumbass. Here's the output. I had to do it again, as I closed the window.
[results testing.txt](https://github.com/ValveSoftware/SteamOS/files/14471213/results.testing.txt)

**Comment by manuelpmtsousa** [comment]
Edit 2: Don’t wanna clog this with messages, but sorry again. I don’t know too well Linux, not even console on Windows, so that’s why I messed it up on that chunky paragraph before until I figured out what to actually do.

**Comment by geeksville** [comment]
btw @kisak-valve from this log (because the device size is correct): this seems to me to be a different SD card bug than #1339.  Though it was also introduced in 3.7.

**Comment by bertogg** [comment]
> ```
> NAME      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
> mmcblk0   179:0    0 477.5G  0 disk 
> mmcblk0p1 179:1    0 477.5G  0 part 
> /dev/mmcblk0: PTUUID="a82557fa-2f29-4817-8cc8-35d8aaece2e9" PTTYPE="gpt"
> /dev/mmcblk0p1: PARTLABEL="primary" PARTUUID="7a5c44de-cdc2-44c7-bc7e-37c78c16d27b"
> mar 03 00:28:32 SDmanuels steamos-automount.sh[2091]: Error mounting /dev/mmcblk0p1: wrong fstype:  - {
> mar 03 00:28:32 SDmanuels steamos-automount.sh[2091]:   "path": "/dev/mmcblk0p1",
> mar 03 00:28:32 SDmanuels steamos-automount.sh[2091]:   "label": null,
> mar 03 00:28:32 SDmanuels steamos-automount.sh[2091]:   "fstype": null
> mar 03 00:28:32 SDmanuels steamos-automount.sh[2091]: }
> ```

According to these logs it sounds as if the sdcard is not formatted. Does it work if you connect it to a computer?

**Comment by manuelpmtsousa** [comment]
I'm sorry, I eventually just reformatted the card and accepted the losses.

If I remember correctly, it didn't show any partitions in Windows storage folder, as Windows didn't even recognize it, other than "existing" in the file manager if I checked there ("existing" since it didn't even show any reading or writing speeds).

I think it might've been one of the recent Deck updates that entangled the SD card's memory, since after reformatting the SD card, it's been running well for a long while now.

**Comment by bertogg** [comment]
Thanks, I guess we can close this issue then.

**Comment by manuelpmtsousa** [comment]
Nevermind @bertogg. With this new update, I forgot to remove the SD card and it went back as being unreadable by the Deck. It seems to be the same bug. I'm going to see if I can check if there is partitions on the SD card on Windows.

**Comment by manuelpmtsousa** [comment]
![image](https://github.com/ValveSoftware/SteamOS/assets/63976222/8c8f1127-7215-4d28-9055-5d170da09607)
Not sure if this is what you wanted, but it shows this. The "Bom estado de funcionamento" means good working state.

**Comment by manuelpmtsousa** [comment]
Nice, that's great Portuguese! :)
Thanks for the quick reply and all the help until now. I executed that script and this was the result: [results testing1.txt](https://github.com/ValveSoftware/SteamOS/files/14891675/results.testing1.txt) I only have a laptop and it's running on Windows, so I ran this from the Deck.

**Comment by bertogg** [comment]
Ok, this is odd, I think that I would need to know a few more details:

1. Your card is inserted in the Steam Deck and you are using it normally.
2. Suddendly after restarting the machine the SD card icon appears and you cannot see your data.

So far this sounds like a known problem (#1339) that will be fixed in SteamOS 3.6. However that problem is relatively minor, if the user ejects the card and inserts it again then everything works.

In you case however it seems that the data is gone.

What did you do exactly when the SD card icon appeared? Do you eject the card, did you go to desktop mode and try to do something with it, ...

**Comment by manuelpmtsousa** [comment]
Sorry for the late reply, I forgot to check for answers yesterday.

This happened twice just after updating with the SD card on the Deck. It never happened under any other circumstance.

Once, the Deck updated with the card plugged on the entry, the data became unreadable (or deleted, not even sure).

The first time, I tried to check first on Desktop mode, and it's not detectable, but on Gaming mode, it's detected, just the data is not readable. After that, I took it out and put it back in, but to no avail.

The second time, I just took it out immediately after the update once I saw the card had gone through this problem, and then I put it back, but the problem still persisted.

**Comment by bertogg** [comment]
I think that I would need to see a system report, check the instructions here: https://github.com/ValveSoftware/SteamOS

It would be especially useful to see a report created _immediately when the problem happens_, but from what you say you would need to update the OS first and you would lose the data on your SD card. But if it happens again in the future I would appreciate it.

**Comment by manuelpmtsousa** [comment]
Damn, now I noticed I forgot to do that. I remember reading it and going there, but then I must have forgotten about it.

Yeah, no problem, if I have the same SD card storage bug again, I'll make the report on the settings and tag you to this thread again for you to take a look at it.

Anyways, thanks for the help!

**Comment by manuelpmtsousa** [comment]
I did a hard reset, as I wanted to also clear some storage, and formatted the SD card. I let it stay on an update to test it out (on Stable Preview) and it seems the bug doesn't happen anymore.

Thus, the other fix for the SD card must have fixed this one. Closed.
