### ISSUE TITLE
Upgrade distrobox  1.4.2.1 to 1.7

### ISSUE THREAD

**Issue by dnkmmr69420** [ValveSoftware/SteamOS#1417]
#### Your system information

* Steam client version: 1709846872
* SteamOS version: 3.5.17
* Opted into Steam client beta?: [Yes/No] no
* Opted into SteamOS beta?: [Yes/No] no
* Have you checked for updates in Settings > System?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Distrobox is still on an older version while 1.7.0 is out. Don't see any reason not to upgrade it.

**Comment by kisak-valve** [comment]
Hello @dnkmmr69420, without there being a specific issues that need to be addressed, there's no particular reason to micro-manage the full set of packages inherited from upstream Arch.

This package will be updated along with the entire set the next time SteamOS is rebased on a newer snapshot of upstream Arch packages.
