### ISSUE TITLE
Set On Screen Keyboard initial position according to mouse again

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/SteamOS#1433]
#### Your system information

* Steam client version: 1710786209
* SteamOS version: 3.5.17
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Being able to hover over what you were going to type in and not open the keyboard on top of it was a nice feature. I wish to have it back.

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/steam-for-linux/issues/10684.

**Comment by Managor** [comment]
God dammit I keep forgetting I've already made these reports 🤦
At least the new report is more robust.
