### ISSUE TITLE
Discover updates every flatpak in parallel

### ISSUE THREAD

**Issue by Martan404** [ValveSoftware/SteamOS#1437]
When doing Flatpak updates in Discovery it will download and update **_every_** Flatpak at the same time in parallel. This results in long and inefficient update times and in the worst case when updating ~+50 Flatpaks then Discover will crash. In multiple instances I have had Discover updates just freeze until I restart Discover and manually select 3-5 packages at the time to update until every Flatpak is updated.

I am pretty sure that on my desktop system running Arch with KDE Plasma 5 and also 6, the default settings for Discover is to download around 5 Flatpaks in parallel.

**Comment by bertogg** [comment]
What's your OS version ?

**Comment by Martan404** [comment]
My OS version is 3.5.17

**Comment by bertogg** [comment]
Oh, right, that comes with Discover 5.27.5.

SteamOS 3.6 will have this fixed.

**Comment by Martan404** [comment]
Okey, great! Thank you for your time
