### ISSUE TITLE
Add ffmpegthumbs as a preinstalled package

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/SteamOS#1440]
#### Your system information

* Steam client version: 1711147596
* SteamOS version: 3.5.17
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative screenshot: ![Screenshot_20240323_180409](https://github.com/ValveSoftware/SteamOS/assets/42655600/64863eb0-300c-4df0-a0eb-8869de971cb3)
It's annoying that I can't view which video is which at a glance value in desktop mode. To remedy this I suggest adding `ffmpegthumbs` as a preinstalled package on SteamOS.

**Comment by manuelafm** [comment]
@Managor : This is now scheduled for 3.6, thanks for the suggestion.

**Comment by Managor** [comment]
Yes. nice. Working as intended in the latest Preview.

**Comment by kisak-valve** [comment]
Closing per "Enabled thumbnail previews for videos in the file browser" in the [SteamOS 3.6.0](https://store.steampowered.com/news/app/1675200/view/4213757668851885208) update.
