### ISSUE TITLE
Make most commonly used terminal commands browseable in recovery mode

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/SteamOS#1459]
#### Please describe your issue in as much detail as possible:
Add the most commonly used commands into the bash history file on the recovery image so that the user can browse them with the dpad without needing a keyboard. Sadly I can't remember what commands I used in the recovery image when I used it so someone would need to go through that process to list them.

#### Steps for reproducing this issue:

1. Create a Steam Deck recovery image
2. Boot it
3. Go to the terminal and press up on the dpad

#### Result
Nothing happens

#### Some commonly used commands should appear.

**Comment by kisak-valve** [comment]
Hello @Managor, booting off a recovery image is standalone and can't (and shouldn't) be influenced by the local system user on the SSD. This is one of the natures of the medium that bash history is not available.

**Comment by Managor** [comment]
That is not what I intended with this request. What I meant was that the image would contain an edited bash history file which would allow for quick access.
