### ISSUE TITLE
Steam Deck OLED - Wireless Xbox Controller stops waking system after it's been rebooted

### ISSUE THREAD

**Issue by BirbObserb** [ValveSoftware/SteamOS#1460]
#### Your system information

* Steam client version: 1710458266
* SteamOS version: 3.5.17
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
After the Steam Deck has been restarted, a paired Xbox controller will no longer wake the device over Bluetooth without being unpaired and then paired again in the Bluetooth settings menu. It will then work properly and wake the device until the system is restarted again. The controller must be repaired every time the Steam Deck is restarted.

I've tested this issue and replicated it with two recent Xbox controllers (both patched with their latest firmware). However, the issue does not occur with an 8bitdo SN30Pro controller paired to the device, which will continue to wake the device after reboot. 

I've tested this docked in the official Steam Deck Dock and undocked, but in the actual use case, it's been docked every time (since I don't normally use a controller undocked). 

#### Steps for reproducing this issue:

1. Pair an Xbox controller to the Steam Deck OLED
2. Put the device in sleep mode. The controller's guide button should wake it.
3. Reboot the Steam Deck
4. Put the Steam Deck into sleep mode
5. The Xbox Controller's guide button will no longer wake the Steam Deck until it is unpaired and repaired.

**Comment by Mowntana** [comment]
I have the same problem since the begining with Steam Deck Oled and Xbox Series X controller. Always on stable branch.

**Comment by AudioEmu** [comment]
Bumping because I have the same issue with my 1tb OLED and would love to wake with the controller

**Comment by fawktop** [comment]
Limited edition steamdeck. never been woken up by my x series controllers (latest firmware)

from 13th june patch notes (stable);

'Added a per-device toggle to Settings->Bluetooth that controls whether a device is allowed to wake SteamDeck from sleep.' 

Option is not there for my controllers

**Comment by Inkerlink** [comment]
I can confirm I have this issue too, exact same behaviour. 
Can only wake with bluetooth using a Series X controller after re-pairing it. 
If I shut down or reboot Steam Deck, then wake with bluetooth won't work until I make the Steam Deck forget the controller, then re-pair it once again. 
Here is my Steam Deck OS info:
![20240614204834_1](https://github.com/ValveSoftware/SteamOS/assets/97848426/b25f2559-1f07-4544-9a0b-83b034a07a8a)

**Comment by MrDanDHotDogMan** [comment]
Same issue with 2 different Series X controllers and and Elite 2 controller, all have up to date firmware. The problem is the same whether I am in the SteamOS Beta build or SteamOS Stable build.

**Comment by neil-119** [comment]
Confirmed problem here as well with the latest firmwares.

**Comment by rchristensen** [comment]
FYI, my Series X and Elite 2 controllers now wake the Steam Deck OLED on SteamOS 3.6.8 (beta channel).

**Comment by BirbObserb** [comment]
> FYI, my Series X and Elite 2 controllers now wake the Steam Deck OLED on SteamOS 3.6.8 (beta channel).

That's promising! Just to confirm, that's after a system reboot?

**Comment by rchristensen** [comment]
Yes, the 'allow to wake ' toggle is even there.

**Comment by Rafficer** [comment]
Can confirm, SteamOS 3.6.8 (Beta) works with XBOX Series X Controller, even after reboots.
It also shows the toggle on my XBOX One Controller, but I didn't try it there, but guessing it works.

**Comment by BirbObserb** [comment]
This now appears to be fixed in the latest stable release! After powering off and back on, the controller was able to wake the system. Great update!
