### ISSUE TITLE
Bitstream output

### ISSUE THREAD

**Issue by dborel** [ValveSoftware/SteamOS#1471]
My TV supports HDR, but my amplifier doesn't. So I run HDMI from my Steam Deck to my TV and then SP/DIF to my amplifier. SP/DIF and HDMI ARC only support stereo PCM or bitstream Dolby Digital or DTS. It would be nice if my Steam Deck could output any multichannel format supported by SP/DIF. There are real-time encoders for AC-3 or even Dolby Pro-Logic 2, which has pretty good sound quality. Without this, I cannot simultaneously use HDR and surround sound.

**Comment by kisak-valve** [comment]
Hello @dborel, this is functionally the same issue as #989. Closing in favor of the older issue report.

**Comment by mike4president** [comment]
Not sure if this is the same issue, but I really need bitstream Dolby audio output, since my OLED TV can only pass through Dolby and not multichannel PCM.
