### ISSUE TITLE
The latest steam beta client seems to have a NVIDIA encoding issue

### ISSUE THREAD

**Issue by WENGXUEZHI** [ValveSoftware/SteamOS#1476]
ISSUE:
I think steam beta updated changed something of streaming encoder of NVIDIA cards. Steam link app (both android and windows) cannot keep the same FPS as PC when the game FPS is closed to 120 and gets a significant frame loss when game FPS is higher than 120. I found this issue after steam beta updated on Mar 8th and it do not exist in latest steam non-beta (Mar 7th), steam link app can always keep the same FPS as PC even the game FPS is up to 120. I tested this issue in different games, different NVIDIA cards under a local network streaming, they all got this problem, so I think it is not caused by a personal reason.

Test conditions:
OS: Windows 11
PC CPU: Intel i9-12900ks
PC GPU: NVIDIA RTX 4090 24G (so most games can run up to 120 FPS in 4k) or laptop RTX 3080
Steam client: all beta versions after updated on Mar 8th
Steam link app: the latest beta version on android or windows
Streaming network: local network through 5G wifi6 (Extremely stable)

STEPS:
Start steam link app on android phone or windows under a local network (5G wifi6)
Select a game and start

RESULTS:
Once the game FPS in PC is higher than 120, steam link app gets a significant FPS loss, please check these videos for detail:
youtu.be/cIwXbj1G1H4?si=o3ydNG72mSvBHvbR, youtu.be/FrAkqzMrOlw?si=d_1GhJrEvO3ro8vW.

So now no games can run at 120 FPS in steam link app through steam beta even you have a NVIDIA 4090 cards. If so, what a waste of NVIDIA 4090 graphics card and the 120 FPS and 144 FPS options in the steam link app make no sense.

EXPECTED:
Remote play through steam beta should maintain the same FPS as PC if the streaming conditions are excellent enough, just like what steam non-beta can do. Please check it out! Thanks a lot!

**Comment by kisak-valve** [comment]
Hello @WENGXUEZHI, this issue tracker is for issue with the SteamOS platform. Similar to https://github.com/ValveSoftware/steamlink-sdk/issues/41, please report issues you see with the Steam Link app on the community forums at https://steamcommunity.com/app/353380/discussions/.
