### ISSUE TITLE
Add non Steam game from within Big Picture mode

### ISSUE THREAD

**Issue by Manuel-Kehl** [ValveSoftware/SteamOS#148]
As I am using a few non Steam programs like SuperTuxKart or XBMC, it would be nice to have an option for easily adding those without tweaking lightdm.conf + rebooting every time.

**Comment by elmat0** [comment]
I cannot for the life of me get supertuxkart to show up as an addable game. The .desktop is stored in /usr/share/applications. Here is the .desktop contents. Any tips?
```
[Desktop Entry]
Name=SuperTuxKart
Version=1.0
Icon=supertuxkart
GenericName=A kart racing game
GenericName[de]=Ein Kart-Rennspiel
GenericName[fr]=Un jeu de karting
GenericName[gl]=Xogo de carreiras con karts
GenericName[ro]=Un joc de curse cu carturi
Exec=supertuxkart --log=file
Terminal=false
StartupNotify=false
Type=Application
TryExec=supertuxkart
Categories=Game;
```

**Comment by ProfessorKaos64** [comment]
@elmat0 , see #424 for notes. Since it's inception, this features does not allow spaces in the Exec= line. A workaround is to create a script and reference it:

Script:
```
#!/bin/bash
supertuxkart --log=file
```

Desktop file
```
[Desktop Entry]
Name=SuperTuxKart
Version=1.0
Icon=supertuxkart
GenericName=A kart racing game
GenericName[de]=Ein Kart-Rennspiel
GenericName[fr]=Un jeu de karting
GenericName[gl]=Xogo de carreiras con karts
GenericName[ro]=Un joc de curse cu carturi
Exec=/absolute/path/supretuxkart.sh
Terminal=false
StartupNotify=false
Type=Application
TryExec=supertuxkart
Categories=Game;
```

**Comment by madmodderx** [comment]
Are you sure you can't use "\ " to add the space character?
