### ISSUE TITLE
I'm disappointed that Valve is attempting to fix the mura effect in an update instead of the aggressive PWM with a DC-Dimming option :(

### ISSUE THREAD

**Issue by Sightlyjester** [ValveSoftware/SteamOS#1482]
![fyi-the-mura-compensation-update-is-now-officially-added-on-v0-8f0ppkvn3eoc1](https://user-images.githubusercontent.com/105895386/325685980-1923d4f1-bab3-4e1f-a9c0-480479527380.png)
              I'm disappointed that Valve is attempting to fix the mura effect in an update instead of the aggressive PWM with a DC-Dimming option :(

A notable percentage of users, though small compared to the 100% of Steam Deck OLED owners, are sensitive to OLED screens with aggressive PWM. Many modern OLED displays are bad for the eyes because their brightness regulation method employs very aggressive rapid on-off cycles of the screen, which strain the eyes and can cause dizziness and headaches.

When the Steam Deck OLED was released, I analyzed its screen with additional instruments, which indicated that its screen is one of the worst on the market for people sensitive to vision issues. Currently, a large number of OLED screens have DC dimming, low blue light, or PWM frequencies so high that they are imperceptible to the eye. However, the Steam Deck OLED screen lacks any of these measures to protect the eyes. Unfortunately, this harms the visual and overall health of people, even those who are not as sensitive to PWM as myself, because the aggressive flickering is an objective fact that affects the eye in every gaming session.

Now I see that another significant issue, albeit less perceptible to most people, will be patched to reduce it in the future on the Steam Deck OLED through software. However, we haven't heard a single message from Valve, its developers, or anyone in charge regarding the PWM issue. Not a word from Steam support either. I'm disappointed because now I know that they could also patch this through software, as they have done with the mura effect, but they don't because the affected individuals 'aren't important enough and don't raise their voices loud enough.' I had to return my Steam Deck OLED after a week and buy an LCD instead, but I feel terrible for not being able to enjoy that incredible OLED screen due to it being so unbearable for my eyes.

For anyone who thinks this issue is subjective or doesn't exist, I conducted a very scientific and detailed analysis months ago, and I published it here: 
https://www.reddit.com/r/SteamDeck/comments/1882kys/analysis_of_the_pwmflickervisual_fatigue_of_the/

This same issue in Reddit of the lack of communication and support of the pwm problem with Valve but the exiiting support of the effect mura and update of software: 
https://www.reddit.com/r/SteamDeck/comments/1caksco/im_disappointed_that_valve_is_attempting_to_fix/

_Originally posted by @Sightlyjester in https://github.com/ValveSoftware/SteamOS/issues/1392#issuecomment-2077592388_

**Comment by jazir555** [comment]
> Hello @Sightlyjester, these are unrelated topics and this is not a general forum. Closing because there isn't an actionable issue in this issue report.

The actionable issue is "aggressive PWM with a DC-Dimming option".

Did you not even read the issue he posted?

**Comment by Kunailby** [comment]
Why has valve not connected on this yet ? Why is valve ignoring this ?
