### ISSUE TITLE
Steam desktop mode font rendering looks awful in stable Steamdeck OLED

### ISSUE THREAD

**Issue by lifeiscontent** [ValveSoftware/SteamOS#1484]
#### Your system information

* Steam client version:
* SteamOS version: 3.5.19
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

#### Steps for reproducing this issue:

1. download chrome
2. browse the web
3. watch your eyes bleed

#### Steps for fixing:

update `~/.fonts.conf`

```diff
 <?xml version='1.0'?>
 <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
 <fontconfig>
+ <match target="font">
+  <edit mode="assign" name="rgba">
+   <const>rgb</const>
+  </edit>
+ </match>
+ <match target="font">
+  <edit mode="assign" name="hinting">
+   <bool>true</bool>
+  </edit>
+ </match>
+ <match target="font">
+  <edit mode="assign" name="hintstyle">
+   <const>hintslight</const>
+  </edit>
+ </match>
  <dir>~/.fonts</dir>
+ <match target="font">
+  <edit mode="assign" name="antialias">
+   <bool>true</bool>
+  </edit>
+ </match>
 </fontconfig>```

**Comment by Sunspark-007** [comment]
I can help you with this because I've spent a lot of time with this.

To start with, don't use rgb in the rgba section. Neither the lcd or oled ones are rgb. The lcd one is v-bgr (because it's rgb rotated) and the oled is pentile. Instead, what you should use is "none" which would be greyscale.

You should also experiment with not using hinting either, depending on the font being used, you might have better results if it's not trying to fit to a pixel grid when you're not using a stripe layout.

**Comment by lifeiscontent** [comment]
@Sunspark-007 do you have a config I can copy/paste I'm so far removed from this kind of stuff that I have no idea what you're talking about 😅

**Comment by Sunspark-007** [comment]
Sure, here is my .fonts.conf

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <dir>~/.fonts</dir>
 <match target="font">
  <edit name="lcdfilter" mode="assign">
   <const>lcdnone</const>
  </edit>
 </match>
 <match target="font">
  <edit name="autohint" mode="assign">
   <bool>false</bool>
  </edit>
 </match>
 <match target="font">
  <edit name="hinting" mode="assign">
   <bool>true</bool>
  </edit>
 </match>
 <match target="font">
  <edit name="hintstyle" mode="assign">
   <const>hintfull</const>
  </edit>
 </match>
 <match target="font">
  <edit name="rgba" mode="assign">
   <const>none</const>
  </edit>
 </match>
 <match target="font">
  <edit name="embeddedbitmap" mode="assign">
   <bool>false</bool>
  </edit>
 </match>
 <match target="font">
  <edit name="antialias" mode="assign">
   <bool>true</bool>
  </edit>
 </match>
</fontconfig>
```
In addition to that, in the directory /home/deck/.config/plasma-workspace/env make a textfile ending in .sh, name doesn't matter, can be variables.sh if you like. Add these following variables into it.

```
export FREETYPE_PROPERTIES='cff:no-stem-darkening=0 autofitter:no-stem-darkening=0 type1:no-stem-darkening=0 t1cid:no-stem-darkening=0'
export gtk-hint-font-metrics=1
export QT_ENABLE_HIGHDPI_SCALING=0
export KWIN_DRM_PREFER_COLOR_DEPTH=24
```

Save, reboot, and see how it is for you.

PS. That last one, KWIN_DRM_PREFER_COLOR_DEPTH value of 24 is for 8-bit and value of 30 is for 10-bit. I am skeptical that a value of 30 will be better with the current setup, but you can experiment and see both now and later.

**Comment by bertogg** [comment]
With SteamOS 3.6.8 I don't see anything wrong with the fonts, can anyone confirm if the problem is still there for them?

**Comment by lifeiscontent** [comment]
@bertogg I'll look into it later today.

**Comment by lifeiscontent** [comment]
it looks like after a re-imaging of Steam OS there is no longer a `~/.fonts.conf` in the system, and whatever is currently being set as the default looks pretty great on my Samsung Odyssey G9 Monitor as well as the steam deck screen.
