### ISSUE TITLE
SteamOS 3.7 main branch no audio output

### ISSUE THREAD

**Issue by wantija** [ValveSoftware/SteamOS#1489]
#### Your system information

* Steam client version: 1714520927
* SteamOS version: 20240502.1000
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Using Main branch 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
SteamOS Main branch has no audio output devices.

#### Steps for reproducing this issue:

1. update to SteamOS 3.7 Main Branch
2. try adjustibg volume with volume buttons
3.notice no audio output devices are available

**Comment by cosmic-skier** [comment]
Same issue here. No audio devices present in sound manager but lspci is showing the pci audio controller and lsmod shows k modules present

Steam client version: 1714520927
SteamOS version: 20240502.1000
Opted into Steam client beta?: Yes
Opted into SteamOS beta?: Using Main branch
Have you checked for updates in Settings > System?: Yes

Bit more info:

lspci | grep Audio
04:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt Radeon High Definition Audio Controller
04:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] ACP/ACP3X/ACP6x Audio Coprocessor (rev 50)
 
lsmod | grep snd
snd_soc_acp5x_mach     28672  0
snd_acp5x_i2s          12288  2
snd_acp5x_pcm_dma      12288  1
snd_sof_amd_vangogh    16384  0
snd_sof_amd_acp        69632  1 snd_sof_amd_vangogh
snd_sof_pci            24576  1 snd_sof_amd_vangogh
snd_sof_xtensa_dsp     16384  1 snd_sof_amd_acp
snd_hda_codec_hdmi     94208  1
snd_sof               450560  2 snd_sof_amd_acp,snd_sof_pci
snd_hda_intel          65536  0
snd_soc_cs35l41_spi    12288  2
snd_sof_utils          16384  1 snd_sof
snd_soc_cs35l41        61440  1 snd_soc_cs35l41_spi
snd_intel_dspcfg       32768  2 snd_hda_intel,snd_sof
snd_soc_wm_adsp        57344  1 snd_soc_cs35l41
cs_dsp                 86016  1 snd_soc_wm_adsp
snd_hda_codec         225280  2 snd_hda_codec_hdmi,snd_hda_intel
snd_soc_nau8821        65536  2 snd_soc_acp5x_mach
snd_intel_sdw_acpi     16384  1 snd_intel_dspcfg
snd_soc_cs35l41_lib    45056  2 snd_soc_cs35l41_spi,snd_soc_cs35l41
snd_hda_core          151552  3 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec
snd_pci_acp5x          16384  0
snd_soc_core          458752  7 snd_acp5x_i2s,snd_soc_nau8821,snd_soc_wm_adsp,snd_sof,snd_acp5x_pcm_dma,snd_soc_cs35l41,snd_soc_acp5x_mach
snd_acp_config         20480  2 snd_pci_acp5x,snd_sof_amd_vangogh
snd_hwdep              20480  1 snd_hda_codec
snd_compress           28672  2 snd_soc_wm_adsp,snd_soc_core
ac97_bus               12288  1 snd_soc_core
snd_pcm_dmaengine      16384  1 snd_soc_core
snd_pcm               208896  14 snd_sof_amd_acp,snd_soc_nau8821,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_sof,snd_acp5x_pcm_dma,snd_compress,snd_soc_core,snd_sof_utils,snd_hda_core,snd_soc_cs35l41,snd_soc_acp5x_mach,snd_pcm_dmaengine
snd_soc_acpi           16384  2 snd_sof_amd_acp,snd_acp_config
snd_timer              53248  1 snd_pcm
snd                   155648  10 snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_pcm,snd_soc_acp5x_mach
soundcore              16384  1 snd
 
ps -A | grep pipewire
   1665 ?        00:06:29 pipewire-pulse

**Comment by cosmic-skier** [comment]
Main branch update 20240503.1000 was just pushed and has resolved my issue.
