### ISSUE TITLE
On screen keyboard not showing in desktop mode on main 3.7 

### ISSUE THREAD

**Issue by ezzinekaemel** [ValveSoftware/SteamOS#1495]
#### Your system information

* Steam client version: Main Beta 3.7
* SteamOS version: 3.7
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

In desktop mode, steam+X makes the screen flicker to bring up the on screen keyboard but does mot bring it up. The second time I, it does not flicker and simply does not bring the on screen keyboard up. 

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @ezzinekaemel, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/10851. Closing as a duplicate.
