### ISSUE TITLE
Double Inputs on Bluetooth-connected Dualsense face buttons when connected to HDMI

### ISSUE THREAD

**Issue by omfgnuts** [ValveSoftware/SteamOS#1500]
This is really a weird issue, happened twice now.

So, I ran main update channel for a while, but since the last one to two versions of "main" branch builds right before the first 3.7 release I've started getting double inputs when using Bluetooth gamepad while connected to HDMI to TV. My controllers are fine, re-pairing doesn't help, etc etc.

So whenever I press up-down-left-right on d-pad or any of the other buttons on a wirelessly connected dualsense gamepad, both in UI and in games ONLY when connected to the TV via HDMI (JSAUX dock and a macbook official dock, always worked fine), all my inputs get doubled. In games, parts of the gamepad buttons start to act weird. i.e i start a Binding of Isaac run, and i try to press options button, and it registers as a different gamepad (?) and opens a menu for a second player to join, in the UI if I, for example, select the power menu and press X, my console goes to sleep, due to UI reacting on X+X, selecting power menu and selecting a sleep in the menu. The joysticks work just fine, single inputs, can scroll the menus. The built-in steamos gamepad tester also registers only 1 press.

And I had to roll back to the preview channel. It worked just fine for a while.

Now the newest update in Preview channel, the big one, released just now (3.06 20240509.100) that brought new mesa (my main kinda suspect for some reason?) and a kernel got this issue too.

Any logs I can provide to help debug the issue or something else? Did I choose a proper repo to report this issue, or this sould go to https://github.com/ValveSoftware/steamos?

**Comment by kisak-valve** [comment]
Previously mentioned at https://github.com/ValveSoftware/SteamOS/issues/1326#issuecomment-2101726910.

**Comment by omfgnuts** [comment]
> Previously mentioned at [#1326 (comment)](https://github.com/ValveSoftware/SteamOS/issues/1326#issuecomment-2101726910).

Damn, I've looked through the threads but didn't see this one, thank you for pointing it out. At least I'm not insane :D

Feeling tempted to try the main branch now that some kind of fix is mentioned.

**Comment by omfgnuts** [comment]
Disabling HDMI CEC fixed it for me

**Comment by Plagman** [comment]
A fix is in main packages for this, will be in next preview.

**Comment by sonic2kk** [comment]
The CEC double inputs have been fixed for me, however now CEC does not work at all.
