### ISSUE TITLE
Mesa not updated to 24.1

### ISSUE THREAD

**Issue by rafrafek** [ValveSoftware/SteamOS#1503]
#### Your system information

* Steam client version: latest beta
* SteamOS version: latest main
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
The latest update for the main channel was expected to include Mesa 24.1, but after updating, I still have Mesa 24.0.x.

#### Steps for reproducing this issue:

1. Take the Steam Deck LCD in your hands.
2. Switch to the main update channel.
3. Update SteamOS.
4. Navigate to settings and check the GPU driver version.

**Comment by kisak-valve** [comment]
Hello @rafrafek, this is a minor version inconsistency between the Vulkan and OpenGL driver which are packaged separately on SteamOS. Both packages have been updated, and a more conservative version was picked for the OpenGL driver.

Functionally, this isn't a bug.
