### ISSUE TITLE
After disconnecting from external monitor, Deck's internal screen stays off instead of switching display

### ISSUE THREAD

**Issue by dangerousdonut** [ValveSoftware/SteamOS#1504]
#### Your system information

* Steam client version: 1714854927
* SteamOS version: 3.6
* Dock Firmware Version: 0.13.15.124
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
When unplugging the Steam Deck from a dock that connects it to an external monitor, I expect the primary display to switch back to the Deck's internal screen. 

However, since updating to SteamOS 3.6 in the current Preview branch, what happens instead is that the Deck's screen stays off if you disconnect it from an external monitor. There is still sound though.

Putting the Deck to sleep and waking it will not turn the display back on. Only a reboot fixes it.

Conversely, plugging the Deck into a dock while it was on and an image was displayed on it will properly transfer primary display over to a monitor. 

This issue is only present in game mode. In desktop mode the display switches without issue. The dock in use here is Valve's Steam Deck Docking Station. The external monitor is connected over Displayport.

After re-imaging the Deck, the issue was not present on the stable branch while the Dock was still on FW 0.13.15.124. It began again after the system was updated to SteamOS 3.6. This seems to point to 3.6 rather than the new Dock firmware as the source of the bug.

#### Steps for reproducing this issue:

1. Connect Steam Deck to a dock and external monitor
2. Ensure the Deck is in game mode
3. Unplug the USB-C cable to the Deck while an image is being output to the display

**Comment by Managor** [comment]
I have this issue as well.

**Comment by Grazgamer** [comment]
And me

**Comment by Managor** [comment]
I pinpointed the issue (at least for me). In the manual external display resolutions if I select anything over 720p the internal screen won't turn on after disconnect but anything below that resolution works fine
![image](https://github.com/ValveSoftware/SteamOS/assets/42655600/1dc319ef-67dd-4c1c-ae12-355d8603ebd2)

**Comment by dangerousdonut** [comment]
> I pinpointed the issue (at least for me). In the manual external display resolutions if I select anything over 720p the internal screen won't turn on after disconnect but anything below that resolution works fine !

Nice find! I was also able to get it to switch primary display at 1280x720, and ever since it did that successfully, it now works with any other resolution. It continued to function as expect after a sleep and wakeup cycle and after a restart. Maybe re-check it on your end

**Comment by jbbandos** [comment]
Same issue on Steam Deck OLED with 3.6.x (up until SteamOS 3.6.3 at least), and setting the external resolution to 1280x720@60 allows the inner screen to turn back on when the external is disconnected. However, I can't get it to work with any higher external resolution.
And desktop mode works with both screens on, until now my workaround was to switch to desktop mode, disconnect the external screen, and switch back to gaming mode.

**Comment by micsama** [comment]
me too

**Comment by matte-schwartz** [comment]
You can recover from this with an external keyboard and switching to a TTY (terminal type) window with Ctrl + Alt + F6 and then switching back to your main session, usually on TTY 1, with Ctrl + Alt + F1.

**Comment by drake90001** [comment]
I have the same issue. undocking at all results in a black screen.

I also cannot enable or disable HDR on my TV.

**Comment by mkaliaha** [comment]
Same issue. Mine is Steam Deck OLED.
Also, when I reconnect it to the monitor for the 2nd time, the internal screens starts to fill with yellow artifact-y lines right-to-left. While the image on the monitor is OK.
Works without any issues on 3.5.19.
I'm just plugging my monitor straight with type c cable.

**Comment by drake90001** [comment]
Yeah, yellow artifact lines here too sometimes. Good to know it’s not just
me.

**Comment by matte-schwartz** [comment]
This should be fixed in an upcoming steamos build. https://github.com/ValveSoftware/gamescope/commit/e31b8dea137d2cedd4cf71fede560feb2ad3ffc5 fixes this on my setup.

**Comment by drake90001** [comment]
Awesome, thanks!

**Comment by Managor** [comment]
This is fixed in Main but not in Preview

**Comment by matte-schwartz** [comment]
Should be fixed with https://store.steampowered.com/news/app/1675200/view/6500469346411814006?l=english

**Comment by Managor** [comment]
Yep. It's fixed. You can sort of trigger this if you unplug the dock immediately after the screen turns off after plugging it in. Even then the screen stays off for only 7 or so seconds.

**Comment by dangerousdonut** [comment]
Yep, I haven't encountered the issue since updating to 3.6.10.

**Comment by kisak-valve** [comment]
Closing per the last several comments.
