### ISSUE TITLE
SteamOS fails to boot on some boot attempts after an update

### ISSUE THREAD

**Issue by patrykk114** [ValveSoftware/SteamOS#1514]
#### Your system information

* Steam client version: 1715635533
* SteamOS version: 3.5.19
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [Yes](I did it after experiencing this issue repeatedly, reverted back to stable after it didn't fix the issue)
* Have you checked for updates in Settings > System?: [Yes]

#### SteamOS fails to boot on some boot attempts, hard reset gets it to boot
shutting down from desktop mode seems to fix it for longer

this issue started to appear after an update to 3.5.19

#### Steps for reproducing this issue:

1. start up steamdeck
2. restart it repeatedly
3. it will eventually hang on boot screen

**Comment by patrykk114** [comment]
I would also like to add that I don't use any plugins

**Comment by chuliang007** [comment]
Same problem for my OLED device. It appears '4 failures' for 3.6.x update in secure start after applying 'restart'.

**Comment by infernn** [comment]
Same problem here with LCD model. Sometime i got Stuck on logo and i have to force restart the deck. Tried with stable and beta and i got the same problem

**Comment by KikitheKing** [comment]
Same here on Oled.
I guest it started with Steam Client update from May 16th.
Never had this issue before and it’s very annoying !

**Comment by dangerousdonut** [comment]
I had this issue when I switched from Stable to Preview branch a few weeks ago, and it persisted in the Preview branch. Re-imaging the Deck got rid of the issue.

**Comment by lostgoat** [comment]
A fix for this issue is available as part of a steam client update:
https://steamcommunity.com/games/1675200/announcements/detail/4177730135023930555

**Comment by patrykk114** [comment]
Issue seems to be gone after downloading the update mentioned above, I restarted my deck around 20 times and it managed to boot every time

**Comment by dangerousdonut** [comment]
Again, similar but not quite: with recent update from 3.6.3 to 3.6.4, the Deck didn't reboot properly. The device is on, but the screen is off but touchpad haptics are responsive. It seems to stay in that state indefinitely until it's hard powered down.

**Comment by kisak-valve** [comment]
Closing as fixed.

Hello @dangerousdonut, if you're still seeing a follow up issue, please open a new issue report with the details.
