### ISSUE TITLE
Waking up Steam Deck while opening a non-steam app on Deck and opening multiple non-steam games on PC through Steam causes Steam on PC to exit and to close all PC non-steam games

### ISSUE THREAD

**Issue by Evlos** [ValveSoftware/SteamOS#1532]
#### Your system information

* Steam client version: 1716584667
* SteamOS version: 3.5.19
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

#### Steps for reproducing this issue:

1. Opening a non-steam app on Deck and put deck to sleep
2. Opening multiple non-steam games on PC through Steam
3. Waking up Steam Deck causes Steam on PC to exit and to close all non-steam PC games

**Comment by kisak-valve** [comment]
Hello @Evlos, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9074. Closing as a duplicate.
