### ISSUE TITLE
Cursor randomly changes it's position in Game Mode when external mouse is plugged in

### ISSUE THREAD

**Issue by kajetan000** [ValveSoftware/SteamOS#1533]
#### Your system information

* Steam client version: 1716584667
* SteamOS version: 3.5.19
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
When scrolling in **Game Mode** on Steam Store using **an external mouse** and **an external monitor**, the mouse cursor sometimes changes its position randomly to the bottom right corner of the screen. I've noticed it in Steam Store's wishlist, but I also recall it happening in games library. It makes using an external mouse quite frustrating. I'm using an official Valve docking station and a 1080p display.

_Side note:_ Another thing worth pointing out about using Game Mode with keyboard and mouse is that there doesn't appear to be a keyboard shortcut to open either right or left menu. This means that if a user wants to open any of those menus while playing with an external monitor/mouse/keyboard, they need to reach for the physical STEAM or Three Dots buttons on the Steam Deck. This should be possible using a super (Windows) key.

#### Steps for reproducing this issue:

1. Plug in an external mouse and monitor.
2. Scroll anywhere in the Steam Store on Game Mode for some time (for example, in wishlist).
3. The cursor should randomly move to the bottom right corner of the screen.

**Comment by kisak-valve** [comment]
Hello @kajetan000, this issue is already being tracked at #1093.

Closing as a duplicate.
