### ISSUE TITLE
[Feature Request] Valve said no to Auto HDR (which breaks my heart) but can we have frame generation?

### ISSUE THREAD

**Issue by Deus-nsf** [ValveSoftware/SteamOS#1543]
Since the recent release of Lossless Scaling Frame Generation and it's new AI model that honestly makes the software very usable even at moderately low framerates, Linux gaming is left behind.

The decision to not implement an auto HDR toggle at the gamescope level for the OLED deck was... very concerning, so I'm wondering if Valve plan to not do what the community wants once more or if they actually want Linux to compete with Windows.

Thanks.

**Comment by kisak-valve** [comment]
Hello @Deus-nsf, this request is already being tracked at #1499. Closing as a duplicate.
