### ISSUE TITLE
[3.6.4-20240612.101] Left track pad makes repeated clicking noises and stops working every 2-3 seconds

### ISSUE THREAD

**Issue by popsUlfr** [ValveSoftware/SteamOS#1544]
#### Your system information

* Steam client version: Stable
* SteamOS version: 3.6.4-20240612.101
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: Yes 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Hello, since the new SteamOS update my left track pad stops working randomly every 2-3 seconds with a clicking noise. It then works again after 1 second or so. The clicking noise repeats forever randomly every 1-3 seconds.

Closing the Steam client in desktop mode makes this behaviour stop.

#### Steps for reproducing this issue:

1. Update to 20240612.101
2. Notice problem with left trackpad while the Steam client is open

**Comment by matte-schwartz** [comment]
Hmm this looks very similar to a commit in `jupiter-hw-support` with new controller firmware pushed a few days ago: 

`Controller FW: Fix issue w/ lingering trackpad 'tick's on left trackpad`

maybe it's only made it to Main and not Preview yet?

**Comment by Sanaki** [comment]
Preview 3.6.5 from today fixes the issue.

**Comment by popsUlfr** [comment]
I can confirm that **3.6.5-20240614.100** fixed the issue for me. Thank you very much.
