### ISSUE TITLE
Dual Boot DVD can't handle two versions of SteamOS

### ISSUE THREAD

**Issue by SimonBiggs** [ValveSoftware/SteamOS#155]
If you create a second install of SteamOS with the dual boot DVD it has a kernel panic after the recovery image is captured.

**Comment by ProfessorKaos64** [comment]
While I can understand that this is a possible bug (i'm not a dev on this git repo), why would you ever want two installs of SteamOS on the same machine? I'm trying to understand the motivation there.

**Comment by ProfessorKaos64** [comment]
please recheck this and close. SteamOS is not designed for this kind of behavior. It is possible to do this with two hard drives, attach drive 1 install SteamOS ver 1, detach, attach drive 2, install SteamOS ver 2. Reconnect drives, and update grub. os-proper will find both installs.

**Comment by SimonBiggs** [comment]
If I remember correctly I wanted a "stable" install and a "development/testing" install. If the dev/testing install broke I would be able to fall back to the stable.

However I gave up after too many issues some time ago.
