### ISSUE TITLE
Radial Menu Disappears

### ISSUE THREAD

**Issue by JacobAboytes** [ValveSoftware/SteamOS#1569]
#### Your system information

* Steam client version: 1719259903
* SteamOS version: 3.5.17
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes I’ve tried so many things and always get an error code when I try to apply the update… 

#### Please describe your issue in as much detail as possible:

I created a radial menu for the game Team Fortress 2, on the left trackpad. The menu would appear whenever I touched down on the trackpad, and helped do in game actions like Picking a class, taunting, etc… well I expected it to always work, but after playing a bit in TF2, the menu ends up not appearing at all. It still seems to do the functions whenever I click down, but the radial menu does not appear at all when I place my finger on the trackpad. 

#### Steps for reproducing this issue:

1. Download Team Fortress 2
2. Go into controller settings (in Game Tab) 
3. Go to left trackpad 
4. Change the behavior of the trackpad to be a radial menu
5. Customize the radial menu and add a in game action like taunting 
6. Now In TF2 press Find a Game
7. Click Casual
8. Click start search
9. Now once the match loaded and you’ve selected your character, the radial menu should appear and work when you use the left trackpad. 
10. Play for a bit, it might work for a match or two, then suddenly the radial menu will stop appearing.
11. Restarting the game does nothing and the radial menu is still invisible  
12. Restating the steam deck is the only solution but the radial menu will disappear in the same way all over again after a bit of playing

**Comment by kisak-valve** [comment]
Hello @JacobAboytes, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9832. Closing as a duplicate.
