### ISSUE TITLE
It's impossible to disable the build in vsync / go above the refresh rate since the latest beta

### ISSUE THREAD

**Issue by DreamboxMinerva** [ValveSoftware/SteamOS#1572]
Steam client version: 1719453458
SteamOS version: 3.6.8
Opted into Steam client beta?: Yes
Opted into SteamOS beta?: Yes
Have you checked for updates in Settings > System?: Yes

With the latest beta update which is the one where you guys forced the unified frame limit slider on us, it is now impossible to go above 60 FPS if you have a LCD or 90 with the OLED,

It does not matter which settings we turn on or off, allow tearing, disable frame limit, it just don't work, I even managed to make an emulated game run past 100 fps in his software ( I could see it with the emulator osd ) yet my LCD Deck was still stuck at 60 fps.

My guess is, we can't disable the Deck vsync at all, would be nice to have a fix soon, there's some scenario where playing with the framerate completely unlocked can have benefit.

**Comment by kisak-valve** [comment]
Hello @DreamboxMinerva, this issue is already being tracked at #1521. Closing as a duplicate.

**Comment by DreamboxMinerva** [comment]
Oh, ok, thanks for the info !
