### ISSUE TITLE
Request: Update Podman to latest version

### ISSUE THREAD

**Issue by kavishgr** [ValveSoftware/SteamOS#1573]
#### Your system information

* SteamOS version: 3.5.19
* Opted into Steam client beta?: No 
* Opted into SteamOS beta?: NO
* Have you checked for updates in Settings > System?: Yes

**Comment by kisak-valve** [comment]
Hello @kavishgr, this isn't a package that SteamOS devs would micromanage the version. When SteamOS rebases on a newer snapshot of Arch, then podman naturally gets an update as well. Podman 4.9.3 in SteamOS 3.6: https://steamdeck-packages.steamos.cloud/archlinux-mirror/extra-3.6/os/x86_64/podman-4.9.3-1-x86_64.pkg.tar.zst

**Comment by kavishgr** [comment]
Awesome!! Thanks :-)
