### ISSUE TITLE
Dualsense Gyro does not work until Steam Deck is put into Sleep mode

### ISSUE THREAD

**Issue by Chalking** [ValveSoftware/SteamOS#1577]
#### Your system information

* Steam client version: 1721173382
* SteamOS version: 3.5.19
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

When connecting a Dualsense controller to Steam Deck, gyro is not active unless you put the console to sleep once after connecting it, and then it will function as normal.
I looked up a solution for this online a while ago and found the fix by putting it to sleep, so other people are having the same issue and are aware of it. I'm surprised no one has put in a support ticket. This has been an ongoing issue for months.

#### Steps for reproducing this issue:

1. Connect Dualsense to Steam Deck via Bluetooth 
2. Gyro will not be active
3. Put Steam Deck to Sleep
4. Wake Steam Deck from Sleep
5. Reconnect Dualsense to Steam Deck via. Bluetooth 
6. Gyro will now be active

**Comment by kisak-valve** [comment]
Hello @Chalking, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/10328. Closing as a duplicate.
