### ISSUE TITLE
Internal microphone and external microphone jack 3.5mm not work since 3.6.8 beta LCD

### ISSUE THREAD

**Issue by Labestiajake** [ValveSoftware/SteamOS#1581]
#### Your system information

* Steam client version: 1722028579
* SteamOS version: 3.6.8 20240626.100
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] Yes
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

When I updated to the latest version of Steam Os Beta, the internal and external microphone stopped working. Then I went to the stable version and the microphone works, but when I go back to the beta version it no longer works.

#### Steps for reproducing this issue:

1. I enter desktop mode
2. I look at the bar inside the KDE audio menu and it doesn't move when I speak and Steam Chat not detect my voice.
3. I insert the external microphone and it doesn't work either
4. I change to the stable version and check the same and if it works without problems.
5. I went to the beta version and again the internal and external microphone stopped working.

**Comment by Labestiajake** [comment]
Tested on :

- Steam client version: 1722380543
- SteamOS version: 3.6.9 20240807.101 Beta

in this version still problem with microphone.

**Comment by Labestiajake** [comment]
Tested on :

    Steam client version: 1723685248
    SteamOS version: 3.6.9 20240814.100 Beta

in this version still problem with microphone.

**Comment by Labestiajake** [comment]
[systemreport-20240902140105.txt](https://github.com/user-attachments/files/16846928/systemreport-20240902140105.txt)

**Comment by Labestiajake** [comment]
Tested on :

- Steam client version: 1725412627
- SteamOS version: 3.6.12 20240905.101

in this version still problem with microphone.

[systemreport-20240906193703.txt](https://github.com/user-attachments/files/16912360/systemreport-20240906193703.txt)

**Comment by Labestiajake** [comment]
Still bug in:

- Steam client version: 1726683985
- SteamOS version: 3.6.13 20240913.113

[systemreport-20240919091534.txt](https://github.com/user-attachments/files/17056751/systemreport-20240919091534.txt)

**Comment by Labestiajake** [comment]
Still bug in:

- Steam client version: 1726683985
- SteamOS version: 3.6.17 20241003.100

[systemreport-20241004110937.txt](https://github.com/user-attachments/files/17257357/systemreport-20241004110937.txt)

**Comment by Labestiajake** [comment]
Still bug in:

- Steam client version: 1726683985
- SteamOS version: 3.6.19 20241021.100 Stable LCD

[systemreport-20241029205654.txt](https://github.com/user-attachments/files/17563086/systemreport-20241029205654.txt)

**Comment by Taboulet** [comment]
Same

**Comment by Taboulet** [comment]
But i'm not in beta i'm in the stable release

**Comment by Labestiajake** [comment]
> But i'm not in beta i'm in the stable release

The bug remained since 3.6, 4 months ago, they have not fixed it and it remained in the stable version. I updated to version 3.6.20 stable and the error continues. I think it's a kernel problem since the 3.6 preview, if more people don't report the bug I don't think they will fix it.

**Comment by Taboulet** [comment]
I fixed it, try going to desktop mode and in the mics setting either put the microphone at max volume or unmute the 2 other microphones (their names are like "Virtual mic" and "Voice cleaner" or idk i forgot)

**Comment by Labestiajake** [comment]
> I fixed it, try going to desktop mode and in the mics setting either put the microphone at max volume or unmute the 2 other microphones (their names are like "Virtual mic" and "Voice cleaner" or idk i forgot)

You are my hero. I gave him the two microphone options.
![micrófono](https://github.com/user-attachments/assets/4a2839b5-0774-4117-a2b9-752b224ab1bb)

I was with this icon:
![mute](https://github.com/user-attachments/assets/6bc06a41-6693-4986-8f86-6559d8eb1ef7)
I changed it to:
![unmute](https://github.com/user-attachments/assets/100d2571-521f-45e3-bbe3-656921a171c7)

I already have a microphone, I thank you very much for providing the solution.

**Comment by Taboulet** [comment]
No problem, i tried randomly changing settings and when i unmuted it my obs finally showed my mic
