### ISSUE TITLE
Windows drivers???

### ISSUE THREAD

**Issue by hist90** [ValveSoftware/SteamOS#1590]
I really don`t know where I could ask about SD Oled windows drivers there was no update at all on that... Any eta or something on that promise?
While I love the OS in gaming mode I`m not a fan of Linux and as a Desktop environment and as a client who types this on a steam deck oled I`d like to have an answer. 
Thank you!

**Comment by kisak-valve** [comment]
Hello @hist90, this question is out of scope for this issue tracker. Feel free to post it on the [Steam Deck](https://steamcommunity.com/app/1675200/discussions/) community forums.
