### ISSUE TITLE
Quake 2 RTX problems with SteamOS

### ISSUE THREAD

**Issue by KingVulpes** [ValveSoftware/SteamOS#1596]
Has happened with all SteamOS versions but currently I am on SteamOS beta 3.6.9

I've noticed that SteamOS is capping the Quake 2 RTX frame rate to 20fps and hindering performance. I know this because sometimes I can glitch out SteamOS to uncap the frame rate and increase performance but it's very difficult to pull off, it's what I had to do when making a Quake 2 RTX optimization mod for Steam Deck

How I noticed this:
At first when I finished the optimizations the game ran fine on the preview build, I got the game running at 30fps with a dynamic resolution of 70-80%
The first issue I noticed tho is when pulling up the built in performance overlay (this also helped confirm that SteamOS was the issue), the FPS would cap to 20fps and drop performance, I thought it was weird but nothing too big
Then when I restarted the Steam Deck, this issue became permanent even without the performance overlay, it was capped to 20fps and dynamic resolution dropped to 40-50% (this is all at 800p, 1080p has different scales)
The way I was able to glitch back the performance sometimes was by switching from preview to beta than back to preview builds in SteamOS.

I really do hope there is a way to fix this as I have been trying to show off the RT capabilities of Steam Deck and right now the software is the biggest issue for this game

**Comment by W4ldgeist** [comment]
I think this must be connected to RT. Because I have a similar "weirdness" when I run The Witcher 3 with RT, that performance "degrades" over time. I am using HoloISO on a Minisforum HX100G, I get 30fps with RT on, but then it degrades over time until I restart the whole system. Does it help your issue if you restart? Or is the fps always in the 20s?

**Comment by KingVulpes** [comment]
> I think this must be connected to RT. Because I have a similar "weirdness" when I run The Witcher 3 with RT, that performance "degrades" over time. I am using HoloISO on a Minisforum HX100G, I get 30fps with RT on, but then it degrades over time until I restart the whole system. Does it help your issue if you restart? Or is the fps always in the 20s?

It's always at 20, this is the only game I've experienced do this. Every other RT game can run at 30+. Also I'll probably experience RT performance differently than you since I'm using a Steam Deck
