### ISSUE TITLE
TouchScreen in Games not working correctly in SteamOS beta 3.6.9

### ISSUE THREAD

**Issue by EddyArellanes** [ValveSoftware/SteamOS#1598]
#### Your system information

* Steam client version: SteamClient021
* SteamOS version: 3.6.9
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

After latest Update august 13 in Beta Channel, touch screen stop working correctly in any game, in some games the touch hits in other part of the screen, in other games touch simply does not do nothing.

- When  I change to Desktop Mode and Open any game the Touch works fine.
- Also if I return to the latest version in Stable Channel , Touch Screen works 100%.

#### Steps for reproducing this issue:

1.  Update to latest beta channel
2. Try any game with TouchScreen Support as Stumble Guys, Gunbound, any Clicker like
3. Touch does not work.

**Comment by e270889o** [comment]
Same here

**Comment by streamingdv** [comment]
Users of my App/ game reported this bug to me after the updated to the latest Beta 3.6.9. The issue is exactly as described by @EddyArellanes, a clarification about this issue would be nice

**Comment by FistyDollars** [comment]
I'm having the same issue when I try using RetroArch in the latest SteamOS beta. If I enable native touchscreen support using an AlwaysOn command like I used to, it's completely unresponsive; if I don't, it jumps around the screen and is completely inaccurate.

**Comment by K900** [comment]
This seems specifically related to the Steam client beta, not necessarily SteamOS (and it is still happening even on the September 3rd beta).

**Comment by EddyArellanes** [comment]
With the current version: 3.6.12
 now it works!
