### ISSUE TITLE
Latest SteamOS/Update has stuck 40FPS cap when home screen - works fine when playing games.

### ISSUE THREAD

**Issue by DrBob2** [ValveSoftware/SteamOS#1604]
#### Your system information

* Steam client version: 1723685248
* SteamOS version: 3.6.9
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
With latest Beta update, steam home screen & UI is capped at 40FPS, changing frame limit doesn't do anything (not changing refresh rate for example).
This goes away when launching a game, where FPS goes straight to profile setting, and even default profile switching works as expected. Only affects home UI not once titles are launched, desktop mode unaffected.

#### Steps for reproducing this issue:

1. Load to latest Beta/Preview OS, start browsing for a game to play, notice the UI isn't smooth.
2. Turn on 'Show Perf Overlay In Steam', see FPS cap is at 40FPS, try switching Frame Limit, refresh rate switching doesn't change like expected, no FPS caps work.
3. Load game, FPS goes back up, refresh rate switching works as expected while in title in game profile or default profile.
4. Close title, back to 40FPS cap.

Fresh boot no titles launched:
![Steam UI 40FPS](https://github.com/user-attachments/assets/1ed47ccd-5821-4a4f-85ef-ac319b457534)
Loading up Batman, FPS cap etc works as expected:
![Bman 60FPS](https://github.com/user-attachments/assets/6b2b5e77-201b-4ead-a208-87ad75464ffb)

**Comment by matte-schwartz** [comment]
Have you used an external display with adaptive sync (VRR) at all?

**Comment by DrBob2** [comment]
> Have you used an external display with adaptive sync (VRR) at all?

Yep, was docked to a VRR screen last night before going back to handheld. 4K 120HZ output when connected.

**Comment by matte-schwartz** [comment]
You are running into this bug: https://github.com/ValveSoftware/gamescope/issues/1369 + one quirk of the Steam client. which is that it caches a "VRR Enabled" state if you disconnect it from an external monitor that supports VRR.

You have a few options to fix this:

1. The easiest option is to re-connect to the TV, disable VRR in the pop-up menu, and then disconnect again
2. If you have ssh set up on your Deck, you can also run the command `gamescopectl adaptive_sync 0` from another device and it will disable VRR again.
3. If you have a keyboard connected to your Deck, you can also use that `gamescopectl adaptive_sync 0` command after switching to a TTY window with Ctrl + Alt + F5 while game mode runs in the background. You can switch back to game mode after running the command with Ctrl + Alt + F1.
4. Or finally - return to SteamOS Stable for now until the bug is fixed.

**Comment by DrBob2** [comment]
> You are running into this bug: [ValveSoftware/gamescope#1369](https://github.com/ValveSoftware/gamescope/issues/1369) + one quirk of the Steam client. which is that it caches a "VRR Enabled" state if you disconnect it from an external monitor that supports VRR.
> 
> You have a few options to fix this:
> 
>     1. The easiest option is to re-connect to the TV, disable VRR in the pop-up menu, and then disconnect again
> 
>     2. If you have ssh set up on your Deck, you can also run the command `gamescopectl adaptive_sync 0` from another device and it will disable VRR again.
> 
>     3. If you have a keyboard connected to your Deck, you can also use that `gamescopectl adaptive_sync 0` command after switching to a TTY window with Ctrl + Alt + F5 while game mode runs in the background. You can switch back to game mode after running the command with Ctrl + Alt + F1.
> 
>     4. Or finally - return to SteamOS Stable for now until the bug is fixed.

Thanks for the options, I've gone ahead and disabled VRR and all is working again in portable!

Will sit tight for a fix, VRR is a nice to have but I can live without in the meantime. You've given me a few options to resolve if I use it again and forget to disable. Thanks for the work!

Cheers.

**Comment by matte-schwartz** [comment]
@DrBob2 This bug has been fixed upstream in gamescope and should make its way into a SteamOS Preview image at some point soon.

**Comment by matte-schwartz** [comment]
this is fixed in SteamOS 3.6.12 on the Preview channel now.

**Comment by kisak-valve** [comment]
Closing per the last comment.
