### ISSUE TITLE
Enabling Gyro controls causing crashes on current Beta channel

### ISSUE THREAD

**Issue by AwkwaBear** [ValveSoftware/SteamOS#1606]
#### Your system information

* Steam client version: 1723685248
* SteamOS version: 3.6.9
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes, no pending updates
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

Problem Behavior:
- Steam deck is crashing to a black screen when in game (specifically in my case, Selaco) and changing a setting to enable gyro controls or adjust any gyro related control.

Expected behavior:
- Gyro is able to be utilized without crashing

#### Steps for reproducing this issue:

1. Open game Selaco and enter campaign
2. Press steam button and navigate to controller settings
3. Set Gyro Behavior to "Gyro to Mouse [Beta]
4. Return to Game
5. Game freezes and black screen then reboot follows

## Comments:
I have replicated this issue 3 times in a row under the same conditions and with other gyro related settings,

After the first reboot, gyro was left enabled in game. 

Repeating the steps to get into game above, then modifying ANY gyro related sensitivity slider would also recreate the same crash within a 2 seconds of returning to gameplay.

I have since tested further and do not believe it matters whether a game is something can can utilize gyro or not, I have just tested a moonlight streamed game and turned on gyro controls and crashed within a couple seconds of returning to the game.

There also seem to be similar reports with other games using gyro in the last 48 hours on reddit.

https://www.reddit.com/r/SteamDeck/comments/1et3x45/gyro_crashessystem_power_off/

https://www.reddit.com/r/SteamDeck/comments/1eu3huo/enabling_gyro_just_crashes_my_entire_deck_and/

**Comment by DrBob2** [comment]
Just adding that yep, crashes when playing with Gyro settings in game, black screen after returning to game from changing gyro settings, have to fully power-cycle like above.

The latest update (SteamOS 3.6.10) also doesn't seem to be applying as I'm still marked as on 3.6.9 like above (Doesn't appear on Beta or Preview OS options) which notes fixes for crashing with steam input.

**Comment by AwkwaBear** [comment]
I have tested a little further and can verify the crash/reboot does not occur if you do not have a game open when you modify the gyro settings.

My current workaround has been to quit the game every time I tweak a setting then reopen after. It's not a great solution but at least you don't have to restart the whole deck each time you tweak something.

**Comment by AwkwaBear** [comment]
Just tested today and this has been fixed in the most recent beta channel update
