### ISSUE TITLE
Controls do not work when exiting a non-Steam game in Gaming Mode.

### ISSUE THREAD

**Issue by Labestiajake** [ValveSoftware/SteamOS#1607]
#### Your system information

* Steam client version:1723685248
* SteamOS version: 3.6.9 20240814.100 Beta
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] Yes
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I run a non-Steam game, the controls work, but when I exit, all the controls (except STEAM button and ···) stop working until I press one of those buttons that works. If I use a PS5 and Xbox controller, none of the buttons work, I have to get up until I reach the Steam Deck and press one of the buttons that the Steam Deck works.

Always in game mode.

Tested on Battle.net, Firefox and emulators.

If they are Steam games the controls work without problems.
#### Steps for reproducing this issue:

1. Run a Non-Steam games.
2. Exit Non-Steam games.
3. Control not work.

**Comment by kisak-valve** [comment]
Hello @Labestiajake, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/11188.

Closing as a duplicate.
