### ISSUE TITLE
Resolution issues in docked mode after beta patch August 22nd

### ISSUE THREAD

**Issue by RedT0ny** [ValveSoftware/SteamOS#1613]
#### Your system information

* Steam client version: 1724453533
* SteamOS version: 3.6.9
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Ubisoft launcher does not recognize higher resolutions when docked using valve steam deck dock. It starts at 800p. Ubisoft games then see as "native" 800p resolution. Can be changed to 720p in 16:9 but not further. 

Connected to several external screens/TV with different native resolutions. Mostly 1080p. Happens every time. Didn't happen before 22nd August update. 

#### Steps for reproducing this issue:

1.  Making sure game parameters are 'native'. Tried as well manually setting to 1080p and higher. Setting the "maximum game resolution" in the screen menu to "native" as well, or manually to 1080p and higher. 
2. Opening ubisoft game launcher or a game (ac odyssey).
3. Screen is stretched. Game recognizes 800p and 16:10 as "native" and res. cannot be increased. Only other option is 720p with 16:9, resolution cannot be increased either.

**Comment by wynn1212** [comment]
Can confirm after the 8/22 steam client beta update, all of non-steam games resolution has been set to 800p despite changes the game resolution to `Native` or anything goes above to `1280x800` in game settings->general or maximum game resolution in display->advanced settings

**Comment by yargh82** [comment]
Thank god, I'm not the only one. Happens for me with Kodi, Chiaki, Shadow, GeForce Now, Xcloud.

Hopefully it gets fixed soon, I'm stuck to SD Beta because of Steam Family. Just tried it with the Stable and the issue was gone.

**Comment by Labestiajake** [comment]
It happens to me too

**Comment by manuzzo24** [comment]
I have the same issue

**Comment by lostgoat** [comment]
This should be fixed in today's steam client update.

**Comment by Sunspark-007** [comment]
@kisak-valve Hi, should this thread have been moved to the Steam Client for Linux github like my recent issue was? I'm confused because this thread is about the steam client on the steam deck and it stays, and mine was the same, but it was moved?

**Comment by kisak-valve** [comment]
Hello @Sunspark-007, for transparency, this issue report wasn't transferred because I wasn't able to determine if this was a Steam client issue or a SteamOS platform sided issue in the preliminary read of the issue report.

In general, we want issues that need to be evaluated by the SteamOS distro maintainers in this issue tracker and issues with the Steam client running on SteamOS in the steam-for-linux issue tracker.

**Comment by RedT0ny** [comment]
I confirm as well if was fixed with the latest client update. Thank you for the great job :)
