### ISSUE TITLE
Missing source packages for pure installer-only packages

### ISSUE THREAD

**Issue by directhex** [ValveSoftware/SteamOS#162]
It seems source packages for source packages which only generate .udeb files, but not .deb, are missing from repo.steampowered.com.

For example:
http://repo.steampowered.com/steamos/pool/main/a/apt-setup/
http://repo.steampowered.com/steamos/pool/main/p/partman-ext3/

**Comment by directhex** [comment]
This still seems to be the case? None of the Brewmaster udeb sources are up, eg http://repo.steamstatic.com/steamos/pool/main/c/cdrom-detect/

**Comment by johnv-valve** [comment]
finally got around to fixing this
