### ISSUE TITLE
[Feature Request - Steam Deck] Steam Deck as a USB Game controller

### ISSUE THREAD

**Issue by stubobis1** [ValveSoftware/SteamOS#1623]
I would like to be able to use the steamdeck as a controller for another machine VIA usb connection. It would be ideal if I could configure the controls via the steam os controller UI. From what I understand this should be possible. some information that I have found:

From here
https://github.com/dafta/DeckMTP
> you need to enable DRD (Dual-Role Device) support through the Steam Deck BIOS. Without this, it's impossible to create USB gadgets, since the USB controller can only act as a host in that case.
> 
> To enable DRD, go into BIOS by shutting down your deck, and holding Volume Up and Power until you hear a beep.
> 
> Then, select Setup Utility, then Advanced, then USB Configuration, and finally USB Dual-Role Device. Select DRD instead of the existing XHCI and you're set.

I also see that this exists: https://github.com/BigfootACA/systemd-gadget/blob/master/usbgadget-func-hid.service

Thank you for your time!

**Comment by kisak-valve** [comment]
Hello @stubobis1, the request at #844 takes priority over this one. Feel free to add a note to that request that there's interest in a hard wired mode in addition to a wireless method.

Closing in favor of the older feature request.
