### ISSUE TITLE
Third party dock bug in 3.6.12 beta.

### ISSUE THREAD

**Issue by Labestiajake** [ValveSoftware/SteamOS#1626]
Your system information

* Steam client version: 1725412627
* SteamOS version: 3.6.12 20240905.101
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

Please describe your issue in as much detail as possible:
When going from version 3.5.19 to 3.6.12, when I start a third-party dock from gaming mode to desktop mode, the steam deck screen does not turn on and the secondary works, if I remove the USB connection it still does not turn on the Deck screen. If I restart and connect the USB connection, the Deck screen turns off but the secondary screen does not turn on, if I remove the USB the Deck screen works.

With version 3.6.9 it worked.
Steps for reproducing this issue:

1. Update to 3.6.12 beta.
2. Keep the secondary screen with the usb connected.
3. Change gaming mode to desktop mode.
4. The Deck screen does not work.
5. Change desktop mode to gaming mode.
6. If you disconnect the USB the Deck screen does not work.

-First try
[systemreport-20240906193703.txt](https://github.com/user-attachments/files/16912489/systemreport-20240906193703.txt)
-Second try
[systemreport-20240906194036.txt](https://github.com/user-attachments/files/16912491/systemreport-20240906194036.txt)

I have returned to version 3.5.19 with the steam beta client. Everything works again.
[systemreport-20240906200816.txt](https://github.com/user-attachments/files/16912551/systemreport-20240906200816.txt)

**Comment by Labestiajake** [comment]
If I only use the external screen there is no problem, the sound and image look great and the deck connects to the secondary screen very quickly. Comparing version 3.5.19 with 3.6.12.

**Comment by Labestiajake** [comment]
It has been repaired, I had to deactivate the deck screen in desktop mode, switch to Gaming Mode, turn it off and on without the base, plug it in after a while and turn it on in Gaming Mode, switch to Desktop Mode and then enable it again. If it continues to fail I will reopen the topic.

**Comment by Labestiajake** [comment]
I have tested on another screen model UE50AU7105KXXC, in version 3.5.19, 3.6.8 and 3.6.9 it worked perfectly, now in version 3.6.12 it only works in Gaming Mode, in desktop mode both the Deck and the external screen remain. remains black. When I disconnect the HDMI, the Deck turns on the screen.

In 4k resolution external
[systemreport-20240910174204.txt](https://github.com/user-attachments/files/16955719/systemreport-20240910174204.txt)

720p resolution
[Uploading systemreport-20240910221833.txt…]()

**Comment by matte-schwartz** [comment]
I believe there was a KWin update in 3.6.12, could be related? Especially as you say the problem happens in Desktop mode only now and KWin manages that. I'll see if I have any issues with my own third-party dock and add a report here if I do.

**Comment by Labestiajake** [comment]
> I believe there was a KWin update in 3.6.12, could be related? Especially as you say the problem happens in Desktop mode only now and KWin manages that. I'll see if I have any issues with my own third-party dock and add a report here if I do.

Maybe you are right about KWin management, I have tested on several screens (about 5) and it seems that it may be that. Since all of them in Gaming Mode do not give any error, but when it starts loading in Desktop mode they are failing, when before they did not, and if I return to the stable version the error no longer occurs.

**Comment by matte-schwartz** [comment]
Hmm, if you want to try something, I'd be interested if renaming or moving `~/.config/kwinrc` to a different folder and then re-launching the desktop mode helps.

**Comment by Labestiajake** [comment]
> Hmm, if you want to try something, I'd be interested if renaming or moving `~/.config/kwinrc` to a different folder and then re-launching the desktop mode helps.

Just so it's not luck, I've tested it on a screen I've never used before. It gave the same error. I did what you told me, and it worked. The KDE splash screen loaded and didn't give me any errors. I tested it on my screen and now it works like the stable version, no flickering and the first time.

Backup:

```
[$Version]
update_info=kwin.upd:replace-scalein-with-scale,kwin.upd:port-minimizeanimation-effect-to-js,kwin.upd:port-scale-effect-to-js,kwin.upd:port-dimscreen-effect-to-js,kwin.upd:auto-bordersize,kwin.upd:animation-speed,kwin.upd:desktop-grid-click-behavior,kwin.upd:no-swap-encourage,kwin.upd:make-translucency-effect-disabled-by-default,kwin.upd:remove-flip-switch-effect,kwin.upd:remove-cover-switch-effect,kwin.upd:remove-cubeslide-effect,kwin.upd:remove-xrender-backend,kwin.upd:enable-scale-effect-by-default,kwin.upd:overview-group-plugin-id,kwin.upd:animation-speed-cleanup,kwin.upd:replace-cascaded-zerocornered

[Desktops]
Id_1=104ccf6b-c6b3-44fc-8ab2-612865282310
Number=1
Rows=1

[Tiling]
padding=4

[Tiling][5b7a5ba4-43cc-5910-8e98-f358f9d54b43]
tiles={"layoutDirection":"horizontal","tiles":[{"width":0.25},{"width":0.5},{"width":0.25}]}

[Tiling][9ee7efe8-bde2-5f73-ac16-e94b84b00765]
tiles={"layoutDirection":"horizontal","tiles":[{"width":0.25},{"width":0.5},{"width":0.25}]}

[Tiling][b878145a-2d4c-58f1-8f3b-137c74223253]
tiles={"layoutDirection":"horizontal","tiles":[{"width":0.25},{"width":0.5},{"width":0.25}]}

[Tiling][cd0b0725-df91-5af0-a18e-91b85e88a1bb]
tiles={"layoutDirection":"horizontal","tiles":[{"width":0.25},{"width":0.5},{"width":0.25}]}

[Tiling][d3b3d9bc-06de-5748-bbfe-56dd26acb3ce]
tiles={"layoutDirection":"horizontal","tiles":[{"width":0.25},{"width":0.5},{"width":0.25}]}

[Tiling][d7c311d5-a709-5fa3-bf2d-6c506024c741]
tiles={"layoutDirection":"horizontal","tiles":[{"width":0.25},{"width":0.5},{"width":0.25}]}

[Tiling][e2bb44a9-9e5a-5433-96d7-3dba3839880a]
tiles={"layoutDirection":"horizontal","tiles":[{"width":0.25},{"width":0.5},{"width":0.25}]}

[Tiling][fab0b009-5dc2-5f2f-8b24-8c53da4c339b]
tiles={"layoutDirection":"horizontal","tiles":[{"width":0.25},{"width":0.5},{"width":0.25}]}
```

And new:

```
[Desktops]
Id_1=aa967776-a3ea-4600-9201-e7e19523d7de
Number=1
Rows=1

[Tiling]
padding=4

[Tiling][cd0b0725-df91-5af0-a18e-91b85e88a1bb]
tiles={"layoutDirection":"horizontal","tiles":[{"width":0.25},{"width":0.5},{"width":0.25}]}

[Tiling][e2bb44a9-9e5a-5433-96d7-3dba3839880a]
tiles={"layoutDirection":"horizontal","tiles":[{"width":0.25},{"width":0.5},{"width":0.25}]}

[Tiling][fab0b009-5dc2-5f2f-8b24-8c53da4c339b]
tiles={"layoutDirection":"horizontal","tiles":[{"width":0.25},{"width":0.5},{"width":0.25}]}
```

Thanks for the help @matte-schwartz

**Comment by Labestiajake** [comment]
Bad luck, I connected to the dock on my Steam Deck, Gaming Mode worked, but when I switched to Desktop Mode it happened again:

![photo_2024-10-01_12-20-04](https://github.com/user-attachments/assets/beded90b-7c5e-446d-8dfc-fb06e7e2b751)

When I unplug the Dock, the Steam Deck does not turn on the screen:

![photo_2024-10-01_12-19-59](https://github.com/user-attachments/assets/6954b5dc-8ac6-4d3c-90c9-c109a56e1037)

And when I connect it it happens to me like the first image. But when I press the power button once, it goes to sleep, but if I press it a second time the screen activates.

![photo_2024-10-01_12-19-49](https://github.com/user-attachments/assets/c626ac10-1f5d-44c9-ab9a-ca90ec7add74)

System Report
[systemreport-20241001102211.txt](https://github.com/user-attachments/files/17203547/systemreport-20241001102211.txt)

**Comment by matte-schwartz** [comment]
So kwinrc is basically a way for kwin to hold on to various display settings, and it seems like maybe it's applying invalid settings to different monitors. Probably needs a SteamOS dev to take a look at some point but we've gotten some useful info now that we know clearing kwinrc works, even temporarily.

**Comment by Labestiajake** [comment]
In the version 3.6.16 fixed the problem.
