### ISSUE TITLE
After closing a non-steam game in gaming mode, the controller becomes unresponsive.

### ISSUE THREAD

**Issue by gaker19sc** [ValveSoftware/SteamOS#1629]
#### Your system information

* Steam client version: 1725654351
* SteamOS version: 3.5.19
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When closing a non-steam game in gaming mode by pressing the Steam button and selecting exit game, you get taken back to the launch page of the game where the controller is unresponsive (Steam Deck Controller and external controllers are both affected). 
Expected behavior: You get taken back to the launch page and can press buttons to control the menu (pressing B to go back for example)

This is easily fixed by pressing the Steam button to open the menu, then closing it again. You will now have regained control. Not a huge issue, just an annoyance. This does not happen with Steam Games.

#### Steps for reproducing this issue:

1. Add a non-steam game to Steam
2. Go into gaming mode
3. Start the non-steam game
4. Press the Steam button and exit the game
5. Press B to go back (it will not do anything)

**Comment by Labestiajake** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/11188

**Comment by kisak-valve** [comment]
Hello @gaker19sc, as @Labestiajake noted, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/11188.

Closing as a duplicate.
