### ISSUE TITLE
Steam Deck boot movies no longer work

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/SteamOS#1634]
#### Your system information

* Steam client version: 1726088054
* SteamOS version: 3.5.19
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Boot movies used to work fine on my oled le 1 tb deck, updated to the latest stable update that introduces Steam families and now my boot movies fail to play on launch, trying to play for half a second before jumping straight to my main screen. (I see briefly a screen with a white outline border when it tries playing)

I'm using the oled le boot movie for my boot screen.

#### Steps for reproducing this issue:

1. Make sure boot movies work on older version of Steamos
2. Update to latest stable client update
3. Watch as the movie tries to play, but fails and moves onto the main screen

**Comment by kisak-valve** [comment]
Hello @waspennator, this appears to be more of a Steam client issue than an issue with SteamOS as a platform. Closing in favor of https://github.com/ValveSoftware/steam-for-linux/issues/11253.
