### ISSUE TITLE
Point Shop Startup Movies Broken

### ISSUE THREAD

**Issue by CaptainHowdy1989** [ValveSoftware/SteamOS#1636]
#### Your system information

* Steam client version:
* SteamOS version: 3.5.19
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [YNo] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. 

When I select a Point Shop Startup movie in steam OS, it just skips the startup movie entirely upon booting up. When I use the shuffle option, it also skips the movie on boot up. The default movie plays fine on startup.
#### Steps for reproducing this issue:

1. Choose any startup movie from Point Shop besides the default.
2. Shut down system.
3. Boot system back up.
4. Startup movie will be skipped.

**Comment by kisak-valve** [comment]
Hello @CaptainHowdy1989, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/11253. Closing as a duplicate.
