### ISSUE TITLE
Discover suggest to downgrade apps instead of upgrade (KDE Plasms 2.27.5 bug)

### ISSUE THREAD

**Issue by smlcr** [ValveSoftware/SteamOS#1638]
![5418341470471053805_121](https://github.com/user-attachments/assets/5ca76b6f-db00-4f57-a51a-5a94ccecedc7)
* Steam client version: 1726256783
* SteamOS version: 3.5.19
* Opted into Steam client beta?: No 
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Please, update KDE Plasma from 5.27.5 to 5.27.6. 
"Discover" app in 5.27.5 has a bug when apps is always suggest to update backwards: the app literally offers a downgrade your soft instead of a upgrade (and it's not only visual bug). 
This was fixed in 5.27.6. Proof (and another discussion about this bug): https://discuss.kde.org/t/discover-software-center-always-downgrading/9957/7

#### Steps for reproducing this issue:

1. Use Discover for some time to upgrade your soft.
2. Another bug proofs: and discussions: 
https://www.reddit.com/r/SteamDeck/comments/19askub/discover_store_showing_old_versions_of_apps_as/
https://www.reddit.com/r/SteamDeck/comments/1aloejl/discover_store_wants_to_update_to_lower_version/

**Comment by kisak-valve** [comment]
Hello @smlcr, KDE's package set has already been updated to 5.27.10 as part of a general rebase for the SteamOS 3.6 release. (https://steamdeck-packages.steamos.cloud/archlinux-mirror/extra-3.6/os/x86_64/discover-5.27.10.1-1-x86_64.pkg.tar.zst)

Realistically, I would expect that there will only be critical updates to SteamOS 3.5.x at this point in the release lifecycle and there's no action for a SteamOS dev to take for future releases.
