### ISSUE TITLE
Streaming Stutter with Moonlight

### ISSUE THREAD

**Issue by mufaaf** [ValveSoftware/SteamOS#1640]
Hey folks. 

I have the Steam Deck OLED running on the current stable release.

I am trying to stream via Moonlight + Sunshine from my desktop PC, and the stream just constantly stutters before it ultimately breaks itself and becomes unplayable. 

On the other hand, I can stream at 1440p/60fps at 80mbps with HDR on my Android tablet without any problems. Same for MacBook Air.

Desktop Setup:
Intel i9-12900K
RTX 3080
32GB RAM
Games capped to 60fps w/RTSS, played at 1080p
Wired to Ethernet

Steam Deck Setup:
60fps/60Hz
Moonlight settings: 800p, 60fps, 30mbps bitrate, VSYNC and Frame Pacing on, Decoders set to Auto
Connected via 5Ghz WiFi

Router Setup:
TP Link Deco P7, two nodes, separate 2.4Ghz and 5Ghz bands, 80Mhz channel width

Things I have tried:
- Powersave conf
- Turning of Power Management in Dev settings
- WPA Supplicant conf
- Beta release (it was quite buggy and wouldn't even launch Moonlight properly)
- A different router, Linksys, not mesh
- Setting BSSID
- Turning WiFi off and on mid-stream and/or before it

Nothing seems to help, and I have exhausted my search on Google. Is there a work around this to get Moonlight to stream properly? I am extremely frustrated as I got the Deck OLED primarily for streaming purposes because it has a nice screen.

**Comment by kisak-valve** [comment]
Hello @mufaaf, this issue is already being tracked at #1256. Feel free to add your experience to the older issue report.

Closing as a duplicate.
