### ISSUE TITLE
Please update the APU drivers for both OLED and LCD steam decks.

### ISSUE THREAD

**Issue by Dr1fte** [ValveSoftware/SteamOS#1644]
#### Your system information

* Steam client version:
* SteamOS version: 3.5.19
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

#### Steps for reproducing this issue:

1. No software/hardware issue. The APU driver is outdated. I would like an option to be able to update my APU driver to the AMD RDNA 2 latest/preview release. So I can utilise AFMF from AMD. I don’t see why you (Valve), are distributing Steamos to windows handhelds. But yet, can’t improve our own gaming experience, by running up to date APU drivers. If this doesn’t become a reality in the near future. I’m afraid, I’ll be jumping ship to a windows handheld. I don’t honestly see a reason as to why we are left out. We are your customers after all.
2. AFMF has greatly improved latency and fps in AAA games.

**Comment by kisak-valve** [comment]
Hello @Dr1fte, AMD Fluid Motion Frames is a Windows video driver feature that does not have a direct equivalent implemented  in the Linux driver ecosystem.

This general topic is already being discussed at #1499. Closing as a duplicate.
