### ISSUE TITLE
Bluetooth devices Auto-Connect on Wake when Bluetooth is turned OFF

### ISSUE THREAD

**Issue by cbmelton** [ValveSoftware/SteamOS#1647]
#### Your system information

* Steam client version: 1726683985
* SteamOS version: 3.5.19
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

The Bluetooth setting (on/off) is not adhered to when waking the steam deck from sleep.  If I have Bluetooth turned OFF before I sleep my steam deck, when I wake it, my airpods will automatically pair to the steam deck and switch to it for audio.  I check that the Bluetooth settings on the steam deck is still OFF, and it is.  But my airpods are connected to it and playing sound.  My workaround is that I have to then go and toggle Bluetooth ON, and then OFF.  This then disconnects my airpods.

What is Expected:
- When I wake the steam deck and Bluetooth is turned OFF, I do not expect any Bluetooth device to automatically connect to the Steam Deck

What Actually Happens:
- When I wake the steam deck and Bluetooth is turned OFF, my airpods automatically connect to the steam deck and start playing its audio.

Semi-related Issue:  https://github.com/ValveSoftware/SteamOS/issues/1406

#### Steps for reproducing this issue:

1. Pair Bluetooth headset that has the ability to pair with multiple devices (ex: airpods)
2. Turn Bluetooth off on the steam deck
3. Put the Steam Deck to sleep
4. Connect Bluetooth headset to another device
5. Wake steam deck (and see that Bluetooth is still off, but headset switches to Steam Deck)

**Comment by fsdread** [comment]
Can confirm the bug still persists with 3.6.20. Very annoying

**Comment by cbmelton** [comment]
Closing, as I no longer see the issue.  I am on 3.6.20 with OS Build 20241030.1
