### ISSUE TITLE
[Kernel Request] backport scarlett-gen2

### ISSUE THREAD

**Issue by Ashe** [ValveSoftware/SteamOS#1658]
#### Your system information

* Steam client version: 1726683985
* SteamOS version: SteamOS Holo 3.5.19
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

In Kernel 6.7 onwards, this kerenel module is enabled by default as described here:

https://github.com/geoffreybennett/scarlett-gen2

But I cannot take advantage of this as the steamdeck's kernel is behind. 

I was wondering how difficult it would be to backport this so that we can use our Focusrite hardware devices - I use my steamdeck as my daily driver now (thank you so much!) and would be nice to be able to use my 4th gen 2i2 with it. Specifically, I want to take advantage of and install this driver:

https://github.com/geoffreybennett/alsa-scarlett-gui/

I don't know how much work this is and I don't want to make a request which will drain your devtime, but I thought I'd make this request just in case it is something you can do / if the kernel update is coming soon etc.

**Comment by kisak-valve** [comment]
Hello @Ashe, unless something critical comes up, the kernel used with SteamOS 3.5 is the final iteration for that release branch.

My understanding is that SteamOS 3.7 will have a kernel based on 6.8 or newer and this kind of feature enablement will come along with that release branch.

You could experiment with that now with the [main] update channel, but keep in mind that is where active development happens and it's generally not intended for end users. Things could break unexpectedly from ongoing adjustments.
