### ISSUE TITLE
Bluetooth menu intermittently vanishes

### ISSUE THREAD

**Issue by fadookie** [ValveSoftware/SteamOS#1661]
#### Your system information

* Steam client version: 1726683985
* SteamOS version: SteamOS Holo 3.5.19 (20240422.1)
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

I am using a Steam Deck LCD 512gb model. System report uploaded for steam ID https://steamcommunity.com/id/fadookie/

#### Please describe your issue in as much detail as possible:
Sometimes the Bluetooth menu in gaming mode settings completely vanishes from the settings menu. It's completely hidden and can't be accessed. I am not sure what triggers it but I usually leave my deck on in sleep mode all the time, perhaps that's related. I was also offline once when trying to access the Bluetooth menu.

Restarting the deck seems to fix it temporarily.

Other users have also reported this issue:
* https://www.reddit.com/r/SteamDeck/s/vsqtwSn2ef
* https://www.reddit.com/r/SteamDeck/s/3qiS4cAJU9

I didn't used to have this issue. It started happening maybe a month or so ago.

#### Steps for reproducing this issue:

1. Not sure of the exact trigger condition, maybe let the deck soak in sleep mode for a long time like 12-24 hours. Having no Internet connection might also be related.
2. In gaming mode, Hit steam button -> Settings
3. Look for Bluetooth menu

**Comment by poudink** [comment]
I've had the same issue for the past week or two on a 64GB LCD model. I recently switched to the Beta update channel so I could have recent enough glibc for ShadPS4's AppImages, but I don't remember whether this started happening before or after I switched.

I've been working around the problem whenever it occurs by connecting my devices using Plasma's Bluetooth applet through Nested Desktop. Apparently there's also a Bluetooth Decky plugin you can use, which is probably more convenient, but I haven't tried it.

**Comment by ampentium2** [comment]
Commenting to make this issue gain more traction.
The same issue happened to me today as well, rebooting seems to bring back the menu, Steam Deck OLED 512GB on 3.5.19.

**Comment by ampentium2** [comment]
So, this happened again to me today at the office (similarly, it happened to me yesterday at my office too).
It seems like the menu is tied to the ability of the device to connect to internet upon wake up after sleeping for a long time.

At home, it can always connect to the wifi when waking up so I don't see this issue.
At office, I don't connect it to the wifi so essentially it is offline. I decided to try to connect it to wifi hotspot from my phone, once it got connected the bluetooth menu magically re-appears.

Since then, I haven't been able to make it disappear again even after I disconnect the wifi. Maybe it just takes time.

So, if you're having similar issue try to connect it to a wifi/internet and see if it appears again.

**Comment by andy-hubb** [comment]
Same issue here.  Always when no internet.
Switching in and out of desktop mode seems to fix it.

**Comment by Pixelzated** [comment]
Happens to me too on my 64gb lcd

**Comment by lostgoat** [comment]
If you see this problem again, could I trouble you to submit a system report to steam support. This report will include the relevant logs from your system to help us track down this bug. 

To submit a system report, go to Settings->System and then scroll to the bottom of the page and you'll find a button to create and submit a system report.

**Comment by fadookie** [comment]
@lostgoat i did submit a system report for the ID I linked in my original bug report above. I didn't have Internet when the bug happened so I was not able to submit the report until I got home, though.

**Comment by lostgoat** [comment]
@fadookie Perfect thank. That works as the data is preserved for some amount of time.

**Comment by tahlsr** [comment]
I also have this issue occur regularly on my SteamDeck Oled. Not sure if relevant but it does seem to have started only in the past couple of weeks and my Steam Deck is often offline as I use it on a subway commute.

**Comment by lostgoat** [comment]
Thanks for the info and the logs. A fix for this issue will ship with the next beta client update.

**Comment by fadookie** [comment]
Awesome, thanks for the quick turnaround on this!

**Comment by omgboom** [comment]
Been happening to me for about 2 months now and just happened this morning on my way to work. Trigger condition is when I leave the house (ie. off wifi). Disappears from Settings and Quick Settings. Otherwise Bluetooth works just fine 100% of the time while at home. 

OS Update Channel: Beta
Steam Client Update Channel: Steam Deck Stable
OS 3.6.15
20240923.100

**Comment by lostgoat** [comment]
@omgboom there is a fix for this in the client beta update channel.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by Xriuk** [comment]
This still happens on the Steam Machine as well

**Comment by McCrossin** [comment]
This happened to me on the steam machine

**Comment by matte-schwartz** [comment]
please open a new issue report if the issue is occurring on Steam Machine, preferably with a steamos system report along with it

**Comment by McCrossin** [comment]
I actually found the problem after compiling a bug report so won't bother. But just in case someone else runs into this problem. I was in desktop mode and entering steam big picture via pressing steam button twice. In big picture mode Bluetooth does not appear, but it functionally appears very similar to the default gaming mode.

Just going back to gaming mode (not big picture) fixed the problem.
