### ISSUE TITLE
OLED nausea and dizzyness

### ISSUE THREAD

**Issue by Kunailby** [ValveSoftware/SteamOS#1662]
I'm getting massive headaches, nausea and dizzyness while play on my steam deck oled.

Why js Valve ignoring this issue ? Where's the DC Dimming option at ?

**Comment by kisak-valve** [comment]
Hello @Kunailby, please do not intentionally open duplicate issue reports. Closing as a duplicate of #1392.

**Comment by Kunailby** [comment]
How are we supposed to get this out then ? One simple thread won't do anything. They need more people that complain about it 

Been 1 year and valve still ignoring
