### ISSUE TITLE
[Feature Request] add Winetricks binary to /usr/bin

### ISSUE THREAD

**Issue by DarkenLX** [ValveSoftware/SteamOS#1672]
#### Your system information

* Steam client version: 1726683985
* SteamOS version: 3.6.18
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

Please add Winetricks binary to the /usr/bin so programs that call to it function as intended.

**Comment by kisak-valve** [comment]
Hello @DarkenLX, this is a legally grey area that's not worth the risk.
