### ISSUE TITLE
umr needs a rebuild for SteamOS 3.6

### ISSUE THREAD

**Issue by matte-schwartz** [ValveSoftware/SteamOS#1676]
#### Your system information

* Steam client version: 1729208001
* SteamOS version: 3.6.18
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes, Preview
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
installing umr from the repo and trying to use it results in:
```
(deck@steamdeck ~)$ umr
umr: error while loading shared libraries: libLLVM-15.so: cannot open shared object file: No such file or directory
```

**Comment by bertogg** [comment]
Thanks, I confirm the problem

**Comment by matte-schwartz** [comment]
closed with: https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-3.6/os/x86_64/umr-1%3Ajupiter_extras_1.0.8-1.1-x86_64.pkg.tar.zst

thanks!
