### ISSUE TITLE
"Format SD Card" causes microSD card to not be recognized in gaming mode

### ISSUE THREAD

**Issue by mserajnik** [ValveSoftware/SteamOS#1684]
#### Your system information

* Steam client version: 1726683985
* SteamOS version: 3.6.19
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

After updating to SteamOS 3.6.19 (from 3.5.19), formatting the inserted microSD card via  the `Format SD Card` option in the `System > System Settings` menu causes it to not be recognized in gaming mode, but it works normally and without issues in desktop mode (see my [update comment](https://github.com/ValveSoftware/SteamOS/issues/1684#issuecomment-2452003128) for details). There is no error and the format seems to complete without issues, but if I then check the `Storage` menu the card shows as unformatted and can't be used (_"To use this drive with Steam Deck, it first needs to be formatted."_). Rebooting or running `Format SD Card` again doesn't work either. I also tried fully reinstalling SteamOS 3.6.19 via factory reset which also didn't help. Finally, removing and reinserting the card doesn't change anything.

Formatting the microSD card directly in the `Storage` menu instead __does__ work but results in a different mount point used (based on the chosen drive name, e.g., `/run/media/deck/sr256` for a drive named `SR256`) than when formatting through `System > System Settings` in the past (where it would always result in a mount point named `/run/media/mmcblk0p1`).

__Edit:__ One more thing to note is that I didn't check if the microSD card didn't already show as unformatted after updating to 3.6.19 _before_ I attempted to reformat it via the `Format SD Card` option; however, there are [some reports on Reddit](https://www.reddit.com/r/SteamDeck/comments/1gc5leq/latest_steam_deck_update_asking_me_to_format/) about users being prompted to format their microSD cards after updating, which would suggest that a card that had been previously formatted via `Format SD Card` option under 3.5.x might show up as needing to be reformatted immediately after updating to 3.6.19.

__Edit 2:__

Here are a few other reports of apparently the same issue:

- https://www.reddit.com/r/SteamDeck/comments/1gbwp2m/cant_use_sd_card_after_updating_steam_deck_dock/
- https://www.reddit.com/r/SteamDeck/comments/1gbexio/updated_my_official_steam_deck_dock_and_now_i/
- https://www.reddit.com/r/SteamDeck/comments/1gdkyws/sd_card_gone_after_3619/
- https://www.reddit.com/r/SteamDeck/comments/1gc5leq/latest_steam_deck_update_asking_me_to_format/

The first two of these linked reports mention the Dock update potentially being the culprit, but based on the comments it seems more likely they just didn't notice until after updating the Dock (after updating to 3.6.19). I personally haven't used my Dock after updating to 3.6.19, so that couldn't be it.

I'm using a 64GB LCD Steam Deck model (purchased in April 2023), just in case there's any sort of difference (e.g., model-specific code branching) that could limit which devices are affected and which not.

#### Steps for reproducing this issue:

1. Install/update to SteamOS 3.6.19
2. Insert a microSD card
3. (Re)format the microSD card via `Format SD Card` option in `System > System Settings`
4. Observe that the microSD card shows as unformatted in the `Storage` menu

**Comment by mserajnik** [comment]
I wanted to try the fix suggested [here](https://www.reddit.com/r/SteamDeck/comments/1gdkyws/sd_card_gone_after_3619/) (assuming that maybe `Format SD Card` somehow could cause a bad superblock) when I noticed that the microSD card gets auto-mounted and works normally in desktop mode:

![IMG_3239](https://github.com/user-attachments/assets/97f61f3d-063c-42f9-b668-7da7a68579e5)

However, after then switching back to gaming mode and checking the `Storage` menu, it still shows like this there:

![IMG_3240](https://github.com/user-attachments/assets/b9b09726-1d63-4f92-9516-6d0ab561b3e3)

Sorry for the photos, this was a lot quicker than getting screenshots from the Deck on my notebook.

---

So I can only assume that this is a (UI?) bug in the Steam client in gaming mode that was introduced with 3.6.19 (at least in my particular case; others, like the Reddit post with the supposed fix I linked, might of course have encountered different issues).

**Comment by mserajnik** [comment]
Update: after updating to SteamOS 3.6.20, the issue still persists (with the same observed behavior, the microSD card works without any issues in desktop mode).

**Comment by bertogg** [comment]
Using today's Steam client (version 1730853027):

- System -> Format SD Card -> Format sends you to the Storage menu
- From there you can format the SD card pressing 'Y'. After that it should work and it should be mounted automatically. If it doesn't then there's a problem, but from your report I understand that this does work correctly.

About the mount point:

- If the filesystem has a label ("Drive name" on the format dialog): `/run/media/deck/<label>`  (e.g. `SR256`).
- If the filesystem does not have a label: `/run/media/deck/<uuid>` (`d5cbf486-9c50-11ef-bf1d-b32034d67591`).

For compatibility with older versions a symlink is created:

- If there is a label: `/run/media/SR256 -> /run/media/deck/SR256`
- If there is no label: `/run/media/mmcblk0p1 -> /run/media/deck/d5cbf486-9c50-11ef-bf1d-b32034d67591`

Since you can select the label at format time you can decide what the mount point is going to be.

I hope that clears things up a bit.

**Comment by mserajnik** [comment]
Thank you, I can confirm that this behaves as described with the latest Steam client update.

So, I assume `System -> System Settings -> Format SD Card` was always intended to "link" to the `Storage` menu with `3.6.19` (and onwards), but there was a bug that instead caused it to directly format the SD card instead (as used to be the case with `3.5.19` and older versions), in a manner that prevented the SD card from being recognized correctly and auto-mounted in gaming mode?

Anyway, this resolves the issue.

**Comment by newtox** [comment]
For me it doesn't even show up, neither in desktop more or gaming mode. Not sure how and where it is being mounted tbh.
