### ISSUE TITLE
Denuvo Issues after update to 3.6

### ISSUE THREAD

**Issue by cyo93** [ValveSoftware/SteamOS#1688]
#### Your system information

* Steam client version: 1726693985
* SteamOS version: 3.6.19
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After I updated to the latest Steam OS, I have some problems with some games that use Denuvo and they may not be playable offline after cold boot, even though I didn't find any pending updates for SteamOS. I tested the following games:

Puyo Puyo Tetris
Persona 4 Golden
Persona 5 Royal
Sonic Frontiers
HI-FI RUSH

For some reason, downgrading the Linux Kernel to 6.1 fixes the problem. I have a video describing the problem: https://drive.google.com/file/d/1e92OvSfXdUs2jBsgMvfvm6oQq7TS65qn/view?usp=sharing

#### Steps for reproducing this issue:

1. Launch the game online (make sure the deck is up to date first)
2. Restart or shut down the Steam Deck. You may need to try this more than once.
3. Try launching the game offline.

**Comment by matte-schwartz** [comment]
I ran into this the other day, it seems like some Denuvo games will treat different kernel versions as separate machines. I had it happen in Star Wars Jedi: Survivor. Not sure it's really a SteamOS regression since it happened outside of SteamOS. Your games should probably work again after a cooldown on the new kernel.

**Comment by cyo93** [comment]
The actual problem is that on the new kernel, the games sometimes don't work after cold boot, even though I didn't update SteamOS or the current Linux Kernel, which is 6.5, I haven't seen a problem like this and I think it's a kernel regression. I noticed this problem since Linux Kernel 6.2 and I'm aware that changing kernels causes games to stop working offline until next online launch, but it's also happening even when the kernel version isn't changed, just above 6.1.
