### ISSUE TITLE
Restarting after updating to 3.6.19 takes me back to 3.5.19

### ISSUE THREAD

**Issue by firemonk3y** [ValveSoftware/SteamOS#1691]
#### Your system information

* Steam client version: 1726683985
* SteamOS version: 3.5.19
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Running the Stable release 3.5.19, i can see the new update notification in System for 3.6.19.  When I click on Apply, the update takes a few mins to reach 100% but seems to complete without any errors.
I am then presented with the Restart button and after clicking it my SteamDeck reboots into 3.6.19.
However, once booted into 3.6.19, in System menu, the Restart button is still there next to Software Updates and if i click it, it reboots back into 3.5.19 and I am back to the beginning.

I have tried several times and also tried changing to the beta channel but nothing makes any difference.  No matter what I try, it is always revertng back to 3.5.19.

#### Steps for reproducing this issue:

1. Apply update to 3.6.19
2. Restart
3. System shows OS version 3.6.19
4. Restart again
5. System shows OS version 3.5.19

**Comment by firemonk3y** [comment]
Note: I also tried updating via the command line and it seemed to complete but the Restart button still shows under System and when i click, it reboots back to 3.5.19.

`(deck@steamdeck ~)$ steamos-update
WARNING:image.py:179: The image manifest has some unknown key-values: {'branch': 'stable', 'default_update_branch': 'stable'}
Update available
WARNING:image.py:179: The image manifest has some unknown key-values: {'branch': 'stable', 'default_update_branch': 'stable'}
0%
5%
7%
9%
11%
14%
16%
18%
20%
23%
25%
27%
34%
41%
47%
54%
61%
68%
74%
81%
88%
95%
100%
Applied an update`

**Comment by matte-schwartz** [comment]
That output all looks normal to me. Submitting a system report would probably be helpful to get a better picture of the chain of events here.

**Comment by lostgoat** [comment]
Hey @firemonk3y 

In particular, it would be good to submit a system report when you are in Step 3 (i.e. your system says 3.6.19).

1. Apply update to 3.6.19
2. Restart
3. System shows OS version 3.6.19
4. Submit System Report to Steam Support under Settings->System->Scroll to bottom of the page
5. Restart again
6. Confirm you are back to 3.5.19

Then let me know your steam username and I should be able to check the data your unit submitted.

**Comment by firemonk3y** [comment]
My Steam username is flremonkey (note the 2nd letter is an L).

I submitted a couple of System Reports the other day under both 3.5.19 and 3.6.19 but i have just submitted a fresh one now under 3.6.19.

I also found that i was able to upgrade to 3.7 by selecting Main in the OS update channel but the behavior is the same - clicking Restart afterwards brings me right back to 3.5.19.

**Comment by lostgoat** [comment]
@firemonk3y The update seems to have applied correctly, and your system currently thinks it should stay in 3.6.19 as it is marked as a successful boot:

```
---------------------------------------------------
Command: rauc status

=== System Info ===
Compatible:  steamos-amd64
Variant:     
Booted from: rootfs.0 (A)

=== Bootloader ===
Activated: rootfs.0 (A)

=== Slot States ===
○ [rootfs.1] (/dev/disk/by-partsets/B/rootfs, raw, inactive)
	bootname: B
	boot status: good
    [verity.1] (/dev/disk/by-partsets/B/verity, raw, inactive)

⏺ [rootfs.0] (/dev/disk/by-partsets/A/rootfs, raw, booted)
	bootname: A
	boot status: good
    [verity.0] (/dev/disk/by-partsets/A/verity, raw, active)

○ [rootfs.2] (/dev/disk/by-partsets/dev/rootfs, raw, inactive)
	bootname: dev
	boot status: good


---------------------------------------------------
Command: steamos-dump-info

SteamOS System Info: SteamOS
SteamOS System Info: Partition:
A
SteamOS System Info: Serial Numbers:
SteamOS System Info:	board_serial: MEBR21917557
SteamOS System Info:	product_serial: FVAA220066FB
SteamOS System Info: Battery:
SteamOS System Info:	model_name: GETAC
SteamOS System Info:	status: Discharging
SteamOS System Info:	capacity: 97
SteamOS System Info: Boot Config:
SteamOS System Info:	A       boot-attempts	0
SteamOS System Info:	A          boot-count	160
SteamOS System Info:	A   boot-requested-at	20241029053052
SteamOS System Info:	A           boot-time	20241029053213
SteamOS System Info:	A             comment	[2024-10-29 06:32:13 +0100] bootconf mode: boot-ok
SteamOS System Info:	A       image-invalid	0
SteamOS System Info:	B       boot-attempts	0
SteamOS System Info:	B          boot-count	344
SteamOS System Info:	B   boot-requested-at	20240427140355
SteamOS System Info:	B           boot-time	20241029052309
SteamOS System Info:	B             comment	[2024-10-29 06:23:09 +0100] bootconf mode: boot-ok
SteamOS System Info:	B       image-invalid	0
---------------------------------------------------
```

There are a fair amount of plugins outputting to the journal in these logs. Could you try with the thirdparty plugins disabled?

**Comment by firemonk3y** [comment]
Ok, I have uninstalled everything i could find - not sure if they all count as plugins but here is the list:

- Deck Loader
1. PowerTools
2. EmuDecky
3. ProtonDB Badges
4. Junk Store

- CryoUtilities
- Gyro DSU

- Xone (xbox gamepad usb dongle driver - install script here: https://gist.github.com/SavageCore/263a3413532bc181c9bb215c8fe6c30d)

Unfortunately its still doing the same thing, so I have uploaded a new System Report from both 3.5.19 and 3.6.19.  Please let me know if there is anything else I should try to remove.

**Comment by RyuzakiKK** [comment]
@firemonk3y just to be sure, when you are in the step 3, if you go to Settings->System you get the "restart" button immediately, without having to re-apply an update. Is that correct?

When you are in that situation, running 3.6.19 with the system unexpectedly telling you to reboot, can you please provide the output of these commands?

```
sudo atomupd-manager get-update-status
sudo atomupd-manager check --verbose
sudo steamos-update check --enable-duplicate-detection
sudo steamos-bootconf list-images
```

**Comment by firemonk3y** [comment]
Yes, correct. As soon as it boots into 3.6.19 the (!) notification is on the System menu and the Restart button is there.  Everything appears to work fine as long as I don't press the Restart button.

Here are the command outputs:

- sudo atomupd-manager get-update-status

`An error occurred while getting the update status: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: startup job failed.`

- sudo atomupd-manager check --verbose

`GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: startup job failed.(1)`

sudo steamos-update check --enable-duplicate-detection
``

sudo steamos-bootconf list-images
`+ dev
+ B
+ A *`

**Comment by vFones** [comment]
I have the same exact behaviour @firemonk3y is describing. Outputs of those command are the same also.

**Comment by firemonk3y** [comment]
Out of curiosity, I also ran the same commands on 3.5.19.  Here are the outputs if it helps:

sudo atomupd-manager get-update-status

`Usage:
  atomupd-manager [OPTION?]

  check                     Check for available OS updates
  update ID                 Apply the update ID (i.e. version number)
  switch-variant VARIANT    Select a different variant

Help Options:
  -h, --help       Show help options

Application Options:
  --verbose        Be more verbose.
  --version        Print version number and exit.

This tool let developers to control atomupd-daemon, allowing them to check and install OS updates.`

sudo atomupd-manager check --verbose

`Updates available:
ID: 20241021.100 - variant: 'steamdeck' - estimated_size: 0 - update_type: 0`

sudo steamos-update check --enable-duplicate-detection

`WARNING:image.py:179: The image manifest has some unknown key-values: {'branch': 'stable', 'default_update_branch': 'stable'}
Update available
20241021.100`

sudo steamos-bootconf list-images

`+ dev
+ B *
+ A`

**Comment by RyuzakiKK** [comment]
I can see that `/etc/steamos-atomupd/client.conf` is marked as "edited".

When you are in 3.5, can you please:
- Do not install any system update
- Run `sudo rm /var/lib/overlays/etc/upper/steamos-atomupd/client.conf`
  - This command will remove your edited `client.conf` file and revert it to the default one shipped with SteamOS
- Reboot
- You should still be in 3.5
- Apply the 3.6 update
- Reboot

**Comment by firemonk3y** [comment]
I have removed that file and rebooted and it is just applying the update now.  One immediate difference is that is says 9 mins remaining as opposed to 3 mins all the other times.

For reference, the contents of the file `/etc/steamos-atomupd/client.conf` before and after removing it and rebooting:

before:
```
[Server]
QueryUrl = https://steamdeck-atomupd.steamos.cloud/updates
ImagesUrl = https://steamdeck-images.steamos.cloud/
```

after:
```
[Server]
QueryUrl = https://steamdeck-atomupd.steamos.cloud/updates
ImagesUrl = https://steamdeck-images.steamos.cloud/
MetaUrl = https://steamdeck-atomupd.steamos.cloud/meta
Variants = rel;rc;beta;bc;main
```
