### ISSUE TITLE
SteamOS Fails to upgrade to 3.6

### ISSUE THREAD

**Issue by CoderMonkey1956** [ValveSoftware/SteamOS#1695]
#### Your system information

* Steam client version: 1726683985
* SteamOS version: 3.5.19
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Recently I had a problem where my steam deck would not boot. After initially trying to update to steamos 3.6 my system would just hang and eventually the whole deck wouldnt boot, I eventually fixed it by changing to beta, downloading the update, and swiching back to stable, and it is somehow fine. But now I have a new problem. Updating does not work.                                                                          

#### Steps for reproducing this issue:

1. Check for updates
2. Download and apply the update to 3.6
3. Restart.
4. Restart button still shows, so restart again
5. Upon restarting still stuck on 3.5

This seems almost identical to #1691 but that solution did not work (no such file existed)

**Comment by kisak-valve** [comment]
Hello @CoderMonkey1956, similar to #1691, a SteamOS dev will need you to gather what system reports you can to take a look at the details. Please roughly follow the request for information at https://github.com/ValveSoftware/SteamOS/issues/1691#issuecomment-2442797266.

**Comment by CoderMonkey1956** [comment]
> Hello @CoderMonkey1956, similar to #1691, a SteamOS dev will need you to gather what system reports you can to take a look at the details. Please roughly follow the request for information at [#1691 (comment)](https://github.com/ValveSoftware/SteamOS/issues/1691#issuecomment-2442797266).

My steam username is MonkeyGamer1956

**Comment by lostgoat** [comment]
Hey @CoderMonkey1956

MonkeyGamer1956 doesn't seem to be a steam account name, but I found a couple of accounts that have that display name. One of them had an incomplete system report uploaded, I think that might be yours.

Can you send me your account name (the one used to login), or a link to your steam profile page to confirm I'm looking at the right account?

And can I trouble you to try uploading a couple of system reports again? I've edited your repro steps slightly to include the steps:

    1. Check for updates
    2. Download and apply the update to 3.6
    3. Restart. 
    4. Submit system report
    5. Restart button still shows, so restart again
    6. Upon restarting still stuck on 3.5
    7. Submit system report

**Comment by CoderMonkey1956** [comment]
> Hey @CoderMonkey1956
> 
> MonkeyGamer1956 doesn't seem to be a steam account name, but I found a couple of accounts that have that display name. One of them had an incomplete system report uploaded, I think that might be yours.
> 
> Can you send me your account name (the one used to login), or a link to your steam profile page to confirm I'm looking at the right account?
> 
> And can I trouble you to try uploading a couple of system reports again? I've edited your repro steps slightly to include the steps:
> 
> ```
> 1. Check for updates
> 2. Download and apply the update to 3.6
> 3. Restart. 
> 4. Submit system report
> 5. Restart button still shows, so restart again
> 6. Upon restarting still stuck on 3.5
> 7. Submit system report
> ```

https://steamcommunity.com/profiles/76561199126402401/ here's a link to my steam profile, I'll try those steps in a sec

**Comment by CoderMonkey1956** [comment]
Whoa - somethings going on. I can't upload to steam support or even save to desktop. I tried enabling wifi but no networks are shown (I'm sitting right next to the router and the Internet is definitely working) so I try going to desktop mode but the system just hangs on "Switching to Desktop..."

**Comment by CoderMonkey1956** [comment]
Update: I downgraded to 3.5 and was able to save the file to desktop (couldn't upload to steam support for some reason, it would just say it was uploading forever) is the report something I can upload here or should I upload it in some other way? Don't want to be doxxing myself lol.

**Comment by CoderMonkey1956** [comment]
@kisak-valve or @lostgoat (idk which one needs the system report) if it does contain private info, I could add it to a private repository and give you access

**Comment by lostgoat** [comment]
@CoderMonkey1956 thanks, no need. I got your system report.

**Comment by CoderMonkey1956** [comment]
> @CoderMonkey1956 thanks, no need. I got your system report.

Ok! (Probably should've mentioned I was able to submit one lol)

**Comment by lostgoat** [comment]
@CoderMonkey1956 I'm looking at your system report again and it looks like it was generated in desktop mode. Is that correct? There is some information that is missing that is only generated when running under the game mode session.

Could you try updating to 3.6 and trying the "submit to steam support" path from game mode? Also, don't click on "save to desktop" there is a bug that causes submissions to fail if you do "save to desktop" -> "cancel" -> "Submit to steam support"

**Comment by CoderMonkey1956** [comment]
> @CoderMonkey1956 I'm looking at your system report again and it looks like it was generated in desktop mode. Is that correct? There is some information that is missing that is only generated when running under the game mode session.
> 
> Could you try updating to 3.6 and trying the "submit to steam support" path from game mode? Also, don't click on "save to desktop" there is a bug that causes submissions to fail if you do "save to desktop" -> "cancel" -> "Submit to steam support"

Yea my only successful report sent to valve support was in desktop big picture mode. So my understanding of what to do next is to apply the update to 3.6, restart once (not twice), attempt to submit a report to valve support (not save to desktop), and if that does not work than attempt to ssh into the steam deck, run some commands (from your other post), and post the output here? Is that right?

**Comment by lostgoat** [comment]
Yeah, that is a good start.

If you are familiar with ssh, collecting the extra data @RyuzakiKK mentioned would also be useful. But if you haven't used it before then lets check the system report first.

**Comment by Mte90** [comment]
I have a similar issue and I already have ssh so I executed the various commands https://github.com/ValveSoftware/SteamOS/issues/1709

**Comment by CoderMonkey1956** [comment]
> Yeah, that is a good start.
> 
> If you are familiar with ssh, collecting the extra data @RyuzakiKK mentioned would also be useful. But if you haven't used it before then lets check the system report first.

Now I'm having the same issue here: #1704 

Great!

**Comment by CoderMonkey1956** [comment]
> > Yeah, that is a good start.
> > If you are familiar with ssh, collecting the extra data @RyuzakiKK mentioned would also be useful. But if you haven't used it before then lets check the system report first.
> 
> Now I'm having the same issue here: #1704
> 
> Great!

Basically I'll apply the November 5th stable update, itl say update failed, I'll restart (as the restart button still shows) and I'll be right back on 3.5, after 1 restart.

**Comment by CoderMonkey1956** [comment]
https://github.com/ValveSoftware/SteamOS/issues/1709#issuecomment-2459748417 I also tried this and did ``` sudo reboot ```

**Comment by lostgoat** [comment]
@CoderMonkey1956 please submit a system report after any of these errors. Without that data we can’t tell what is happening on your system.

**Comment by CoderMonkey1956** [comment]
> @CoderMonkey1956 please submit a system report after any of these errors. Without that data we can’t tell what is happening on your system.

Ok, so first I applied the update but before restarting tried to submit a report, it just hung on "submitting to steam support" so I saved to desktop (I can try to upload here if needed), theni applied the update, system wouldn't boot. So I booted into the previous boot option (in the menu you get to by using the QAM button) and tried submitting a report from there (also all of this was in 3.5 as I could not get into 3.6 without the system hanging on the steam logo) but it just said "couldn't submit report" and wouldn't even let me save to desktop.

**Comment by Mte90** [comment]
I get an alert saying that the submission was uncessful because of connectivity issues after a while. I didn't stopped their submissions.

**Comment by CoderMonkey1956** [comment]
I was able to get a report from 3.6 (i guess the first restart puts it into 3.6 but restarting again downgrades it) but i had to save to desktop, does it contain private info or can i upload it here?

**Comment by lostgoat** [comment]
It contains your unit serial number, names of games you have launched in the current and previous boot, and other things that could have been logged to the journal by any apps you have installed.

If you are comfortable with that, you can paste it here. Or you can attach it to a steam support ticket and I can get it from there.

**Comment by CoderMonkey1956** [comment]
> It contains your unit serial number, names of games you have launched in the current and previous boot, and other things that could have been logged to the journal by any apps you have installed.
> 
> If you are comfortable with that, you can paste it here. Or you can attach it to a steam support ticket and I can get it from there.
[systemreport-20241108204834.txt](https://github.com/user-attachments/files/17685087/systemreport-20241108204834.txt)

Here is the report (I redacted my SN but tell me if you need that and i can send it or check my previous reports)

**Comment by lostgoat** [comment]
@CoderMonkey1956 when you are in steamos 3.6 this command seems to be failing:
```
steamos-select-branch -c
```

Because of this the system goes into emergency mode (since it can't apply any updates) and sends you back to the previous OS when you click the restart button via the SteamUI.

Based on the system report it looks like there are a lot of modifications to your OS, including changes to the pacman configuration. The best steps would be to try to remove the modifications you've applied one by one to try to find which one interferes with the command I mentioned above. If you get that figured out you'll stop getting kicked back to SteamOS 3.5.

Alternatively, you can factory reset your deck to remove all your data and all the customization.

**Comment by CoderMonkey1956** [comment]
> @CoderMonkey1956 when you are in steamos 3.6 this command seems to be failing:
> 
> ```
> steamos-select-branch -c
> ```
> 
> Because of this the system goes into emergency mode (since it can't apply any updates) and sends you back to the previous OS when you click the restart button via the SteamUI.
> 
> Based on the system report it looks like there are a lot of modifications to your OS, including changes to the pacman configuration. The best steps would be to try to remove the modifications you've applied one by one to try to find which one interferes with the command I mentioned above. If you get that figured out you'll stop getting kicked back to SteamOS 3.5.
> 
> Alternatively, you can factory reset your deck to remove all your data and all the customization.

Hmm, i do remember messing with pacman to get https://gist.github.com/rondhi/f9163e7649aa734b5421a8f58bd6c49e this to work, so ill remove that along with any other configurations i can think of.

**Comment by lostgoat** [comment]
@CoderMonkey1956 if you run that command I pasted above in 3.6, do you get any output in the terminal?

If you send that over we can try to take some guesses at what might help. But we can't guarantee that we'll get a proper answer/solution for you as we aren't really in control of how third party mods change the system.

**Comment by CoderMonkey1956** [comment]
> @CoderMonkey1956 if you run that command I pasted above in 3.6, do you get any output in the terminal?
> 
> If you send that over we can try to take some guesses at what might help. But we can't guarantee that we'll get a proper answer/solution for you as we aren't really in control of how third party mods change the system.

when i enter the command it says "rel"

**Comment by CoderMonkey1956** [comment]
i didnt realze you said 3.6, lemme try it...

**Comment by CoderMonkey1956** [comment]
> @CoderMonkey1956 if you run that command I pasted above in 3.6, do you get any output in the terminal?
> 
> If you send that over we can try to take some guesses at what might help. But we can't guarantee that we'll get a proper answer/solution for you as we aren't really in control of how third party mods change the system.

I also checked the pacman config and figured out that I had removed the chaotic-aur thing.

**Comment by CoderMonkey1956** [comment]
> @CoderMonkey1956 if you run that command I pasted above in 3.6, do you get any output in the terminal?
> 
> If you send that over we can try to take some guesses at what might help. But we can't guarantee that we'll get a proper answer/solution for you as we aren't really in control of how third party mods change the system.

Unfortunately the command just says it has an error without giving any output, even when I started konsole in verbose (-v) mode. Note that in the weird half broken 3.6 that my system enters I cannot enter desktop mode so I had to run the command in a nested desktop app I had. Here's a list of the non flatpak apps/configs (excluding apps installed with pacman or through the aur) I can think of

1. Decky Loader https://decky.xyz/
2. SteamOS-Clover-Dualboot https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot
3. SteamOS-Waydroid-Installer https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer

Is it possible that you could list out some of the mods that is shows (if it shows them lol) and would it help if I showed a list of my pacman installed packages?

**Comment by lostgoat** [comment]
@CoderMonkey1956 The system report doesn't have a list of the mods themselves (we can't really keep track of these), but it does list modified files in /etc to help us track configuration changes that may have affected SteamOS behaviour.

If you ctrl+f in your system report for this string `find /var/lib/overlays/etc/upper` you'll find a list of modified files that might be relevant.

Something else to try for more verbose output could also be:
```
atomupd-manager tracked-branch --verbose
```

**Comment by CoderMonkey1956** [comment]
> @CoderMonkey1956 The system report doesn't have a list of the mods themselves (we can't really keep track of these), but it does list modified files in /etc to help us track configuration changes that may have affected SteamOS behaviour.
> 
> If you ctrl+f in your system report for this string `find /var/lib/overlays/etc/upper` you'll find a list of modified files that might be relevant.
> 
> Something else to try for more verbose output could also be:
> 
> ```
> atomupd-manager tracked-branch --verbose
> ```

Hmm, I can't find anything in that list, I'll try running the verbose command. Also for some reason my SD card got wiped? Super glad I didn't have anything too critical on there. But I'll go ahead and try that command.

**Comment by CoderMonkey1956** [comment]
> > @CoderMonkey1956 The system report doesn't have a list of the mods themselves (we can't really keep track of these), but it does list modified files in /etc to help us track configuration changes that may have affected SteamOS behaviour.
> > If you ctrl+f in your system report for this string `find /var/lib/overlays/etc/upper` you'll find a list of modified files that might be relevant.
> > Something else to try for more verbose output could also be:
> > ```
> > atomupd-manager tracked-branch --verbose
> > ```
> 
> Hmm, I can't find anything in that list, I'll try running the verbose command. Also for some reason my SD card got wiped? Super glad I didn't have anything too critical on there. But I'll go ahead and try that command.

Wait... Maybe the SD card is fine?

**Comment by CoderMonkey1956** [comment]
> Replying to https://github.com/ValveSoftware/SteamOS/issues/1695#issuecomment-2465949427

Here's the output of that command (run in 3.6)

**Comment by CoderMonkey1956** [comment]
Ok, the sd card is fine

**Comment by lostgoat** [comment]
> Here's the output of that command (run in 3.6)

The comment looks empty. Was a paste accidentally skipped?

**Comment by CoderMonkey1956** [comment]
> > Here's the output of that command (run in 3.6)
> 
> The comment looks empty. Was a paste accidentally skipped?

Oops, sorry about that. Here's the output: 

An error occurred while getting the branch: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: startup job failed.

**Comment by CoderMonkey1956** [comment]
Not sure if this is relevant or not, but before this, when I originally tried to update to 3.6, the system hung on the steamos logo (like the vendor logo) so I force reset, then booted into it from the QAM menu, and it gave me an error like "sh: can't access tty job control turned off" so I booted into previous, and eventually figured out that if I switched the system to beta steamos channel, restart, apply beta update, restart, then switch to stable channel, and restart, it would fix the issue and boot into 3.5, and every time I update to 3.6 I have to do that. Is that related in any way?

**Comment by RyuzakiKK** [comment]
```
Command: lsblk -nro name,partuuid,size,fstype,label,mountpoint
[...]
nvme0n1p6 2d8d0224-4e8a-824e-b9ad-cf8571fc8b40 3.2G ext4 var 
nvme0n1p7 1c5f1a21-5b1e-c44f-b24a-848b4caaeb93 455M ext4 var /var
```

@CoderMonkey1956  from your log it seems like you resized the var partitions. By default they should be both of 256M in size.

Related to that, I can see this error message, likely what's causing `atomupd-manager` to fail:
```
Nov 08 14:47:55 steamdeck atomupd-daemon[2940]: An error occurred while initializing the daemon: Failed to write file “/etc/steamos-atomupd/preferences.conf.O7KGW2”: write() failed: No space left on device
Nov 08 14:47:55 steamdeck systemd[1]: atomupd.service: Main process exited, code=exited, status=1/FAILURE
Nov 08 14:47:55 steamdeck systemd[1]: atomupd.service: Failed with result 'exit-code'.
Nov 08 14:47:55 steamdeck systemd[1]: Failed to start Atomic Update Daemon.
```

You can run:
```
find /var -type d \( -path /var/lib/flatpak -o -path /var/cache/pacman -o -path /var/log \) -prune -o -type f -exec du -h {} + 2>/dev/null | sort -rh | head -n 20
```
which will print out the 20 biggest files under `/var`.
If you can make some space there, as a short term solution it is probably enough. (if you are unsure of which files are safe to be deleted, feel free to post the output here)

However, given the highly modified system environment, I'd highly recommend to use the [recovery image](https://help.steampowered.com/en/faqs/view/1b71-edf2-eb6d-2bb3) and start over from a clean state.

**Comment by CoderMonkey1956** [comment]
> ```
> Command: lsblk -nro name,partuuid,size,fstype,label,mountpoint
> [...]
> nvme0n1p6 2d8d0224-4e8a-824e-b9ad-cf8571fc8b40 3.2G ext4 var 
> nvme0n1p7 1c5f1a21-5b1e-c44f-b24a-848b4caaeb93 455M ext4 var /var
> ```
> 
> @CoderMonkey1956 from your log it seems like you resized the var partitions. By default they should be both of 256M in size.
> 
> Related to that, I can see this error message, likely what's causing `atomupd-manager` to fail:
> 
> ```
> Nov 08 14:47:55 steamdeck atomupd-daemon[2940]: An error occurred while initializing the daemon: Failed to write file “/etc/steamos-atomupd/preferences.conf.O7KGW2”: write() failed: No space left on device
> Nov 08 14:47:55 steamdeck systemd[1]: atomupd.service: Main process exited, code=exited, status=1/FAILURE
> Nov 08 14:47:55 steamdeck systemd[1]: atomupd.service: Failed with result 'exit-code'.
> Nov 08 14:47:55 steamdeck systemd[1]: Failed to start Atomic Update Daemon.
> ```
> 
> You can run:
> 
> ```
> find /var -type d \( -path /var/lib/flatpak -o -path /var/cache/pacman -o -path /var/log \) -prune -o -type f -exec du -h {} + 2>/dev/null | sort -rh | head -n 20
> ```
> 
> which will print out the 20 biggest files under `/var`. If you can make some space there, as a short term solution it is probably enough. (if you are unsure of which files are safe to be deleted, feel free to post the output here)
> 
> However, given the highly modified system environment, I'd highly recommend to use the [recovery image](https://help.steampowered.com/en/faqs/view/1b71-edf2-eb6d-2bb3) and start over from a clean state.



> ```
> Command: lsblk -nro name,partuuid,size,fstype,label,mountpoint
> [...]
> nvme0n1p6 2d8d0224-4e8a-824e-b9ad-cf8571fc8b40 3.2G ext4 var 
> nvme0n1p7 1c5f1a21-5b1e-c44f-b24a-848b4caaeb93 455M ext4 var /var
> ```
> 
> @CoderMonkey1956 from your log it seems like you resized the var partitions. By default they should be both of 256M in size.
> 
> Related to that, I can see this error message, likely what's causing `atomupd-manager` to fail:
> 
> ```
> Nov 08 14:47:55 steamdeck atomupd-daemon[2940]: An error occurred while initializing the daemon: Failed to write file “/etc/steamos-atomupd/preferences.conf.O7KGW2”: write() failed: No space left on device
> Nov 08 14:47:55 steamdeck systemd[1]: atomupd.service: Main process exited, code=exited, status=1/FAILURE
> Nov 08 14:47:55 steamdeck systemd[1]: atomupd.service: Failed with result 'exit-code'.
> Nov 08 14:47:55 steamdeck systemd[1]: Failed to start Atomic Update Daemon.
> ```
> 
> You can run:
> 
> ```
> find /var -type d \( -path /var/lib/flatpak -o -path /var/cache/pacman -o -path /var/log \) -prune -o -type f -exec du -h {} + 2>/dev/null | sort -rh | head -n 20
> ```
> 
> which will print out the 20 biggest files under `/var`. If you can make some space there, as a short term solution it is probably enough. (if you are unsure of which files are safe to be deleted, feel free to post the output here)
> 
> However, given the highly modified system environment, I'd highly recommend to use the [recovery image](https://help.steampowered.com/en/faqs/view/1b71-edf2-eb6d-2bb3) and start over from a clean state.

Can confirm, I have resized the /var partitions because pacman packages would not install if I didn't, I'll try clearing the pacman cache and running that command after.

**Comment by CoderMonkey1956** [comment]
For anyone having the same issue, all I did was run ```sudo pacman -Scc``` and run the find command that @RyuzakiKK mentioned and deleted some of those.

**Comment by CoderMonkey1956** [comment]
> > @CoderMonkey1956 if you run that command I pasted above in 3.6, do you get any output in the terminal?
> > If you send that over we can try to take some guesses at what might help. But we can't guarantee that we'll get a proper answer/solution for you as we aren't really in control of how third party mods change the system.
> 
> Unfortunately the command just says it has an error without giving any output, even when I started konsole in verbose (-v) mode. Note that in the weird half broken 3.6 that my system enters I cannot enter desktop mode so I had to run the command in a nested desktop app I had. Here's a list of the non flatpak apps/configs (excluding apps installed with pacman or through the aur) I can think of
> 
> 1. Decky Loader https://decky.xyz/
> 2. SteamOS-Clover-Dualboot https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot
> 3. SteamOS-Waydroid-Installer https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
> 
> Is it possible that you could list out some of the mods that is shows (if it shows them lol) and would it help if I showed a list of my pacman installed packages?

Just noticed that if forgot that I had "SteamOS-Mount-External-Drive" which I think was the issue.
