### ISSUE TITLE
Steam deck LCD requires more power to do the same things it did before  after F7A0131 Bios update

### ISSUE THREAD

**Issue by srmoska** [ValveSoftware/SteamOS#1701]
#### Your system information

* Steam client version: 1730416762
* SteamOS version: 3.6.20
* Opted into Steam client beta?: [Yes/No] YES
* Opted into SteamOS beta?: [Yes/No] YES
* Have you checked for updates in Settings > System?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
After  the 3.6.19 stable update that included and update to the BIOS, the Steam Ui started performing with lots of hiccups and stuttering becoming almost unusable with a TDP of 3 watts, didn't had this problem before the update (been using my steam deck since 2022), Steam even froze once while browsing settings. Switched to Steam BETA 3.6.20 but the problem persisted

Also noted that the game The mummy demastered that worked fine with a TDP of 3 watts before the update, but now I had the ramp up the TDP up to 5 watts to get the game working, at 3 watts the game runs at 27FPS instead of 60FPS like it used to work before

Downgraded F7A0131 to F7A0121 and both problems corrected

#### Steps for reproducing this issue:

1. At 3 watts  with bios  version F7A0131, the steam library is very slow and with very bad stuttering
2. downgraded to BIOS version F7A0121 
3. Performance returned to normal

**Comment by deathblade201243** [comment]
from what I heard the issue in this video was fixed. https://www.youtube.com/watch?v=fZ7T3mDPtZY idk how true that is though. I never use the TDP limit I just use powertools which provides the same effect with much more control of whats underclocked

**Comment by srmoska** [comment]
> from what I heard the issue in this video was fixed. https://www.youtube.com/watch?v=fZ7T3mDPtZY idk how true that is though. I never use the TDP limit I just use powertools which provides the same effect with much more control of whats underclocked

that video is form 2022, this problem I'm mentioning started early this week when they rolled the new BIOS F7A0131. I fixed it by rolling back to the previous version F7A0121 that I was using last week

**Comment by deathblade201243** [comment]
> > from what I heard the issue in this video was fixed. https://www.youtube.com/watch?v=fZ7T3mDPtZY idk how true that is though. I never use the TDP limit I just use powertools which provides the same effect with much more control of whats underclocked
> 
> that video is form 2022, this problem I'm mentioning started early this week when they rolled the new BIOS F7A0131. I fixed it by rolling back to the previous version F7A0121 that I was using last week

I posted the video to show you the issue that was supposedly fixed. the date of the video is irrelevant. it being fixed would explain your issue since TDP was higher than reported.

**Comment by kisak-valve** [comment]
Hello @srmoska, this issue is already being tracked at #1689. Since this issue report adds a bit more detail, I've gone ahead and transferred it to https://github.com/ValveSoftware/SteamOS/issues/1689#issuecomment-2452559631. Closing as a duplicate.
