### ISSUE TITLE
Updating to 3.6.20 fails from 3.5.19 after some package installations

### ISSUE THREAD

**Issue by Mte90** [ValveSoftware/SteamOS#1709]
I am with the Steam deck with the 3.5.19 release but trying to update my guide to get the OpenRazer on SteamDeck https://daniele.tech/2022/12/how-to-get-openrazer-working-easily-on-steam-deck/ I probably changed something internally.
Right now doesn't update to 3.6.20, there is the progress bar but at the end is still the 3.5.19, also the boot menu show that version and the 3.5.17. In the past I had the issue that sometimes at boot will load the wrong version and the 3.6.20 should fix that issue.

I tried to send the report on Settings->System to Steam as Mte90 but fails, also the desktop one fails (I generated with the command).

I executed some commands from https://github.com/ValveSoftware/SteamOS/issues/1695#issuecomment-2456786322

```
(1)(deck@T-800 ~)$ atomupd-manager check --verbose
Updates available:
ID: 20241030.1 - variant: 'steamdeck' - estimated_size: 1708671204 - update_type: 0
```

```
(deck@T-800 ~)$ journalctl -u atomupd
Nov 06 13:59:12 T-800 systemd[1]: Starting Atomic Update Daemon...
Nov 06 13:59:13 T-800 systemd[1]: Started Atomic Update Daemon.
Nov 06 13:59:13 T-800 atomupd-daemon[6611]: WARNING:image.py:179: The image manifest has some unknown key-values: {'branch': 'stable', 'default_update_branch': 'stable'}
```

```
(deck@T-800 ~)$ ls /var/lib/overlays/etc/upper/steamos-atomupd
client.conf
(deck@T-800 ~)$ ls /var/lib/overlays/etc/upper/rauc
system.conf
```

**Comment by Mte90** [comment]
[report.txt](https://github.com/user-attachments/files/17647543/report.txt)
Attached there is the report generated (it was too long for github).

**Comment by Mte90** [comment]
Seems that compared to few days ago now Reboot to install the updates doesn't do anything, I don't see any progressbar and the version sometimes is .17 or .19

Let me know if I can do something else to help you :-)

PS: I think that I executed the command as beta channel configured (I did various tests).

**Comment by RyuzakiKK** [comment]
It seems like nearly all your `/etc` files have been marked as user edited.

In theory if you run:
```
sudo rm /var/lib/overlays/etc/upper/desync/config.json
sudo rm /var/lib/overlays/etc/upper/steamos-atomupd/client.conf
sudo rm /var/lib/overlays/etc/upper/rauc/system.conf
```

And then reboot, you'll revert those key files to their default values from the SteamOS image.

After that the 3.6.20 update should succeed.

**Comment by Mte90** [comment]
[report.txt](https://github.com/user-attachments/files/17647804/report.txt)

Executed the 3 commands and rebooted on the system settings to apply the updates but it is still 3.5.19.

**Comment by Mte90** [comment]
I executed the 3 commands and rebot as you said but it is still reporting an update and to reboot and the 3.6.20 version is not installed.

[report.txt](https://github.com/user-attachments/files/17658443/report.txt) generated after the reboot.

```
(1)(deck@T-800 ~)$ sudo rm /var/lib/overlays/etc/upper/desync/config.json
[sudo] password for deck:
rm: cannot remove '/var/lib/overlays/etc/upper/desync/config.json': No such file or directory
(1)(deck@T-800 ~)$ sudo rm /var/lib/overlays/etc/upper/rauc/system.conf
rm: cannot remove '/var/lib/overlays/etc/upper/rauc/system.conf': No such file or directory
(1)(deck@T-800 ~)$ sudo rm /var/lib/overlays/etc/upper/steamos-atomupd/client.conf
rm: cannot remove '/var/lib/overlays/etc/upper/steamos-atomupd/client.conf': No such file or directory
(1)(deck@T-800 ~)$ sudo reboot
```

**Comment by RyuzakiKK** [comment]
If you are still in 3.5.17, as when you generated your last report, could you please run:
```
sudo steamos-update check -d
sudo steamos-update -d
journalctl -u rauc > rauc.log
```
and copy paste the output and the `rauc.log`?

**Comment by Mte90** [comment]
Yeah because sometimes reboot to the old version.

```
(1)(deck@T-800 ~)$ sudo steamos-update check -d
[sudo] password for deck:
Update available
20241030.1
(deck@T-800 ~)$ sudo steamos-update -d
Update available
100.00%
Update completed
Applied an update
```

[report.txt](https://github.com/user-attachments/files/17662065/report.txt)

I am trying a reboot now :-)

**Comment by Mte90** [comment]
Ok it worked now it is updated to 3.6.20, I will try my script to install openrazer hoping that the problem is gone now.

**Comment by RyuzakiKK** [comment]
> I will try my script to install openrazer hoping that the problem is gone now.

I had a brief look at it. You definitely shouldn't change the pacman repositories. That's an easy way to end up with a broken system.

If you need more up to date packages that are not available in the `-rel` repositories (now called `-3.6`), should move to SteamOS beta or main from the Steam UI, and not manually change the repos and run `pacman -Syu`.

**Comment by Mte90** [comment]
I don't remember why I changed the repositories but I think because the packages weren't available otherwise.
Also the steamos image for steam deck is not updated since 2 years so I can't test it in a VM.

**Comment by CoderMonkey1956** [comment]
> I don't remember why I changed the repositories but I think because the packages weren't available otherwise. Also the steamos image for steam deck is not updated since 2 years so I can't test it in a VM.

Has your issue been fixed?

**Comment by Mte90** [comment]
Yes I fixed at the end following the commands above.
