### ISSUE TITLE
Gamescope scales Zenity/GTK dialogs differently on legacy Steam Deck versus Steam Deck OLED

### ISSUE THREAD

**Issue by aclist** [ValveSoftware/SteamOS#1722]
#### Your system information

* Steam client version: 1721173382
* SteamOS version: 3.5.19
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes (see remarks below)

GTK3 applications launched as a Non-Steam Game through Gaming Mode are scaled to a resolution that exceeds the boundaries of the viewport.

This can be seen with standalone GTK3 applications, or simple dialog tests such as wrapping the commandline `zenity --question` into a script.

Images provided by a user (I do not have a Steam Deck OLED test bench):

Zenity example
---
![1731286198](https://github.com/user-attachments/assets/e9d0efe7-d8f1-456b-adea-5b3400de4afa)

PyGTK example
---
![1731286322](https://github.com/user-attachments/assets/c93173c1-13bf-43b1-b84c-1a465aa49909)

The Steam client and OS version numbers provided above were current at the time I received the initial bug report. They are some revisions behind as of this writing, but the user confirmed the same behavior again on the latest version of Steam OS and Steam client.

By contrast, this behavior is not observed on legacy (non-OLED) Steam Deck. GTK applications and their dialogs are constrained to the viewport.

It seems as though the different formfactor of the Steam Deck OLED causes unintended behavior when gamescope tries to fullscreen GTK applications, in particular (but not limited to) modal dialogs. The screen overflow issue also happens to the root application window.

I am not sure whether this issue is peripheral to https://github.com/ValveSoftware/SteamOS/issues/1534, but because I cannot reproduce it on a legacy Steam Deck, and it is not localized to zenity, I believe it is a separate issue specific to Steam Deck OLED's interaction with gamescope.

If the `zenity --question` example above does not suffice, I can provide a small PyGTK MRE demonstrating this behavior. 

I've limited the scope of the report above to GTK3, but it should be easy to verify whether this also happens with GTK4 applications.

**Comment by bertogg** [comment]
Hi, `zenity --question` looks identical to me on the LCD and the OLED decks. This is running SteamOS 3.6 stable, but it was also working fine with 3.5.

![pic](https://github.com/user-attachments/assets/60197b53-f490-4b69-aea2-8d382ce6a2d7)

**Comment by aclist** [comment]
I assume this is user error, then. I have asked for additional information. Given that you can't inadvertently change the stock settings on Gaming Mode without customizing the launch parameters of each application, I'm not sure how this effect was achieved.

**Comment by aclist** [comment]
I was unable to get further repro information from the end-user or simulate this behavior myself on physical hardware. I'm forced to conclude it's user error or interference from third-party customizations for now. I will reopen this ticket if further information is obtained at some point.
