### ISSUE TITLE
[Feature Request| Gyroscope aiming for Deadlock/CS2

### ISSUE THREAD

**Issue by fiestafutbolX9** [ValveSoftware/SteamOS#1726]
Steam client version: 4.62.99.22
SteamOS version: 3.0
Opted into Steam client beta?: No
Opted into SteamOS beta?: No
Have you checked for updates in Settings > System?: No

I would like to request the implementation of gyroscope aiming support for Deadlock and CS2 on the Steam Deck running SteamOS. Currently, Deadlock and CS2 does not utilize the Steam Deck's gyroscope for aiming, which limits the potential for more precise and intuitive control schemes. Integrating gyroscope aiming would enhance the gameplay experience by allowing for finer control, especially in aiming and shooting scenarios, like its utilized in games such as TOTK or Splatoon 3. 

1.Launch Deadlock/Counter Strike 2 on the Steam Deck.
2. Attempt to use the gyroscope for aiming.
3. Observe that the gyroscope input does not affect aiming.

**Comment by kisak-valve** [comment]
Hello @fiestafutbolX9, this request should be directed at the game devs, not at SteamOS as a platform. Unfortunately, neither of these games track feature requests on GitHub. Feel free to post this request on the individual game's community forums.

**Comment by pinknoseboopy** [comment]
> Hello @fiestafutbolX9, this request should be directed at the game devs, not at SteamOS as a platform. Unfortunately, neither of these games track feature requests on GitHub. Feel free to post this request on the individual game's community forums.

Thanks, I'll make sure to do that.
