### ISSUE TITLE
[Bug] WiFi 6ghz and WPA 3 still broken

### ISSUE THREAD

**Issue by systox** [ValveSoftware/SteamOS#1730]
#### Your system information

* Steam client version: 3.6.19
* SteamOS version: latest stable
* Opted into Steam client beta?: [Yes/No] no
* Opted into SteamOS beta?: [Yes/No] no
* Have you checked for updates in Settings > System?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Connecting to WiFi 6ghz band with WPA3 only works in desktop mode. This will then let you connect in game mode for about a day. Eventually game mode will stop connecting and prompt to recenter the WiFi password for some reason. However there is no way to enter the. Password and you have to reconnect in desktop mode to get WiFi for a piddly couple days again. Rinse repeat.

#### Steps for reproducing this issue:

1.  Connect to 6ghz WiFi with wpa 3 security
2. Wait a couple days
3.  Be prompted to enter WiFi password again and receive no field to enter password in.

**Comment by kisak-valve** [comment]
Hello @systox, this issue is already being tracked at #1096. Closing as a duplicate.
