### ISSUE TITLE
Git no longer included on SteamOS Main images as of 20241125.1000

### ISSUE THREAD

**Issue by matte-schwartz** [ValveSoftware/SteamOS#1732]
Looks like git is no longer included in the SteamOS Main base image since staging was merged into it, is this an intentional change?

**Comment by Kaizo107** [comment]
Also bumped into this last night, even after manually installing Git, this has rendered EmuDeck inoperable.

**Comment by bertogg** [comment]
Thanks for the report, this should be fixed in the next image.

**Comment by matte-schwartz** [comment]
fixed in 20241217.1000
