### ISSUE TITLE
Offical xbox wireless adapter not working

### ISSUE THREAD

**Issue by frzifus** [ValveSoftware/SteamOS#1747]
#### Your system information

* Steam client version: 1733265492
* SteamOS version: 3.6.20
* Opted into Steam client beta?: No 
* Opted into SteamOS beta?:No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I have tried to connect my wireless adapter for xbox controller to the steam deck. Unfortunately without success. (Link: [Microsoft Store](https://www.microsoft.com/de-de/d/xbox-wireless-adapter-for-windows/91dqrb97l130))

The use of the dongle enables the use of the audio connection on the controller, allows up to 8 controllers to be paired simultaneously and switches them off when the machine is shut down.
At least on my living room pc with [ChimeraOS](https://chimeraos.org/) this works perfectly.

There is a community workaround. However, a direct integration would be much more convenient and safer:
https://gist.github.com/SavageCore/263a3413532bc181c9bb215c8fe6c30d/

#### Steps for reproducing this issue:

1. Start the Steam Deck and connect it to the docking station
2. Plug the wireless paring adapter into the docking station
3. Bring xbox one controller into pairing mode
4. Press the pairing button on the wireless dongle
5. Nothing happens

**Comment by kisak-valve** [comment]
Hello @frzifus, this issue is already being tracked at #745. Closing as a duplicate.

**Comment by frzifus** [comment]
Thanks for pointing me there.
