### ISSUE TITLE
[Feature Request] Full-disk encryption

### ISSUE THREAD

**Issue by chexo3** [ValveSoftware/SteamOS#1760]
Since I know Valve are looking at making parts of SteamOS available for use on other machines than the Steam Deck, this might be something to look into, at least as a "nice to have" feature. This may be a low priority for the Steam Deck's use case, but I still think it's worth investigating. For other hardware form factors, such as a laptop or even a standalone VR headset like the various Deckard leaks, I think it is something many people wouldn't want to go without.

Performance is perfectly adequate for both booting and running games off an encrypted LVM + LUKS setup, such as what I have going on the computer I'm writing this issue on. If I had a secondary game drive for Steam games, I *might* not encrypt it, but since it's on the same drive as my OS anyways I figured I might as well, and I haven't noticed any problems doing so.

There are however some concerns for user experience, security, error recovery, and deployment.

1. **User Experience:** I don't think a lot of people will want to type in a password using the on-screen keyboard when they boot their device. Teams working on disk encryption should look into key derivation techniques, so that a shorter PIN could be used. On devices with appropriate hardware support (e.g. a TPM on x86, similar on Arm) it may be a good idea to use Secure Boot or similar to prevent brute forcing a PIN.
2. **Security:** In the context of portable/handheld devices, unattended or stolen but already running (and therefore, disks unlocked) devices are a concern. The data on the storage medium itself will still be encrypted, but if you can bypass a lock screen and copy everything from the running OS, then the security has been defeated. I don't know how feasible it is, but maybe SteamOS could re-lock the storage device after a certain time has passed?
3. **Error Recovery:** Fixing things will be much more difficult. If something breaks (whether because of bad design or a user doing something foolish), encrypted drives can make it harder to recover.
4. **Deployment:** Full-disk encryption can make setup more complicated since you have to gather a pass-(word/key/code), then create an encrypted volume to install into, rather than simply copying files to the storage device once at the factory.

Prior art:

Apple and their macOS and iOS devices have done this already and may be worth looking into as another *nix-like system under the hood. They have the advantage of more specialized hardware, though.

Similar story with Google, Android, and that whole ecosystem. Android is closer to what Steam Decks run, being modified Linux, but there is a lot of stuff Android adds or changes that can't be translated 1:1 to a closer to mainline Linux kernel like Steam OS runs.

PostmarketOS is a small community Linux distribution for primarily mobile devices running Linux, based off Alpine Linux. Their main focus is older mobile devices, many of which used to run Android and no longer get security updates. They support full disk encryption and their contributors may be worth reaching out to for help. Valve is one of the few companies I could trust to be equal partners in a relationship like that, so if y'all do reach out to them for this or other similar problem domains (since both Valve's work and PostmarketOS are working on embedded/mobile devices, there may be more overlap than just this specific feature) I hope both parties get something out of it.

**Comment by kisak-valve** [comment]
Hello @chexo3, this request is already being tracked at #771. Closing as a duplicate.

**Comment by chexo3** [comment]
Thanks Kisak, sorry!

**Comment by chexo3** [comment]
Want me to copy-paste the part about prior art? I think it could still be handy for y'all.

**Comment by chexo3** [comment]
@kisak-valve Want me to copy-paste the part about prior art? I think it could still be handy for y'all.
