### ISSUE TITLE
Valve-bugreporter stores credentials in plain text

### ISSUE THREAD

**Issue by ndob** [ValveSoftware/SteamOS#19]
Package: valve-bugreporter
Version: 2.10+bsos1

If user checks "Remember Credentials", when using Valve Bug Reporter tool, the tool stores credentials in plain text to a file called ~/.valve-bugreporter.cfg.

The valve-bugreporter-package seems to have dependency to some gnome-keyring related packages, but they are not being used.

**Comment by johnv-valve** [comment]
we are no longer shipping this on steamos
