### ISSUE TITLE
SteamOS for Tegra

### ISSUE THREAD

**Issue by dmmdea** [ValveSoftware/SteamOS#191]
There is a new development kit, called the "Jetson TK1", released for testing by Nvidia.

It is an interesting piece of hardware, as it comes equipped with Tegra K1 SOC:
- 4-Plus-1 quad-core ARM Cortex A15 CPU.
- Kepler GPU with 192 CUDA cores.
- 2 GB x16 memory with 64 bit width.
- 16 GB 4.51 eMMC memory.
- For full specs visit: https://developer.nvidia.com/jetson-tk1

The thing is... It supports Linux for Tegra, and more specifically, it supports OpenGL 4.3 (OpenGL 2.1 is needed for most SteamOS games).
- More info on Linux for Tegra can be found in: https://developer.nvidia.com/linux-tegra-rel-19

Now, I'm no expert in this subject, but I wonder if Valve could implement some kind of support for this platform, since the specs are pretty much similar to a regular PC (It would only be suitable for some light gaming though, but Linux doesn't have many AAA titles yet, anyway), and it already supports Linux in some way (again, I'm not familiar with the subject).

I think this has a lot of potential for a really small form factor rig at an extremely low price.
- More info about support for the platform: https://developer.nvidia.com/jetson-tk1-support

Could it be done? Thanks.

**Comment by proglo** [comment]
why is steam not open source / why do people still tolerate such behavior

**Comment by not83** [comment]
Not a bug. Please close

**Comment by MrSchism** [comment]
Uh... wrong post, @not83?

**Comment by not83** [comment]
No?

**Comment by Tele42** [comment]
Just to be clear, asking for a closed issue report to be closed isn't going to lead to an action.

**Comment by not83** [comment]
If it's not a bug then it can't be felt with can it. This is a bug reporter

**Comment by MrSchism** [comment]
Our point was that you asked for it to be closed.  It *is* closed.

**Comment by not83** [comment]
Ahh 😊 doing this by email sorry
