### ISSUE TITLE
During setup, when asked about location, the UK is confusingly listed listed as "Britain (UK)"

### ISSUE THREAD

**Issue by mdiluz** [ValveSoftware/SteamOS#192]
Probably not the most important issue to fix right now, but I figure it's worth mentioning.

As a country we usually have to look under U (UK), E (England) and G (Great Britian) to find the correct entry in these lists, but finding the UK under B was a confusing user experience.

**Comment by johnv-valve** [comment]
timezone list is now sorted by UTC offset, so you can find UK at "UTC-00:00 Greenwich Mean Time: Dublin, Liberia, London, Reykjavik"
