### ISSUE TITLE
SteamOS issue with netflix-desktop

### ISSUE THREAD

**Issue by psymin** [ValveSoftware/SteamOS#203]
netflix-desktop works properly as user 'steam' when the desktop is 'gnome'
netflix-desktop works properly when added as a non-steam game to the steam library and steam is run in big picture mode from within gnome
netflix-desktop does not work properly when launched as a non-steam game when the desktop is 'steamos' and not 'gnome'

Everything appears to work properly except the video stream.  Audio is fine.

**Comment by ProfessorKaos64** [comment]
Netflix-desktop will not work. You can talk to the devs in the pipelight IRC channel. There is a specific reason it will not work. I believe the page on their website for installing it has this message. As you likely know at this point @psymin , using Google Chrome in kiosk mode is the way to go.
