### ISSUE TITLE
[Feature Reqest] Exit running game through Steam BPM overlay

### ISSUE THREAD

**Issue by AsavarTzeth** [ValveSoftware/SteamOS#206]
This feature kind of exists on consoles and I would like to see it in SteamOS.

There are situations where a game might behave weirdly and you are unable to close it. This will force you to do one of 3 things. Either you reboot the computer, enter another TTY (not user-friendly) and kill the process, thus returning you to BPM or you wait and hope Steam detects the issue (might crash) and restarts itself some time later.

This could simply be implemented with a shortcut next to "(A) Select", using for example, (X) Exit game. This would then kindly send SIGINT or SIGTERM and if all else fails use SIGKILL if it really has to.

If you think SIGKILL is to risky a pop-up could be presented in the overlay informing the user that the game does not respond to your command and that it could force kill it and informing the user of the usual risks like lost data and so on. Not that you lose data that often, but still.

Combine this with my other issue #205
and you will often get the feeling of a broken system where you have to restart or mess around a lot to get things working.

Please consider this request. A lot of times when games behave badly or break Steam still works great and the overlay still responds. To Windows gamers this could probably be a better replacement to using Ctrl+Alt+Del than entering a shell on a different TTY would be...

**Comment by sigboe** [comment]
I am under the impression that the way the feature is implemented now is only a SIGTERM, so if the game for some reason does not respond to SIGTERM then it would be nice to not have to fiddle with a terminal or whatever. Makes it more user-friendly for the regular joe, so I hope @johnv-valve would reopen this request.
