### ISSUE TITLE
[Suggestion] Upgrade SteamOS's core to Debian 8 jessie

### ISSUE THREAD

**Issue by waitwhobrokethat** [ValveSoftware/SteamOS#210]
Why i'm saying this is Debian 8 jessie will be released around February 2015 and seeing how Debian 8 Jessie will be frozen on 5 November 2014 not a lot of change will happen from November to February? as we all know steam machines are? delayed until some time in 2015? i see this as greatly benefiting your customers/vendors/developers by giving them a better performing core with more hardware support Etc and more up to date software stacks

**Comment by cwaffles** [comment]
Debian 8 has been released, hopefully the merge will start :+1:

**Comment by not83** [comment]
Seconded. Debain 7 is really old and this might give better performance

**Comment by ProfessorKaos64** [comment]
I'd have to hope that Jessie would be in the works before the November Steam Machines release. To release those machines based on Wheezy would be quite an odd choice.
