### ISSUE TITLE
Bios time reset

### ISSUE THREAD

**Issue by cyndairin** [ValveSoftware/SteamOS#218]
Fri , Aug , 8 , 2014
I logged into Steam OS today after an update and had the clock reset to 12:00 I then logged out to my Windows OS and found that the time had been changed there as well so I rebooted again to find that the computer bios clock was also changed .

**Comment by supertin** [comment]
A note to anyone coming across this - set Linux to use local instead for trying to get Windows to use UTC.

Windows support for UTC in RTC is terrible, and you WILL have problems in Windows with such a setup. For starters, you will get incorrect times every few hours if the "internet time" client is left on.

**Comment by johnv-valve** [comment]
We no longer set the time in SteamOS brewmaster. But Linux and Windows will always disagree over whether the BIOS time is local (Windows) or UTC (Linux)
