### ISSUE TITLE
SteamOS update 133 no sound output with Nvidia HDMI

### ISSUE THREAD

**Issue by zaxen** [ValveSoftware/SteamOS#225]
With SteamOS update 133 on the beta channel, no sound can be heard through an Nvidia card using an HDMI connection.

Multiple people experiencing this in this thread: http://steamcommunity.com/groups/steamuniverse/discussions/1/35221584678322281/

User sylence posted a work around in the thread here: http://steamcommunity.com/groups/steamuniverse/discussions/1/35221584678322281/#c35222218678959581

**Comment by johnv-valve** [comment]
I think this is resolved in the current Steam beta client, please reopen if you are still seeing this.
