### ISSUE TITLE
Default login page appears on boot

### ISSUE THREAD

**Issue by udev** [ValveSoftware/SteamOS#226]
Big Picture mode fails to launch after installing Node Version Manager via script.

relevant script: curl https://raw.githubusercontent.com/creationix/nvm/v0.16.0/install.sh | bash
NVM home: https://github.com/creationix/nvm

I ran the script above, rebooted and saw the default Debian login screen. I've tried to reconfigure steam-launcher using dpkg as well as attempting to remove and reinstall the steam-launcher package. /var/log/boot and /var/log/syslog don't really show anything useful and dmesg doesn't offer any hints as to what's going on.

Any assistance greatly appreciated.

**Comment by ProfessorKaos64** [comment]
Please recheck this and close if it no longer affects you. In desktop mode, open a terminal window and check the output of `lsb_release -a`. Ensure you are on brewmaster, as Alchemist is no longer supported. You must do a full reinstall to move to brewmaster at this time. See the [wiki](https://github.com/ValveSoftware/SteamOS/wiki) for details.

This isn't a SteamOS bug, but I could try to help if you submit this to SteamOS-Tools as a request to package it. There is a makefile, so it's definitely possible.

**Comment by udev** [comment]
I've updated to Brewmaster and I'll give it a try as soon as I get home from work. Will update accordingly. Thanks.

**Comment by udev** [comment]
Haven't seen this issue in a while so I'm closing it.
