### ISSUE TITLE
libqtgui4 package can't be installed. Missing dependencies in repository

### ISSUE THREAD

**Issue by Ryochan7** [ValveSoftware/SteamOS#237]
The package **libqtgui4** that is available in the repositories cannot be installed due to missing dependencies.
**libmng1** and **libaudio2** are not available from the SteamOS repositories. Those packages have to be installed from wheezy in order to install the libqtgui4 package that is available from the SteamOS repositories.

**Comment by johnv-valve** [comment]
pretty sure this was fixed quite a while ago
