### ISSUE TITLE
[Big Picture] WM is unusable after waking up

### ISSUE THREAD

**Issue by tarvitz** [ValveSoftware/SteamOS#241]
Big picture window manager (or that should be called by that term) states unusable after waking up computer after hybernate.
Video effects (floating/ points) shows normaly but there's no any method of user input available.

I tried use gamepads (xbox one, x360), keyboard, mouse but there was no effects of my input tries.
Still gnome desktop is usable and I can swtich to it via ctrl+alt+F# hotkey combination.

Got this issue on: ATI Radeon R9 280x, Intel i7, SteamOS beta autoinstalled (no huge modification of eco-system all default)

**Comment by johnv-valve** [comment]
suspend/hibernate no longer supported
