### ISSUE TITLE
Game: Serious Sam 3: BFE (2015-01-09) no controllers

### ISSUE THREAD

**Issue by VenKamikaze** [ValveSoftware/SteamOS#257]
Serious Sam 3: BFE does not recognise any of my controllers once I get past the introduction (I can skip past the Croteam etc screens with my controllers, until I hit the menu)
I've tried with:
Logitech F710
Logitech F310
PS3 controller via bluez

**Comment by slagerfin** [comment]
This game recognises my Rumblepad™ 2, but not my seconds controller which is some Xbox 360 controller clone. Can't wait to play with my friends in split screen!

**Comment by rbrs** [comment]
Xbox One controller does not work as well. Since it's the same situation on Linux (not SteamOS), I assume it's a problem with the game, not with SteamOS itself.

**Comment by randomweej** [comment]
to get the controllers working in serious sam 3 you need to create an xml file with the name found in the Sam3.log
/SeriousSam3/Content/Config/Input/Linux

as the logitech controllers support xinput just copy and rename the Microsoft_X_Box_360_pad.xml to whatever name the Sam3.log is looking for.

for xbox one controllers create a Microsoft_X_Box_One_pad.xml with the contents
    <?xml version="1.0" encoding="UTF-8"?>
<gamepad>
  <name>Microsoft X-Box One Controller</name>
  <icons>XBox360</icons>
  <control id="LX+"          type="axis" number="0" idle="0"      max="32767"  deadzone="4000"/>
  <control id="LX-"          type="axis" number="0" idle="0"      max="-32767" deadzone="4000"/>
  <control id="LY+"          type="axis" number="1" idle="0"      max="-32767"  deadzone="4000"/>
  <control id="LY-"          type="axis" number="1" idle="0"      max="32767" deadzone="4000"/>
  <control id="RX+"          type="axis" number="3" idle="0"      max="32767"  deadzone="4000"/>
  <control id="RX-"          type="axis" number="3" idle="0"      max="-32767" deadzone="4000"/>
  <control id="RY+"          type="axis" number="4" idle="0"      max="-32767"  deadzone="4000"/>
  <control id="RY-"          type="axis" number="4" idle="0"      max="32767" deadzone="4000"/>
  <control id="LeftTrigger"  type="axis" number="2" idle="-32767" max="32767"  deadzone="500"/>
  <control id="RightTrigger" type="axis" number="5" idle="-32767" max="32767"  deadzone="500"/>
  <control id="ButtonLeft"   type="axis" number="6" idle="0"      max="-32767" digital="true"/>
  <control id="ButtonRight"  type="axis" number="6" idle="0"      max="32767"  digital="true"/>
  <control id="ButtonUp"     type="axis" number="7" idle="0"      max="-32767" digital="true"/>
  <control id="ButtonDown"   type="axis" number="7" idle="0"      max="32767"  digital="true"/>
  
  <control id="ButtonA"       type="button" number="0"/>
  <control id="ButtonB"       type="button" number="1"/>
  <control id="ButtonX"       type="button" number="2"/>
  <control id="ButtonY"       type="button" number="3"/>
  <control id="LeftShoulder"  type="button" number="4"/>
  <control id="RightShoulder" type="button" number="5"/>
  <control id="ButtonBack"    type="button" number="6"/>
  <control id="ButtonStart"   type="button" number="7"/>
  <control id="LeftThumb"     type="button" number="9"/>
  <control id="RightThumb"    type="button" number="10"/>
</gamepad>

**Comment by ProfessorKaos64** [comment]
@rbrs , The Xbox One controller does work, wired.

**Comment by not83** [comment]
As this is a problem with the game, not the system, please close this bug.
