### ISSUE TITLE
Controllers become completely unresponsive after resuming from suspend

### ISSUE THREAD

**Issue by Two-Tone** [ValveSoftware/SteamOS#259]
I've been working on a ITX build as a now very late xmas gift for my two younger brothers, using SteamOS as the base system. Out side of a couple issues related to starting up certain games, most things have been fairly smooth sailing. But one of the single biggest issues is that if I put the system into suspend mode and then wake it up (the amount of time it's in suspend doesn't matter) the controllers become completely unresponsive unless I disconnect them from USB, wait at least a minute, then reconnect them.

Interestingly enough, it isn't until after the system has been suspended at least once that the indicators on the Xbox 360 controllers actually work.

Both controllers come up as `0e6f:0401 Logic3` when using `lsusb`.

**Comment by johnv-valve** [comment]
suspend is no longer supported

**Comment by Two-Tone** [comment]
Curious, why is suspend no longer supported? It's a common function of PCs AND consoles, seems odd that SteamOS and Steam Machines would be the only modern system that doesn't support it.

**Comment by johnv-valve** [comment]
Given the state of hardware and software support throughout the graphics stack on Linux we didn't think we could make this reliable.

**Comment by Two-Tone** [comment]
Huh, I thought it had gotten a lot better over the years.  I personally have not had any issues in the last five years using all three major vendors.

**Comment by onodera-punpun** [comment]
This is anecdotal, but I've never had any problems with suspend or heard of anyone having problems with it..

**Comment by cybik** [comment]
@Two-Tone @onodera-punpun the most likely explaination is that SteamOS needs to cover both "made for SteamOS" hardware and the more "crafty" setups, and doing a reliable suspend/hibernate on so many different hardware mixes can be, at best, well, impossible.

**Comment by Holzhaus** [comment]
@Two-Tone @onodera-punpun @cybik And there are Steam machines with AMD graphics. The open source Mesa driver can handle suspend just fine, but I expect them to use Catalyst (which are unreliable - when waking up from suspend, the screen often stays black and you need to hard reset your computer).

**Comment by ipr** [comment]
I would assume "graphics stack" includes the X11 which is a whole another set of issues.

Hopefully Wayland will at some point resolve and become "de facto" replacing aging X11.

**Comment by madscientist42** [comment]
@cybik @johnv-valve Then why doesn't valve come out and *SAY* that, instead of the bogus remarks then just made.  Be better for them.  Be better for everyone and still be flatly honest.  NVidia's stuff comes out nicely.  Don't know about Intel's.  Do know about AMD's...need to get AMD to get their act together.  When the FOSS bunch does better than you on something this fundamental...

**Comment by madscientist42** [comment]
@ipr I doubt that it's X11 that's the problem, per se, and more a power management problem that not all vendors have a handle on.  This would very probably be fubared with Wayland as well.

**Comment by Half-Shot** [comment]
Suspend has always been 50/50 for me. I wish that valve/developers explore the problems at a later date, but I can understand why it might be dropped not too far off a proper release. People want things to either work or not exist.

**Comment by paroj** [comment]
you could try if the workaround for suspend resume in my xpad driver also works for you:
https://github.com/paroj/xpad/commit/49177a41a94d8319d2cb42f87e1f3bd084b9833a

**Comment by ProfessorKaos64** [comment]
For anyone on this thread, the below commend from Slashdot has a lot of details on why this is an issue overall. I don't blame Valve and the team here for not officially supporting it.

http://games.slashdot.org/comments.pl?sid=7855261&cid=50329207

**Comment by twoolie** [comment]
> I have an issue with your USB hardware/driver

> Lol nope, linux graphics issue. *CLOSED*

**Comment by ProfessorKaos64** [comment]
@twoolie ... this is about a larger issue, not the patched xpad kernel driver. Did you read the link I attached? There is much more to this than what everyone is bickering about. Research from then on, decide for yourself. It isn't a clear-cut issue.

**Comment by twoolie** [comment]
@ProfessorKaos64 I absolutely agree it's not a clearcut issue. That's why I was surprised to see this closed with only a handwavey "graphics stack issue" explanation. If the real issue is systemic in how linux deals with USB device mappings during the suspend/restore process, and it's interaction with X11's input system, I really don't think it's fair to fob it off on the graphics stack.
