### ISSUE TITLE
SourceTv

### ISSUE THREAD

**Issue by sync667** [ValveSoftware/SteamOS#261]
Hi, sorry that I'm writing that here, but steam support send me here and I don't see any other way to contact dev team. I will paste my message to support and hope you will help me with my issue.

-------
Hi, I'm trying to find solution for my problem with SourceTv. What I'm trying to achieve is automatic streaming of matches on my linux servers for example Twitch or File at least. I know that SourceTv can save match data file with is overall replay of it, but it is any way to get save of auto director by any way (app or programmed custom solution) of that in video file? I mean linux. Maybe you know with way will be most efficient. CS:GO linux client? and stream from it or any other. Most important is of course performance.

Thanks for help.
-------

**Comment by thinkallabout** [comment]
Sorry I don't really thing this really the best place to post that. This is for technical issues with SteamOS which I assume means the OS only.

**Comment by sync667** [comment]
I know that it isn't best pleace, but I don't have any idea for other way of contact valve tech team and like i sayed steam support send me here.

**Comment by vgturtle127** [comment]
Have you seen this page?

https://developer.valvesoftware.com/wiki/SourceTV

I would recommend doing what you suggested and writing a custom solution. It seems like this wouldn't be a problem for "normal use", and I don't think Valve wants to either write a bunch of code to fix it, or create a whole new application for Linux (or any Steam-compatible OS for that matter).

From what I understand you are trying to do, I would just record everything you do manually and then have a script/app that sends your files to your server. Open Broadcaster Software uses hardware-accelerated recording and it multiplatform. Maybe use that, then write a custom script that uploads it to your server. As for viewing, I'm not sure what you had planned for that, but if you just want everything streamed to Twitch, then just use Open Broadcaster Software:

https://obsproject.com/

Then you/others can view it on the Twitch stream, and then you can archive it on YouTube or something.

I'm not sure if that helps at all, or if that is what you are trying to accomplish, but I suppose it is a start at least.

Other than that, I can't think of a solution other than heavily involved custom solutions, which I am sure you are not interested in. Some other ideas I had included using FFMPEG, but I didn't know if you knew how to use that or not.

Anyway, hope this helps somewhat.
