### ISSUE TITLE
SteamOS fails to install base systems halting at unpacking nvidia-kernel-common.

### ISSUE THREAD

**Issue by bwrigh16** [ValveSoftware/SteamOS#263]
I have tried to install this many times and overtime it fails at unpacking nvidia-kernel-common in the installing base systems phase.

http://i.imgur.com/qAUsf8g.jpg
http://imgur.com/76VnULj
http://imgur.com/2PT915G
http://imgur.com/xwDe4ur

**Comment by ProfessorKaos64** [comment]
Hi @bwrigh16 , this is ProfessorKaos64 from IRC, there is another issue opened with this same topic, so be sure to bookmark it:
Issues: #176 ,

**Comment by loonbg** [comment]
Some one fix this error ???

**Comment by AnsisMalins** [comment]
I'm also affected. This didn't happen the previous time I installed SteamOS which was in spring of 2014.

**Comment by sixnoteprod** [comment]
I am also experiencing this issue, have Nvidia Geforce.

**Comment by franky384** [comment]
same here, nvidia geforce gt 8900

**Comment by directhex** [comment]
SteamOS currently requires a GeForce GTX400 or newer, and will error out during install of the NVIDIA driver packages if your detected GeForces are too old.

Stephenson's Rocket will avoid erroring out, and use an older NVIDIA driver to support legacy cards (but may not be able to run all modern games)
