### ISSUE TITLE
Cannot use second HDD

### ISSUE THREAD

**Issue by not83** [ValveSoftware/SteamOS#264]
I just installed SteamOS and there is no options anywhere to scan, use, or set where the games are saved. I have installed SteamOS to my SSD and all my games are on my HDD. This should be in an option menu somewhere I believe

**Comment by Balderick** [comment]
One work around is to start steam client in gnome-session as steam user where you will be able to access all steam for linux client settings.   Steam > Settings > Downloads > Steam Library Folders.   You may also need an fstab entry to mount drive autiomatically each boot.

The fact second drive does not get any fstab entry at install time is probably more of an issue than not being able to set SteamLibrary directories from within BPM ui.

**Comment by ProfessorKaos64** [comment]
Steam will be located in the applications / activities overlay, or you can navigate to /usr/share/applications. Most games are installed to /home/steam/.local/share/steamapps/common

**Comment by not83** [comment]
Duplicate of #271, closing.
