### ISSUE TITLE
Running "steam" on the desktop terminal causes issues

### ISSUE THREAD

**Issue by not83** [ValveSoftware/SteamOS#265]
I installed SteamOS and I believe it is running the latest build.

when I ran steam on the desktop terminal within SteamOS the following happened:

-downloaded steam again
-a few error messages pop up
-steam welcome login appears, but it does not respond to clicks or any other actions
-causes the "Return to SteamOS" script/icon object to change from returning to Big Picture mode to running steam. This means that clicking this will not result in going back to SteamOS/BPmode but instead opens the non-responsive steam.

**Comment by ProfessorKaos64** [comment]
Try again, I don't have the same issues with this. Backup your .desktop file for /usr/share/applications that corresponds to the return to Steam action.

**Comment by not83** [comment]
Closing unless I can reproduce this. This was an issue back when you manully needed to run Steam from the terminal in order to continue with the install process. Because the way of installing has changed this is no longer an issue for me.
