### ISSUE TITLE
[Suggestion] Enable CTRL + A 

### ISSUE THREAD

**Issue by not83** [ValveSoftware/SteamOS#268]
In all other OSes CTRL + A selects all text in the text field. I think this would be handy in SteamOS also especially for selecting the whole URL in the browser

**Comment by Gordon01** [comment]
I can use ctrl+a in browser url field...

**Comment by not83** [comment]
It must have been recently added then

**Comment by ProfessorKaos64** [comment]
@not83 , is this still an issue? If not, can you close the ticket?
