### ISSUE TITLE
Scrolling needs work.

### ISSUE THREAD

**Issue by not83** [ValveSoftware/SteamOS#269]
When I scroll anywhere in SteamOS it goes about half a pages worht instead of about a quarter. I have to scroll down and then use Arrow keys in order to get to where I wanted in the page. This is so for chatting with friends and also in the browser.

Also the thing to click on to scroll does not work well either. I click ever so slightly to the right of it and the whole page disapears until I scroll up.

**Comment by johnv-valve** [comment]
are you still seeing this problem? If so, can you be more specific about exactly which pages you are talking about. Web browser or library or ?
