### ISSUE TITLE
Big Picture mode: Unable to scroll to the bottom of chat

### ISSUE THREAD

**Issue by udev** [ValveSoftware/SteamOS#275]
While using Big Picture mode's chat in SteamOS it appears that the most recent messages sent or received are hidden behind the textbox meant for text input. Scrolling does not allow the newest messages to be brought into view.

Build info:
built: Feb 9 2015, at 20:15:18
Steam versions: 1423545883
Steam API: v017
SteamOS version: SteamOS 1.0 update 153

**Comment by Mblackwell1024** [comment]
I'm seeing this bug still in BPM

**Comment by ProfessorKaos64** [comment]
> I'm seeing this bug still in BPM, even in regular Ubuntu.

If that is true, and it's a client issue, it should be in the Steam for Linux tracker instead, not here. I'd search first there though, as chances are it's there already.
