### ISSUE TITLE
SteamOS Shutdown and Restart for Systemd

### ISSUE THREAD

**Issue by abc-mikey** [ValveSoftware/SteamOS#278]
Hello,

Just wondering if it would be possible to get SteamOS to Shutdown and Restart commands to work on systems that use systemd-logind for power management? I imagine this will be required at some stage anyway as Debian is due to switch to systemd.

**Comment by Tele42** [comment]
No, this is not a required task, as only the _default_ init system of debian was changed. The existing solution is still available with Debian 8. Valve's choice of init system to use with SteamOS is completely independent of this change by Debian.

**Comment by abc-mikey** [comment]
OK. Great Valve get to choose, but please consider making it compatible with both for every other distro other than SteamOS.

**Comment by johnv-valve** [comment]
Currently we only support ConsoleKit. Looks like we would need to detect at runtime whether ConsoleKit or systemd-logind is active then use the appropriate one.

**Comment by johnv-valve** [comment]
This should now work with logind/systemd as well as with ConsoleKit.
