### ISSUE TITLE
SteamOS iso not recognizing other filesystems

### ISSUE THREAD

**Issue by riggsb2** [ValveSoftware/SteamOS#279]
It seems that the expert installation mode isn't recognizing the file systems I have in place. I assume that trying to install without seeing what's already here will overwrite everything. 

When the loader checks the drives it recognizes 3 10 gb drives of ext4, ext4, and swap and one 960 gb of ext4. 

I currently have 400gb of NTFS for my windows, 100gb for Mint, and 200gb of swap. Any ideas?

I couldn't find other open or closed issues addressing this problem.

**Comment by kellevan** [comment]
Not exactly clear on what's going on here!

It is finding 3 10GB drives, but your smallest partition of 100GB?

You have 200GB of swap space?!

**Comment by riggsb2** [comment]
I'm a little (a lot) inexperienced and got a reminder, when I was installing Mint, that I needed some swap space and assigned a random amount. Needless to say, a re partitioning to remedy this is needed.

Right. The SteamOS partitioner is seeing four partitions. 3 of 10 gb, 1 of 960 gb.
What I have installed, and what the Mint partitioner sees is the 400gb NTFS, 100gb Mint, 200gb Swap (which I need to fix), and 300 of free space. 

In brief, the SteamOS partitioner isn't seeing the partitioners correctly.

**Comment by elmat0** [comment]
I could be wrong though this is my understanding... 

The partitions you say it 'recognises' is actually how the installer wants to repartition your HDD for an exclusive SteamOS install, not what is actually already there. If you click 'go back' then click on 'partition drives' or 'guided partitioning' (I forget) it should show your existing partitions so you can choose to resize etc. and install SteamOS alongside your existing OS.

**Comment by directhex** [comment]
Click "undo changes". As a side effect of how the automatic installer works, the expert installer will show you its proposed kill-all-existing-partitions view of the world by default - click undo, then make changes.

https://youtu.be/3MjkfMs-4T4?t=178
