### ISSUE TITLE
Dying Light and GTX 9{7|8}0 textures problems dues to drivers version

### ISSUE THREAD

**Issue by ephase** [ValveSoftware/SteamOS#280]
Hi all,

For a month now, I can't play Dying Light on SteamOS dues to Nvidia outdated drivers for GTX 9xx Card. The issues is simple : all characters textures missing an all seems to be metallics ones :/. 
This problem disapear for thoses who update manually drivers.

**Comment by not83** [comment]
Hey valve any idea when new drivers are inbound?

**Comment by Plagman** [comment]
alchemist_beta should be updated sometime this week with the fixed driver. Thanks!
