### ISSUE TITLE
List of supported Video Cards?

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#281]
Is there a list of supported video cards? Or can you tell me what video drivers load so I can reference the card list?

**Comment by waitwhobrokethat** [comment]
i know SteamOS supports more cards them what i'm going to post but it's safe to say Atm Nvidia Geforce GTX 5xx to GTX 9xx Intell HD 3xxx Intell HD 4xxx and AMD HD 6xxx and up now remember it's a beta so thing's will change down the road

**Comment by ProfessorKaos64** [comment]
For now, I am just referencing the release notes driver versions for each vendor. From there, I can reference the supported cards under that driver version. Not an "official list" by far, but better than what I knew before. I threw the info into a steam community guide to improve over time.

**Comment by ProfessorKaos64** [comment]
non-steamos issue really. closing
