### ISSUE TITLE
Connected A2DP bluetooth audio devices not detected by pulseaudio

### ISSUE THREAD

**Issue by climbupthewalls** [ValveSoftware/SteamOS#283]
I have installed SteamOS on an Intel NUC D54260WYK1. I have enabled desktop mode. From there, I was able to pair and connect my A2DP bluetooth headset. However, the headset is never added to pulseaudio's list of connected devices, leaving only the previously-connected sound output (HDMI). From the perspective of the headset's auditory and LED interfaces, the connection occurred normally.

**Comment by retardTonic** [comment]
After updating pulseaudio to version 4.0 from wheezy-backports I was able to use my headset, but only in HSP/HFP mode.
Related issue: #96

**Comment by johnv-valve** [comment]
brewmaster is now on pulseaudio 5.0-13
