### ISSUE TITLE
Missing packages from public repository for rebuilding Mesa

### ISSUE THREAD

**Issue by directhex** [ValveSoftware/SteamOS#286]
There's a bunch of crud missing from alchemist/beta to allow rebuilding SteamOS's Mesa package - and they can't be resolved from Wheezy either, as wheezy's versions are too old for building alchemist Mesa:

src:x11proto-present-dev
src:x11proto-dri3-dev
src:isl
src:wayland
src:libffi

**Comment by johnv-valve** [comment]
libffi is there http://repo.steampowered.com/steamos/pool/main/libf/libffi/

I'll add the rest in the next update

**Comment by directhex** [comment]
Oh, you're right. The libffi one was a false positive from trying against Jessie's libwayland, which uses libffi6 not libffi5

**Comment by directhex** [comment]
Marking closed, I can now rebuild Mesa from brewmaster w/ brewmaster_beta and debian repos enabled.
