### ISSUE TITLE
[FEATURE REQUEST] easy install inside free space partition. 

### ISSUE THREAD

**Issue by tails101** [ValveSoftware/SteamOS#290]
It will be really useful to add inside steam os installer a automated installation inside a free space partition of the hard drive. With a free space checker .It will make dual boot easier.

**Comment by ProfessorKaos64** [comment]
It does this already. In expert mode, you double click the free space, or hit enter, and you are asked if you want the partition to be automatically setup. If you are referring to hosting two OS's on one physical drive, that is something you must setup yourself with the appropriate EFI/boot flags. I suggest writing down the default partition values created from a blank space, cancelling the changes, then setting up the integrated (2 OS) layout yourself.

**Comment by ProfessorKaos64** [comment]
@tails101 please review and close
