### ISSUE TITLE
Driver Support for Realtek 8111G

### ISSUE THREAD

**Issue by 8BitAron** [ValveSoftware/SteamOS#299]
I am trying to set up my first SteamOS Box and it looks like my network card is not supported out of the box, I have download the drivers from Realtek for linux.

How does one install the drivers so the usb stick install.

Any help would be great for a Linux Noob

**Comment by Evozx** [comment]
have you fixed this?

**Comment by 8BitAron** [comment]
I wasn't able to install it via the usb stick based on Valves install, but I was able to use this to make an ISO and boot off a usb and install using Rocket
 
https://github.com/steamos-community/stephensons-rocket

Cheers
Aron
