### ISSUE TITLE
debian jessie and alchemist[beta] repositories

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/SteamOS#303]
If anything was decide about those, what is it?

**Comment by ProfessorKaos64** [comment]
It would be nice to at least have the intentions of the Valve devs known, in regard to using Jessie, now that it is stable. I'd hate for SteamOS to keep falling behind with Jessie's packages are quite stale anyway in comparison to other distros, and should be fairly "tried and true."

**Comment by sylware** [comment]
If the ABI changes all time enough to break game binaries... That's pointless.

**Comment by johnv-valve** [comment]
SteamOS brewmaster is based on Debian jessie, so I think this issue is fixed.
