### ISSUE TITLE
Debootstrap Error Nvidia

### ISSUE THREAD

**Issue by CoWbOyZ** [ValveSoftware/SteamOS#307]
Hello,

I'm actually stuck on the core installation of steamOS. I use the last steamOS alchemist (MD5 verified) on DVD. I boot on it and tried the expert mode (10GB / 10GB swap 10GB /restore 2GB /home) and automatic mode. Each failed at the same step. VaporOS and Stephenson's Rocket steamOS do the same.

HW spec:
32GB SSD (for the moment)
NVIDIA 9800GTX+
ASUS P5N-E MOBO

ctrl+alt+F4 when the first debootstrap failed shows
debootstrap: aborting nvidia driver installation
debootstrap: dpkg: error processing /var/cache/apt/archives/libgl1-nvidia-glx_343.22-2+bsos1_amd64.deb (--unpack);
debootstrap: subprocess new pre-installation script returned error exit status 1
debootstrap: dpkg: version 343.22-2+bsos1 of libnvidia-eglcore:amd64 already installed, skipping
several similar messages
debootstrap: dpkg: version 20130816+1+bsos12 of nvidia-kernel-common already installed, skipping
debootstrap: Errors were encountered while processing:
debootstrap: /var/cache/apt/archives/libgl1-nvidia-glx_343.22-2+bsos1_amd64.deb

Any idea?

**Comment by directhex** [comment]
It is intentional that NVIDIA breaks on your old card. You need Stephenson's Rocket 153plus2 or above.

**Comment by CoWbOyZ** [comment]
Thanks, i will try this and report back.

**Comment by CoWbOyZ** [comment]
Stephenson's Rocket latest version works fine. I thought i used it but apparently i didn't. I needed to completely uninstall the graphic  nouveau driver (see http://steamcommunity.com/groups/steamuniverse/discussions/1/540743757298243719/)

Now everything works!
thanks
