### ISSUE TITLE
Errors encountered during Google Chrome install

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#308]
I am following the Valve [Wiki page](https://github.com/ValveSoftware/SteamOS/wiki/Installing-Google-Chrome-for-Netflix) on this, but like before when I tried the non 64 bit .deb package for Ubuntu/Debian, I get an dpkg error about libappindiactor1 not being installed. This will also break apt, required the ol' `apt-get install -f` fix, or removing libappindicator1. I have a routine that does install chrome after adding debian repos noted [here](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/testing/scriptmodules/extra-pkgs.shinc#L399), which is run after the debian repo script from my git [here](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/testing/add-debian-repos.sh). On a fresh install, this does install Chrome, but it won't launch from Big Picture Mode, presumably because of this missing library.

If I try to launch it via the cli command `google-chrome-stable`, I get:

```
/usr/bin/google-chrome-stable: error while loading shared libraries: libXss.so.1: cannot open shared object file: so such file or directory
```
Your method **does work**, however, you need to instruct users to either run `sudo apt-get install -f` after installation, **or** `sudo apt-get remove libappdicator1` Then, the command will execute, but again, only from the desktop session.

I *would* change my routine to shrink immensely in code match yours, but since chrome does not launch from Big Picture Mode, I am hesitant to do so. What I suspect is happening, is Chrome does launch, but is hidden, as the "loading" Big Picture Mode trio of bars does show. Possibly a reworked `/usr/share/applications/google-chrome.desktop` would be in order.

**Comment by johnv-valve** [comment]
curious, why are you trying to install the "non 64 bit .deb package" instead of the 64 bit package?

**Comment by ProfessorKaos64** [comment]
Johnv, it was just what I attempted before* I found your wiki page. Your instructions are, of course, much simplier, but there should notes about libappindicator dpkg errors breaking installations until `apt-get install -f` is issues. I will test from a clean backup image again tonight. In any case, do you envision Chrome every being able launch from Big Picture? I was messing with .desktop launchers, but only did so for a little while. If it launched from Big Picture, I would be able to rig up an launch script to load Netflix and swap xpad for xbxodrv temporarily to drive mouse support with a gamepad and on screen popup keyboard.  

In any case, thanks for the reply. I appreciate it.

**Comment by johnv-valve** [comment]
Sorry I don't know why Chrome won't run under Big Picture.

**Comment by ProfessorKaos64** [comment]
If the Valve team tasked with SteamOS got at least Chrome running on the steamOS session under BPM, that would really be something. I've tried up and down the wall on my www.github.com/ProfessorKaos64/SteamOS-Tools repository to compile pipelight, rebuild the pipelight deb pkgs (which works, but other things are in the way), shoehorn experimental widevine libraries into Chromium, create special launcher .desktop files to put Chrome on top of the Steam compositor and more. I'm sure something will work possibly, but my hope is that Valve has something great coming this November.

Thank you regardless for your responses and communication here.

**Comment by ProfessorKaos64** [comment]
Never mind, fixed my own issues, and with one last little push by a nice forum member in the Steam Universe group, Netflix now launches off of Chrome in kiosk mode :)

If anyone sees this post and is interested in this, please see:
http://steamcommunity.com/groups/steamuniverse/discussions/0/617336568069840473/
