### ISSUE TITLE
steam store purchase bugs

### ISSUE THREAD

**Issue by Reab31** [ValveSoftware/SteamOS#309]
For whatever reason I could not enter purchase through the steam store build in SteamOS. Thus I used the webbrowser to attempt a purchase for a game (Stronghold Collection). During this I encountered two problems.

1) I live in the Netherlands and attempted to pay through iDeal. A dropdown menu appeared wherein I was supposed to select my bank. However the dropdown menu never dropped down. I was unable to make the dropdown menu to drop by clicks from the mouse and an attempt to use the arrow-keys also failed to scroll through the menu. Eventually, I was able to select the proper bank through the use of the letters on the keyboard (pressing the first letter of the name of the bank gave me my correct option). I guess there might be a problem with some more dropdown menus.

|---------
2) I'm not sure whether this is a problem related to the SteamOS or not. After finishing the iDeal process the basket page returned and on the bottom a green bar appeared with the text "Working". With this the process of purchase should be finalized, however the bar never disappeared and the page remained as such till I shut the system down. My bankaccount shows the transaction has taken place, but when I check my steam games the games are absent.

Edit: games have been added a while after the purchase. So this might not have been a SteamOS related issue.
----------|
It might be worth mentioning that the (Stronghold Collection) contained a game I already owned and gave me a warning about this.

**Comment by Reab31** [comment]
The games for the 2) problem have been added after I finished typing this report. Thus it's likely not on the SteamOS end that caused a problem. It took a while though.

**Comment by ProfessorKaos64** [comment]
If this persists, I would maybe advise submitting this to the Steam for Linux github page or reporting it via the Steam Client Beta group on SteamCommunity if you are opted into that. Otherwise, i'd close this.

**Comment by ProfessorKaos64** [comment]
@Reab31 given your last comment, can you please close?
