### ISSUE TITLE
UNetBootin creates defective USB installers

### ISSUE THREAD

**Issue by directhex** [ValveSoftware/SteamOS#311]
The .iso installer is a valid USB disk image, and can be used to install to BIOS systems.

However, the most commonly recommended ISO -> USB tool, UNetBootin is fundamentally broken on Debian derivatives (specifically, it uses its own private copy of ISOLINUX which skips any isolinux.cfg stuff from the detected Debian Installer image, meaning it skips preseed= lines, meaning post_install.sh never gets executed)

This patch to cdrom-detect-udeb throws a critical install message if it detects signs that a USB installer has been tampered with by UNetBootin.

https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=30;filename=unetbootin.diff;att=1;bug=744865

**Comment by ProfessorKaos64** [comment]
In the past, true, I could use Unetbootin to create the USB stick for SteamOS, then add the missing ISOLINUX files for booting. Strangely enough, the troubles with straight up `dd if='infile' of='outfile` are no more and I made a USB key just last night with that. Intresting analysis though @directhex  .

**Comment by aaronfranke** [comment]
I recommend using Rufus for creating bootable USB images on Windows. It hasn't failed me yet.

**Comment by not83** [comment]
Unetbootin has never worked for me for any Linux images

**Comment by MrSchism** [comment]
Adding to this: In the past five months or so, I've had Unetbootin only work with Linux Mint.  I've tried with Debian, Kali, and Xubuntu without success (in the past five months).  As such, it doesn't surprise me that Unetbootin isn't working with SteamOS.  I'll test out a few tools and see if I can come up with a compatibility list.

**Comment by ProfessorKaos64** [comment]
@aaronfranke , I don't use Windows.

**Comment by aaronfranke** [comment]
@ProfessorKaos64 On Windows, use Rufus, on Linux, use dd. UNetBootin is a terrible piece of software, that's all I'm saying.

**Comment by MrSchism** [comment]
[It's worth mentioning that the official guide supports two methods, neither of which are UNetBootin.](http://store.steampowered.com/steamos/buildyourown)  I suggest using one of the methods mentioned in the linked article (or dd as mentioned above).  I'm still working on a list/matrix of functional installers
