### ISSUE TITLE
PlayOnLinux for SteamOS

### ISSUE THREAD

**Issue by wb9688** [ValveSoftware/SteamOS#312]

**Comment by wb9688** [comment]
Can there come a custom version of PlayOnLinux so you can play Windows games in SteamOS, which you can activate as a experimental feature in the settings.

**Comment by MrSchism** [comment]
Please add content/description.

This has been asked over on the Steam-for-linux tracker (as has Wine).  The general consensus is that this is not desirable; you'd probably have better success talking to the devs to get a native linux support.

**Comment by wb9688** [comment]
useless...

**Comment by wb9688** [comment]
...because it isn't possible

**Comment by not83** [comment]
You know have https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Playing-Steam-for-Windows-Games-On-SteamOS#adding-your-steam-wine-games-to-steamos--bpm

this if you want to go down this route
