### ISSUE TITLE
Cannot navigate back to main menu (using up) from Steam Profile

### ISSUE THREAD

**Issue by AsavarTzeth** [ValveSoftware/SteamOS#314]
I am using a Xbox360 Gamepad, bud this issue should be true for any controller configured within Big Picture.

The problem is if I enter my Steam profile AsavarTzeth/Profile in menu, I cannot go back the usual way. I press up and nothing happens. This forces me to use B to go back, but that is not the same.

If, for example, I have been browsing and chatting back and forth it easily forces me to a dozen jumps before I get back to the main menu.

**Comment by alfred-valve** [comment]
We are working on a navigation overhaul, watch for the next big Steam Client beta update to further help here.
