### ISSUE TITLE
Games Support link is not equivalent to Steam on the desktop

### ISSUE THREAD

**Issue by AsavarTzeth** [ValveSoftware/SteamOS#315]
If I click Support under a game on Steam on the desktop, it now uses the smart new system on help.steampowered.com. But if I use the Support link in Big Picture on SteamOS I get a page from support.steampowered.com.

This is a problem because it means the refund system is not easily available to SteamOS/Steam Machine users. It is also a bit confusing.

I actually assume this is being worked on and that this might even get a native UI instead of opening the browser. But still, I thought I would report it just in case.

**Comment by alfred-valve** [comment]
This should be fixed in the next big steam client beta update.

**Comment by not83** [comment]
When is that 😊

**Comment by alfred-valve** [comment]
In the fullness of time, at the appropriate juncture (see https://en.wikipedia.org/wiki/Yes_Minister).

**Comment by not83** [comment]
Fair enough haha keep up the good work

**Comment by ProfessorKaos64** [comment]
@alfred-valve , shining moments of humor amidst technical discussions always gives me a great chuckle :) Thanks for the great work your team is doing.

**Comment by alfred-valve** [comment]
And speaking of timing, that beta client is now public.
