### ISSUE TITLE
Big Picture version of Steam Profile displays emoticons weirdly

### ISSUE THREAD

**Issue by AsavarTzeth** [ValveSoftware/SteamOS#316]
My Steam profile description contains emoticons and the Big Picture UI does display them. However the text is displayed as if the emoticons are not there, resulting in icons on top of text and an unreadable mess.

**Comment by alfred-valve** [comment]
Can you provide the URL of your profile so we can look at it.

**Comment by AsavarTzeth** [comment]
It did not occur to me to provide a URL, because as a user you cannot access it this way. But since you asked for it: http://steamcommunity.com/id/asavartzeth/ (Not sure how/if you can use it though).

I also realized I might need to clarify. The view I am referring to is the one you reach via Big Picture Mode menu > Profile name > Profile > About Me.

If you need another way of replicating this, simply write a descriptive text about yourself on your profile. Then put in emoticons between the words.

**Comment by alfred-valve** [comment]
This should be fixed in the new major Steam Client Beta update.
