### ISSUE TITLE
Timezone Big Picture configuration does not work in Brewmaster

### ISSUE THREAD

**Issue by tYGjQCsvVI** [ValveSoftware/SteamOS#317]
# Issue
Timezone saving doesn't work using the configuration menu in Brewmaster

# Steps to produce
1. Head to settings, then timezone
2. Configure timezone
3. Press 'X' on your controller to save
4. Go back into timezone, see the timezone information didn't save.

# Workaround
Run the following commands as root in order:
1. `rm /etc/localtime`
2. `ln -s /usr/share/zoneinfo/${continent}/${city} /etc/localtime`
3. `systemctl reboot`

I've verified with two other people, excluding myself, that this issue also affects other people. This issue didn't occur on Alchemist.

**Comment by PyGuy95** [comment]
Just dropping by to confirm this bug on my side, as well.

**Comment by johnv-valve** [comment]
fixed in brewmaster_beta update 2.20
