### ISSUE TITLE
SteamOS 2.0 won't install on Mesa systems

### ISSUE THREAD

**Issue by directhex** [ValveSoftware/SteamOS#318]
This is an old old issue affecting "bleeding edge" distros like Arch, which finally affects SteamOS.

Steam Runtime bundles libstdc++.so.6 and libgcc_s.so.1 from GCC 4.8.3

Brewmaster ships with GCC 4.9.2.

Because C++ is a toy language, and our linker is terrible, we wind up in a situation where the distro foobar_dri.so module (as required for Mesa) tries to load the Steam Runtime version of libstdc++.so.6 rather than the distro version, which fails due to missing symbols in the Steam Runtime copy vs. the copy foobar_dri.so was built against.

The end result here is steam can't display its window. causing the SteamOS install to hang forever at the client bootstrap phase.

**Comment by johnv-valve** [comment]
what hardware are you seeing this on? I don't see it on my Intel graphics system.
We do have a work item to statically link mesa but it's not done yet.

**Comment by stbenz** [comment]
I see this problem on my Intel NUC5i3RYH (Intel Core i3-5010U, HD Graphics 5500).

**Comment by smcv** [comment]
Debian 8's steam package works around this by deleting the Steam Runtime's copy of libstdc++6 so everything will use the OS one: https://sources.debian.net/src/steam/1.0.0.49-1/debian/scripts/steam/

**Comment by directhex** [comment]
It definitely happens on VMware/VBox. I've seen reports on IRC & Twitter of it happening on Intel.

**Comment by directhex** [comment]
Also reports on steamuniverse, e.g. http://steamcommunity.com/groups/steamuniverse/discussions/1/530645446315989152/#c530645446320084839

**Comment by fledermaus** [comment]
Hey directhex: Working on reviving the static-libstdc++-linking hacks in mesa, hope to land them soon.I believe this should work around the problem.

**Comment by directhex** [comment]
Fixed in Mesa 10.3.2-2+bsos1

**Comment by fledermaus** [comment]
Just a note for anyone watching: 10.3.2-2+bsos1 hasn't hit the main brewmaster archive yet, have only just started testing it.

**Comment by RXM307** [comment]
This is good news, I'm assuming there will need to be a new ISO built to allow installations to complete.

**Comment by fledermaus** [comment]
Yep. I believe you can parachute the new .debs into the installer but I haven't actually done it myself.

**Comment by directhex** [comment]
If you want to test, I did said parachuting - http://steamcommunity.com/groups/steamuniverse/discussions/1/537405286646809031/

**Comment by RXM307** [comment]
Thanks, will test this out.

**Comment by johnv-valve** [comment]
Should be fixed in the current brewmaster release
