### ISSUE TITLE
glibc packages missing from repo

### ISSUE THREAD

**Issue by directhex** [ValveSoftware/SteamOS#319]
It seems that when Brewmaster moved from src:eglibc to src:glibc for libc6 et al, the whitelist for reprepro packages wasn't updated. So http://repo.steampowered.com/steamos/pool/main/g/glibc/ is ~empty, preventing debootstrap.

**Comment by johnv-valve** [comment]
Nice catch, just updated brewmaster_beta to 2.10 to fix this
