### ISSUE TITLE
[SteamOS 2.0] HDMI Audio configuration issues

### ISSUE THREAD

**Issue by karmictoucan** [ValveSoftware/SteamOS#322]
My Sys Specs:
CPU: Athlon II X2
GPU: Nvidia GT440
RAM: 4GB

Steam client build: Jun 19 2015, at 15:04:42
SteamOS version: SteamOS 2.0 update 1:2.9

I installed SteamOS 2.0 on my machine and it seems that audio via HDMI works now but there are few issues with it:
1) There are 4 duplicate audio presentations. That's how my audio presentation dropdown list looks like:

Digital Stereo (HDMI) Output
Digital Surround 5.1 (HDMI) Output
Digital Stereo (HDMI) Output
Digital Surround 5.1 (HDMI) Output
Digital Stereo (HDMI) Output
Digital Surround 5.1 (HDMI) Output
Digital Stereo (HDMI) Output
Digital Surround 5.1 (HDMI) Output
Off

2) By default, first option ('Digital Stereo (HDMI) Output') is selected and there is no sound. Sound appears only when I select bottom "Digital Stereo" option.

3) After system restart, audio configuration resets so I need to select correct audio presentation after every reboot.

**Comment by Vash63** [comment]
Same issue here, though I fix mine by selecting the second "Digital Surround 5.1" option. It's similarly temporary and doesn't survive a reboot.

**Comment by martinoj2009** [comment]
I also have this issue. Selecting the second "Digital Stereo (HDMI) Output" fixes this, but it also doesn't survive a reboot.

**Comment by morfah** [comment]
I have this issue as well, on a GTX 580. I have to select the second "Digital Stereo (HDMI) Output" after every boot.

**Comment by Ryochan7** [comment]
I have the same kind of problem on a GTX 550. Even setting the option in pavucontrol doesn't make the setting stick after a reboot.

**Comment by aaronfranke** [comment]
Same issue, however I only have one duplicated set (4 total, 2 unique options). i5-2320, 10GB RAM, Nvidia GT 520, SteamOS Beta 2.0 Brewmaster.

**Comment by ProfessorKaos64** [comment]
Same issue here with a GTX 770 and an Intel core i5 over HDMi out from the Nvifia GPU. Duplicated entries in the audio select menu as well. Desktop changes make no difference.

**Comment by sharkwouter** [comment]
I get all the same issues with my GTX 750 ti.

**Comment by ProfessorKaos64** [comment]
I should add, that on brewmaster (even beta), the sound works once selected in SteamOS BPM, however desktop mode, under the same selection, does not produce test results of left/right.

**Comment by martinoj2009** [comment]
In this recent update my issue has been fixed.

**Comment by sharkwouter** [comment]
@martinoj2009 that's odd, for me none of these issues were fixed yet. Did you change the hdmi port?

**Comment by johnv-valve** [comment]
Should be fixed in the latest Steam Client beta http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/52144327686735794

**Comment by not83** [comment]
Thank you for the update John. Will be sure to test. Thanks for all the
hard work

**Comment by ProfessorKaos64** [comment]
@johnv-valve . I'm not so sure, see my forum post below. It "works", but I had to exit to the desktop to get my sound back. After the first audio selection "HDMI," then "HDMI" (I don't have 5.1) The third box was blank for me. I'll look at this more tomorrow.

http://steamcommunity.com/groups/steamuniverse/discussions/1/527274088381810284/

**Comment by karmictoucan** [comment]
I have the same issue with hdmi sound as ProfessorKaos64. After latest update it is possible to make sound working only via desktop mode.

**Comment by johnv-valve** [comment]
@ProfessorKaos64 can you open a new issue on this behavior. And if you can include the output from 'pactl list' in both the working and non-working states, that will help reproduce this. (use a gist)

**Comment by ProfessorKaos64** [comment]
I get home in about 2 hours. I'll attach that in a new issue then. No problem.

**Comment by Schlesiger** [comment]
I have the same issues as ProfessorKaos64 after the latest updates. I've commented in the new ticket:
https://github.com/ValveSoftware/SteamOS/issues/372

**Comment by cbuteau** [comment]
No sound no matter what in the 2 item selection I select.

Nvidia GTX 750 Ti
Sony KDL-40W4100

The Windows 10 partition works great and sound and video come through on the TV great.
Thank god I made this dual boot.
