### ISSUE TITLE
[SteamOS 2.0] Wireless Xbox 360 gamepad led is blinking

### ISSUE THREAD

**Issue by karmictoucan** [ValveSoftware/SteamOS#323]
My Sys Specs:
CPU: Athlon II X2
GPU: Nvidia GT440
RAM: 4GB

Steam client build: Jun 19 2015, at 15:04:42
SteamOS version: SteamOS 2.0 update 1:2.9

This issue happened before on other systems(Ubuntu) where xpad driver was not patched (https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1272765). It seems that SteamOS 2.0 is affected by this issue too.

**Comment by ekianjo** [comment]
I confirm this issue exists for me, on Brewmaster - latest update from yesterday (suscribed to beta clients). The LED keeps blinking, while the pad operates normally.

**Comment by DazWorrall** [comment]
This is fixed for me in 2.30 @ekianjo, are you sure you're running the correct kernel?

**Comment by ekianjo** [comment]
@DazWorrall , I installed SteamOS Brewmaster yesterday, so I'm not sure how much more recent I can go :)

**Comment by DazWorrall** [comment]
@ekianjo I dont think the installers have been updated. It's not the beta client you need, it's the beta SteamOS install - the instructions in the [FAQ][0] are for alchemist but are the same for brewmaster:

`If you want to opt your machine into alchemist_beta, you can run this command from a terminal session on the desktop: "sudo apt-get install steamos-beta-repo" Now when SteamOS checks for updates, you will get the newer packages from the alchemist_beta repository. WARNING: there is no easy way to opt out of the beta, you will need to either restore your system partition or wait for "alchemist" to catch up to the alchemist_beta!`

[0]: http://steamcommunity.com/groups/steamuniverse/discussions/1/648814395741989999/

**Comment by ekianjo** [comment]
OK - but arent't there some risks in signing for the beta ? as indicated in the warnings you cannot easily come back to the main branch.

**Comment by sharkwouter** [comment]
@ekianjo if it breaks you are in trouble, yes. I'm guessing a new non-beta release is happening soon, so you could wait for that.

**Comment by ekianjo** [comment]
@sharkwouter I'll be patient then :)

**Comment by johnv-valve** [comment]
Should be fixed in the current brewmaster release

**Comment by ekianjo** [comment]
How do you update to the current version?

On 9/2/15, johnv-valve <notifications@github.com> wrote:
> Should be fixed in the current brewmaster release
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ValveSoftware/SteamOS/issues/323#issuecomment-136896110


-- 
Raphael

**Comment by not83** [comment]
Use the system update in the settings

**Comment by ekianjo** [comment]
I actually tried that, but it goes into an endless "loop" (searching for an update) and does nothing.

**Comment by ProfessorKaos64** [comment]
When you check "Check for SteamOS updates", it will often take while if there are large updates. Give it time. Check it, if it starts the "loading bars" and sits there, let it go and grab a cold beer :) Do you have external sources added that may prevent the packages from  updating? You could try cli commands to see what is going on, but I would not advise that quite yet.

**Comment by ekianjo** [comment]
I do not get to the "loading bar" stage. I get the circle going around and
it never gets to any other stage. How long does one need to wait?

On Wed, Sep 2, 2015 at 10:44 AM, mikeyd <notifications@github.com> wrote:

> When you check "Check for SteamOS updates", it will often take while if
> there are large updates. Give it time. Check it, if it starts the "loading
> bars" and sits there, let it go and grab a cold beer :) Do you have
> external sources added that may prevent the packages from updating? You
> could try cli commands to see what is going on, but I would not advise that
> quite yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/SteamOS/issues/323#issuecomment-136912223>
> .
>



-- 
Raphael
