### ISSUE TITLE
SteamOS 2.0 The Compressed Folder is invalid

### ISSUE THREAD

**Issue by eshaw** [ValveSoftware/SteamOS#327]
So, I'm trying to unzip onto a usb drive in order to install the new release. It seems that the zip file is somehow corrupted. I tried downloading multiple times and nothing changes. I'm trying this on Windows 10 preview. I can do this on a different OS, but I just thought I'd post to see if there is a solution.

**Comment by tYGjQCsvVI** [comment]
Have you [verified the hash](http://repo.steampowered.com/download/brewmaster/SHA512SUMS) [of your download](http://repo.steampowered.com/download/brewmaster/MD5SUMS)?

**Comment by directhex** [comment]
I've had lots of problems in the past with Valve's CDN on repo.steampowered.com resetting connections after 60 seconds of transfer. How quickly is your download "finishing"?

**Comment by tYGjQCsvVI** [comment]
I was going to make a torrent for you to download from, but apparently I need a license to create my own mirrors of the proprietary Steam client. My only recommendation, if what @directhex says it true, is to use a download manager like [aria2](https://github.com/tatsuhiro-t/aria2) which will pick up on connection errors and resume using the http range header. I've downloaded the file multiple times, never had an issue, but I've always used aria2, so many there were issues in the background that aria2 worked around.

**Comment by eshaw** [comment]
Okay, all those comments helped. I think the problem is solved.
