### ISSUE TITLE
Opting into brewmaster beta?

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#328]
Is there currently a package or process to opt into Brewmaster / 2.0 beta? I know in the past there was the below command. I figured it was a bit early, but would try asking anyway. I am aware there is an ISO of brewmaster out there, which I am using, this would be akin to the alchemist, and alchemist_beta repositories.

```
sudo apt-get install steamos-beta-repo
```

**Comment by tYGjQCsvVI** [comment]
My (limited) understanding is that you have to do a full OS wipe to get onto Brewmaster. The download is publicly available [here](http://repo.steampowered.com/download/brewmaster/SteamOSInstaller.zip) and you just follow the standard installation steps as before.

**Comment by ProfessorKaos64** [comment]
I am already on brewmaster, testing out Debian Jessie installs. Before, there was alchemist_beta, the actual OS beta, not the Steam client.

**Comment by directhex** [comment]
The steamos-beta-repo package needs an update.

**Comment by ProfessorKaos64** [comment]
Ah, I see. I'll just be patient, but see johnv picked it up. Thank you all.

**Comment by johnv-valve** [comment]
Added in 2.20
