### ISSUE TITLE
Steam OS Brewmaster - Controller Issue

### ISSUE THREAD

**Issue by rookster1984** [ValveSoftware/SteamOS#329]
On the wireless xbox 360 controller it always blinks (as reported by someone else), on the steam interface it keeps going left thinking i am pressing it when i am not, the going left issue is not there when i am playing a game through home streaming.

**Comment by ProfessorKaos64** [comment]
I thought they fixed this. I can't pull up the webpage from where I am now, but you should be able to see that int the Steam Universe > SteamOS subforum updates. It's possible this is only in brewmaster_beta right now. See below on how to opt in.

```
sudo apt-get install steamos-beta-repo
sudo apt-get update
```

**Comment by sharkwouter** [comment]
It's not fixed yet for the wireless version in the 2.26.

**Comment by ProfessorKaos64** [comment]
This is now fixed in brewmaster beta. I would close this ticket if you could. The updates for brewmaster_beta will make their way into the stable branch in due time. Can you please test @rookster1984 and review?

**Comment by johnv-valve** [comment]
fixed in brewmaster 2.30
