### ISSUE TITLE
Separate the installer configuration and the installer

### ISSUE THREAD

**Issue by cheery** [ValveSoftware/SteamOS#33]
I just realized that the installer without all those questions is much more in spirit of Unix than traditional Debian installer. Why ask people questions about timezone, user or keyboard settings in the first place? They will figure it all out while they get in and if it matters. They will add themselves an user if it matters. They change the timezone settings if it matters. And so on...

Well I'm sure you figured that out yourself. Maybe it's exactly what you wanted to show us. Now I'm going to propose something that might be out of scope in SteamOS, but useful to consider.

There's one thing where you provide sane defaults and expect the work for everyone. That one is partitioning disks. You assume that the user wants to nuke the system and it's true for most. For some it isn't and that's harder to change afterwards.

Where to decide which kind of partitioning to apply? I think there are several sensible choices:

 * On the console before running the installer
 * On a remote computer probing the console
 * On any computer prior the computer has been built, perhaps on OEM's design table?

The OEM could throw the configuration along the SYSRESTORE stick and be done with it. Just make sure the defaults can be used instead if the configuration is incompatible with the machine.

**Comment by johnv-valve** [comment]
I am not sure what you are asking for. Automated setup will not ask you anything. Expert setup will let you customize partitions, etc, all you want.
