### ISSUE TITLE
Unable to exit games using the Steam big picture overlay.

### ISSUE THREAD

**Issue by tYGjQCsvVI** [ValveSoftware/SteamOS#330]
# Issue
Locked/unresponsive games cannot be killed using the in-overlay 'exit' option.

# Steps to produce
1. Launch a game
2. Press your guide button to open up the overlay
3. Go to the far let menu, 'links & more'
4. Select 'exit game'
5. Select 'exit anyway'
6. SteamOS will idle ~30 seconds before informing you it was unable to kill the process and offer you the ability to restart the entire machine.

# Workaround
The easiest workaround as of now is to let the kill timeout and then agree to the reboot that Steam is offering.

**Comment by morfah** [comment]
I got this issue as well. Would be good if this worked because sometimes the games locks up.

**Comment by johnv-valve** [comment]
This should be fixed with the steam beta client released this week.
