### ISSUE TITLE
[Feature request] Add a virtual package that requires everything SteamOS has installed by default

### ISSUE THREAD

**Issue by pmk1c** [ValveSoftware/SteamOS#331]
As the title says I'd like to have a virtual package, that requires everything SteamOS needs for a default install. This would make it easier to update between versions (for example update to brewmaster). Also it would make managing installed packages more easy. I love how I can mark all packages as "automatically installed" in Ubuntu, but the packages I explicitly want to be installed.

I know this is not a Distribution for linux administrators, but as I said I think it could make transitions to newer versions easier.

**Comment by johnv-valve** [comment]
I'm not quite sure what you're trying to achieve. dpkg --get-selections can give you a list of all installed packages. I don't see how this helps you as the list is going to be different between alchemist and brewmaster.

**Comment by pmk1c** [comment]
Maybe I didn't make myself clear enough. Ubuntu uses meta packages (or virtual packages) without content but dependencies to define what packages are needed for a base Ubuntu install. See here: http://packages.ubuntu.com/precise/ubuntu-standard

This package changes from Ubuntu version to Ubuntu version, since packages are added or removed from a default Ubuntu installation. The main advantage is, that when upgrading to a newer Ubuntu version you can just adjust the repository files and update. Packages that are now part of the base installation will just be installed, since they are required by the meta package.

So when you say a default brewmaster installation has different packages installed then a default alchemist installtion (which makes sense) you could acknowledge that with an updated meta package and it would be quite easier to go from alchemist to brewmaster.

I read that you are investigating if you can offer official ways to update from alchemist to brewmaster and such a meta package could solve one part of the problem.
