### ISSUE TITLE
SteamOS Still goes to a black screen after installing?

### ISSUE THREAD

**Issue by BlakeBarnes00** [ValveSoftware/SteamOS#332]
I am installing SteamOS on my [Asus Zenbook UX31E](https://www.asus.com/Notebooks_Ultrabooks/ASUS_ZENBOOK_UX31E/), and when I start to install it just goes to a black screen and nothing else happens. Am I doing something wrong? I thought that the new update allowed Intel Graphics?

**Comment by waitwhobrokethat** [comment]
i think it maybe a bug in Mesa as of SteamOS 2.0 https://github.com/ValveSoftware/SteamOS/issues/318
