### ISSUE TITLE
G++ Brewmaster Issue with 'build-essential'

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#333]
What is the preferred package for SteamOS in contrast with Debian's `build-essential`? 'steamos-dev` has some packages, but not all I was looking for. Is there a package missing in brewmaster? Is this bug tracker appropriate for brewmaster bug reports?

```
The following packages have unmet dependencies:
 build-essential : Depends: libc6-dev but it is not going to be installed or
                            libc-dev
 g++ : Depends: g++-4.9 (>= 4.6.4-1~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by ProfessorKaos64** [comment]
Sorry, wrong package, g++, which I think is already reported.

**Comment by sharkwouter** [comment]
Do you still have this issue if you add the brewmaster_beta repo?

**Comment by ProfessorKaos64** [comment]
No, I suppose I can just close it now that I tested that. Other issues to look at now :)

On July 6, 2015 10:28:58 PM EDT, Wouter Wijsman <notifications@github.com> wrote:
>Do you still have this issue if you add the brewmaster_beta repo?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ValveSoftware/SteamOS/issues/333#issuecomment-119050849

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
