### ISSUE TITLE
Cannot delete browser favourites

### ISSUE THREAD

**Issue by not83** [ValveSoftware/SteamOS#336]
System:

Steam client built: Jul 14 2015, at 10:24:48
Steam versions: 1436896316
Steam API: v017
SteamOS version: SteamOS 2.0 update 1:2.25

CPU vender: GenuineIntel
CPU clock: 3.60 GHz
CPU cores: 4 Cores, 4 Threads
System memory: 7.7GB
Video Card: NVIDIA Coporation GeForce GTX 660 Ti/PCIe/SSE2
Driver version: 4.5.0 NVIDIA 346.72
Video memory: 2.0 GB

When pressing X to delete the favourite from the SteamOS built in browser the favourite does not delete.

Steps to reproduce: Visit any website. Press the down key on the D-pad. Close tab. Go to the new favourite. Press X to delete favourite. Nothing happens
What should happen: Favourite is deleted when X is pressed
What happens instead: Nothing happens when favourite is pressed

**Comment by ProfessorKaos64** [comment]
I will attempt to reproduce this tonight to see what I get.

**Comment by ProfessorKaos64** [comment]
This affects me too. I have not tested this after the latest updates, but I believe it is still an issue. It may have something to do with the controller settings system menu still being borked a bit.

**Comment by johnv-valve** [comment]
seems to be working now on the current beta client

**Comment by ProfessorKaos64** [comment]
Confirmed good, thank you @johnv-valve
