### ISSUE TITLE
Cannot currently comment on Friend Activity

### ISSUE THREAD

**Issue by not83** [ValveSoftware/SteamOS#337]
System:

Steam client built: Jul 14 2015, at 10:24:48
Steam versions: 1436896316
Steam API: v017
SteamOS version: SteamOS 2.0 update 1:2.25

CPU vender: GenuineIntel
CPU clock: 3.60 GHz
CPU cores: 4 Cores, 4 Threads
System memory: 7.7GB
Video Card: NVIDIA Coporation GeForce GTX 660 Ti/PCIe/SSE2
Driver version: 4.5.0 NVIDIA 346.72
Video memory: 2.0 GB

You cannot currently comment on Screenshots, friends new purchases, or friends new friends.
Desktop Steam client has this feature currently and it would be nice to have. The only option you have is to look at the game, the person profile or message them.

**Comment by sharkwouter** [comment]
You might want to report this in the Steam beta group, since the Steam developers seem to look at that a lot: http://steamcommunity.com/groups/SteamClientBeta/discussions/0/

**Comment by not83** [comment]
Fixed
