### ISSUE TITLE
repo.steampowered.com down (nginx default)

### ISSUE THREAD

**Issue by reedstrm** [ValveSoftware/SteamOS#344]
Can't finds a place in the forums to report this, so, in the spirit of #214, posting here. The deb repo at repo.steampowered.com is  serving the 'Welcome to nginx' page for all urls. Breaks Package Manager
on Ubuntu, since it stores the HTML as the Repository list, then fails to parse it. (I think I'll go file an issue w/ Ubuntu about that ...)

**Comment by sharkwouter** [comment]
Same page on repo.steampowered.com for me.

**Comment by johnv-valve** [comment]
fixed

**Comment by reedstrm** [comment]
confirmed. Thanks!
