### ISSUE TITLE
[brewmaster-beta] Package conflict for libpangol1.0-0

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#347]
Google Chrome installation errors on brewmaster-beta:

```
2015-07-26 09:36:55 (3.20 MB/s) - ‘google-chrome-stable_current_amd64.deb’ saved [48147924/48147924]

Selecting previously unselected package google-chrome-stable.
(Reading database ... 116749 files and directories currently installed.)
Preparing to unpack google-chrome-stable_current_amd64.deb ...
Unpacking google-chrome-stable (44.0.2403.107-1) ...
dpkg: dependency problems prevent configuration of google-chrome-stable:
 google-chrome-stable depends on libpango1.0-0 (>= 1.14.0); however:
  Package libpango1.0-0 is not installed.
```

Required for: dep for google-chrome-beta
Release: Brewmaster-beta
Debian repositories added: yes
Debian repo type: Jessie, Jessie-backports
Verified apt-cache policy: yes

```
desktop@steamos:~/SteamOS-Tools$ sudo apt-get install libpango1.0-0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libpango1.0-0 : Depends: libpangox-1.0-0 (>= 0.0.2-2~) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

**Comment by johnv-valve** [comment]
It's hard to tell what you have installed from where. I was able to install google chrome on brewmaster without any additional dependencies from jessie. Did you try "apt-get -f install"

**Comment by ProfessorKaos64** [comment]
Hi @johnv-valve , I've capture my steps to the below slexy paste. I also have included my preferences files and lists for Debian Jessie. The first bullet of reference script code is just there in case you wanted to see it, the attached files are from a "vanilla install" of chrome-stable. I typically use gdebi to pull in the dependencies.

* [Reference script code](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster-beta/scriptmodules/extra-pkgs.shinc#L98)
* [Chrome install](http://slexy.org/view/s20PngUvUq)
* [preferences](http://slexy.org/view/s20HMqmUhM)
* [sources.list set for Jessie](http://slexy.org/view/s212reAaat)
* [apt-cache policy](http://slexy.org/view/s2Ia46zwsz)

This time it worked fine, so many a glitch before. I am making sure to remove any perquisite packages I had supplied ahead of time to install Chrome ages ago. Gdebi seems to pull everything it needs now, when previously, with Wheezy, libappindicator1 gave me headaches. 

If I am going about any of these in the wrong way, that is fine, and is entirely on me.

**Comment by johnv-valve** [comment]
It installs fine with gdebi on brewmaster without requiring anything extra from jessie. So I am going to close this. Probably when I added a bunch of packages a few weeks ago it fixed this as well.
