### ISSUE TITLE
[Suggestion] Disable fade transition when browsing the store

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#350]
Steam client: 1438115271
API: V017
Release: 1.0 update 161

While I am not a fan of the new fade in/out transition in the client beta, could someone address the reason why this transition was curiously added to the left/right selection screen for store items? It's highly disorienting and odd to press left/right towards the next game/video in a row of 4 on-screen, only to have the screen fade as if we were entering an entirely new area.  This animation is not present from the base store page, main top row, rather when you enter any of the sub-fields below (top sellers, controller friendly, genres, etc.)

Please advise if this post if better suited for the Steam Client Beta community group.

Store > Genres > Movies

**Comment by johnv-valve** [comment]
Unless it's a SteamOS-specific issue (and this isn't) the Client Beta forum is usually a better bet.

**Comment by ProfessorKaos64** [comment]
Ok, will do. Thank you @johnv-valve
