### ISSUE TITLE
[Suggestion] Setup portal page to determine SteamOS eligibility 

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#353]
http://store.steampowered.com/steamos/buildyourown is woefully uninformative for users who are not Linux-savy. Even on my own, it would be possible to cross reference with Curl, the latest driver from repo.steampowered.com or distrowatch, and the supported products from nvidia's website or otherwise. I believe it would be highly beneficial to have some sort of drop down box to select your graphics card at a minimum (possibly CPU and RAM), to determine if your machine is low/med/high or not usable for SteamOS. I am unaware of any community efforts in this.

**Comment by obialfred** [comment]
Valve needs to make this OS (and it's installation) idiot-proof if it wants any mass appeal.

**Comment by ProfessorKaos64** [comment]
Closed. Not a bug. Moving to SteamUniverse forum when I have time today.
