### ISSUE TITLE
Seeing broken User Agents in web logs

### ISSUE THREAD

**Issue by nicksay** [ValveSoftware/SteamOS#354]
Hi,

We're seeing web requests with UserAgent headers that start with:

`Mozilla/5.0 (%s; U; %s; en-US; Valve Source Client; %s)`

The `%s` placeholders are in the string, which makes it look like a formatting step is being skipped.  We're not sure this is SteamOS, but it seems possible.  Any help tracking this down or fixing it at the source would be appreciated. 

(Originally reported at http://steamcommunity.com/groups/steamuniverse/discussions/1/541907867748380395/)

**Comment by alfred-valve** [comment]
I've been unable to reproduce this locally. If you can find a way to cause us to emit this user agent please provide details.

**Comment by johnv-valve** [comment]
If you can tell us what content is being requested that would help, otherwise we cannot reproduce this.
