### ISSUE TITLE
Intel Drivers are too old for Broadwell-U graphics

### ISSUE THREAD

**Issue by dawnson** [ValveSoftware/SteamOS#360]
Looks like the Broadwell-U's graphics isn't supported by the Intel driver version being shipped in SteamOS.
They're shipping driver 2.21.15, which is the most recent stable release - but is from 2013, clearly too old for this generation of CPU.
I've done some poking around in the driver sauce, looks like version 2.99.913 is the bare minimum.

(from here: https://www.reddit.com/r/SteamOS/comments/3h179p/announcing_brewmasterbased_stephensons_rocket/cu74g08 )

**Comment by fledermaus** [comment]
Have grabbed the .917 package from bpo, not sure if it'll get in though.

**Comment by fledermaus** [comment]
Whole bunch of new stuff, including .917, currently being tested.

**Comment by johnv-valve** [comment]
brewmaster_beta is at 2.99.917, does that work for you?
