### ISSUE TITLE
[brewmaster] Legacy ISO leaves you at root prompt

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#362]
CPU: Intel x86
GPU: Nvidia GT 640

Install Method: Automatic
Method of transfer:
```
sudo dd if=SteamOS-brewmaster.iso of=/dev/sdj
```
Using ISO from:
http://steamcommunity.com/groups/steamuniverse#announcements/detail/83663183294752597

The legacy ISO leaves me a a steam@steamos:~$ root prompt, tty7. I can switch tty lines, but I'm unsure why this is the case. I noticed the generic X-server "crosshair" is in the center of the screen, inside a boundry. Outside it, it disappears, indicating a possible dialog box just sitting there, hidden.

**Comment by sharkwouter** [comment]
That's odd, I've actually successfully installed Brewmaster with that iso.

**Comment by ProfessorKaos64** [comment]
I've tried two different USB drives now. Have you tried in the last few days? I will redownload the ISO from the direct link they gave and try again tonight.

**Comment by sharkwouter** [comment]
Have you checked if the checksum of your iso matches the one online?

**Comment by ProfessorKaos64** [comment]
I'll do that as well. I typically have renamed iso's to live in the same folder (due to the 1.0 and 2.0 ISO file sharing the same name that I have stored). Totally forgot to check that as well. Will do. I wonder if they will ever fix the grub install page stopping the auto install method.

**Comment by sharkwouter** [comment]
If we don't solve it, I guess Valve won't be fixing the grub installation on mbr.

**Comment by ProfessorKaos64** [comment]
mikeyd@archboxmtd downloads $ sudo sha512sum -c SHA512SUMS 
/home/mikeyd/downloads/SteamOSDVD.iso: OK

I removed the 2nd line from the check, since I was only dealing with the .ISO and not the zip archive.
Hopefully this works. Installing now.

**Comment by ProfessorKaos64** [comment]
Yep, same thing. dang. Well, i'll have to checkout the system, see what's going on. Strange.

**Comment by ProfessorKaos64** [comment]
Oddly enough I burned a fresh ISO (still dated from July) to a DVD and it worked...odd. I did try two USB drives. Do you think it had anything to do with my use of dd? I don't typically specify block size, as I never had to before with SteamOS. I'll try another go with this exact image from a USB drive tonight.

**Comment by ProfessorKaos64** [comment]
redownloaded SteamOSDVD.iso verified integrity, and installed again .Works fine. Maybe just a bad dd image /  one-time occurrence, not sure. I actually used a [download tool](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/utilities/steamos-mega-downloader.sh) I made to do the whole thing, nice for multi-installations / testing.
