### ISSUE TITLE
[brewmaster-beta] libattr1:i386 package fails 

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#363]
Using "stock" brewmaster/brewmaster-beta repos, libattr1:i386 (a dependency of libasound2-plugins:i386) will fail. `apt-get install -f` will offer to install this, however the issue is that dpkg cannot unpack the archive's changelog file, reporting "/usr/share/doc/libattr/changelog_Debian.gz' is different from other instances of package libattr1:i386. Manually backing up the old changelog and removing it works.

**Comment by Ryochan7** [comment]
I have run into this problem as well. The problem came up when initially trying to get sound working in the Wine wrapped version of Baldur's Gate 2 purchased from GOG. Removing the old changelog and installing the libattr1:i386 package worked for me and the game runs fine now.

**Comment by guyr34** [comment]
On jessie, the file changelog.Debian.gz  is exactly the same in amd64 and i386.
But this is not the case in brewmaster (the diff of the uncompressed files).
As the source package attr (jessie and brewmaster) are the same, 
i suppose that the problem arise in the build process. 

--- amd64/usr/share/doc/libattr1/changelog.Debian	2015-11-28 22:53:56.536068826 +0100
+++ i386/usr/share/doc/libattr1/changelog.Debian	2015-11-28 22:54:19.712068411 +0100
@@ -1,9 +1,9 @@
 attr (1:2.4.47-2+bsos3) unstable; urgency=medium
 
   * Building attr for project steamos:brewmaster:main repository main
-    arch x86_64 srcmd5 32217f161569b7881d41a45ab6ccbfcb
+    arch i586 srcmd5 32217f161569b7881d41a45ab6ccbfcb
 
- -- abuild <abuild@buildd>  Fri, 08 May 2015 16:29:29 +0000
+ -- abuild <abuild@buildd>  Fri, 08 May 2015 16:40:03 +0000
 
 attr (1:2.4.47-2) unstable; urgency=medium

**Comment by johnv-valve** [comment]
Fixed in the brewmaster beta 2.55

(note the jessie approach only works if both the amd64 and i386 packages are the exact same version)
