### ISSUE TITLE
[ Category Nonsense ] Don't put Movies in "Games you Can Play"

### ISSUE THREAD

**Issue by ekianjo** [ValveSoftware/SteamOS#367]
I suspect this is more of an issue with the Steam Client than with SteamOS itself, but it does not make any sense at all to put the movies that are now available for streaming in the "Games You Can Play" category. If it's not a game, put it in a "Videos You Can Watch" or something like that. This looks really silly.

**Comment by ProfessorKaos64** [comment]
It already goes in Videos as a category, and does not show up in my list of games.

**Comment by ekianjo** [comment]
Well it does show up for me in SteamOS in my category of "Games You Can Play", which is precisely why I have opened this issue.

**Comment by ProfessorKaos64** [comment]
Ok, I was talking about my "all games" category, i'll check again. For me, the big show stopper with the latest client beta, is the complete absence of a "SteamOS/Linux" filter category. That is jarring...

**Comment by ekianjo** [comment]
Strange, I have a SteamOS games category in the filters.

On Wed, Sep 2, 2015 at 10:45 AM, mikeyd <notifications@github.com> wrote:

> Ok, I was talking about my "all games" category, i'll check again. For me,
> the big show stopper with the latest client beta, is the complete absence
> of a "SteamOS/Linux" filter category. That is jarring...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/SteamOS/issues/367#issuecomment-136912322>
> .
>



-- 
Raphael

**Comment by ProfessorKaos64** [comment]
SteamOS 2.0, and the beta client? I am also subscribed to the brewmaster beta repo.

**Comment by ekianjo** [comment]
I'm in the brewmaster stable branch, I think, with beta client. So, not the
beta brewmaster repo, I think.

On Wed, Sep 2, 2015 at 11:15 AM, mikeyd <notifications@github.com> wrote:

> SteamOS 2.0, and the beta client? I am also subscribed to the brewmaster
> beta repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/SteamOS/issues/367#issuecomment-136915196>
> .
>



-- 
Raphael

**Comment by ProfessorKaos64** [comment]
I don't see SteamOS / Linux as a category anywhere: http://imgur.com/a/Z7vnZ

**Comment by johnv-valve** [comment]
I'd like to keep this issue tracker specifically for SteamOS issues.

There are a lot of changes in Big Picture, so for general Steam Beta client issues, the team requests you post here http://steamcommunity.com/groups/SteamClientBeta/discussions/0/

**Comment by ekianjo** [comment]
ProfessorKaos64, thats because you are in the latest beta of the client. the previous  beta clietn had a SteamOS category.

**Comment by ProfessorKaos64** [comment]
I know that. This topic was moved to the forums regardless.
