### ISSUE TITLE
[ Misleading Information ] Recent Games Show Windows Titles

### ISSUE THREAD

**Issue by ekianjo** [ValveSoftware/SteamOS#368]
While everything is filtered by default when you go in the games library and games you can play, there is still this issue that if you play on a Windows machine with your account on a separate machine, the [Recent Games] view will precisely show those Non-SteamOS titles by default if you played them recently.

This does not make any sense to show them here, and will give a wrong impression that those games are also on SteamOS until users get an error while trying to run them. This should be filtered down to SteamOS compatible titles as well, by default.

**Comment by johnv-valve** [comment]
I'd like to keep this issue tracker specifically for SteamOS issues.

There are a lot of changes in Big Picture, so for general Steam Beta client issues, the team requests you post here http://steamcommunity.com/groups/SteamClientBeta/discussions/0/

**Comment by ProfessorKaos64** [comment]
Done. Thank you
