### ISSUE TITLE
[Suggestion] add other episodes in big picture

### ISSUE THREAD

**Issue by not83** [ValveSoftware/SteamOS#369]
I love the new game selection tab in big picture.

when selecting a video to watch e.g. payday the web series ep 1, why not list the other episodes somewhere in this option. After users watch episode 1 I would bet that they would want to watch the other episodes.

Adding this small entry would increase the enjoyment in the couch experience for watching videos.

**Comment by johnv-valve** [comment]
I'd like to keep this issue tracker specifically for SteamOS issues.

There are a lot of changes in Big Picture, so for general Steam Beta client issues, the team requests you post here http://steamcommunity.com/groups/SteamClientBeta/discussions/0/

**Comment by not83** [comment]
Fair enough, I understand
