### ISSUE TITLE
[bug] screen goes blurry when selecting manage controllers

### ISSUE THREAD

**Issue by not83** [ValveSoftware/SteamOS#370]
when selecting manage controllers when about to watch a video via big picture mode a few things happen:

there is no option listed to go back. it should show the Red B button to go back.
when you go back to the previous screen (i.e. the one that shows the manage controllers option) the screen does not come back into focus. It stays blurry as if it is in the background.

**Comment by ProfessorKaos64** [comment]
I get this too. Check some other bugs I listed at http://steamcommunity.com/groups/steamuniverse/discussions/1/527274088381810284/. You may find you have some of the same issues/experience

**Comment by johnv-valve** [comment]
I'd like to keep this issue tracker specifically for SteamOS issues.

There are a lot of changes in Big Picture, so for general Steam Beta client issues, the team requests you post here http://steamcommunity.com/groups/SteamClientBeta/discussions/0/

**Comment by ProfessorKaos64** [comment]
Done. Thank you
