### ISSUE TITLE
No SteamOS / Linux category on for latest client beta?

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#371]
This can be moved to the steam-for-linux bug tracker if it does not apply here. See the images below.

http://imgur.com/a/Z7vnZ

**Comment by johnv-valve** [comment]
I'd like to keep this issue tracker specifically for SteamOS issues.

There are a lot of changes in Big Picture, so for general Steam Beta client issues, the team requests you post here http://steamcommunity.com/groups/SteamClientBeta/discussions/0/
