### ISSUE TITLE
Bump cdrom-detect.udeb to 1.50

### ISSUE THREAD

**Issue by directhex** [ValveSoftware/SteamOS#375]
Brewmaster has cdrom-detect 1.49. Updating to the next release will introduce a method for detecting and bailing out on unetbootin-created install images (where unetbootin is the devil and will always break SteamOS, by bypassing/ignoring default.preseed)

**Comment by ProfessorKaos64** [comment]
>here unetbootin is the devil and will always break SteamOS, by bypassing/ignoring default.preseed
My laugh of the day :)

**Comment by directhex** [comment]
Another day, another user affected by this. https://www.reddit.com/r/SteamOS/comments/3lkjgb/steamos_installation_kernel_error/

**Comment by directhex** [comment]
Another day, another user affected by this.
https://www.reddit.com/r/SteamOS/comments/3m50oc/steamos_didnt_properly_configure/

(I don't need to wait for confirmation that they were using UNetBootin, since the problems it causes are so predictable)

**Comment by johnv-valve** [comment]
done

**Comment by not83** [comment]
Awesome! SteamOS documentation recommends not using this method, right?
