### ISSUE TITLE
Wireless Internet Card Not Found (TOSHIBA Satellite C855-S5115)

### ISSUE THREAD

**Issue by Kingdude** [ValveSoftware/SteamOS#376]
SteamOS update 161

**Comment by ProfessorKaos64** [comment]
Beta Steam client or did you op into the OS beta track? Also, in a gist please provide the output of `lspci -v`

**Comment by Kingdude** [comment]
Beta Steam Client, however, I'm unsure about the OS beta. Give me a moment to find the output of lspci.

**Comment by ProfessorKaos64** [comment]
If you did not manually run `sudo apt-get steamos-beta-repo` or mess with `/etc/apt/sources` et. all, you likely do not. You would also see this in a manual `apt-get update` command.  You may be able to install the firmware yourself with Debian sources, however, it is important that you did submit this, so Valve is aware that this hardware is not recognized automatically.

**Comment by Kingdude** [comment]
Steam OS won't let me paste output, does not have functionality for pasting in the steam web client.

**Comment by ProfessorKaos64** [comment]
For some reason, the version of pastebinit from the official package pool reports a bad API key. The command below will out the required command to sprunge:

```
lspci -v | curl -F 'sprunge=<-' http://sprunge.us
```

[Source](http://mewbies.com/pastebinit_how_to_pastebin_commnad_line_output_from_terminal_to_pastebin.htm)

**Comment by Kingdude** [comment]
Will paste when my Steam Machine has charged (ethernet cord is too far from power source). What is "sprunge" by the way?

**Comment by ProfessorKaos64** [comment]
Just a basic paste site but works well for the command line. For some reason I get an API error with pastebinit on SteamOS. You could also do `lspci -v > log.txt` and just open it in desktop node, copy the text and paste it to slexy or a github gist.

**Comment by johnv-valve** [comment]
Is this working now in brewmaster 2.49? Kernel has been upgraded to 4.1

**Comment by Tele42** [comment]
Toshiba's documentation on what wireless chipset is in this model is completely vague. There's no point in continuing troubleshooting without specifics, which was requested repeatedly.
