### ISSUE TITLE
[Package conflict ]  libpostproc-dev 

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#379]
Found this rebuilding Kodi from source

```
The following packages have unmet dependencies:
 libpostproc-dev : Depends: libpostproc53 (= 10:2.6.4-dmo1) but it is not going to be installed
                   Depends: libavutil-dev (>= 10:2.6.4-dmo1) but 6:11.4-1~deb8u1+bsos1 is to be installed

```

**Comment by johnv-valve** [comment]
What repositories have you added? SteamOS doesn't ship libpostproc-dev, so I don't know where it is coming from. And our libav is in sync with Jessie at version 6:11.4-1~deb8u1. Even sid is only at 7:2.8-1

**Comment by ProfessorKaos64** [comment]
Just tried again, not sure how i ran into this before. closing
