### ISSUE TITLE
Partnership with Mozilla to ship a Firefox branded version

### ISSUE THREAD

**Issue by AntoineTurmel** [ValveSoftware/SteamOS#38]
Just like Canonical does, it would be nice that @Mozilla and Valve cooperate to ship a Firefox branded version instead of IceWeasel :)

**Comment by not83** [comment]
Hey @AntoineTurmel I disagree. The iceweasel version is fine and that is just my two cents :)

**Comment by AntoineTurmel** [comment]
@not83 
I think Mozilla and Valve could benefit each others... but Valve direction may be just removing the IceWeasel and proposed only the Steam web browser

**Comment by johnv-valve** [comment]
I'm going to close this. People who want official branded Firefox (or Chrome) can install it.
