### ISSUE TITLE
[brewmaster-beta] libselinux1:i386 package fails

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#381]
Using "stock" brewmaster/brewmaster-beta repos,  libselinux1:i386 will fail. `apt-get install -f` will offer to install this, however the issue is that dpkg cannot unpack the archive's changelog file, reporting "/usr/share/doc/ libselinux1/changelog_Debian.gz' is different from other instances of package libattr1:i386. Manually backing up the old changelog and removing it works. 

Same outcome as #363

**Comment by johnv-valve** [comment]
should be fixed in 2.39

**Comment by not83** [comment]
Update hype!

**Comment by ProfessorKaos64** [comment]
Thank you very much @johnv-valve
