### ISSUE TITLE
SteamOS Brewmaster: Mouse X7 connecting as Xinput controller

### ISSUE THREAD

**Issue by kerkenetida** [ValveSoftware/SteamOS#382]
I had two mouses: both of them are X7 in different forms. 
When any of them is connected to computer SteamOS recognizes it like "XInput Controller" and it seems like always "up" button on controller is pressed. 

I cant turn off an option of automatic search of controllers

I tried to remove this joysticks with "rm /dev/input/by-id/*-joystick" and "rm /dev/input/by-id/*-event-joystick" but it doesn't work at long perspective (they are returning)

**Comment by kerkenetida** [comment]
There wasn't this problem at "Alchemist"-distro

**Comment by ServAlex** [comment]
I can confirm that I also have the same problem with A4 Tech X7 (XL-750BH) mouse on brewmaster.

**Comment by johnv-valve** [comment]
Should be fixed in the latest brewmaster_beta release. If not, please post the output of lsusb
