### ISSUE TITLE
SteamOS 2.0 try to recover from fatal error

### ISSUE THREAD

**Issue by LeeOnell** [ValveSoftware/SteamOS#383]
Hello
On Zbox ID18 after testing SteamOS 1.0 with succes, I would try SteamOS 2.0
but after the installer process and first reboot, I have this message "SteamOS is attempting to recover from a fatal error" under the logo. I tried the restore option with no success same problem.

I found this log file in the dump folder which can help : (sorry I can't upload it ?!?!) steam_stdout.txt
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Running Steam on steamos 2.0 64-bit
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
STEAM_RUNTIME is enabled automatically
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Installing breakpad exception handler for appid(steam)/version(0)
Assert( Assertion Failed: UpdateUI CreateGlFont regular failed ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/steamexe/./updateui_gl.cpp:293

Installing breakpad exception handler for appid(steam)/version(1.0)
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20150928085848_3.dmp[3989]: Uploading dump (out-of-process)
/tmp/dumps/crash_20150928085848_3.dmp
crash_20150928085848_3.dmp[3989]: Finished uploading minidump (out-of-process): success = no
crash_20150928085848_3.dmp[3989]: error: libcurl.so: cannot open shared object file: No such file or directory
crash_20150928085848_3.dmp[3989]: file ''/tmp/dumps/crash_20150928085848_3.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2015-09-28 08:58:48] Startup - updater built May  5 2015 12:15:27
[2015-09-28 08:58:48] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/steamexe/./updateui_gl.cpp (293) : Assertion Failed: UpdateUI CreateGlFont regular failed
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/steamexe/./main.cpp (513) : Assertion Failed: failed to initialize update status ui, or create initial window

**Comment by ProfessorKaos64** [comment]
I had this same thing when I had a preemptive reboot once. I had to reinstall my entire machine, which was rotten. Can you please list:

1. Where you downloaded SteamOS 2.0/brewmaster and what file name
2. How you made your installation media
3. What type motherboard you have (older BIOS, UEFI, or dual-bios)
4. What type graphics card you have

Getting out of this loop is tough. The process launches from a script in `/usr/bin/steamos-recovery` (something around that naming, i'm building source code so I can't check right now), but I wasn't able to break the cycle when it happened to me.

**Comment by LeeOnell** [comment]
Thanks for your quick answer
1) from here http://steamcommunity.com/groups/steamuniverse/announcements/detail/83663183294752597, this link ZIP (for UEFI systems) : http://repo.steampowered.com/download/brewmaster/SteamOSInstaller.zip
2) Usb key fat32 formatted but (maybe my mistake) I just deleted all files from SteamOS 1.0 zip and extracted on it file for steamOS 2.0
3) It's a UEFI MB, at least I use it in UEFI mode.
4) Intel® Ivybridge Mobile
5) Automatic Install, nothing special, only, I remenber now, a first boot on steam desktop with a message about the network config (but i had the same behaviour with 1.0/alchemist) and a reboot with loop on fatal error.

I will try an installation from zero with formated usb key in case if ...

**Comment by LeeOnell** [comment]
Thanks for your quick answer
1) from here http://steamcommunity.com/groups/steamuniverse/announcements/detail/83663183294752597, this link ZIP (for UEFI systems) : http://repo.steampowered.com/download/brewmaster/SteamOSInstaller.zip
2) Usb key fat32 formatted but (maybe my mistake) I just deleted all files from SteamOS 1.0 zip and extracted on it file for steamOS 2.0
3) It's a UEFI MB, at least I use it in UEFI mode.
4) Intel® Ivybridge Mobile
5) Automatic Install, nothing special, only, I remenber now, a first boot on steam desktop with a message about the network config (but i had the same behaviour with 1.0/alchemist) and a reboot with loop on fatal error.

I will try an installation from zero with formated usb key in case if ...

**Comment by ProfessorKaos64** [comment]
1. Can't check right now, but if that's the brewmaster announcement page, ok there. URL to zip seems legit :)
2. Make sure you cleanly format the drive with a program like gparted (GUI visual application). Don't just delete files and call it a day. Format as FAT32 and leave it be. Unzip the contents of the USB drive to it.
3. ok sounds good 
4. Mesa drivers should be fine with that I believe
5. You need to connect to a network or Steam will not update and place the appropriate library files and so forth. Are you connected to a lan or WLAN (wi-fi)? Did you connect to the internet when told to?

**Comment by LeeOnell** [comment]
My computer is connected to a lan all the time. I precise again I could use the steamos 1.0 with no problem outside the know issues lol. I am redoing the install.

**Comment by ProfessorKaos64** [comment]
It depends on how* you created that USB key. The zip file download is meant for UEFI systems, so you were right in choosing that. The ISO is for legacy hardware / BIOS. Strange, but glad you are up and running. Thank you for the update.

**Comment by MattDevo** [comment]
I'm getting the same errors with on my Haswell 2955U ChromeBox.  Steam client constantly restarts, is unusable.  Doesn't matter if I restore from an older clonezilla backup image (from 7-25-15, which works fine) and update, or install cleanly.  regular and beta client both exhibit same issue

**Comment by fledermaus** [comment]
Just bumped into this while working on something unrelated. Looks to be a corrupted/missing font/font-cache problem (at least here - I had the exact symptoms described).

steam looks for a file at roughly this location (the exact location varies depending on whether you are on SteamOS or Ubuntu or Debian or whatever):

 /home/steam/.local/share/Steam/tenfoot/resource/fonts/tenfoot.uifont

On my broken box, this file was absent. It is present on my other non-steamos box with steam installed.

If it fails to find that, it then attempts to open:

/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf

Which is in package ttf-dejavu-core (and is _not_ installed by default on SteamOS)

I managed to get into the steam box while it was doing its emergency recovery process
and install  ttf-dejavu-core, whch worked around the problem sufficiently to allow steam
to start in 10' mode - and this resulted in the recreation of the missing uifont file too.

**Comment by ProfessorKaos64** [comment]
Nice find. Sometimes you need to purge the package as well. Strange though...

**Comment by fledermaus** [comment]
I _think_ the uifont file gets regenerated by steam sometimes, but it's not an atomic change:
So you can end up missing the file if it's interrupted... which would still be fine if ttf-dejavu-core was present in the default install.

**Comment by NahsiN** [comment]
I also ran into a similar issue today. Started up the computer and got the "Steam is attempting to recover from a fatal error." The log files in /tmp were similar to the first post including an error with loading libcurl.so. Double checked all the hardware and finally tried restoring factory image to no avail. 

Then I stumbled upon @fledermaus posts so I took out the hard drive and plugged it into my desktop. Low and behold, under .local/share/Steam, the tenfoot folder was completely _missing_! So I copied over the tenfoot folder from my Steam installation on Ubuntu 16.04 taking care of permissions. On reboot, Steam immediately showed an update screen and from what I can tell, reinstalled some stuff and I ended up having to login again and update my information. But all my games were still there! And it's been working fine since then.

Looking over at SteamOS discussions on Steam, it seems there are a number of people with similar issues. I wonder if all of them are somehow connected to the corruption of .local/share/Steam folder.
[Example 1](http://steamcommunity.com/groups/steamuniverse/discussions/1/358415206100393243/),
[Example 2, the image links in these discussions are exactly what I ended up with when examining journalctl](http://steamcommunity.com/groups/steamuniverse/discussions/1/648814395877413023/?ctp=2)

**Comment by Schlesiger** [comment]
@NahsiN Thank you! I arrived home from vacation and my SteamOS machine wouldn't start. It was working fine before I left. I have no idea what could have corrupted the steam home directory. Your solution worked! I am relieved I won't have to wipe the machine.

**Comment by ProfessorKaos64** [comment]
For what it's worth, I detailed (with help from @sharkwouter) the process here:  
https://github.com/ValveSoftware/SteamOS/wiki/SteamOS-auto-repair-process

**Comment by nimbius** [comment]
this issue still exists as of now.

**Comment by ekianjo** [comment]
Yeah i have no idea why this issue is marked as closed, it is still occuring to me in 2.87 stable. This is so not fixed.

**Comment by VaysseB** [comment]
I can still confirm this issue.
I *'fixed it'* with the solution provided by @Schlesiger, but this is still a workaround.
And once again, thank you for your solution ! (I really didn't wanted to redo all the downloads and lose my datas).
Now I got the *"failed to apply update"*, great day :(

**Comment by nimbius** [comment]
ive decided to reinstall the OS, mostly because this type of failure isnt a huge inconvenience given the nature of steam. If it occurs in the future, I will be sure to take a more investigative approach and post logs where applicable.
August 6 2016 3:36 PM, "Bastien Vaysse"  wrote:
	I can still confirm this issue.
I 'fixed it' with the solution provided by @Schlesiger (https://github.com/Schlesiger), but this is still a workaround.
And once again, thank you for your solution ! (I really didn't wanted to redo all the downloads and lose my datas).
Now I got the "failed to apply update", great day :(

**Comment by VaysseB** [comment]
Thanks to @ekianjo (here: [explaination](https://github.com/ValveSoftware/SteamOS/issues/546#issuecomment-238065686)), I fix my installation. 
I basically forgot to set permission for the steam user of the 'tenfoot' folder. It was still with root's.

**Comment by ekianjo** [comment]
@VaysseB good to know it worked for you too !

**Comment by urandom** [comment]
I just got this issue on my steam machine. The correct fix (after much wasted time) was indeed to just install dejavu-core. The system would fix itself afterwards. Which means as of now, this issue is definitely not fixed.

**Comment by johnv-valve** [comment]
SteamOS now (as of 2.88) includes ttf-dejavu-core as suggested by @fledermaus

**Comment by deepfire** [comment]
@johnv-valve, why, oh why is 2.87 not released yet?  Had spent a couple fruitless days hunting this down in #568..

**Comment by Tele42** [comment]
@deepfire, it is released, but you have to opt into the SteamOS beta. The stable version has not been updated yet.

There is some info on this at https://github.com/ValveSoftware/SteamOS/wiki/Opting-into-SteamOS-Beta.

**Comment by ekianjo** [comment]
@Tele42 "released" does not mean what you think it means. "released" implies a stable release. A beta is not recommended for regular users. So in practice 2.87 is not released beyond the testing community.
