### ISSUE TITLE
Document newest version(s) in README.md

### ISSUE THREAD

**Issue by MrSchism** [ValveSoftware/SteamOS#388]
A couple weeks ago, those of us who have beta machines got our controllers.  I hadn't kept my beta machine up to date, so I had to go through some painful updating.  Now, I have no idea what the current versions of Alchemist, Alchemist_beta, and Brewmaster are, so it's difficult to be certain of if I have all of the updates.

**Comment by johnv-valve** [comment]
Check the SteamOS discussion group http://steamcommunity.com/groups/steamuniverse/discussions/1/. The current released version is always announced & pinned there.
