### ISSUE TITLE
Switching from Fglrx to Mesa driver on SteamOS Brewmaster results in "VMware Driver" mode

### ISSUE THREAD

**Issue by egee-irl** [ValveSoftware/SteamOS#389]
I'm not sure of the best way to explain this because I don't understand what exactly is happening. Here are the steps to reproduce:

Prerequisite - Be using an FGLRX supported card (I am using an AMD R7 360).

1. In the terminal, do "update-alternatives --config glx"
2. Select "/usr/lib/mesa-diverted   5  manual mode"
3. Save changes and reboot computer
4. Check glx info (I used KInfo)

Results - OpenGL vendor info shows "Gallium 0.4 on llvmpipe VMware"

Needless to say I am *not* running on a virtualized environment. I discovered this bug because I was curious about the performance of SteamOS using the Mesa driver. Apparently, it is not good.

**Comment by sharkwouter** [comment]
Graphics drivers are updated on boot, you can't manually change it without disabling the init script for it. If you reboot again, it should be back to fglrx.

**Comment by johnv-valve** [comment]
You can disable the auto graphics setting like this:

    systemctl disable update-graphics

**Comment by egee-irl** [comment]
Ran the systemctl disable update-graphics command, still having the Mesa issue. Glxinfo | grep OpenGL reports this:

OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.5, 128 bits)
OpenGL version string: 3.0 Mesa 10.6.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:

**Comment by Tele42** [comment]
@egee-irl you still need to deal with the 'too old for that version of mesa' steam runtime libraries. The <a href=https://wiki.archlinux.org/index.php/Steam#Steam_runtime_issues>Arch workaround</a> should help with that.

**Comment by egee-irl** [comment]
> you still need to deal with the 'too old for that version of mesa' steam runtime libraries.

It's affecting the whole of SteamOS. The Steam Runtime libraries are only used by games launched via Steam. This appears to be a systemic SteamOS issue.
