### ISSUE TITLE
No "add to wishlist" button while viewing games in store

### ISSUE THREAD

**Issue by phevenn** [ValveSoftware/SteamOS#390]
Steps to reproduce:
1. Go to steam game

Expected result:
Along with "buy -game title-", I would expect to see "add to wishlist" or "not interested"
Neither options exist or if they do they are not easy to see.

Actual Result:
Only "Buy -game title-" exists under preview window.
![2015-10-17 16_01_51-steam](https://cloud.githubusercontent.com/assets/12129874/10560953/84eb8d90-74e8-11e5-965d-cf288510ac60.png)

**Comment by ProfessorKaos64** [comment]
A lot of those windows expand when you click them, missing text or not. Did you try clicking it to see if it expands? I've noticed this to be the case for item-heavy panes such as Features and User Tags. I do agree it should show the text even if so.

**Comment by phevenn** [comment]
I did, it brings you to the purchase screen
![2015-10-20 01_45_30-steam](https://cloud.githubusercontent.com/assets/12129874/10599002/5dc5f332-76cc-11e5-9d92-fa891995db88.png)

**Comment by ProfessorKaos64** [comment]
Sounds more like a Steam Client issue. If you are opted into the Beta Client, could you move this to the [Beta Client Group](https://steamcommunity.com/groups/SteamClientBeta) under the "Bugs" sub-discussion? Also in the description, can you include if this also affects the keyboard control (if you have one to hook up) mappings? This isn't a SteamOS issue as far as I can tell.

**Comment by johnv-valve** [comment]
This is there in the current beta client
