### ISSUE TITLE
Browser current tab does not show close mapping button 

### ISSUE THREAD

**Issue by phevenn** [ValveSoftware/SteamOS#394]
While in the browser and viewing the current tab the "close tab" is not visible on all windows besides the first window.

Expected:
Select first tab (default), shows buttons "Select", "Close Tab", "New Tab"
Move to next window, shows buttons "Select", "Close Tab", "New Tab"

Actual:
Select first tab (default), shows buttons "Select", "Close Tab", "New Tab"
Move to next window, shows buttons "Select", "New Tab" (Missing "Close Tab")

![2015-10-20 01_43_41-steam](https://cloud.githubusercontent.com/assets/12129874/10599137/40c9d086-76cd-11e5-8d6c-deca0cd265a4.png)
![2015-10-20 01_43_57-steam](https://cloud.githubusercontent.com/assets/12129874/10599138/4690da14-76cd-11e5-8ebd-926af21beba8.png)

**Comment by ProfessorKaos64** [comment]
Sounds more like a Steam Client issue. If you are opted into the Beta Client, could you move this to the [Beta Client Group](https://steamcommunity.com/groups/SteamClientBeta) under the "Bugs" sub-discussion? Also in the description, can you include if this also affects the keyboard control (if you have one to hook up) mappings?

**Comment by johnv-valve** [comment]
Looks like this is fixed in the current Steam Beta Client
