### ISSUE TITLE
Error: Couldn't find bootstrap, it's not safe to reset Steam.

### ISSUE THREAD

**Issue by Burrito-Bazooka** [ValveSoftware/SteamOS#395]
After [today's beta update](http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/48770934355708173), I get the error message mentioned in the title. It happens when I try to start Steam, and Steam doesn't start successfully.

I use SolydX, which is based on Debian Testing.

Here's the error as seen from command line:

```
user@burrito-linux-desktop:~/temp$ steam
Running Steam on solydxk 8 64-bit
STEAM_RUNTIME is enabled automatically
[2015-10-20 17:59:38] Startup - updater built Oct 20 2015 09:02:49
[2015-10-20 17:59:38] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Error: Couldn't find bootstrap, it's not safe to reset Steam. Please contact technical support.

user@burrito-linux-desktop:~/temp$ cat ~/.steam/error.log 
rm: cannot remove ‘/home/user/.steam/steam’: Is a directory
rm: cannot remove ‘/home/user/.steam/bin’: Is a directory
/bin/bash: /home/user/.steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
/home/user/.steam/steam.sh: line 756: 32202 Illegal instruction     $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

wat do? Do I reinstall steam? Or is this fixable without reinstalling?

**Comment by ProfessorKaos64** [comment]
This is for SteamOS bugs, not the Steam client. You can move this to the "Steam for Linux" GitHub page, or better yet, post this bug in the [Steam for Linux](https://steamcommunity.com/app/221410/discussions/) discussions group under "Bugs." I believe that group sub-section gets a bit more visibility.

**Comment by Burrito-Bazooka** [comment]
oops. Thanks.

**Comment by ProfessorKaos64** [comment]
Not a problem!
