### ISSUE TITLE
lightdm crash on startup, SteamOS not working

### ISSUE THREAD

**Issue by Fensterbank** [ValveSoftware/SteamOS#396]
Hello,
I successfully used SteamOS for over a year, but since yesterday SteamOS Alchemist didn't show the GUI and was in a loop.
I tested it with another graphics card and with the SteamOS HDD in another computer and had the same results.
My SteamOS installation was completely broken and because it's reproducible on another computer, it doesn't look like a hardware fault.

I installed now SteamOS Brewmaster.
- Downloaded the iso from the announcement thread
- older bios Installation via USB stick
- MSI nvidia Geforce GTX 650
- Automatic installation

The installation worked fine, at the end, gnome has been booted and steam was installed.
After the next boot, I had exact the same issues, but a "better error handling":
Booting SteamOS, no signal, "SteamOS is attending to recover from a fatal error" and again.

I added the **/var/log/messages** and **/var/log/syslog** in a gist:
https://gist.github.com/Fensterbank/7ab87f6f5bb173b34ef7

I marked the reboots as "### PC START".
In the logfiles, we see all, including the steam installation in gnome or the steamos-autorepair.sh.

The interesting fact are the errors which result in the lightdm fail:

    Oct 21 11:23:48 steamos NetworkManager[460]: <info> startup complete
    Oct 21 11:23:48 steamos dbus[467]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
    Oct 21 11:23:48 steamos kernel: [   20.233146] sound hdaudioC1D0: HDMI: invalid ELD data byte 36
    Oct 21 11:23:48 steamos dbus[467]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
    Oct 21 11:23:48 steamos nm-dispatcher: Dispatching action 'up' for eth0
    Oct 21 11:23:49 steamos kernel: [   20.445493] traps: steam[888] trap invalid opcode ip:f756b2f9 sp:ff89de30 error:0 in steam[f7334000+3a2000]
    Oct 21 11:23:49 steamos kernel: [   20.580655] sound hdaudioC1D0: HDMI: invalid ELD data byte 33
    Oct 21 11:23:49 steamos nm-dispatcher[791]: E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
    Oct 21 11:23:49 steamos nm-dispatcher[791]: E: Unable to lock directory /var/lib/apt/lists/
    Oct 21 11:23:49 steamos systemd[1]: lightdm.service: main process exited, code=exited, status=1/FAILURE
    Oct 21 11:23:49 steamos systemd[1]: Unit lightdm.service entered failed state.
    Oct 21 11:23:50 steamos kernel: [   21.278722] nvidia 0000:07:00.0: irq 26 for MSI/MSI-X
    Oct 21 11:23:50 steamos acpid: client 724[0:0] has disconnected
    Oct 21 11:23:50 steamos acpid: client connected from 981[0:0]
    Oct 21 11:23:50 steamos acpid: 1 client rule loaded
    Oct 21 11:23:50 steamos kernel: [   21.707608] sound hdaudioC1D0: HDMI: invalid ELD data byte 4
    Oct 21 11:23:50 steamos kernel: [   22.079183] sound hdaudioC1D0: HDMI: invalid ELD data byte 39
    Oct 21 11:23:51 steamos kernel: [   22.308698] traps: steam[1129] trap invalid opcode ip:f75d62f9 sp:ffeb9e70 error:0 in steam[f739f000+3a2000]
    Oct 21 11:23:51 steamos kernel: [   22.470808] sound hdaudioC1D0: HDMI: invalid ELD data byte 40
    Oct 21 11:23:51 steamos systemd[1]: lightdm.service: main process exited, code=exited, status=1/FAILURE
    Oct 21 11:23:51 steamos systemd[1]: Unit lightdm.service entered failed state.
    Oct 21 11:23:51 steamos kernel: [   23.185412] nvidia 0000:07:00.0: irq 26 for MSI/MSI-X
    Oct 21 11:23:52 steamos acpid: client 981[0:0] has disconnected
    Oct 21 11:23:52 steamos acpid: client connected from 1140[0:0]
    Oct 21 11:23:52 steamos acpid: 1 client rule loaded
    [...]
    Oct 21 11:24:02 steamos systemd[1]: lightdm.service: main process exited, code=exited, status=1/FAILURE
    Oct 21 11:24:02 steamos systemd[1]: Unit lightdm.service entered failed state.
    Oct 21 11:24:02 steamos systemd[1]: lightdm.service start request repeated too quickly, refusing to start.

I removed the graphics card and tested it with an old AMD Radeon but had the same issues.
Since the first boot to the graphical gnome had no problems, the steam client installation must have caused this issue.
And since I had **the same problems with SteamOS v1 Alchemist**, it looks like a simple **steam client or graphics driver update could have broken SteamOS** for me to a state where no autorepair helps.

I'm looking forward to a solution. I just got my Steam Controller and lost my Steam Machine where I want to use it. :disappointed_relieved:

**Comment by ProfessorKaos64** [comment]
How did you create the media for the ISO image on your USB stick? Is the target motherboard UEFI/BIOS/Dual-BIOS? It you used the announcement thread, the ISO should be sourcing from the brewmaster folder at repo.steampowered.com.

**Comment by johnv-valve** [comment]
Unfortunately we shipped a beta Steam client which required AVX instructions. If you are running on an older CPU that does not support AVX and you are in the beta, then Steam will crash before the bootstrapper can update you to the newer version.

The current Steam client should have a fix for this, so if you do a fresh install you shouldn't have this problem any more. Sorry about that.

**Comment by Fensterbank** [comment]
I used Rufus (https://github.com/pbatard/rufus), a very popular usb creation tool on Windows to create the media.
The target motherboard is a ASRock P55M PRO, its classic AMI BIOS.
I downloaded the ISO from http://repo.steampowered.com/download/brewmaster/SteamOSDVD.iso

Thanks for the answer, John. This mainboard has Sockel 1156, so indeed one generation before Sandy-Bridge.

But I cannot accept your answer, because I made a fresh install today at ~19:00 CET.
My pc didn't had the correct timezone, but as you see in the linked log file, a fresh beta steam client has been downloaded a few hours ago.
So when has the "current Steam client" you are talking about released?

**Comment by Tele42** [comment]
@Fensterbank The fixed steam beta client didn't have an attached changelog when it shipped, since you're able to move around the terminal, you should be able to figure out how to run steam --reset as the steam user, which should pull a working version on the next start. (I don't know if steamos-autorepair.sh does the same easier)

**Comment by Fensterbank** [comment]
Okay, alright.
steam --reset didn't work because it couldn't start. But I simply just ran a clean reinstall.
And indeed the client update must have released in the small timespan between my installation and the creation of this issue. :+1: 
Now it works fine! Thanks.

**Comment by not83** [comment]
https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/48771157886777279

😊
