### ISSUE TITLE
SteamOs completely crashed since oct 20

### ISSUE THREAD

**Issue by GargGit** [ValveSoftware/SteamOS#397]
Since oct 20, the last upgrade had completly broke my steamos. I seen the upgrade for the client. And then, I had a infinite reboot loop...
So juste before the load (normaly you see the big picture animation), the system try a small restore and then reboot etc.

I tried yesterday a full restore (so escape when booting and then restore). With not exactly the same problem, I doesn't see the small restore, but after a few minutes, reboot etc.

I'll try to find informations in logs

Thx
(sorry for my english...)

**Comment by ProfessorKaos64** [comment]
You want to look at #395 . There was a faulty update.

**Comment by johnv-valve** [comment]
This is the same as 395 if you are running on a CPU without AVX support

**Comment by not83** [comment]
for anyone who doesn't know.

1. Update has been fixed.
2. you will need to reinstall

On Fri, Oct 23, 2015 at 4:47 AM, johnv-valve <notifications@github.com>
wrote:

> This is the same as 395 if you are running on a CPU without AVX support
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/SteamOS/issues/397#issuecomment-150267984>
> .
>



-- 
Joshua Murphy

**Comment by ClementJansen** [comment]
I got the same problem while I just downloaded steamos today. So... how could I fix it since I theorically got the last update of steamos ?

**Comment by ProfessorKaos64** [comment]
@ClementJansen , I would advise creating a new ticket with detailed system information and steps to reproduce.
