### ISSUE TITLE
X no longer starting

### ISSUE THREAD

**Issue by mafgh** [ValveSoftware/SteamOS#398]
As of 21. October 2015 X is no longer starting on my machine.

I can see Grub starting, a couple of console log messages, a resolution switch, a mouse pointer appearing for just a second and disappearing again. After that, resolution switch after resolution switch.

I found #397, but I don't get full reboots.

Nvidia GeForce GT 425M GPU

**Comment by ProfessorKaos64** [comment]
You want to look at #395 . There was a faulty update.

**Comment by mafgh** [comment]
Thanks, that lead me to https://github.com/ValveSoftware/steam-for-linux/issues/4076 and by performing these steps:

  - reboot into recovery mode
  - su - steam
  - steam --reset
  - exit
  - reboot

X is again starting. However it forgot our Accounts and Family Sharing Settings, also I can no longer play shared games.

**Comment by ProfessorKaos64** [comment]
Thanks for listing the commands here for folks that reach this. Shame this borked a lot of installs. Easy fix for technical folks, not so much for non-techies.

**Comment by GargGit** [comment]
I tried the commands but no change in my case.
Now I have "SteamOs is attempting to recover from a fatal error" and then it reboot again.
It's too bad, I hope that a full new install will resolve this.
