### ISSUE TITLE
Will be SteamOS  using systemd?

### ISSUE THREAD

**Issue by DarkminecrafterHD** [ValveSoftware/SteamOS#403]
As SteamOs Alchemist is based on Debian Wheezy, that's systemd free i'm supose alchemist will be also free of it, corect me if i'm wrong

But what about Brewmaster?

**Comment by not83** [comment]
Not a bug report. Try moving this to the SteamOS community discussion

**Comment by sharkwouter** [comment]
You can install systemd in wheezy, but it is not the default.

**Comment by johnv-valve** [comment]
brewmaster uses systemd

**Comment by DarkminecrafterHD** [comment]
Thanks you all
I know that this is a bug report and that shouldn't be here.
but i wanted to known from the developers and not form anyone else.
my apologies for disturbing you
