### ISSUE TITLE
Spurious "Enable Steam Beta Client" alert.

### ISSUE THREAD

**Issue by 3vi1** [ValveSoftware/SteamOS#404]
Even though I'm already using the Steam Beta Client, I have an "Enable Steam Beta Client" alert/mail that won't go away.  When I click it, it restarts Steam but the alert is still there.  It also persists after a full reboot.

Inside of the System settings, the box to enable the Steam Beta Client is already checked/active.  If I deactivate it, it will downgrade me to the release client, and the alert about enabling the beta client will *not* be present.  But, as soon as I re-activate the box and upgrade/reboot back to the beta client I have the spurious alert again.

Anyone know where that alert is generated?  Is there some file I can check from desktop mode, that may be out of sync somehow?

Hardware:  Alienware Steam Machine (i7)
Repo/OS ver:  Brewmaster_beta (2.48)
Steam version:  1445896823

**Comment by ProfessorKaos64** [comment]
This likely is  a client issue, I made a report [here](http://steamcommunity.com/groups/SteamClientBeta/discussions/0/490123938446717152/)

**Comment by 3vi1** [comment]
Ah, good to know I'm not the only one seeing the behavior.  I agree that it's probably something with the new client if it's happening to both of us; thanks for the confirmation!

**Comment by ProfessorKaos64** [comment]
Yep, you  can subscribe to that page to get updates. I don't think this is a SteamOS issue. If you wish to close it, you can do so.

**Comment by 3vi1** [comment]
Looks like they just pushed a new update that fixes it!  Closing.
