### ISSUE TITLE
Z170A Hardware not supported

### ISSUE THREAD

**Issue by Dungeonseeker** [ValveSoftware/SteamOS#406]
MSI Z170A Gaming M7 board (Skylake), after install is finished there is no NIC (Killer E2400) support or Sound (Realtek HD unsure of which exactly) working.

Heres the lspci -v 
http://pastebin.com/UtBkySFf

uname -a
desktop@steamos:~$ uname -a
Linux steamos 3.10-5-amd64 #1 SMP SteamOS 3.10.60-1+steamos1 (2014-12-04) x86_64 GNU/Linux

**Comment by Tele42** [comment]
For reference, the audio chipset in question is a Realtek ALC1150. Is there a reason you tried Alchemist over Brewmaster? This is a very new chipset and Alchemist is simply too old to have have a chance of being compatible.

**Comment by Dungeonseeker** [comment]
I downloaded the latest zip direct from the following -

http://store.steampowered.com/steamos/buildyourown

In Steam it shows as SteamOS 1.0 Update 1.61. Is that not the latest?

Any chance of a link to the latest version then please.

**Comment by Dungeonseeker** [comment]
OK, all udated to latest brewmaster beta (now says Version 2.0 Update 2.49).

Sound is working fine but I am still unable to connect to the internet by ethernet.

**Comment by Tele42** [comment]
@Plagman here's the proper patch: https://www.mail-archive.com/netdev@vger.kernel.org/msg77021.html

**Comment by Dungeonseeker** [comment]
So is there nothing I can do now except wait it out?

**Comment by Dungeonseeker** [comment]
@Tele42 I'm gonna go back to Ubuntu and keep an eye on the SteamOS updates section for Brewmaster 2.50 as I just can't live on WiFi, been waiting for 2 days now and Dying Light is still only at 70%. 

Thanks for everything you've done, hopefully you guys will get this patched up.

**Comment by Tele42** [comment]
This should have been addressed with https://github.com/ValveSoftware/steamos_kernel/commit/af203d6dc82f4c6902eff148291d01d1e0b77073.

**Comment by johnv-valve** [comment]
Should be fixed in brewmaster_beta 2.55 http://steamcommunity.com/groups/steamuniverse/discussions/1/492379439674068368/

**Comment by lukaslin** [comment]
I had the same problem with this motherboard MSI Z170A with Linux.
I tried to install drivers manually on Linux mint 17.3 (equivalent Ubuntu 14.04).
There is a link :
https://code.launchpad.net/~ubuntu-audio-dev/+archive/ubuntu/alsa-daily/+packages
I used the Debian package .deb  to install.
After reboot sound works well.
