### ISSUE TITLE
Hybrid graphics Intel/NVIDIA not working (ASUS ROG GR8 with Brewmaster)

### ISSUE THREAD

**Issue by scottydont264** [ValveSoftware/SteamOS#410]
I have an ASUS ROG GR8 with SteamOS installed, but it only seems to utilize the integrated Intel GPU and never the discrete NVIDIA GPU.

This machine is used for gaming so I don't care about shutting the discrete GPU down for efficiency - I would prefer using it at all times for the sake of performance.  If SteamOS could recognize this hardware setup and allow for a simple user selection between toggling the discrete GPU on and off (and allow it to be left on) in the settings menu that would resolve this issue nicely without the need to include any kind of power optimization algorithm.

I would think that ASUS would have to have a resolution for this issue in place before launching the GR8S - unless they plan on changing the hardware configuration from the GR8, but I don't know.

**Comment by ProfessorKaos64** [comment]
Try reading this [thread](https://www.reddit.com/r/SteamOS/comments/23kfgc/installation_choose_intel_integrated_gpu_over/). I don't believe this is something that will get supported anytime soon, it's bad enough with Linux-based operating systems in general as it is.

**Comment by Tele42** [comment]
Duplicate of #23.

**Comment by Plagman** [comment]
The GR8S has been canceled and store page removed a few weeks ago. The GR8 VGA design is muxless and the NVIDIA driver does not support hybrid graphics without screen tearing, so running SteamOS on the GR8 is not supported.

**Comment by scottydont264** [comment]
Well that stinks.  Luckily I think I still have time to return the machine.  Thanks for the info!
