### ISSUE TITLE
Installer: Latest Brewmaster Installer Boots To Grub Prompt

### ISSUE THREAD

**Issue by egee-irl** [ValveSoftware/SteamOS#413]
The latest SteamOS Brewmaster installer boots into grub prompt after copied from zip file.

The SteamOS Brewmaster installer I am using is dated - 28-Oct-2015 12:34

**Comment by ProfessorKaos64** [comment]
1. Where did you get the installer?
2. How did you prepare the installation media?
3. What is your system hardware? (specifics or gist paste of `lspci -v`, UEFI/BIOS/GPU)

**Comment by egee-irl** [comment]
Seemed to be an issue with my USB stick. Tried using a different one and it worked.
