### ISSUE TITLE
Wireless PS3 USB headset: Stuttering audio in some games and overlay

### ISSUE THREAD

**Issue by HanJiexi** [ValveSoftware/SteamOS#421]
My wireless PS3 USB headset is in good working condition and has had no problem with any device or game on any OS whatsoever since the moment I got it. However, when I use this headset with SteamOS, the following games exhibit severe audio stuttering: Civilization V, Metro 2033 Redux, and the Talos Principle. I fixed Talos audio with an in-game console command, but the issues with Civ and Metro remain, so I can't play those games except through the TV's HDMI audio.

Additionally, there are a lot of other games whose audio doesn't stutter at all in game, but when opening the Steam Controller configurator, the UI navigation sounds exhibit some minor stuttering.

Unfortunately, this is the only USB headset I have with which to test this issue.

**Comment by ProfessorKaos64** [comment]
Does it work fine with other games? This would be an implementation issue with the game/port/wrapper, more so than SteamOS I would think.

**Comment by HanJiexi** [comment]
Yes the audio in other games does work fine (among those I tested -- several dozen). However, there's still the overlay UI navigation sound stuttering.

I do intend to contact those developers directly, and will update this topic when I get answers, but since it's three different games from three different companies, it could potentially be a SteamOS issue. I'll close the issue if I discover otherwise.

**Comment by Tele42** [comment]
This reminds of pulseaudio tuning issues that have come up in the past, how does adding ```default-fragment-size-msec = 5``` to pulseaudio's daemon.conf affect your system?

**Comment by HanJiexi** [comment]
That does indeed resolve the problem for me with those games using the headset on the Syber Steam Machine P, but I'll have to test many other games both with headset and without to ensure that the fix didn't cause any other problems.

Plus, that's a non-default configuration on a system where everything is supposed to be configured correctly by default already. My concern is not for myself (as I am technically inclined) but for everyone else who can't be expected to jump through so many hoops just to play their games.

**Comment by HanJiexi** [comment]
This is resolved via the fix in #433.
