### ISSUE TITLE
SteamOS BPM fails to load GUI when returning from Gnome Desktop after playing a game.

### ISSUE THREAD

**Issue by madmachinations** [ValveSoftware/SteamOS#429]
I keep having this issue when I am switching back to BPM from the Gnome Desktop. It only seems to do it after I have played a game. BPM hasn't crashed, its still running. It tends to show a frozen background image, but none of the interface. I have to blindly log out to get BPM to start working properly again, or reboot entirely.

My SM is a custom build running what I assume is the latest Brewmaster, as the machine was only built a week ago. Main components are an Intel Core 2 Duo 64bit 2.93Ghz, Nvidia GTX 750 TI, and 4GB of RAM.

**Comment by Ryochan7** [comment]
steamcompmgr does not refresh when switching sessions for some reason. On my system, I have a shortcut set to launch a bash script that performs the desktop switch and also launch an instance of feh so steamcompmgr has a window to grab. Switching between Steam BPM and the Desktop session will work properly if a game is active.

**Comment by madmachinations** [comment]
hmmmm, how strange, an interesting work around though. I will give it a try, I've got some applications I need to add to my library shortcuts anyway.

**Comment by madmachinations** [comment]
this problem appears to have gone away now, or at least it has for me xP
