### ISSUE TITLE
steam os not loading on pc

### ISSUE THREAD

**Issue by gideongek** [ValveSoftware/SteamOS#434]
i burnd the iso on an dvd and it wont work on my pc.
i have booted into my current os and then clickt on the setup.exe file but it doesnt load it shows an comand promt for an split second and then it closes.
plz help

**Comment by gideongek** [comment]
sorry for bad englich i am dutch

**Comment by ProfessorKaos64** [comment]
Please review:
https://github.com/ValveSoftware/SteamOS/wiki

Most important, the getting started and installation pages. Let me know how you do. The wiki pages should explain the key points you need to know for installation.

**Comment by gideongek** [comment]
ok tnx
