### ISSUE TITLE
xorg-xserver-xorg-video-vmware doesn't support VMWare Workstation 12

### ISSUE THREAD

**Issue by FireCulex** [ValveSoftware/SteamOS#437]
Initialized VMWARE_CTRL extension version 0.2
Failed to initialize Gallium3D Xa. No render acceleration available.
Skipped initialization of direct rendering due to lack of render acceleration.
Render acceleration is disabled.
Rendercheck mode is disabled.
Direct rendering (3D) is disabled.
Backing store disabled
Silken mouse enabled
RandR 1.2 enabled, ignore the following RandR disabled message.
DPMS enabled
No 3D acceleration. Not setting up textured video.
RandR disabled

**Comment by FireCulex** [comment]
Invalid. Took about 5 hours to discover that VMWare 12 disables 3d acceleration by default.

**Comment by not83** [comment]
Is this solved?

**Comment by FireCulex** [comment]
It shows Gallium 0.4 on SVGA3D now. The problem stemmed from there being a black screen on reboot with and without the desktop environment. The desktop environment would work initially, update, then go black. 

It finally came up this time. I notice the black screen after the update takes a while on the first time but there's disk activity I could see.
