### ISSUE TITLE
fglrx and gnome do not work together

### ISSUE THREAD

**Issue by FireCulex** [ValveSoftware/SteamOS#439]
On the installation of SteamOS, before updating gnome will say Oh no! Something has gone wrong System can't recover, extensions disabled. Have to alt-ctrl-f2 update-alternatives --config glx and switch it to mesa.

Desktop mode is effectively broken out of the box and Big picture mode will not run in software mode so if you want to run the desktop you have to change it back and forth every time.

**Comment by ProfessorKaos64** [comment]
This is a [known issue](https://www.reddit.com/r/Steam/comments/3b4oxj/introducing_steamos_brewmaster/) 

>Known Issues * Initial splash screen is black on hybrid graphics (both NVIDIA and Intel graphics) systems * On the second boot of the installation process, AMD systems will display an "Oh No! Something has gone wrong" screen. Leave it alone and installation will continue normally. * Desktop mode on AMD systems does not work, you will just get an "Oh No! Something has gone wrong" screen.

That is taken from the brewmaster release post (pinned).

**Comment by FireCulex** [comment]
@ProfessorKaos64 It happens upon first time installation before SteamOS actually updates. I found reference to this problem on reddit back in April 10th of 2014. Might I suggest that at the very least, mesa-diverted be the default driver on first boot installation so it can update without confusion?
