### ISSUE TITLE
Cant load ICC profiles

### ISSUE THREAD

**Issue by FireCulex** [ValveSoftware/SteamOS#440]
My Laptop monitor is extremely blue, Adding a Icc profile by way of xcalib or dispwin in the /usr/bin/steamos-session, .xsession, or .xinitrc yields no results.Profile gets loaded as can be confirmed by verifying the Video LUT, however the display does not change. fglrx module. 

In mesa-diverted gnome desktop mode nothing works either. The gnome-color-manager changes nothing.

**Comment by FireCulex** [comment]
Well after several hours of trying i figured it out suddenly. It was a permissions issue, steam doesn't have access to the desktop directory. chmod's the icm's to 777 and it suddenly worked.

closed.

**Comment by ProfessorKaos64** [comment]
I wouldn't suggest just adding 777 mode to files. It was either a case of the steam user not having permissions, or a bit missing to execute/read. The SteamOS BPM session runs as the user "steam," the desktop session as the user "desktop."
