### ISSUE TITLE
Time is incorrect

### ISSUE THREAD

**Issue by FireCulex** [ValveSoftware/SteamOS#441]
I set the Timezone to PST. However timedatecontrol shows UTC to actually be the correct time 5am, while local time is showing 9pm, the same in the SteamOS interface. Switched it to dublin to show the correct time. I assume the interface updates after reboot only. This is a dual boot laptop.

**Comment by Tele42** [comment]
By default, windows sets the hardware clock to the local timezone, not UTC, which linux uses by default. Windows is causing the trouble, not SteamOS. See https://wiki.archlinux.org/index.php/Time#UTC_in_Windows for more details.

**Comment by ProfessorKaos64** [comment]
#431 , same issue? duplicate issue?

**Comment by FireCulex** [comment]
I think you don't understand, what Windows are you talking about?

**Comment by Tele42** [comment]
"This is a dual boot laptop" usually implies windows + linux.
