### ISSUE TITLE
Black screen then reboot loop

### ISSUE THREAD

**Issue by FireCulex** [ValveSoftware/SteamOS#446]
I tried to install XFCE4 as the default window manager but failed horribly. I tried to configure it switching the autologin user but now it just reboots endlessly.

Went into recovery mode and removed xfce4 and everything else but nothing has changed. Restored lightdm.conf and update-alternatives, nothing changed.  There's nothing in the logs and it boots before I can get an ssh session going. I removed flgrx-driver and still nothing different. Don't know what else to do

**Comment by ProfessorKaos64** [comment]
Perform a system recovery from the grub menu. Is this a bug? It seems to be outside the stock experience. Also, please include system specifics (see contributing.md in the git root here), most importantly your hardware and steps to reproduce. How did you install/apply/etc.

**Comment by FireCulex** [comment]
running /usr/bin/steamos-autorepair.sh corrected the issue.
