### ISSUE TITLE
[Patch] When connected, prefer external HDMI or DP output to internal panel

### ISSUE THREAD

**Issue by Coucouf** [ValveSoftware/SteamOS#447]
Currently SteamOS systematically defaults to using the first output reported by xrandr, which will usually be internal LVDS or eDP panel when the computer has one.
Plugging an external monitor over HDMI or display port has no effect and is always disabled on steam-compositor startup.

This patch improves output auto-detection.
When several outputs are connected, it will prefer HDMI, then DP, then default to the first output reported by xrandr as was before.

It doesn’t otherwise change behavior (like trying to support multi screen configurations…), and still uses one single output while disabling others.
Only the selection of the « on » display is improved.

**Comment by Coucouf** [comment]
https://gist.github.com/Coucouf/42d2167cd282addc008d

**Comment by Coucouf** [comment]
Complete script file to replace /usr/bin/steamos/set_hd_mode.sh:
https://gist.github.com/Coucouf/e4cd93b070c5ef1487a4

**Comment by littlegamer87** [comment]
Any chance this gets committed? People are still reporting issues
http://steamcommunity.com/groups/steamuniverse/discussions/1/392184289303111596/

**Comment by Plagman** [comment]
This is included in the new 2.67 beta update. Thanks!
