### ISSUE TITLE
Powering off display causes logout of BPM

### ISSUE THREAD

**Issue by TierraDelFuego** [ValveSoftware/SteamOS#450]
I have experienced this multiple times now on different brewmaster versions.  Here is the scenario.
1. Large updates for games start downloading
2. leave steam machine running
3. shut off the display power
4. come back later to find steamos waiting for a user to log in to BPM

The work-around I have used is to select one of the downloads and leave the display power on. The updates to the download progress bar seems to provide the acitivity to keep the display from powering itself down.

May need to have multiple accounts on the steam machine as well but not certain.

**Comment by brain-anti-freeze** [comment]
I have noticed that if you power the machine on without turning the display
on then it does not boot in to the OS but appears to boot loop (based on
the entries in /var/log/messages) but does successfully start BPM once you
connect the display.

**Comment by TierraDelFuego** [comment]
@brain-anti-freeze you should consider filing a separate issue with your information. They may or may not be related. Best to let valve folks determine that.

**Comment by brain-anti-freeze** [comment]
@TierraDelFuego thanks - I've logged #455

**Comment by TierraDelFuego** [comment]
No longer have access to a steamos rig.
