### ISSUE TITLE
Going "back" does not have any effect in Big Picture Mode

### ISSUE THREAD

**Issue by embik** [ValveSoftware/SteamOS#451]
After searching the bug tracker for anything recent, I'd like to open a bug report. I'm running a fresh installation of `brewmaster` on my system (CPU: Intel i5-4670, GPU: Gainward GeForce GTX 770 Phantom). It's up-to-date as of today.

I noticed I cannot go "back", i.e. return to the previous page in Big Picture Mode. Neither the arrow in the top-left corner nor the "back" button placed on some pages have any effect. I suspect pressing the escape key should have a similar functionality, but there's nothing happening as well. I can go back to the main page by clicking the Steam logo in the top-left corner though.

I have absolutely no idea how to debug this issue, but I'm happy to provide any information that might be of use.

**Comment by johnv-valve** [comment]
Do you have a controller attached? There were some navigation bugs if you didn't have a controller attached but it should be fixed at least in the client beta.

**Comment by embik** [comment]
I have no controllers attached.
