### ISSUE TITLE
360 gamepad controls mouse for Metro apps

### ISSUE THREAD

**Issue by BlinksTale** [ValveSoftware/SteamOS#468]
Streaming Windows 10 metro apps treats gamepad input as a mouse. Great for Solitaire, notsomuch for Minecraft Win 10 ed. 

Only testing on Steam Link, but I imagine this is relevant for SteamOS too. Apologies if wrong to post this here.

**Comment by not83** [comment]
I think this is a streaming issue, not one with SteamOS

**Comment by BlinksTale** [comment]
Is there a Streaming issue tracker I can post this on then? Just trying to bring some light to it.

**Comment by BlinksTale** [comment]
Moved to SteamLink issues, closing this one.

https://github.com/ValveSoftware/steamlink-sdk/issues/8
