### ISSUE TITLE
SteamOS locks up when clicking the 'Bluetooth' setting

### ISSUE THREAD

**Issue by not83** [ValveSoftware/SteamOS#470]
When I boot into SteamOS all is fine.

When I go to my system settings all is fine.

As soon as I click on the settings option "Bluetooth" my system is then unusable. The mouse moves but nothing else works.

I have to reboot in order to use the system again.

Specs: Steam Client built:
	Jan 14 2016, at 18:46:58
Steam versions
	1452827987
Steam API
	v017
SteamOS version
	SteamOS 2.0 update 1:2.60

CPU vendor
	GenuineIntel
CPU clock
	3.60GHz
System memory
	7.7GB
Video card
	NVIDIA Corporation GeForce GTX 660 Ti/PCIe/SSE2
Driver version
	4.5.0 NVIDIA 352.55
Video memory
	2.0 GB

**Comment by ekianjo** [comment]
I had the same issue yesterday. Instead of rebooting I waited a very long time and then the interface could be used again. But still, very strange.

**Comment by johnv-valve** [comment]
Can you tell me what kind of hardware you are running on? If you can run 'bluetoothctl' from a terminal window and tell me the output of the 'info' command that will help.

**Comment by ekianjo** [comment]
From my side I do not have any bluetooth hardware at all. I wanted to see what would occur when clicking on the option, and it froze for a while (system became completely unresponsive) until it finally came back to be usable. I think I had to use another controller to make the system usable again, the Steam Controller remained unresponsive at first.

**Comment by not83** [comment]
I too have no Bluetooth hardware

**Comment by johnv-valve** [comment]
With the Jan 20. Steam Client Beta update, the Bluetooth button will no longer show up if you don't have Bluetooth.

If you **do** have Bluetooth and either don't see the button, or the button hangs when you press it, please open a new bug with your detailed hardware description.
