### ISSUE TITLE
Auto-trust plugged in DualShock 3 controllers

### ISSUE THREAD

**Issue by SoulEst** [ValveSoftware/SteamOS#479]
DualShock 3 controllers are not trusted automatically trusted when they are plugged in. This means that users have to pair and trust the controller(s) manually which degrades the user experience a lot. This patch adds that functionality to Bluez:
  
```
--- plugins/sixaxis.c	2015-03-31 09:41:57.000000000 -0400
+++ sixaxis.c	2016-02-06 20:09:26.056396357 -0500
@@ -303,6 +303,7 @@
 	btd_device_set_pnpid(device, devices[index].source, devices[index].vid,
 				devices[index].pid, devices[index].version);
 	btd_device_set_temporary(device, false);
+    btd_device_set_trusted(device, true);
 
 	return true;
  }
```
  
The patch should be downloaded into the bluez code directory and applied with:  
  
```patch -p0 sixaxis.patch```
  
This will set the controller's trusted status to TRUE as soon as they are plugged into the SteamOS powered system and start charging (flashing LEDs). Whenever the user wishes to use that controller with the system again, they merely have to plug it in and wait for the LEDs to start flashing before unplugging it and powering it on by pressing the PS button.

**Comment by Plagman** [comment]
Thanks for the patch; can you describe what the pairing process for a DS3 is before and after the patch?

**Comment by SoulEst** [comment]
These would be steps after connecting the controller via USB to pair the controller:
(Steps are taken from here: https://wiki.gentoo.org/wiki/Sony_DualShock)

Start bluetoothctl:
```user $ bluetoothctl```
Enable the agent and set it as default:
```[bluetooth]# agent on```
```[bluetooth]# default-agent```
Power on the Bluetooth controller, and set it as discoverable and pairable:
```[bluetooth]# power on```
```[bluetooth]# discoverable on```
```[bluetooth]# pairable on```
Connect the DualShock 3 to the system using a USB cable.
Discover the DualShock 3 MAC address:
```[bluetooth]# devices```
Disconnect the USB cable from the DualShock 3:
Allow the service authorization request:
```[agent] Authorize service service_uuid (yes/no): yes```
Trust the DualShock 3:
```[bluetooth]# trust device_mac_address```
The DualShock 3 is now paired:
```[bluetooth]# quit```

These steps must be done when first pairing and trusting the controllers. With the patch, the steps would be:

Connect the DualShock 3 to the system using a USB cable and wait the LEDs to start blinking.
Disconnect the controller and press the PlayStation button.

It may be possible that the PlayStation has to be pressed when the controller is connected via USB. This has not been the case with the five official DualShock 3 controllers that I have test thus far.

**Comment by johnv-valve** [comment]
shipped in 2.64 http://steamcommunity.com/groups/steamuniverse/discussions/1/412448158143021403

**Comment by SoulEst** [comment]
Thank you and glad to be of help.

**Comment by fmiceli24** [comment]
I have the following problem with the DualShock 3 controller:

Although I could pair it without sixad or sixpair. Just using the bluetooth menu on BPM worked. It gets recognized as a PS3 Bluetooth controller.

After I map the buttons and save the config, the name of the config gets applied to the controller.

After rebooting the DS3 pairs after pressing the PS button but the mappings are gone.

On the plus side I could connect the PS3 Keypad without issues.

Should I open a separate issue for this?

**Comment by SoulEst** [comment]
Yes you should. This issue is closed and as such, most likely isn't subscribed to by a Valve Software member anymore.
