### ISSUE TITLE
Brewmaster 2.63 breaks XCOM Enemy Within

### ISSUE THREAD

**Issue by tyleulen** [ValveSoftware/SteamOS#485]
After installing the 2.63 update I can no longer play XCOM EW, I can hear the opening cinematics in the background, but the screen never changes from the three oscillating loading bars.  If I push the Steam button on the controller while the sounds are playing, it crashes back to the Library, if I wait until the sounds stop, then it becomes completely unresponsive and needs to be hard rebooted.

**Comment by Tele42** [comment]
If you are using the steam beta client on steamos, this is a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/4326 which just came in.

**Comment by tyleulen** [comment]
Yes, it is beta client, thanks

**Comment by ProfessorKaos64** [comment]
This is broken in general, XCOM under both launchable titles. Confirmed here as well. Latest OS and client beta.

**Comment by johnv-valve** [comment]
dupe of https://github.com/ValveSoftware/steam-for-linux/issues/4326
