### ISSUE TITLE
Overlay in Team Fortress 2

### ISSUE THREAD

**Issue by Kengur8** [ValveSoftware/SteamOS#491]
Fedora 23/Gnome/radeon oss

* Steam client version: 1.0.0.51-1.fc23
* Opted into Steam client beta?: y

In steam settings UNCHECKED "Enable overlay". In Team Fortress 2 properties UNCHECK "Enable overlay". Playing Team Fortress 2 full screen mode native client.

Steam group events still cause messages to pop-up. Gnome desktop reacts by drawing a notification window may be? Desktop fall though at the top of the screen for a couple of seconds.

**Comment by ProfessorKaos64** [comment]
> Fedora 23/Gnome/radeon oss

This bug tracker is for SteamOS.

https://github.com/ValveSoftware/SteamOS#reporting-issues

**Comment by Kengur8** [comment]
Ok, gona report it on https://github.com/ValveSoftware/steam-for-linux/issues/4343
