### ISSUE TITLE
Crashes when using the library from the download home button

### ISSUE THREAD

**Issue by VaysseB** [ValveSoftware/SteamOS#492]
#### Your system information

* Steam client version: 04 march 2016 13:51:54
* Steam version: 1457138872
* SteamOS version: 2.0 update 1:2.64
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: No (I'm don't think so)
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I was looking at Cities Skyline game in my library, and I was going back to the game list by pressing the button "b" on the Steam Controller, but the GUI crashes and restarts.
But I found one way that crashes and another that don't.

#### Steps for reproducing this issue:

1. From the home, click on the download button (in the top bar).
2. From the current item "Download", move up on "Game" and select it.
3. Select a installed or non installed game (I tested it, it doesn't matter, neither does filtering, tested it also)
4. Press the button "b" on the Steam Controller (to go back) and that's it. The GUI should freeze and then it restarts.

This bug doesn't appear if I click directly from on "Library" in the home (a.k.a. if I didn't use the download action from the home).

**Comment by subdiff** [comment]
I can confirm this issue. Also on Beta Client.

**Comment by VaysseB** [comment]
It seems to be fixed now (april 03 2016).
* Steam client version:  1459555796 (apr 1 2016 21:10:30)
* SteamOS version: 2.0 update 1:2.64
