### ISSUE TITLE
Exit to Desktop / Desktop Mode broken in latest Client Beta.

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#506]
#### Your system information

* Steam client version: Mar 21, 2016 / 19:34:26
* SteamOS version:  2.0 update 1:2.64
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]
* GPU: Nvidia GTX 770

#### Please describe your issue in as much detail as possible:
After a system restore, I have narrowed down the beta client is giving me issues switching to desktop mode. the desktop flashes for a moment with the full desktop, then goes black. This was only the case after I switched to the client beta. 

* [stdout](https://gist.github.com/ProfessorKaos64/69d4030075f95448eeeb)
* [dmesg](https://gist.github.com/ProfessorKaos64/6205e185b273beb30ba5)
* [Xorg.0.log](https://gist.github.com/ProfessorKaos64/4cb1a225fd87b90d2da3)

Please let me know what specific logs you may want.
#### Steps for reproducing this issue:

1. Enable or disable Steam Client beta
2. Exit to desktop

**Comment by sharkwouter** [comment]
I don't have this issue on my machine.

Can you try pressing Ctrl+Alt+F4, logging in as the user desktop and starting the desktop like this:

`xinit /usr/bin/gnome-session -- :2`

**Comment by ProfessorKaos64** [comment]
Must have been fixed in the last update possibly. I no longer have the issue.
