### ISSUE TITLE
AutoAddGPU setting from /usr/share/X11/xorg.conf.d broke nvidia optimus

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/SteamOS#507]
Up-to-date steamOS beta as of today

nvidia optimus broke (with intel iGFX).

To fix it I had to remove AutoAddGPU setting from /usr/share/X11/xorg.conf.d and use Xorg default value.

**Comment by ProfessorKaos64** [comment]
Wonder if this is related to the new code that prefers HDMI connections (related to laptops choosing a primary display).

**Comment by Zenitur** [comment]
Prove that! A second file added by developers, 55-nvidia-steam.conf, is broking Optimus too! Before removing this file, I saw black screen. "xrandr --listproviders" show only "NVIDIA-0" device and no "modesetting" (the Intel GPU). Removing 55-nvidia-steam.conf fix the problem

I'm using PRIME, not Bumblebee. xorg.conf from there: ftp://download.nvidia.com/XFree86/Linux-x86_64/355.11/README/randr14.html (SteamOS have Xorg 1.16 so I select an old config) lightdm.conf parameters from there: https://wiki.archlinux.org/index.php/NVIDIA_Optimus#LightDM

**Comment by sylware** [comment]
The video output switcher manager hardware should have been properly defined as simple standard ACPI device (no common frame buffer because of the use case of discret GPU and their dedicated vram).
This is an EPIC fail from the hardware industry.
