### ISSUE TITLE
Build dependencies for packages are not included in the SteamOS repo

### ISSUE THREAD

**Issue by sharkwouter** [ValveSoftware/SteamOS#508]
I just tried to see if I can build SteamOS packages on SteamOS with out modifications. To my surprise, doing this is currently not possible.

To be able to build Debian/SteamOS packages, you'll need a few things:

1. The dpkg-dev package for making apt able to download source files, which is in the repo.
2. The fakeroot package for making apt able to build packages, which is missing.
3. Preferably the devscripts package, since it has some nice tools building and changing packages. Also not available in the SteamOS repo.
4. The source package of what you want to build, these are easily downloadable with apt-get source after installing dpkg-dev.
5. The build dependencies for the package you are trying to build. These are not available in the Steam repo for most of the packages I've tried. I could download them for zip and unzip, but not for over 30 other packages.

Unfortunately 2 and 5 prevent you from building any package right now, while 3 is annoying. After installing fakeroot from the Debian repo I was able to build the zip package, but without downloading even more packages from the Debian repo, that is all.

The process I use for building packages from source packages works like this:

1. apt-get source zip
2. sudo apt-get build-dep zip
3. cd zip-3.0
4. dpkg-buildpackage -us -uc

That is all that would be required on a regular Debian install. If you make changes you'll also have to edit the changelog before building, which is why devscripts is nice. dch makes editing the changelog trivial. On SteamOS most attempts to build a package will fail at step 2, though. All other packages will fail at step 4, since fakeroot is missing.

I feel this should be addressed to make it easier for people to make changes to packages. It would be a lot easier to contribute that way.

**Comment by johnv-valve** [comment]
I added devscripts and fakeroot to the steamos_beta repository (2.68 http://steamcommunity.com/groups/steamuniverse/discussions/1/371919771763831102/)

Other build-deps for specific packages will have to be added on a one-off basis, I can't just add everything. Feel free to open a new issue with additional packages that you think would be useful.
