### ISSUE TITLE
[Request] Add exfat FS driver

### ISSUE THREAD

**Issue by Zenitur** [ValveSoftware/SteamOS#528]
# Description

_Sorry for mistakes - an English isn't my native language, and I'm not the GlaDOS to learn it fast._ There are several realizations of Microsoft Exfat filesystem:

1). Exfat-fuse, it's it Debian repository
2). Exfat-nofuse, a fork of Samsung-exfat
3). Samsung-exfat - written for Android devices, but also work on desktops. I think it was written by specs provided by Microsoft
4). Shareware realizations by Tuxera and Paragon, designed for embedded systems

I can't prove it, but Samsung-exfat is more stable than it's fork. I prefer that. But Samsung is trying to hide their driver! If you search "exfat" in http://opensource.samsung.com/, you will find a version for 3.8 kernel. If you search "SM-G935F" you can download 3.18 kernel source with Samsung patches, including the last exfat driver!

There is it: https://yadi.sk/d/L1CA6BqwrhSMo I successfully install it in SteamOS 2.0 with 4.1.0 kernel! How am I doing that:

```
$ tar xf exfat-1.2.19.tar.gz
$ cd exfat-1.2.19
... Apply these two patches:
https://github.com/dorimanx/exfat-nofuse/commit/4dbbb389711fd966dda7cc8b9a14ac4b76976d6d
https://github.com/dorimanx/exfat-nofuse/commit/d2faf3226283c48a14d0c91bed108d685e473fb7
...
$ make
$ su
Password:
# mkdir /lib/modules/`uname -r`/kernel/fs/exfat
# cp *.ko /lib/modules/`uname -r`/kernel/fs/exfat
# depmod -a
# modprobe exfat_core
# modprobe exfat_fs
# mkdir /mnt/exfat
# mount -t exfat /dev/sdb1 -o rw,uid=1000,gid=1000,dmask=0002,fmask=0003 /mnt/exfat
# exit
$
```

To mount your flash drive with correct rules, I'm using an options got there: https://wiki.debian.org/NTFS It assign all flash drive files for the first user in system ("desktop" in SteamOS 2.0)
# What am I want from SteamOS developers?

1). **Find out whether it is legally possible. 70% Android devices manufacturers are paid royalty for using FAT32, before court annulled the patent.**
2). Select exfat realization between FUSE, kernel driver, and the fork.
3). Make udev script with correct mount options
4). Make DEB-package with DKMS support
5). Include that in SteamOS!

**Comment by not83** [comment]
Sorry but what would a lounge gaming is need this for?

**Comment by Zenitur** [comment]
**not83**, for music from flash drive

**Comment by AndyLavr** [comment]
Linux non-fuse read/write kernel driver for exFat and vFat file systems (Full adaptation to kernel 4.19.y) 

https://github.com/AndyLavr/exfat-nofuse

**Comment by tommy4st** [comment]
Because Steam OS is based on Debian Jessie you can try this:
```shell
wget http://ftp.us.debian.org/debian/pool/main/f/fuse-exfat/exfat-fuse_1.1.0-2+deb8u1_amd64.deb
sudo dpkg -i exfat-fuse_1.1.0-2+deb8u1_amd64.deb
```
Now you can easily mount exFAT volumes :smile:

**Comment by davegorst** [comment]
I'd also like to see this. I have an "Extreme Pro Micro SDXC 2TB" (bought from Amazon - I've tried two) which fails under Linux (and SteamOS - formatting on the Deck fails) unless formatted to exFAT. Firstly I get messages indicating that the backup GPT is corrupt but the primary GPT is OK. Secondly even if I do manage to create a full ext4 partition it fails to mount, with the "wrong fs type or bad superblock etc." message. This occurs both when formatting the whole drive or dd'ing an image of a working 1TB SD card to the drive with the idea of resizing it using parted.

Again this happens both on my Linux laptop ("Linux Mint 21.2 Victoria" with a "6.6.8-1-liquorix-amd64" kernel) or on the Steam Deck itself. I've ordered a "2TB Micro SD TF Card" so will see if that helps, and will try to see if that helps, and will have a look at kludging in exFAT support on the Deck, but supporting exFAT natively would be far preferable.

**Comment by lostgoat** [comment]
@davegorst sadly your card is a fake. There are no readily available real 2TB cards in the consumer market.

Your card only works with exFAT because it has a hacked firmware that will report 2TB of space available even though it only has a much smaller internal storage. And it doesn’t know how to produce the same lie for other filesystems.

You should return the card to Amazon and purchase a different one. And avoid 2TB cards, most likely none of them are real.

**Comment by lostgoat** [comment]
Closing this issue as SteamOS 3 supports exFAT.

**Comment by davegorst** [comment]
Sigh. I suspected as much, but thought I was pretty safe with Amazon. Oh
well, at least I can return it.
