### ISSUE TITLE
[BUG] PS3/DS3 default Bluetooth profile is dysfunctional - very little is mapped at all

### ISSUE THREAD

**Issue by Enigma0** [ValveSoftware/SteamOS#529]
#### Your system information
- Steam client version: latest
- SteamOS version: latest
- Opted into Steam client beta?: [Yes]
- Opted into SteamOS beta?: [Yes]
- Have you checked for updates in Settings > System?: [Yes]
#### Please describe your issue in as much detail as possible:

PS3/DS3 controller's default control scheme is dysfunctional and has very little mapped. I think the only things that work are:
- LS for up/down/left/right navigation (d-pad doesn't work)
- LS click is effectively 'a' or 'Enter'
- RS click is back/escape
#### Steps for reproducing this issue:
1. Plug in a PS3 controller with a USB cable
2. Turn it on
3. Press PS button to connect it/bind it to player 1
4. Unplug controller
5. Repeat step 3
6. PS controller should be paired and using Bluetooth now
7. Attempt to use the controller
8. It won't work well

**Comment by theailer** [comment]
Can confirm

**Comment by zeroedout** [comment]
Me too, same experience here.

**Comment by psychotrome** [comment]
Fixed!
