### ISSUE TITLE
libxapian22 keeps appearing in ready.json for unattended upgrades

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#533]
#### Your system information

* Steam client version: June 23 2016 at 00:51:57
* SteamOS version: 2.0 update 1:2.80
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:

Not sure why unattended-upgrades is trying to bump libapian22, when it is already at the desired version?

```
desktop@steamos:~$ cat /var/run/unattended-upgrades/ready.json 
{
  "autoremovals": [],
  "blacklisted": [],
  "kept_back": [],
  "to_install": {},
  "to_upgrade": {
    "libxapian22": "1.2.19-1+deb8u1"
  },
  "whitelisted": []
}
```

Policy:

```
desktop@steamos:~$ apt-cache policy libxapian22
libxapian22:
  Installed: 1.2.19-1+bsos3
  Candidate: 1.2.19-1+bsos3
  Version table:
     1.2.22-3~bpo8+1 0
        120 http://httpredir.debian.org/debian/ jessie-backports/main amd64 Packages
     1.2.19-1+deb8u1 0
        110 http://httpredir.debian.org/debian/ jessie/main amd64 Packages
 *** 1.2.19-1+bsos3 0
        150 http://repo.steampowered.com/steamos/ brewmaster/main amd64 Packages
        500 http://repo.steampowered.com/steamos/ brewmaster_beta/main amd64 Packages
        100 /var/lib/dpkg/status
```

#### Steps for reproducing this issue:

1. Remove libxapian22
2. Install it
3. Check for SteamOS updates

**Comment by johnv-valve** [comment]
Based on your output, you've added Debian jessie & jessie-backports repositories and jessie-backports has a newer version.

**Comment by ProfessorKaos64** [comment]
I actually think this was a possible misconfiguration of my unatteneded upgrades file. Tested now, without issues if forcing the new configuration file from my packages , rather than using other options to potentially keep the old conf file. For now, cut out jessie-backports, and will re-nable if the next OS update goes cleanly.
