### ISSUE TITLE
Add firmware for Killer 1535 wireless module

### ISSUE THREAD

**Issue by twooden** [ValveSoftware/SteamOS#539]
#### Your system information

* Steam client version: 
* SteamOS version:  2.70
* Opted into Steam client beta?:  No
* Opted into SteamOS beta?:  No
* Have you checked for updates in Settings > System?:  Yes

#### Please describe your issue in as much detail as possible:
th10k driver is present in the current steamOS kernel, but the necessary firmware files are missing. 

#### Steps for reproducing this issue:

1. Load Steam OS on platform with Killer 1535 Wireless.

#### Additional Information:
We have verified these steps work to have a Killer 1535 Wireless module work with a clean install of Brewmaster 2.70

Download:
http://www.killernetworking.com/support/K1535_Debian/board.bin
and put it in the /lib/firmware/ath10k/QCA6174/hw3.0/ folder (create the folder if it doesn’t exist)

Download:
http://www.killernetworking.com/support/K1535_Debian/firmware-4.bin
and put it in the /lib/firmware/ath10k/QCA6174/hw3.0/ folder as firmware-4.bin.

Create config file with:

sudo nano /etc/modprobe.d/ath10k.conf

and put the following contents into the file: options ath10k_core skip_otp=y

Reboot.

If a different method is preferred/verified, we would be fine with that as well.

Thanks,
Thomas
Rivet Networks

**Comment by ProfessorKaos64** [comment]
@twooden , if this issue does not receive attention after some time, I would be happen to host a Debian package containing the necessary files. Valve has their own internal bug tracker (on JIRA I believe), and copies issues to that tracker. This is straightforward enough that I think they will see it.

**Comment by twooden** [comment]
After checking, I found that in fact Killer 1535 Boarddata has already included in the linux firmware repository: 
http://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/log/ath10k/QCA6174/hw3.0/board-2.bin 
 
board-2.bin is a collection of multiple board data files with corresponding HWID information, and currently Killer 1535 BDF is already included.

**Comment by johnv-valve** [comment]
This is in the beta that just shipped http://steamcommunity.com/groups/steamuniverse/discussions/1/361798516939144943/?tscn=1471479888

**Comment by twooden** [comment]
Firmware was added, but not the ath10k.conf.

installed clean SteamOS and updated to brewmaster_beta 2.88, but still needed to create ath10k.conf with options ath10k_core skip_otp=y for the modules to load.
