### ISSUE TITLE
Missing firmware

### ISSUE THREAD

**Issue by STEPHEN-GOLDBOROUGH** [ValveSoftware/SteamOS#541]
#### Your system information
- Steam client version:
- SteamOS version: SteamOSDVD current
- Opted into Steam client beta?: [No] 
- Opted into SteamOS beta?: [Yes] 
- Have you checked for updates in Settings > System?: [N/a]
#### Please describe your issue in as much detail as possible:

Installation process asked for missing file rtl_nic/rt18168e-2.fw
However, installation was able  to flow on after this point.

Hardware is ASRock ION3D barebones with Realtek PCIe GBE Family Controller (network card) on board.
#### Steps for reproducing this issue:
1. 
2. 
3.

**Comment by ProfessorKaos64** [comment]
Try installing the realtek firmware package from Jessie:

https://packages.debian.org/jessie/firmware-realtek

**Comment by johnv-valve** [comment]
This should be there as of SteamOS beta 115
