### ISSUE TITLE
During installation, after partclone has finished successfuly, the system does not automatically reboot

### ISSUE THREAD

**Issue by littlegamer87** [ValveSoftware/SteamOS#545]
#### Your system information

* Steam client version: N/A
* SteamOS version: 2.87 ZIP
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: No

#### Please describe your issue in as much detail as possible:
During installation, after partclone has finished successfuly, the user is given a menu with five options (I think). The default option is to enter a shell, which is wrong. The correct option is the one above that, which is to reboot the system.

For a smooth installation experience, this menu shouldn't exist. The system should just reboot.

#### Steps for reproducing this issue:

1. Install SteamOS Express
2. Wait until partclone has successfully finished

**Comment by ProfessorKaos64** [comment]
This has been this way forever, since the dawn of the OS. I can't imagine it's a difficult thing to fix. I wonder if I can locate the config for this and find out. There is no issue on restoring the image and auto-rebooting, so I can't imagine it wouldn't work.

**Comment by ProfessorKaos64** [comment]
I see the entries in /boot/grub/grub.cfg, but i'm unsure how they are injected there. Presumably, that may be from the SteamOS base files package. The parameters for partclone, namely `ocs_live_run` is missing the `reboot` parameter it seems. I'm curious to see if that's all it takes.

**Comment by johnv-valve** [comment]
This behavior is intentional as it allows the OEM to install the system and then image the disk for cloning onto other machines. If the system just reboots then there is no opportunity for that (unless you happen to catch it just before it automatically reboots)
