### ISSUE TITLE
Lightdm fail, recovering loop

### ISSUE THREAD

**Issue by cosmo-ray** [ValveSoftware/SteamOS#551]
#### Your system information

* Steam client version: No idea my steamos creash after the last update(so I guess the lastest)...
* SteamOS version: steamos 4.1.0-0.steamos.25-amd64 #1 SMP Debian 4.1.13-0+steamos5 (2016-05-19) x86_64
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: if I could...

#### Please describe your issue in as much detail as possible:
My SteamOS get an update, crash and now is making a Fatal Error -> recovering loop.

but if I log into a virtual terminal, sudo pkill steam -> startx, steamos load gnome3 normally. so everything sems to work exept that lightdm fail...

I have install some random package from debian repository and so the problem may be mine but:

is there a way to limitate the recovering loop ?
I mean once steamOS have fail 2 or 3 time to recovering the system automatically, 
we should have the posibility to debug the problem ourself with a terminal, or just a windows that help us to reinstall to system, because ther's no poit to keep using the recovering script once he have fail.

here is my  /var/log/lightdm/lightdm.log: http://pastebin.com/aFRvJ99C

but the log don't show any error...
Any  idea why lightdm fail ?

#### Steps for reproducing this issue:

1. break your lightdm
2. get a recovering loop 

Thanks

**Comment by ProfessorKaos64** [comment]
See if any of theses steps from the wiki helps:

https://github.com/ValveSoftware/SteamOS/wiki/Troubleshooting#what-to-do-if-you-cannot-start-steamos

**Comment by cosmo-ray** [comment]
Ok I've fix it thanks:

I've just make ```sudo -u steam steam```, which have update the steam client, and make lightdm able to start steam again I guess :)

But souldn't the recovery script update the steam client ? should I open a new issue about that ?

**Comment by ProfessorKaos64** [comment]
Search the latest tickets. I have the request already entered. 

On August 11, 2016 7:40:52 PM EDT, Matthias Gatto <notifications@github.com> wrote:
>Ok I've fix it thanks:
>
>I've just make ```sudo -u steam steam```, which have update the steam
>client, and make lightdm able to start steam again I guess :)
>
>But souldn't the recovery script update the steam client ? should I
>open a new issue about that ?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ValveSoftware/SteamOS/issues/551#issuecomment-239325812

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
