### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by keynan** [ValveSoftware/SteamOS#552]
Running steam on Windows 10 pro, I upgraded to Win10 EDU. This erased several game saves including dozens of hours into DarkSouls 2.

After spending near 30 hours to run back to the point in game I attempted to use Steams backup feature. However, the client said 18+GB was nessacery. 

While I'm quite glad you have a way to backup The Game, I want a way to backup just the save data.

Cheers

**Comment by ProfessorKaos64** [comment]
The has nothing to do with SteamOS. Please close and open a bug in an appropriate place, such as:

https://steamcommunity.com/discussions/forum/1/

**Comment by keynan** [comment]
Sorry, this was looked like the most appropriate place of the two dozen github repos, anyway thx for the link
