### ISSUE TITLE
Fatal error / Not recovering 

### ISSUE THREAD

**Issue by burnsdrg** [ValveSoftware/SteamOS#556]
#### Your system information

* Steam client version: last official beta version
* SteamOS version: Last official beta version
* Opted into Steam client beta?: [Yes/No] Not sure
* Opted into SteamOS beta?: [Yes/No] Yes
* Have you checked for updates in Settings > System?: [Yes/No] Before updating SteamOs, yes.

#### Please describe your issue in as much detail 
SteamOs is trying to recover from a fatal error
Even after that finishes, it will reboot again with the same message. I already made a diagnosis job on my alienware steam machine and hardware is perfectly fine. I downloaded SteamOs from the official steam site, put the OS on a usb fat32 after formating it, i connected it to my machine and booted from my usb device. SteamOs was installing again. It finished and after that, i get the same fatal error message. I cant fix it with my steam controller recovery option, nor the boot usb OS installation.

I read in some posts that it may be an issue with the beta update, so im downloading the version before the beta. Any help would be really appreciated since this is driving me nuts and i dont really understand much about this.

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by burnsdrg** [comment]
I dont even know much about this... its driving me nuts.

**Comment by burnsdrg** [comment]
I read in some posts that it may be an issue with the beta update, so im downloading the version before the beta. Any help would be really appreciated since this is driving me nuts.

**Comment by burnsdrg** [comment]
OKAY EVERYBODY... I FOUND THE SOLUTION!! :dancer: 
For those having problems, this was the easiest way out :

 DownloadSteamOsInstaller.zip From June of 2015 
This is the link i got it from : http://repo.steamstatic.com/download/alchemist/

Format your USB drive and extract all files in it

Enter F12 to get access to boot menu
Select UEFI BOOT from USB 
Make sure you format all partitions.

Reboot and remove usb, keyboard and mouse

Steam will update but it will let you access and log in again.

I want to mention that i also unchecked auto log in in the middle of the installation where you get access to desktop mode.

**Comment by ProfessorKaos64** [comment]
So your solution was to reinstall SteamOS, steps and info which is on the wiki? Also Alchemist is not supported. Brewmaster is. I do not suggest this.

**Comment by burnsdrg** [comment]
Yeah, its still running with no problems. all good. It may help some people but they can discard this option if they want. thanks for replying man. i think i will consider this thread as closed
