### ISSUE TITLE
[Package issue] libssl1.0.0 is too old, please merge Debian Jessie upstream version

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#557]
#### Your system information

* Steam client version:
* SteamOS version: 2.87
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:

Please reference the posts I made over at [lgogdownloader](https://github.com/Sude-/lgogdownloader/issues/77). The version of SSL installed on SteamOS does not process the local issuer certificate correctly. This was tested on a VPS of Debian 8.5 from Digital Ocean, and SteamOS Brewmaster.

#### Steps for reproducing this issue:

1.  Compile lgogdownlaoder
2.  `lgogdownloader --login --verbose` (fails)
3.  Install current upstream `openssl` package
4.  `lgogdownloader --login --verbose` (successful)

 I initially thought the version of `openssl` was the case, but noticed that downgrading this package on Debian 8.5 and ensuring `ca-certificates` worked. It was only when I downgraded `libssl1.0.0` things broke. When I updated both `openssl` and `libssl1.0.0` on SteamOS, everything worked.

Jessie has the updated version,

```
jessie (stable) (libs): Secure Sockets Layer toolkit - shared libraries 
1.0.1t-1+deb8u2: amd64 arm64 armel armhf i386 mips mipsel powerpc ppc64el s390x
```

**Comment by ProfessorKaos64** [comment]
Err, not the issue. sorry. Strange.

**Comment by johnv-valve** [comment]
This is updated in brewmaster 2.93 http://steamcommunity.com/groups/steamuniverse/discussions/1/350542683209165400/
