### ISSUE TITLE
"update-glx --config glx" to mesa-diverted broken

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/SteamOS#559]
Fresh install of beta SteamOS, with beta client.
GFX: AMD HD7970
Everything up-to-date.

I added password to the desktop account in order to switch from catalyst to mesa with update-glx:
It broke SteamOS.
(because mesa seems quite faster than catalyst in many games, for instance dota2)

**Comment by ProfessorKaos64** [comment]
This isn't broken. I have a system only using an integrated Intel GPU and mesa. If you are modifying the update graphics script, that isn't really supported. Have you testing manual commands on another system to compare these actions/results?  Can you post your commands/ update modifications? Mesa is only 10.6.3 on both stable/testing OS branches. Are you also sure that Mesa supports that card? Seems like an older card.

**Comment by sylware** [comment]
Did a bit of investigation: the AMD PRO driver debian packages broke dpkg dependencies related to mesa. Then it seems mesa misses some stuff to work properly.

**Comment by sylware** [comment]
For AMD southern islands GPU hardware, there are 2 stacks.

The current, about to be deprecated:
mesa - radeon linux module (not vulkan enabled)
catalyst (not vulkan enabled)

The recent/about to be enabled (I run already this mesa/x11 on my custom 64bits clean distro):
mesa - amdgpu linux module (not vulkan enabled as of today)
amdgpu pro - amdgpu linux module (vulkan enabled)

**Comment by sylware** [comment]
Tested on a steamOS with AMD catalyst removed. On AMD southern islands, dota2 seems to run quite faster with mesa. Would be a good thing to fix the switching from catalyst to mesa.

**Comment by mtdeguzis** [comment]
If you don't mind, could you add your testing/results to the above wiki page? Likely under some kind of section describing potential solutions/testing.

**Comment by Plagman** [comment]
We're interested in enabling easy switching between Mesa and AMDGPU-PRO in the future. If you have any details on what breaks when just updating the alternative it'd be appreciated.

**Comment by sylware** [comment]
On Mon, Dec 05, 2016 at 10:52:40AM -0800, Pierre-Loup A. Griffais wrote:
> We're interested in enabling easy switching between Mesa and AMDGPU-PRO in
> the future. If you have any details on what breaks when just updating the
> alternative it'd be appreciated.

AMD southern islands GPUs are still using catalyst or mesa. Once linux 4.9 is there,
amdgpu linux module will be available for AMD southern islands and amd pro drivers
will be used instead of catalyst (waiting for open source vulkan support
without c++, i.e. lean software stack).

-- 
Sylvain

**Comment by sylware** [comment]
I did dive in with an up-to-date SteamOS beta.

It seems fixed: I just need to fix the /etc/init.d/update-graphics with mesa-diverted for my AMD GPU, since catalyst is forced for all AMD GPU which are not supported by the AMDGPU PRO driver.

I was even able to set my monitor 144Hz refresh rate with xrandr command in /usr/bin/steamos-session and commenting out the set_hd_mode.sh script.

You should provide for those scripts (you should use SH scripts, not BASH scripts) a small configuration file in /etc in order to force a glx alternative, and to force a xrandr video mode.

**Comment by johnv-valve** [comment]
If you want to send us a suggested patch, we'll take a look at it.

**Comment by sylware** [comment]
In the past, I did provide patches for dota2 and portal2 start bash->sh script. AFAIK, they were ignored.

**Comment by johnv-valve** [comment]
With SteamOS beta release 115, you can drop a script into /etc/update-graphics.d and override the default graphics selection. See /etc/update-graphics.d/00-update
