### ISSUE TITLE
[Feature Request] Pipe / redirect stdout/stderr from auto-repair to log file

### ISSUE THREAD

**Issue by ProfessorKaos64** [ValveSoftware/SteamOS#560]
#### Please describe your issue in as much detail as possible:

IT would be highly helpful to have stdout/stderr from steamos-autorepair.sh piped/redirected to a log under /var/log for review later. I do this manually, but it would be nice not to have to. Reviewing what is going on with this process is much desired for troubleshooting cases. The easiest way is to just encapsulate the script in `main()` and call main piped to the log.

`/var/log/steamos-autorepair.log`

```
# start main
main 2>&1 | tee log.txt
``

**Comment by johnv-valve** [comment]
systemd already does this automatically. Try
    sudo journalctl -u steamos-autorepair.service
