### ISSUE TITLE
Sound input doesn't work out of the box

### ISSUE THREAD

**Issue by ir0n1e** [ValveSoftware/SteamOS#564]
Gentoo 
* Steam client version: Oct 22, 2016 
* SteamAPI v017
*Steam package version 1477096271 
 
The mic input is not working just in Steam and/or Gold Source Games.
Normal input is OK Teamspeak3 input is OK.
uname -a 
 4.4.6-gentoo #27 SMP PREEMPT Sat Oct 29 11:03:14 CEST 2016 x86_64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz GenuineIntel GNU/Linux

**Comment by sir-ragna** [comment]
This is the SteamOS issue tracker. 
I think you are looking for the [Steam for Linux issue tracker](https://github.com/ValveSoftware/steam-for-linux) 

Issue should probably be closed unless Valve is not keeping a strict tracker policy. (I don't make the here.)

**Comment by kisak-valve** [comment]
Let's continue this issue report at https://github.com/ValveSoftware/steam-for-linux/issues/4852.
