### ISSUE TITLE
[RFC]: mesa radeonsi + amdgpu

### ISSUE THREAD

**Issue by victoredwardocallaghan** [ValveSoftware/SteamOS#566]
Hi,

This is just a RFC to gain some thoughts about switching to using mesa's radeonsi userspace implementation for vulkan and opengl on top of amdgpu by default? I suppose in practice this could only happen once our next mesa release is stamped out that will be GL4.5 conformant (we are very close). However I wanted to start the discussion early to see what is needed from the mesa side for this to happen?

Cheers,
Edward.

**Comment by johnv-valve** [comment]
http://steamcommunity.com/groups/steamuniverse/discussions/1/1291817837636983784/
