### ISSUE TITLE
SteamOS Black Screen After Splash

### ISSUE THREAD

**Issue by tommyknows** [ValveSoftware/SteamOS#567]
#### Your system information

* Steam client version: not sure how to check
* SteamOS version: some brewmaster - It should be the latest one.
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: No, don't think so
* Have you checked for updates in Settings > System?: checked over apt-get.

#### Please describe your issue in as much detail as possible:
When I boot my system (a few days ago, everything worked fine), I get to the splash screen. After that, I see the cursor for a second and then it seems like the video / audio output quits. I get a "No signal" on the TV. My graphics card is a MSI GTX 760. I tried debugging but I don't know where to start. When I check the startup log (/var/log/boot.msg) I don't see anything special. I think it has to do something with the Steam Launcher. 
'ps -ef | grep steam' shows nothing. Xorg however seems to be running. Because the system gets relatively loud I checked with "top" what's running and saw that Xorg utilised 99.9%, but the system usage seems to be around 20%. 
I tried to check Xorg but as I'm not an expert I'm not sure if it really works correctly, but it seems like it does...

I already tried apt-get update && apt-get upgrade but it doesn't seem to change anything.
Does anyone have an advice on what to check? Where can I find information about the steam launcher?

#### Steps for reproducing this issue:

1.  Updating your system?

**Comment by Tele42** [comment]
Hello @tommyknows,
I'm curious if xorg's log has any hint at what has gone wrong. it's usually found at or near ```/var/log/Xorg.0.log```.

**Comment by tommyknows** [comment]
Ok, here's my Xorg-logfile:
[Xorg.O.log.txt](https://github.com/ValveSoftware/SteamOS/files/586681/Xorg.O.log.txt)
I've taken it from /var/log/Xorg.0.log.

**Comment by tommyknows** [comment]
@Tele42 also, here is my lightdm logfile:
[lightdm.log.txt](https://github.com/ValveSoftware/SteamOS/files/587408/lightdm.log.txt)
I'm wondering about these lines in the log file:
```
[+0.84s] DEBUG: Session pid=4771: Exited with return value 0
[+0.84s] DEBUG: Seat: Session stopped
[+0.84s] DEBUG: Seat: Stopping display server, no sessions require it
```

**Comment by tommyknows** [comment]
After further digging, I found out that Steam itself crashes on startup. See the attached logfile.
[steam_stdout.txt](https://github.com/ValveSoftware/SteamOS/files/588786/steam_stdout.txt)
And again, the last two lines of the logfile;
```
../steamexe/updateui_gl.cpp (293) : Assertion Failed: UpdateUI CreateGlFont regular failed
../steamexe/main.cpp (525) : Assertion Failed: failed to initialize update status ui, or create initial window```

May this be because of all those erros?
```
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.```

**Comment by Tele42** [comment]
@tommyknows, does the steamos box have the package ttf-dejavu-core? If not, does adding it help? (from https://github.com/ValveSoftware/SteamOS/issues/383#issuecomment-227842862)

**Comment by tommyknows** [comment]
@Tele42 Installed the ttf-dejavu-core, rebooted and now it seems to work again. 
Thank you!
Just out of curiosity, do you know why this can happen?

**Comment by Tele42** [comment]
I do not have enough access to the details to tell you why this occurs. From what I can tell, a a partial or incomplete steam update happened and adding the font package allows steam to get far enough to auto-repair itself.

This issue has been mitigated with the SteamOS 2.88 update.

**Comment by tommyknows** [comment]
ok, thank you for the explanation!
