### ISSUE TITLE
[bug] steamcompmgr repeatedly crashing after steamos update

### ISSUE THREAD

**Issue by deepfire** [ValveSoftware/SteamOS#568]
#### Your system information

* Steam client version: latest brewmaster
* SteamOS version: latest brewmaster
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: yes -- apt-get update && apt-get -f dist-upgrade

The system is a fresh install of today.

#### Please describe your issue in as much detail as possible:
Turning on the computer doesn't lead to a Steam Big Picture interface showing up,
instead:
 - a series of black screens/resolution changes
 - a splashscreen saying "SteamOS is attempting to recover from a fatal error" hangs on for about five minutes
 - a reboot happens
 - things repeat all over.

GPU is NVidia GeForce GTX 780.

#### Steps for reproducing this issue:

1. Install SteamOS
2. Watch it install, boot into desktop, install drivers, take a system partition snapshot 
3. Watch it never completing a boot into the installed system.

**Comment by deepfire** [comment]
Essentially, this is looks and feels like #454 -- except that I had a running system for a long time, and the bug manifested itself about 24 hours ago.  Did a reinstall afterwards to the same effect.

**Comment by deepfire** [comment]
https://github.com/ValveSoftware/SteamOS/wiki/Troubleshooting#autorepair-boot-loop seems related.

**Comment by Tele42** [comment]
Hello @deepfire, are you able to get to /tmp/dumps/steam_stdout.txt? It may have a hint as to what is failing.

**Comment by ProfessorKaos64** [comment]
You didn't try a system restore from the GRUB menu, did you? Hit Esc a few times when booting.

**Comment by deepfire** [comment]
@ProfessorKaos64, I did try both that, as well as a semi-clean reinstall (the 'expert' installation option, keeping `/home` from being formatted).

**Comment by deepfire** [comment]
Apparently some important files somehow became truncated to zero size:
```
total 2632
drwxr-xr-x  8 steam steam    4096 Nov 14 00:43 .
drwxr-xr-x 43 steam steam    4096 Oct 28 14:48 ..
-rw-r--r--  1 steam steam 2641628 Nov 16 12:38 bootstrap.tar.xz
-rw-r--r--  1 steam steam       0 Oct 15 09:47 .crash
drwx------  2 steam steam    4096 Oct  6 16:14 linux32
drwxr-xr-x  2 steam steam    4096 Nov 14 00:43 logs
drwxr-xr-x  2 steam steam    4096 Oct 15 09:47 package
-rw-r--r--  1 steam steam    2048 Apr 13  2016 ssfn8165870550362384340
drwxr-xr-x  7 steam steam   20480 Nov 12 14:12 steamapps
-rw-------  1 steam steam       0 Nov 26  2013 steamdeps.txt
-rw-------  1 steam steam       0 Nov 26  2013 steam_install_agreement.txt
-rwx------  1 steam steam       0 Oct  6 15:32 steam.sh
drwx------  3 steam steam    4096 Oct  6 16:14 ubuntu12_32
drwxr-xr-x  4 steam steam    4096 Apr 13  2016 userdata
```

**Comment by deepfire** [comment]
Ok, this is #383.
