### ISSUE TITLE
Steam os

### ISSUE THREAD

**Issue by itsfredson** [ValveSoftware/SteamOS#570]
#### Your system information

* Steam client version:
* SteamOS version: 
* Opted into Steam client beta?: [Yes/No] 
* Opted into SteamOS beta?: [Yes/No] 
* Have you checked for updates in Settings > System?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by ProfessorKaos64** [comment]
Do you have an actual issue?

**Comment by sir-ragna** [comment]
I suggest closing this one. There are enough tickets in this issue tracker already.
