### ISSUE TITLE
SteamOS on new Alienware i5 steam machine wifi breaks on initial update

### ISSUE THREAD

**Issue by bufke** [ValveSoftware/SteamOS#573]
#### Your system information

* Steam client version: 
* SteamOS version: 2.96
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

I bought a brand new alienware steam machine. After updating SteamOS, wifi failed. I was able to fix this [these](http://unix.stackexchange.com/a/276879) instructions of copying in a .ucode file. 

#### Steps for reproducing this issue:

1. Factory reset Steam Machine
2. Go to Settings > System > check for updates.
3. Run updates and reboot
4. Wifi is no longer working.

**Comment by Plagman** [comment]
This is peculiar, update 2.98 was released to fix exactly this, just after the issue was initially pushed:

http://steamcommunity.com/groups/steamuniverse/discussions/1/154642447914966924/

It should have updated you to that instead. When did this occur?

**Comment by bufke** [comment]
I checked it and it is 2.98. Not sure if I misread it before or if it updated. It certainly wasn't usable for me on Dec 22 without the wifi work around. Wish I could help more, I'd rather not wipe it again to check since it's working.

**Comment by kisak-valve** [comment]
Thanks for retesting @bufke. This should not be an issue for new installations.
