### ISSUE TITLE
SteamOS - some game installations ends with Steam_AppUpdateError_39 

### ISSUE THREAD

**Issue by sir-ragna** [ValveSoftware/SteamOS#575]
#### Your system information

Because I didn't have enough space on my SSD I put the `steamapps/common` folder on a secondary drive that had more space. `/dev/sdb1 on /home/steam/.local/share/Steam/steamapps/common type ext4 (rw,relatime,data=ordred)`. (I double checked the permissoins) Otherwise my SteamOS installation is as standard as it gets.

* Steam client version: 1482202200
* SteamOS version: 2.0 1:2.98
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: [Yes/No]

#### Please describe your issue in as much detail as possible:

Some games fail to install. They download and start installing, until the installation hangs at a certain percentage. (This differs from game to game.)

The following games have this issue.

- Saints Row, The Third
- Saints Row 2
- Deus Ex: Mankind Divided

A number of other games that install just fine are CSGO, Awesomenauts, Bioshock: Infinite, Insurgency.

#### Steps for reproducing this issue:

1. Click on install game for one of the above listed problematic games
2. Wait for the download to finish
3. During installation you'll see the installation hang and after some time the Steam_AppUpdateError_39  will appear.

#### tmp/dumps

See attachments for the log en dump file created during the last time I tried to install Saints Row 2.

**Comment by sir-ragna** [comment]
It seems I cannot attach the log and dump files. Should I upload them somewhere else?

**Comment by kisak-valve** [comment]
Hello @sir-ragna, you can use [gist](https://gist.github.com/) for the logs and compress the minidumps into an archive before drag and dropping them into the comments, however, if only larger games are failing, then you might be maxing out the SSD with the downloads folder (/home/steam/.local/share/Steam/SteamApps/downloading).

**Comment by sir-ragna** [comment]
> you might be maxing out the SSD with the downloads folder (/home/steam/.local/share/Steam/SteamApps/downloading).

This does not appear to be the case.

```
desktop@steamos:~$ df -H / /home /dev/sdb1
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        10G  3.8G  5.7G  40% /
/dev/sda5        88G   21G   63G  25% /home
/dev/sdb1       985G  105G  830G  12% /home/steam/.local/share/Steam/steamapps/common
```

Both Saints Row games are about 7 GB but I have plenty to spare on that account. Plus I managed to install bigger games before. Not to mention that the error happens after the download has already finished. The issue happens during the installation phase.

I managed to loose the dmp because I left it in the tmp folder. But it also seems that not everytime a dump is created. I'll do some more tests over the coming days (insofar my download limit will provide me) and see if it manages to dump again uppon installation.

I did not manage to upload it in a Gist. The iceweazel browser simply keeps giving me an error message that the connection was reset after I try to save the gist file. So I settled for pastebin: http://pastebin.com/TGTbxUUp

**Comment by sir-ragna** [comment]
It seems that one time I got a dump was an exception. I can't reproduce the dumps. Installation still fails though.

I got another paste of steam_stdout.txt http://pastebin.com/gGrbtLyb

**Comment by sir-ragna** [comment]
I managed to collect some dump files.

[dumps.zip](https://github.com/ValveSoftware/SteamOS/files/697073/dumps.zip)

**Comment by kisak-valve** [comment]
For reference, the attached assert and crash minidumps are DUMP_REQUESTED in crashhandler.so, the crash goes a bit deeper than the assert.

**Comment by sir-ragna** [comment]
@kisak-valve is there anything else I can gather from the system that could be useful?

**Comment by kisak-valve** [comment]
@sir-ragna, does moving the entire steamapps folder to the secondary drive make a difference?

**Comment by sir-ragna** [comment]
@kisak-valve Yes!

1 of the 3 games that previously had issues already installed. I'm going to confirm that one more works now before closing this ticket.

Thanks for the support.

**Comment by sir-ragna** [comment]
Great it works now. 

In case you are interested in the current setup.

`/dev/sdb1` is now mounted on `/mnt/datadrive`

`/mnt/datadrive` contains a `steamapps` folder where I copied all original `steamapps` folder contents to.
After that I renamed  `/home/steam/.local/share/Steam/steamapps` to `steamapps.backup` and created a new symlink. `ln -s -T /mnt/datadrive/steamapps /home/steam/.local/share/Steam/steamapps`
