### ISSUE TITLE
[feature request] linux 4.9 for AMD GCN1 gpu open source vulkan support

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/SteamOS#577]
Up-to-date beta steamos
Up-to-date beta client

Saw that mesa 13 got in. Could we get an linux 4.9 kernel for AMD GCN1 GPUs?
Because then AMD GCN1 will run on amdgpu module, hence enabling open source vulkan support from mesa 13.

**Comment by johnv-valve** [comment]
SteamOS beta 115 is now on 4.11 kernel
