### ISSUE TITLE
[ERROR] Bug: soft lockup - CPU#1 [lspci:1441]

### ISSUE THREAD

**Issue by carlosnewmusic** [ValveSoftware/SteamOS#581]
#### Your system information
MSI GS72 6QE ( https://www.msi.com/Laptop/GS72-6QE-Stealth-Pro4K.html#hero-specification )

* Steam client version: ?
* SteamOS version: 2.98

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

#### Steps for reproducing this issue:

1. Select system in grub and issue repeat loop
![image](https://cloud.githubusercontent.com/assets/19379457/22185160/d2e5aebc-e0e0-11e6-940d-358e7053190a.jpg)
![image](https://cloud.githubusercontent.com/assets/19379457/22185235/2b07ee4c-e0e2-11e6-9792-6e07f070a9bd.jpg)

**Comment by carlosnewmusic** [comment]
After being asked by groups specialized in linux, what I have made clear is that the kernel that has SteamOs is not compatible with my processor 😔 

I hope they update the Linux kernel in SteamOs so that the error is fixed both to me and to others who have new or relatively new hardware, or another solution would be to put a module to support the latest intel processors

**Comment by kisak-valve** [comment]
Hello @carlosnewmusic, I agree with this assessment. SteamOS is a derivative of Debian and upstream needs to support your processor in a stable release before it can be picked up for SteamOS.
