### ISSUE TITLE
[update request] - libva

### ISSUE THREAD

**Issue by mdeguzis** [ValveSoftware/SteamOS#585]
#### Your system information

Please update libva1 to jessie-backports level. This backports just fine. Many users enjoy using Kodi on SteamOS, however, the latest version of Kodi relies on libva1 1.7.3. I specially pin Valve's packages for [SteamOS-Tools](https://github.com/mdeguzis/SteamOS-Tools) at a high level (900) so they are not overwritten. I don't want to resort to pinning libva1 specifically. Would you consider updating libva?

https://packages.debian.org/jessie-backports/libva1

**Comment by mdeguzis** [comment]
Seems to be updated now. Closing.

**Comment by mdeguzis** [comment]
nevermind, this is in the beta channel only.

**Comment by johnv-valve** [comment]
http://steamcommunity.com/groups/steamuniverse/discussions/1/1291817837636983784/
