### ISSUE TITLE
[Request] update "Brewmaster iso" to support GTX1050+ installs

### ISSUE THREAD

**Issue by Toetje585** [ValveSoftware/SteamOS#587]
As for now users with an nvidia 1050+ card can't install SteamOS due the outdated nvidia drivers in the install images.

**Comment by mdeguzis** [comment]
This likely isn't going to happen until those drivers hit the stable channel. Beta -> Stable. This would negates the flow of the OS beta channel. I most certainly get the reasoning though.

**Comment by kisak-valve** [comment]
nVidia driver 375.26 is in the current SteamOS brewmaster beta. When the next brewmaster stable bump occurs, this issue should resolve itself.

**Comment by mattdsteele** [comment]
Any estimate when the next stable bump will occur? Is there a release cadence posted somewhere?

**Comment by JanDC** [comment]
+1
I've build a livingroom pc with a gtx1050, but it's been gathering dust for at least 2 months now.

Certainly there is no need to rush a stable release, but a beta build would be nice for those that don't mind untested packages.

**Comment by mdeguzis** [comment]
I believe you can edit the sources lists during an expert install if you hit back. You'll get the standard lost of Debian installer actions.

**Comment by JanDC** [comment]
@mdeguzis I wasn't able to change the sources during the install. 
But installing a regular build with an older supported graphics card did the trick.

After opting in to the beta repos, I made a root snapshot and swapped the old card with the 1050.

This could be a workaround for those having a spare (old) graphics card laying around...

**Comment by mdeguzis** [comment]
Good to hear. I'mm bookmark this if I see others run into the same issue. I'll see if there is anything else that can be done during install, but I doubt it.

**Comment by johnv-valve** [comment]
http://steamcommunity.com/groups/steamuniverse/discussions/1/1291817837636983784/
