### ISSUE TITLE
[Steam Client][OS Windows][Suggestion] Tray click actions

### ISSUE THREAD

**Issue by PowerSteam** [ValveSoftware/SteamOS#588]
#### Your system information

* Steam client version: Last, AutoUpdate
* SteamOS version: windows 7 x64
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] AutoUpdate

#### Please describe your issue in as much detail as possible:
Add custom tray click actions, for double click and tripple click, left and right clicks. Result is 4 capabilities to click, example:
double click left - open steam Library, Main window
double click righ - open Friends window
tripple click left - open Friends window
tripple click right - open steam Downloads, Main window

**Comment by kisak-valve** [comment]
Hello @PowerSteam, this issue tracker is explicitly limited to the linux distribution SteamOS, and is not for general steam feature requests.

Closing as out-of-scope.

**Comment by PowerSteam** [comment]
Where is on github general steam feature requests?

**Comment by kisak-valve** [comment]
General feature requests are not covered in Valve's github issue trackers. The regular forums looks like it has a suggestions section: https://steamcommunity.com/discussions/forum/10/
