### ISSUE TITLE
Latest Steam OS update removes iwlwifi-7265D-13.ucode and iwlwifi-7265-13.ucode

### ISSUE THREAD

**Issue by buckysrevenge** [ValveSoftware/SteamOS#589]
#### Your system information

* Steam client version: Mar 30, 2017, at 22:20:56 (1490914880)
* SteamOS version: 2.0 update 1:2.98
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After upgrading Steam OS on a brand new Alienware Steam Machine R2, the wireless NIC (Intel Dual Band Wireless 3165) was not detected by Steam OS. Running dmesg revealed that the file iwlwifi-7265D-13.ucode was missing from /lib/firmware. Upon looking, the corresponding file iwlwifi-7265-13.ucode was missing as well.
#### Steps for reproducing this issue:

1. Turn on a brand new Alienware Steam Machine R2 (or install their system restore from their website)
2. Run all the updates (Steam Client, reboot, Steam OS, reboot)
3. Wireless card now no longer detected

**Comment by Plagman** [comment]
Opting into the SteamOS Beta repository and downloading update (over a wired network...) 2.110 should fix that.

**Comment by buckysrevenge** [comment]
I found the needed files online, so I'll just wait until the next official release.
