### ISSUE TITLE
[Feature] Easy way to OPT-IN/OUT of using mesa instead of fglrx

### ISSUE THREAD

**Issue by mcharris** [ValveSoftware/SteamOS#591]
#### Your system information

* Steam client version: 1492565509
* SteamOS version: 2.0 update 1:2.110
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I suspect that steamcompmgr is having issues with in-home streaming when using fglrx drivers on AMD HD Radeon 7800.
When streaming from the SteamOS to a device like a Steam Link or Windows Steam client, You are connected and a still image of the desktop shows. You can hear audio, move the mouse, send keystrokes, etc. However the video is still stuck on the initial image. 

#### Steps for reproducing this issue:

1. Run SteamOS using the fglrx drivers
2. Attempt to run in-home streaming using the SteamOS box as the host

#### Non user friendly solutions:
1. Use gnome as window manager and launch bigpicture from within gnome. This eliminates the great features that steamcompmgr offers so this is NOT preferred
2. Force steamos to use the mesa drivers instead of fglrx [(instructions here)](https://github.com/ValveSoftware/SteamOS/wiki/Working-with-display-drivers#running-mesa-drivers-instead-of-fglrx)

**Comment by johnv-valve** [comment]
With SteamOS beta release 115, you can drop a script into /etc/update-graphics.d and override the default graphics selection. See /etc/update-graphics.d/00-update
