### ISSUE TITLE
[Request] Release Beta builds as well

### ISSUE THREAD

**Issue by JanDC** [ValveSoftware/SteamOS#592]
It would be nice for users who would need unreleased (versions of) packages to opt to install a beta build of SteamOS.

In my case (see also #587 ), due my unsupported GTX1050 card, I cannot even install brewmaster to opt in to the beta repos.

I can imagine other use-cases where one would like to install a beta build (testing future releases of packages for example).

Another option is to document build instructions for those willing to create an iso themselves.

**Comment by drlamb** [comment]
I agree with this. Although with the recent stabilization of the big Brewmaster beta, you (and I with my 1080Ti/Ryzen 7) are now able to install SteamOS.

**Comment by johnv-valve** [comment]
I understand your issue, but it is quite a bit of extra work to make this happen for each release. Development, testing, and just the pain of coercing debian-installer into doing something it is ill-suited to doing. It would add a lot of friction to each beta release (on the order of another week) so we are not going to do this any time soon. Maybe we'll revisit if we ever switch to a more flexible install process, but right now the pain far outweighs the benefit.

**Comment by JanDC** [comment]
If it's lots of work, I understand you'd put more priority on other issues.

I guess in term of newer hardware we have to be patient (or be more careful when selecting parts for a steam machine).
