### ISSUE TITLE
libgles1-mesa not updated to latest version in 2.117/2.118

### ISSUE THREAD

**Issue by pierrep** [ValveSoftware/SteamOS#596]
* SteamOS version:  2.118
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Yes 

I was wondering why in the latest beta updates libgles1-mesa has been held back at 13.0.2-3+bsos1 instead of being updated to 17.1.2-1+bsos1 like everything else.

I have a framework I wanted to test on SteamOS and this prevents me from compiling.
I'm using the nvidia driver so I can probably downgrade mesa, but would rather not.

**Comment by johnv-valve** [comment]
This was dropped upstream in 17.0.0~rc3-1 

See https://lists.debian.org/debian-x/2017/02/msg00099.html

Not sure why you would be using ES 1.x on SteamOS?

**Comment by pierrep** [comment]
OK no problem...I only asked because it was already installed on my system.

I'm wanting to build http://openframeworks.cc/ apps on SteamOS. Their setup scripts require gles because the framework targets single board computers. I'll look into building without it. Thanks for the update.

**Comment by kisak-valve** [comment]
Skimming over the openFrameworks github repository, it looks like they have a gles 2 backend which you may be able to use.

**Comment by pierrep** [comment]
It's fine, I got it working with gles1. thanks
