### ISSUE TITLE
Unable to play movies from Store

### ISSUE THREAD

**Issue by mdeguzis** [ValveSoftware/SteamOS#599]
#### Your system information

* Steam client version: 1498083198
* SteamOS version: 1:2:118
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Tried to play Rakka, got this log entry (full attached)
```
ELF class: ELFCLASS32): ignored.
./ubuntu12_64/html5app_steam: symbol lookup error: ./ubuntu12_64/html5app_steam: undefined symbol: SDL_GetGlobalMouseState
```

#### Steps for reproducing this issue:

1. Add Oats > Rakka from Store
2. attempt to play video from Library

Log: http://sprunge.us/fOPL   
Possibly related: https://steamcommunity.com/discussions/forum/1/135512931366974282/

I am not about to just remove libsdl2 though when other packages depend on it. Usually undefined symbols are due to old packages not containing the proper functions/references. or symbols themselves.

**Comment by mdeguzis** [comment]
No luck switching to the stable Steam client.

**Comment by WillWallace** [comment]
From what I can gather the libsdl2 package in the steamos repo needs to be updated to include commands featured in the 2.0.4 version

**Comment by kisak-valve** [comment]
Adding `export STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0` to /home/steam/.xsessionrc is a possible workaround.

**Comment by mdeguzis** [comment]
Ok I'll try that. Question is why is that even needed or why now after so long.

**Comment by kisak-valve** [comment]
@mdeguzis, per "Updated STEAM_RUNTIME_PREFER_HOST_LIBRARIES logic to still prefer Steam Runtime libraries if they are more recent than the host system" in the [2017-07-25](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1447197096908335573) steam beta client, please remove any workaround, opt into the beta client, and retest this issue.

**Comment by mdeguzis** [comment]
I'll retest soon tonight. Thanks @kisak-valve !

**Comment by mdeguzis** [comment]
The video works now, thanks!
