### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by DmitryHetman** [ValveSoftware/SteamOS#600]
#### Your system information

* Steam client version:
any
* SteamOS version: 
any
* Opted into Steam client beta?: [Yes/No] 
no
* Opted into SteamOS beta?: [Yes/No] 
no
* Have you checked for updates in Settings > System?: [Yes/No]
yes
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.
SteamOS must use Wayland display server protocol instead of deprecated X11 (xorg)
#### Steps for reproducing this issue:

1. Install SteamOS
2. Try to launch wayland-app
3. Fail

**Comment by DmitryHetman** [comment]
https://wayland.freedesktop.org/
https://en.wikipedia.org/wiki/Wayland_(display_server_protocol)
https://jan.newmarch.name/Wayland/ProgrammingClient/

**Comment by johnv-valve** [comment]
Supporting Wayland is not a goal of SteamOS. If we add Wayland support it will be because it improves the customer experience in some way.
