### ISSUE TITLE
Time format cannot be changed

### ISSUE THREAD

**Issue by Haefler1985** [ValveSoftware/SteamOS#620]
#### Your system information

* Steam client version: 1511396778 (v017)
* SteamOS version: 42.121 (4.11.12, 2017-07-25)
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Time format in big picture mode cannot be changed. In Germany time format should be 24:00 h clock (military time) not 12:00 hour clock using pm/am, since this cannot be understand by majority of people.

#### Steps for reproducing this issue:

1. Starting steam machine in big picture mode
2. Time is on the right upper format in English format

**Comment by kisak-valve** [comment]
Hello @Haefler1985, this issue is already being tracked at #452. Closing in favor of the existing issue report.
