### ISSUE TITLE
Provide at least nvidia-396 driver

### ISSUE THREAD

**Issue by urandom** [ValveSoftware/SteamOS#635]
#### Your system information

* Steam client version: irrelevant
* SteamOS version: 2.0 Brewmaster 
* Opted into Steam client beta?: irrelevant 
* Opted into SteamOS beta?: yes
* Have you checked for updates in Settings > System?: yes

#### Please describe your issue in as much detail as possible:
The latest nvidia driver provided  by steamos is version 387.22-0+steamos17+bsos2

There's is now at least one game targetting SteamOS that does not work with this outdated driver:
http://store.steampowered.com/app/505540/Rise_of_the_Tomb_Raider_20_Year_Celebration_Pack/

#### Steps for reproducing this issue:
1. Try to play the game
2. There is no step 2

**Comment by baxeno** [comment]
**Rise of the Tomb Raider requirement:**
Nvidia graphics cards require driver version 396.18 or later.

**Latest Nvidia release:**
Linux, Solaris, and FreeBSD driver 396.24 was just released a few hours ago.
https://devtalk.nvidia.com/default/topic/1032986/b/t/post/5255724/#5255724

**Comment by Daddoggety** [comment]
Thanks baxeno, I think urandom already knew that Rise Of The Tomb Raider required Nvidia driver 396.18 or later.  If you used SteamOS you would know that urandom was annoyed that SteamOS uses Nvidia driver 387 and thus can't play ROTTR even though it is available through SteamOS.
 
Now using the SteamOS desktop and the debian, nvidiagraphicsdrivers wiki page, under "building new drivers using SVN" section you can attempt to install the drivers yourself, up to the point of downloading the NVIDIA TAR packages with "debian/rules get-orig-source" command, at which point the i386 package fails to download.

So yes 396.18/396.24 may be advertised as released by NVIDIA but installing it using the debian wiki is another matter unless as urandom is asking, SteamOS release an update with the driver already installed.

**Comment by mdeguzis** [comment]
I hope a new driver would be here by now. I wonder if it would fix the only* game with intermittent broken sound for me (SOMA). Sometimes it works, then it doesn't and turns into a muffled mess. I am using audio via HDMI on the card.

**Comment by baxeno** [comment]
Looks like SteamOS 3.0 (clockwerk) will contain nvidia 396.45 as seen in [beta non-free package list](http://repo.steamstatic.com/steamos/dists/clockwerk_beta/non-free/binary-amd64/Packages).
I am really looking forward to getting this update on my Alienware Steam Machine when promoted to release channel.

**Comment by monreal** [comment]
Why was this closed? The driver is still outdated in SteamOS 2 and SteamOS 3 is nowhere to be seen. The old driver breaks Steam Play in horrible ways...
