### ISSUE TITLE
stuck on login screen on steam machine

### ISSUE THREAD

**Issue by kinglinc** [ValveSoftware/SteamOS#640]
Your system information
Steam client version (build number or date): june 27 2018, at 22:28:22
Distribution (e.g. Ubuntu): ?
Opted into Steam client beta?: [No]
Have you checked for system updates?: [Yes]
Please describe your issue in as much detail as possible:

my steam box no longer allows me to log in. I come to the first login screen on startup where I see my username and picture on the left, "login" in the middle, and beside that to the right is "join".
Clicking my username causes a noise to play -sounds like an error sound- and login is the same.

The only button that does anything is "join" and all it does is show a pop-up that says: "Create Account. Please open a web browser and navigate to store.steampowered.com/join to create your steam account. Then use your new credentials to log in here. "

I can go into settings, but nothing there helps. This happened after the last update, "SteamOS 2.0 update 1:2.148"

I have restored to factory settings, to no avail. I believe it has something to do with the last update, as thats when it stopped letting me login.

**Comment by jacobmartin03** [comment]
Same for me. I have a fresh installation of SteamOS on an external HDD and it's impossible to login. Nothing happens when I click on "Login", I'm stuck on it, I don't understand what's causing this.

**Comment by vdpollm** [comment]
same for me

**Comment by vdpollm** [comment]
https://steamcommunity.com/groups/steamuniverse/discussions/1/1760230157499060571/
with thanks to @dubigrasu for pointing me in the right direction

**Comment by Lyle-Tafoya** [comment]
I believe a fix to this issue was pushed in late August. I am no longer able to reproduce this issue.

**Comment by kisak-valve** [comment]
Is anyone still experiencing this issue?

**Comment by Lyle-Tafoya** [comment]
For reference, here is a post from someone who appears to be a Valve employee regarding the fix in the community forums: https://steamcommunity.com/groups/steamuniverse/discussions/1/1760230157499060571/?ctp=4#c1734336452601498073

**Comment by kisak-valve** [comment]
Thanks @Lyle-Tafoya, closing.
