### ISSUE TITLE
[Severe security vulnerability] You can big picture xterm

### ISSUE THREAD

**Issue by kramlat** [ValveSoftware/SteamOS#651]
* **Steam client version:** All versions that allow the install of non-steam apps
* **SteamOS version:** All versions 
* **Opted into Steam client beta?:** N/A 
* **Opted into SteamOS beta?:** N/A 
* **Have you checked for updates in Settings > System?:** Yes

#### Please describe your issue in as much detail as possible:
What should happen: xterm should not run in big picture
What does happen: not only does it run in big picture, it gives the end user a shell that starts in ~/.local/share/steam.
Level of compromise to system security: Extreme
End user can pirate games, hack or modify games, deploy payloads that compromise the system, install rootkits, install hacker tools, the list goes on.
#### Steps for reproducing this issue:

1. The automated installer leaves an xterm and a uxterm executable behind.
2. go to the settings and select to create a shortcut.  no need for a desktop session.  choose xterm
3. go to your library. choose to play "xterm". You are now dropped into a 36 pt font bash shell as the user "steam" in the folder /home/steam/.local/share/steam.  lots of errors with a shared library show up but those are harmless.  The fact you can big picture a shell is the real problem.

**Comment by kisak-valve** [comment]
Hello @kramlat, fun fact, SteamOS is not a walled garden and you're free to break your own system if you want.

Closing as invalid.

**Comment by OvermindDL1** [comment]
Just as a use-case for why I would absolutely not want this changed, I use 'big picture' mode to start all kinds of things, including a terminal (though konsole in my case), which I use from my living room via steam link very often.

**Comment by Luckz** [comment]
How would this be for a kiosk/café type system?

**Comment by OvermindDL1** [comment]
> How would this be for a kiosk/café type system?

Then you probably don't want a full installed desktop while also you would want to be sandboxing steam as it's own user with restricted access to other programs.  It's not too hard to set up.
