### ISSUE TITLE
Instalation process fails on Ryzen-based computer

### ISSUE THREAD

**Issue by samip5** [ValveSoftware/SteamOS#657]
#### Your system information

* Steam client version: No idea, downloaded today.
* SteamOS version: No Idea as wont give me the information
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Can't.
* CPU: AMD Ryzen 5 1600
* Motherboard: ASUS PRIME B350-PLUS
* GPU: GTX 1060 6GB

#### Please describe your issue in as much detail as possible:
Tried to install SteamOS onto Ryzen-based computer using the SteamOSInstaller.zip, with automatic install.
Watch it fail, as it's unable to find a suitable kernel.
SteamOS install completely fails.

It should have installed it correctly.

#### Steps for reproducing this issue:

1.  Download SteamOSInstaller.zip from Steam website.
2.  Copy the contents of the .zip to a USB flash drive and boot the Ryzen PC from it.
3.  Choose Automated install
4.  Watch it fail to find a suitable kernel.

**Comment by kisak-valve** [comment]
Hello @samip5, this issue is already being tracked at #602. Closing as a duplicate.

**Comment by samip5** [comment]
Hello,  Valve Employee.  I don't think these are duplicates as I don't get kernel panic errors as they do in #602.
