### ISSUE TITLE
Mouspad not detected on Chromebook device with BRASWELL cpu

### ISSUE THREAD

**Issue by pcs3rd** [ValveSoftware/SteamOS#661]
#### Your system information

* Steam client version:
* SteamOS version: 
* Opted into Steam client beta?: [Yes/No] 
* Opted into SteamOS beta?: [Yes/No] 
* Have you checked for updates in Settings > System?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by mdeguzis** [comment]
To confirm, is this issue for SteamOS? I was not aware of SteamOS running well/at all on a Chrombook device (even an x86 one).

Did you mean to post this in the Steam for Linux github tracker?
