### ISSUE TITLE
Cities: Skylines will not start on Linux; just crashes

### ISSUE THREAD

**Issue by iamdarkmatter** [ValveSoftware/SteamOS#662]
#### Your system information

* Steam client version:
* SteamOS version: 
* Opted into Steam client beta?: [Yes/No] 
* Opted into SteamOS beta?: [Yes/No] 
* Have you checked for updates in Settings > System?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Closing as there's no actionable information here.
