### ISSUE TITLE
Unpacking card decks doesn't work.

### ISSUE THREAD

**Issue by Owl3** [ValveSoftware/SteamOS#665]
#### Your system information

* Steam client version:
* SteamOS version: 
* Opted into Steam client beta?: [Yes/No] 
* Opted into SteamOS beta?: [Yes/No] 
* Have you checked for updates in Settings > System?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Again, this is something that's been going on for weeks, and if steamos could just put a report an issue button into the steamos gui or client, this wouldn't annoy so many people. 

This issue means that users cannot unpack card decks. They should be able to. 

#### Steps for reproducing this issue:

1. Get a pack of card drops. 
2. Go to inventory. 
3. Attempt to unpack cards.

**Comment by TTimo** [comment]
(Maybe this was meant as an Artifact bug report?)
