### ISSUE TITLE
debian ucf causes upgrade process to hang

### ISSUE THREAD

**Issue by marcsello** [ValveSoftware/SteamOS#666]
#### Your system information

* Steam client version: 1548107472
* SteamOS version: SteamOS 2.0 update 1:2.166
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
After SteamOS updated, and rebooted, I wanted to check out if it installed every aviliable upgrade trought apt, so I've connected to the machine over ssh, and issued `apt update`.
I've expected a message saying `All packages are up to date`
But I've got
```
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)                                                                              
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
```

So, I've listed the processes using htop, and noticed, that a running apt install is hanging on `ucf`, which is Debian's tool for dpkg, it's used to ask the user during an update, if a newer version of the config is aviliable, they want it to be updated, or keep their changes.

A regular user would have no way to answer this question, since this question is asked in a non-interactive shell somewhere in the background. They wouldn't even know what to answer.

#### Steps for reproducing this issue:

1. boot up SteamOS
2. ssh into it
3. run apt update
4. check running processes with htop

#### Dirty fix:
I've sent a SIGTERM to the apt process, causing it to terminate.
And then I've used `sudo dpkg --configure -a` to reconfigure unfinished packages, then run `steamos-update` manually to finish the process.

A real fix would be setting `UCF_FORCE_CONFFNEW` environmental variable (not tested), so it wouldn't prompt the user, just always using the new config provided in the package.
It seems like the flag `--force-confnew` on dpkg does not work

**Comment by smcv** [comment]
> A real fix would be setting `UCF_FORCE_CONFFNEW` environmental variable (not tested), so it wouldn't prompt the user, just always using the new config provided in the package.

Maybe. However, this would also result in deliberate configuration changes by the user being overwritten, so it isn't ideal in general. Conversely, `UCF_FORCE_CONFOLD` would avoid the hang and avoid prompting the user, but would not apply new configuration.

Do you know which package was being configured with ucf? `/var/log/apt` might give you more information.

**Comment by smcv** [comment]
The more general problem here is that if you can't apply an update successfully, then it isn't possible to update the updater to fix the bug that made updates not apply successfully...

**Comment by smcv** [comment]
Log files for apt, dpkg and unattended-upgrades (`/var/log/dpkg.log`, `/var/log/apt/*` and `/var/log/unattended-upgrades/*`) would be very useful information here.

I can't immediately reproduce this upgrade failure, but you mentioned `apt install`, and SteamOS doesn't normally use `apt` or `apt-get` for the main part of the upgrade (it uses `unattended-upgrades` which uses the apt library directly). This makes me wonder whether the upgrade is failing part way through, causing `/usr/bin/steamos-update` to recover using `apt-get install`. Unlike `unattended-upgrades`, the `apt` invocations in `/usr/bin/steamos-update` don't use `DEBIAN_FRONTEND=noninteractive` to suppress debconf and ucf prompting.

**Comment by marcsello** [comment]
Oh yeah, I've forgot to mention that this 'steam os update' was prompted in steam bpm, I've clicked "reboot to install upgrades" after that the boot splash came up with a progress bar listing the packages being upgraded... but at around 97% it got stuck for a few minutes (like 1, maybe 2) and then restarted the computer. 
I've never seen this upgrade screen before, so I tought it was normal.

iirc the package being upgraded was grub-efi-amd64, but will upload logs as soon as I get to it.
Also I think I might have some costum repository added, since I have Kodi installed... but I'm not sure... will check that as well. Got to think of it this might cause such problems.

**Comment by smcv** [comment]
> iirc the package being upgraded was grub-efi-amd64

Thanks, that helps to narrow it down.

> but at around 97% it got stuck for a few minutes (like 1, maybe 2) and then restarted the computer

That could be normal (some packages do take a long time to upgrade, particularly the Nvidia driver, which was updated in SteamOS recently) or it could be a problem. The logs would help to say which.

> I've never seen this upgrade screen before, so I tought it was normal.

It's normal that the upgrades install with the boot splash showing, just before the computer shuts down or restarts. In a small update with only security fixes you might not notice it (or it might not appear at all if the upgrade is quick enough, I'm not sure) but a big update involving the kernel and graphics drivers will take a lot longer.

> Also I think I might have some costum repository added, since I have Kodi installed [...] Got to think of it this might cause such problems.

Yes, third-party repositories (including Debian) will sometimes cause situations that unattended-upgrades can't deal with. I wouldn't recommend using third-party repositories unless you are comfortable with using apt (or apt-get or aptitude) at the command line.

**Comment by smcv** [comment]
`/etc/default/grub` is one of the few files on a SteamOS system that gets managed by `ucf`, and if the package being upgraded was `grub-efi-amd64` then that's consistent.

Did you maybe modify that file yourself? (If you didn't, it's possible that SteamOS did.)

**Comment by marcsello** [comment]
Okay, I found out, that I do have regular Debian Jessie repos enabled, but only a few packages were installed from it, since it had a lower priority than the steamos repo.

The following packages were installed from the jessie repos: (I think)
```
irqbalance/oldstable,now 1.0.6-3+deb8u1 amd64 [installed,automatic]
javascript-common/oldstable,now 11 all [installed,automatic]
libaacs0/oldstable,now 0.7.1-1+b1 amd64 [installed,automatic]
libnuma1/oldstable,now 2.0.10-1 amd64 [installed,automatic]
python-imaging/oldstable,now 2.6.1-2+deb8u3 all [installed,automatic]
python-pil/oldstable,now 2.6.1-2+deb8u3 amd64 [installed,automatic]
tmux/oldstable,now 1.9-6 amd64 [installed]
```
Everythin else was installed from the steamos repos, and Kodi was locally installed. 

I can't remember modifying the `/etc/default/grub` file, I'm happy with how my machine boots ^^. I've also installed steamos using the fully automated install, so this was the version came with the installer.
This machine was installed back in 2018.04.28.

You can find the required logs here:
`/var/log/dpkg.log` : https://slexy.org/view/s2j9TDVqOF
`/var/log/apt/history.log` : https://slexy.org/view/s21dBOv7Yw
`/var/log/apt/term.log` : https://slexy.org/view/s20YD1doMU
`/var/log/unattended-upgrades/unattended-upgrades-dpkg.log` : https://slexy.org/view/s21gGGDUld
`/var/log/unattended-upgrades/unattended-upgrades.log` : https://slexy.org/view/s2Q4TLN5lw
`/var/log/unattended-upgrades/unattended-upgrades-shutdown.log` : https://slexy.org/view/s2OWn9RtPL

**Comment by smcv** [comment]
Thanks! Yes, as I suspected, it's grub:

```
A new version (/tmp/grub.D9jkX11zbL) of configuration file /etc/default/grub is 
available, but the version installed currently has been locally modified.
```

I think the SteamOS installer might modify that file, so that might be why this is happening even though you don't remember modifying it yourself.

I'm a little puzzled why this is happening now, because I didn't think moving from grub 2.02~beta2-22+steamos3+bsos1 to 2.02~beta2-22+steamos3+deb8u1+bsos1 modifies that file... but I could be wrong about that.

**Comment by TTimo** [comment]
SteamOS 2.170 has been released to General Availability.

There have been no other reports of this issue. We believe this may be caused by end user modifications, which are outside of the scope of support.

We are working on more robust upgrade solutions for future SteamOS releases. We will be closing this report.
