### ISSUE TITLE
Unable purchase games

### ISSUE THREAD

**Issue by flyhigh72** [ValveSoftware/SteamOS#667]
#### Your system information

* Steam client version: Newest stable client
* SteamOS version: brewmaster 2.166 stable
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Since the last SteamOS and client i am unable to purchase new games like 'Orphan'.
Even though enough money on steam account, i can't buy any games. I am able to put the game on the 'shopping basket' but when 'buy myself' is clicked, then nothing happens.

Note: Language on Steam is set to 'german'. Hardware: Steam Machine Zotac Nen

#### Steps for reproducing this issue:

1. Got enough 'money on steam account'
2. Put game to 'shopping basket'
3. Click 'buy myself'
4. Nothing happens

**Comment by TTimo** [comment]
Hello @flyhigh72 

Can you try again after opting into Steam client beta?
If it still fails, can you provide the contents of `/home/steam/.steam/steam/logs`?

**Comment by flyhigh72** [comment]
Hello TTimo

Many thanks for your support.
After last Steam client stable update, i am able to purchase again.
All seems to be fine :-)

Greetings
