### ISSUE TITLE
can't play mods

### ISSUE THREAD

**Issue by stake45** [ValveSoftware/SteamOS#671]
#### Your system information

* Steam client version:linux mint
* SteamOS version: linux
* Opted into Steam client beta?: [Yes/No] yes
* Opted into SteamOS beta?: [Yes/No] yes
* Have you checked for updates in Settings > System?: [Yes/No]yes
no setting link under top left steam
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.
opened sins rebellion-{sins of a solar empire rebellion}-play on menu choose options then mods.link shows documets on C:.linux uses a different label system.is there a work around I can use?
#### Steps for reproducing this issue:

1. see above
2. 
3.

**Comment by stake45** [comment]
In mods lobby,cliking mod link only shows C: linkage.Is there a way to change link from C: to say a linux folder storing mods files

**Comment by kisak-valve** [comment]
Hello @stake45, issues with Proton games are being tracked in the Proton issue tracker, so I've transferred this issue to https://github.com/ValveSoftware/Proton/issues/265#issuecomment-470967111.

**Comment by stake45** [comment]
thank you for your response and link.
