### ISSUE TITLE
SteamOS update 2.183 causing a Xserver segmentation fault

### ISSUE THREAD

**Issue by dubigrasu** [ValveSoftware/SteamOS#673]
#### Your system information
* i7-4790K
* AMD HD7970
* 16 GB RAM

* Steam client version: 1553301239, Built Mar 23 2019, Steam API v018
* SteamOS version: 2.0 Brewmaster
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
- I installed successfully the latest SteamOS DVD (2019-02-28) on a SSD, opted into the Steam beta client and I was able to play few games and test the system, everything went fine.
- Then I opted into the SteamOS beta repositories (update 2.183) by using the package manager in the Linux Desktop mode and then rebooted when prompted in BPM.
- The machine rebooted few times and finally settled in the auto-repair-boot loop. It displays a message about a fatal error and a successful recovery, then reboots, fails again and so on.
- I should say at this point that I tried several installs and other methods to opt-in the beta repos (including from the command line) and I have no packages left to install or any unattended-upgrades issues. All packages are successfully installed.
- The issue seems to be caused by an Xserver segmentation fault logged here:
[Xorg.log](https://github.com/ValveSoftware/SteamOS/files/3004852/Xorg.log)
- As a side note, I was also able to revert the system to the old state by force install back the older packages (not talking about clonezilla backup), at which point the system started functioning again.

#### Steps for reproducing this issue:

1. Install the latest SteamOS Brewmaster
2. Opt in the beta repos (at this point update 2.183)
3. Observe the recovery boot loop.

**Comment by fledermaus** [comment]
Hi. If you're still seeing this it would be interesting to figure out why the reboot loop is happening - often it's a dkms kernel module build problem, but that really shouldn't apply to your system.

If you have the time, could you log in when it's just booted and edit /usr/bin/steamos-autorepair.sh to remove the final line that says "reboot"?

It will already be running, so the system should reboot one more time and re-run the recovery process, but then it'll be in a state where you can inspect it and maybe we can figure out what's going on.

Of particular interest will be the output of:

# update-alternatives --get-selections| grep glx
# update-alternatives --display glx

and the contents of:

 /var/log/Xorg.0.log

**Comment by dubigrasu** [comment]
Hi

Output of **update-alternatives --get-selections| grep glx**:
`glx                            manual   /usr/lib/mesa-diverted`

Output of **update-alternatives --display glx**:
```
glx - manual mode
  link currently points to /usr/lib/mesa-diverted
/usr/lib/mesa-diverted - priority 5
  slave glx--libEGL.so.1-i386-linux-gnu: /usr/lib/mesa-diverted/i386-linux-gnu/libEGL.so.1
  slave glx--libEGL.so.1-x86_64-linux-gnu: /usr/lib/mesa-diverted/x86_64-linux-gnu/libEGL.so.1
  slave glx--libGL.so.1-i386-linux-gnu: /usr/lib/mesa-diverted/i386-linux-gnu/libGL.so.1
  slave glx--libGL.so.1-x86_64-linux-gnu: /usr/lib/mesa-diverted/x86_64-linux-gnu/libGL.so.1
  slave glx--libGLESv1_CM.so.1-i386-linux-gnu: /usr/lib/mesa-diverted/i386-linux-gnu/libGLESv1_CM.so.1
  slave glx--libGLESv1_CM.so.1-x86_64-linux-gnu: /usr/lib/mesa-diverted/x86_64-linux-gnu/libGLESv1_CM.so.1
  slave glx--libGLESv2.so.2-i386-linux-gnu: /usr/lib/mesa-diverted/i386-linux-gnu/libGLESv2.so.2
  slave glx--libGLESv2.so.2-x86_64-linux-gnu: /usr/lib/mesa-diverted/x86_64-linux-gnu/libGLESv2.so.2
  slave glx--libGLX_indirect.so.0-i386-linux-gnu: /usr/lib/i386-linux-gnu/libGLX_mesa.so.0
  slave glx--libGLX_indirect.so.0-x86_64-linux-gnu: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
/usr/lib/nvidia - priority 100
  slave glx--libEGL.so.1-i386-linux-gnu: /usr/lib/mesa-diverted/i386-linux-gnu/libEGL.so.1
  slave glx--libEGL.so.1-x86_64-linux-gnu: /usr/lib/mesa-diverted/x86_64-linux-gnu/libEGL.so.1
  slave glx--libGL.so.1-i386-linux-gnu: /usr/lib/mesa-diverted/i386-linux-gnu/libGL.so.1
  slave glx--libGL.so.1-x86_64-linux-gnu: /usr/lib/mesa-diverted/x86_64-linux-gnu/libGL.so.1
  slave glx--libGLESv1_CM.so.1-i386-linux-gnu: /usr/lib/mesa-diverted/i386-linux-gnu/libGLESv1_CM.so.1
  slave glx--libGLESv1_CM.so.1-x86_64-linux-gnu: /usr/lib/mesa-diverted/x86_64-linux-gnu/libGLESv1_CM.so.1
  slave glx--libGLESv2.so.2-i386-linux-gnu: /usr/lib/mesa-diverted/i386-linux-gnu/libGLESv2.so.2
  slave glx--libGLESv2.so.2-x86_64-linux-gnu: /usr/lib/mesa-diverted/x86_64-linux-gnu/libGLESv2.so.2
  slave glx--libGLX_indirect.so.0-i386-linux-gnu: /usr/lib/i386-linux-gnu/libGLX_nvidia.so.0
  slave glx--libGLX_indirect.so.0-x86_64-linux-gnu: /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0
  slave glx--libglxserver_nvidia.so: /usr/lib/nvidia/libglxserver_nvidia.so
  slave glx--libnvidia-cfg.so.1-x86_64-linux-gnu: /usr/lib/x86_64-linux-gnu/nvidia/libnvidia-cfg.so.1
  slave glx--nvidia-blacklists-nouveau.conf: /etc/nvidia/nvidia-blacklists-nouveau.conf
  slave glx--nvidia-bug-report.sh: /usr/lib/nvidia/nvidia-bug-report.sh
  slave glx--nvidia-drm-outputclass.conf: /etc/nvidia/nvidia-drm-outputclass.conf
  slave glx--nvidia-load.conf: /etc/nvidia/nvidia-load.conf
  slave glx--nvidia-modprobe.conf: /etc/nvidia/nvidia-modprobe.conf
  slave glx--nvidia_drv.so: /usr/lib/nvidia/nvidia_drv.so
/usr/lib/nvidia/bumblebee - priority 95
  slave glx--libEGL.so.1-i386-linux-gnu: /usr/lib/mesa-diverted/i386-linux-gnu/libEGL.so.1
  slave glx--libEGL.so.1-x86_64-linux-gnu: /usr/lib/mesa-diverted/x86_64-linux-gnu/libEGL.so.1
  slave glx--libGL.so.1-i386-linux-gnu: /usr/lib/mesa-diverted/i386-linux-gnu/libGL.so.1
  slave glx--libGL.so.1-x86_64-linux-gnu: /usr/lib/mesa-diverted/x86_64-linux-gnu/libGL.so.1
  slave glx--libGLESv1_CM.so.1-i386-linux-gnu: /usr/lib/mesa-diverted/i386-linux-gnu/libGLESv1_CM.so.1
  slave glx--libGLESv1_CM.so.1-x86_64-linux-gnu: /usr/lib/mesa-diverted/x86_64-linux-gnu/libGLESv1_CM.so.1
  slave glx--libGLESv2.so.2-i386-linux-gnu: /usr/lib/mesa-diverted/i386-linux-gnu/libGLESv2.so.2
  slave glx--libGLESv2.so.2-x86_64-linux-gnu: /usr/lib/mesa-diverted/x86_64-linux-gnu/libGLESv2.so.2
  slave glx--libGLX_indirect.so.0-i386-linux-gnu: /usr/lib/i386-linux-gnu/libGLX_mesa.so.0
  slave glx--libGLX_indirect.so.0-x86_64-linux-gnu: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
  slave glx--libnvidia-cfg.so.1-x86_64-linux-gnu: /usr/lib/x86_64-linux-gnu/nvidia/libnvidia-cfg.so.1
  slave glx--nvidia-blacklists-nouveau.conf: /etc/nvidia/nvidia-blacklists-nouveau.conf
  slave glx--nvidia-bug-report.sh: /usr/lib/nvidia/nvidia-bug-report.sh
  slave glx--nvidia-modprobe.conf: /etc/nvidia/nvidia-modprobe.conf
Current 'best' version is '/usr/lib/nvidia'.
```
[Xorg.0.log](https://github.com/ValveSoftware/SteamOS/files/3032878/Xorg.0.log)

**Comment by fledermaus** [comment]
Hm. That looks like the older radeon driver rather than the amdgpu one.

I'm going to bounce this across to someone who knows more about it than I do for an opnion, thanks for the info.

**Comment by fledermaus** [comment]
While I'm here, not to go all Columbo on you, but - just one more thing:

Could you grab the output of 'dpkg-query -W' for us? Thanks.

**Comment by dubigrasu** [comment]
Is the old Radeon driver because is a GCN 1.0 card, which defaults to _radeon_ instead of _amdgpu_.
If I force the _amdgpu_ driver, this is the Xorg.log:
[Xorg.0.log](https://github.com/ValveSoftware/SteamOS/files/3049056/Xorg.0.log)

**Comment by dubigrasu** [comment]
Here are the "dpkg-query -W" output before and after the (as of now) 2.184 update. I did again a fresh install.
[before_update.txt](https://github.com/ValveSoftware/SteamOS/files/3049068/before_update.txt)
[after_update.txt](https://github.com/ValveSoftware/SteamOS/files/3049069/after_update.txt)

**Comment by fledermaus** [comment]
Interesting that the other driver crashes in what looks like the same way (makes it easier for me to potentially reproduce here as I think I only have access to cards which want the newer driver). 

Could be a xorg/mesa/llvm incompatibility. 

The package lists will be useful, thanks.

**Comment by fledermaus** [comment]
Update: I can reproduce this here (albeit on a different GPU) - digging into it.

**Comment by fledermaus** [comment]
Version of libLLVM 7 shipped is, uh… bad. Will roll out a fix once we have definitely purged all traces of it.

**Comment by TTimo** [comment]
beta 2.187 should fix this

**Comment by dubigrasu** [comment]
Just want to confirm that the issue is indeed fixed, both on a fresh testing installation, and my main day-to-day SteamOS.
