### ISSUE TITLE
SteamOS stuck in an Xorg startup loop

### ISSUE THREAD

**Issue by ZILCKIQ** [ValveSoftware/SteamOS#677]
* SteamOS version: 2019-04-22 releases iso

My AMD RX480 graphics card cannot install the ISO Steamos image released by 2019-04-22

Automatically Installation->Restart to Boot animation ->Stuck

**Comment by fledermaus** [comment]
You should be able to boot into recovery mode from the grub prompt - it's hidden by default but on my machine mashing F11 (or maybe F12?) brings up the grub menu from which I can boot in emergency/recovery mode. Worst case scenario you can add init=/bin/bash to the command line and get a shell without any of the normal startup and investigate from there.

Also when you say restart-to-boot animation: Are you seeing the steam logo, the steam logo with a little progress bar underneath, the bubbles-rising-through-water animation, or something else?

**Comment by TTimo** [comment]
Hello @ZILCKIQ 

SteamOS uses the grub bootloader. Can you be more specific about what happens the first time you reboot into the newly installed system?

Does the grub prompt appear at all? (you have the option to snapshot/restore your system partition in addition to booting SteamOS at that point)

If you have a grub prompt you could try to boot in safe mode. You may need to press some keys during boot (esc) to get the grub menu (see https://wiki.ubuntu.com/RecoveryMode#Booting_into_recovery_mode)

You could also boot from a live distro on a USB stick diagnose what's going on. Maybe the system booted just fine, but plymouth is stuck .. in that case you'll have some system logs in your root partition.

**Comment by ZILCKIQ** [comment]
I judged that the graphics card driver could not be installed properly. It was normal in the old version.

**Comment by RyuzakiKK** [comment]
I guess I'm facing the same problem.

- CPU: AMD Ryzen 5 1600
- GPU: AMD RX 480

## Steps to reproduce
- Download `SteamOSDVD.iso` published on 2019-04-22.
- Write the iso to a USB pen drive
- Boot from USB, choose the expert mode and select an entire drive.
- At the end it will reboot
- You'll see the desktop environment, the standard steam update process (the popup window) and the "updating drivers" (I don't remember the exact words) at the bottom of the screen.
- After that you'll be stuck with a black window that cycles between showing the steamos mouse just for a fraction of a second to a complete black window. In an infinite loop.


When this happens I'm able to change tty. I also tried `apt update && apt upgrade` but it didn't solve the problem.
This is the Xorg log: [Xorg.0.log](https://github.com/ValveSoftware/SteamOS/files/3355124/Xorg.0.log)

**Comment by TTimo** [comment]
Thanks for the log.

Can you try to jump that install to the latest SteamOS beta? 2.194 has a new kernel which I think may fix this problem.

See https://github.com/ValveSoftware/SteamOS/wiki/Opting-into-SteamOS-Beta (you need to switch to `brewmaster_beta` in your apt sources).

**Comment by RyuzakiKK** [comment]
I just tried upgrading to brewmaster_beta but unfortunately I'm still getting the same issue.
The log is also nearly identical: [Xorg.0.log](https://github.com/ValveSoftware/SteamOS/files/3355650/Xorg.0.log)

**Comment by TTimo** [comment]
@ZILCKIQ can you provide the output of `lspci -v` on the machine you are having this problem with? We suspect a compatibility problem with some audio hardware - see https://github.com/ValveSoftware/steam-for-linux/issues/4753

**Comment by TTimo** [comment]
This crash should be fixed in latest Steam beta client. Please test again!

Note: if your SteamOS install got stuck in this boot cycle, it may not actually be entirely trivial to get Steam to update, let alone to the beta release.

You can temporarily edit out the `-steamos` parameter out of `/usr/bin/steamos-session`, or launch `steam` from desktop mode as the `steam` user, and get it updated to latest Steam beta (at least until this reaches general availability).

**Comment by ZILCKIQ** [comment]
I can't get into the system at all, System jams after grub is completed！
CPU: RYZEN 1600X
GPU: AMD RX480 8G

**Comment by fledermaus** [comment]
Do you get any logging at all? Is the system reponsive over the network, or is it locked up completely? Does the system boot successfully from (for example) a [Debian] buster or stretch liveUSB image?

**Comment by ZILCKIQ** [comment]
Picture tearing in starter animation

**Comment by TTimo** [comment]
@ZILCKIQ it sounds like it will be difficult to recover your system. There is a new installer for brewmaster at http://repo.steampowered.com/download/brewmaster/2.195/ - if we are correct on our diagnostic of the problem you are encountering, this should install and give you a functional SteamOS install.

**Comment by ZILCKIQ** [comment]
The problem has been solved in the new ISO
Thank you~

**Comment by kisak-valve** [comment]
Closing as fixed in SteamOS 2.195.
