### ISSUE TITLE
Please add pastebinit to the official repos.

### ISSUE THREAD

**Issue by hitsuji** [ValveSoftware/SteamOS#68]
The package pastebinit is probably the No. 1 tool used in #ubuntu and #debian to remotely diagnosing issues where we can get users to safely pastebin their Xorg.0.log / dmesg / etc when they are unable to get up a graphical environment in their system.

Can this be added by default to SteamOS, or at least put in the repos?

**Comment by johnv-valve** [comment]
added this quite a while ago
