### ISSUE TITLE
The problem with the mouse in Hitman 2

### ISSUE THREAD

**Issue by vladislavyuzbekov** [ValveSoftware/SteamOS#680]
#### Your system information

* Steam client version: 1560817063
* SteamOS version: 2.0:1:2.190
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] Yes
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

The wireless mouse does not work in the game, but it works if you hold the mouse button down.

**Comment by kisak-valve** [comment]
Hello @vladislavyuzbekov, this issue should also be mentioned to the game's dev(s).

**Comment by dubigrasu** [comment]
@vladislavyuzbekov 
That's something that unfortunately happens frequently with Proton titles played through "steamcompmgr", which is SteamOS's window manager.

**Comment by kisak-valve** [comment]
@dubigrasu, thanks for pointing out this game does not currently have a native linux port.

This is most likely an issue with Proton, and we're using one issue report per unofficially supported game title, so I've transferred this issue to https://github.com/ValveSoftware/Proton/issues/2121#issuecomment-503254964.
