### ISSUE TITLE
fallout new vegas on steamos

### ISSUE THREAD

**Issue by vladislavyuzbekov** [ValveSoftware/SteamOS#681]
#### Your system information

* Steam client version: 1560817063
* SteamOS version: 2.0: 1:2.190
* Opted into Steam client beta?: [Yes/No] yes
* Opted into SteamOS beta?: [Yes/No] yes
* Have you checked for updates in Settings > System?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

1. It is impossible to open additional settings in the settings window.
2. The cursor does not work in the game after the first mouse click.
On other operating systems, such as ubuntu, everything works well. I think the problems are due to the peculiarities of the Steam session.

#### Steps for reproducing this issue:

problem with the game settings window
1. run the game
2. click "settings" in the launch window
2. try to click "advanced"

problem with cursor
1. run the game
2. click "play"
2. click the mouse anywhere and the cursor will freeze in the main menu

**Comment by kisak-valve** [comment]
Hello @vladislavyuzbekov, we're tracking issues with games run through Proton in the Proton issue tracker, and one issue report per unofficially supported game title, so I've transferred this issue report to https://github.com/ValveSoftware/Proton/issues/356#issuecomment-504107883.
