### ISSUE TITLE
The browser periodically freezes after trying to open more than 6 tabs

### ISSUE THREAD

**Issue by vladislavyuzbekov** [ValveSoftware/SteamOS#696]
#### Your system information

* Steam client version: 1570492308
* SteamOS version: 2.0: 1:2.195
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.
The browser periodically freezes after trying to open more than 6 tabs
![2019-10-09 08-09-13](https://user-images.githubusercontent.com/30505454/66453559-73fff580-ea6d-11e9-9e12-b2665eb7308d.JPG)
#### Steps for reproducing this issue:

1. Use the browser as usual, follow the links, at one point the browser freezes
2. 
3.

**Comment by vladislavyuzbekov** [comment]
Now this problem is not observed. Thanks!

**Comment by kisak-valve** [comment]
Thanks for the follow up, closing per the last comment.
