### ISSUE TITLE
Family Sharing Free DLC Restriction

### ISSUE THREAD

**Issue by pedroivf** [ValveSoftware/SteamOS#699]
I'm asking to Steam to allow me to help to improve this feature. Please consider that Family Sharing born as a compensation for lending of physical copies. In the digital world, we can not lend, Family Sharing was an intelligent feature to compensate that, but it's not fully implement it, and that's a real problem for Steam, because then should i prefer to buy a physical copy if i want to share with my wife any game in the future?.
Regards,

Pedro
PD. I'm a programmer and i have a master degree in networks, i know it's possible to develop fully this feature, so i offer myself to develop this feature freely.

**Comment by kisak-valve** [comment]
Hello @pedroivf, this reads like an OS independent Steam issue and not specific to SteamOS.

Please use [Steam Support](https://help.steampowered.com/) to report this to the larger Steam support team.

**Comment by pedroivf** [comment]
Steam Support sent me to this "Official Valve Github", also i already wrote to "Family Share Forums" without any response, i didn't find any information rearding future updates/fixes about this "family sharing" in the "Client Updates Section" either.

-----------------------------------------------------------------------
Message from Steam Support on Sep 27 @ 10:02am | 23 hours ago
Hello,

Thank you for taking the time to report this - we are aware of the bug happening when it comes to family sharing some titles with free DLC.

It is in the developer's queue but Steam Support does not have an ETA on when it will be resolved. All information regarding future updates/fixes can be viewed on our Client Updates Section.

I understand that you would like to contribute to the feature, the best place for this would be to submit it at the Official Valve Github as well as sharing your suggestions in the Family Share Forums as this these are regularly read by the developers.

Unfortunately, I don't have any further information regarding this but if there is something else that we can assist you with, please reply here and we will be happy to help you. 

Steam Support / Jr. Portal Cake Tester 
Vido
-------------------------------------------------------------------
