### ISSUE TITLE
I can not log in after connecting Steam Guard

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/SteamOS#704]
#### Your system information

* Steam client version: 1576908998
* SteamOS version: 2.0 1:2.195
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.
I can not log in after connecting Steam Guard using gamepad.  The keyboard layout does not change from Russian to English when entering the Steam Guard password.
#### Steps for reproducing this issue:

1. Change language layout to russian
2. Log out
3. Try to log in with Steam Quard

**Comment by TTimo** [comment]
Big picture problem then, not specific to SteamOS? This sounds like it would happen in big picture mode on any Linux distribution. But it's not a problem in desktop mode?

**Comment by vladislavyuzbekov** [comment]
> Big picture problem then, not specific to SteamOS? This sounds like it would happen in big picture mode on any Linux distribution. But it's not a problem in desktop mode?

The problem is specific to Steam OS only. In Big Picture mode on any Linux distribution, the keyboard layout is in English. On Steam OS, I have to plug in a keyboard to enter my Steam Quard password.
