### ISSUE TITLE
Add checkbox option to Disable ESYNC in Steam Play Options - Bioshock Remastered Textures Missing

### ISSUE THREAD

**Issue by leocodeninja** [ValveSoftware/SteamOS#706]
#### Your system information

* Steam client version: Latest Stable as of writing
* SteamOS version: 2.195
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
When playing Bioshock 1 and 2 Remastered, the textures are missing and graphics are blocky. When adding the following to launch options it fixes the problems.

E_WINED3D11=1 PROTON_NO_ESYNC=1 %command%

#### Steps for reproducing this issue:

1. Install Bioshock Remastered
2. Launch Game without special command
3. Play Game

**Comment by kisak-valve** [comment]
Hello @leocodeninja, this is a general feature request for Steam, and not limited to SteamOS. It is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5874. Closing in favor of the existing feature request.
