### ISSUE TITLE
Black screen after update and reboot

### ISSUE THREAD

**Issue by stupid-genius** [ValveSoftware/SteamOS#707]
#### Your system information

* Steam client version: Can't use Steam UI to retrieve this information
* SteamOS version: Can't use Steam UI to retrieve this information
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Not sure what this is 
* Have you checked for updates in Settings > System?: Can't use Steam UI

#### Please describe your issue in as much detail as possible:
This system has worked without issue for over a year.  System did a typical update process, but when I rebooted (today 2/3/20), I got the "black screen" (see below for the details).  I can still login by switching to a different tty, but I don't know enough to diagnose what's going on.  `lightdm` appears to be running on tty7 as normal, but doesn't show anything.  It's all just black.  I'm not getting this "reboot loop" that I've seen mentioned, and I get no messages of any kind (not via the UI anyway; haven't started digging through system logs yet).

#### Steps for reproducing this issue:

1. Boot SteamOS (either cold boot, or reboot)
2. Steam logo appears, then a large, oversized mouse cursor appears briefly, then black

**Comment by racecar-driver** [comment]
Does your system use an Nvidia card?  I had a similar issue, it seems the update didn't complete correctly and trigger the Nvidia driver installation.  The kernel defaults to the built in nouveau driver, which the steam interface can't run under for some reason.

You can force the installation to finish via:
1. Boot to black screen
2. Press Ctrl-Alt-F2 to switch to another tty
3. Login as root
4. Run the following command: apt-get -f install
5. After the installation completes, run the following command: reboot
6. Should be working after the reboot.

**Comment by stupid-genius** [comment]
I do have an Nvidia card.  I had previously tried that command, but I tried it again just now to be sure.  It says that everything is up to date and nothing changes.

**Comment by racecar-driver** [comment]
Make sure the Nvidia driver is loaded for your GPU

1. Open a terminal
2. Run the following command: lspci -k | grep -A 2 VGA

If the Nvidia driver is in use, you should see:
Kernel driver in use: nvidia

**Comment by stupid-genius** [comment]
I'm not a linux driver expert; does this mean the driver is loaded, but not in use?
```
00:1f.4 SMBus: Intel Corporation Device a123 (rev 31)
        Subsystem: ASUSTeK Computer Inc. Device 8694
        Kernel driver in use: i801_smbus
01:00.0 VGA compatible controller: NVIDIA Corporation GK208 [GeForce GT 730] (rev a1)
        Subsystem: ZOTAC International (MCO) Ltd. Device 730b
01:00.1 Audio device: NVIDIA Corporation Device 0e0f (rev a1)
        Subsystem: ZOTAC International (MCO) Ltd. Device 730b
        Kernel driver in use: snd_hda_intel
```

**Comment by racecar-driver** [comment]
That means the kernel hasn't loaded any driver nor does it know about one.  The Nvidia package may have been removed and/or not properly updated during the most recent update.

As root, try:
apt-get install nvidia-driver

**Comment by stupid-genius** [comment]
I tried that; it says that it's already the newest version.  I also tried `apt-get --reinstall install nvidia-driver` and rebooted, but still the same as before.

**Comment by racecar-driver** [comment]
Interesting. Perhaps dkms didn't automatically rebuild the kernel driver with the latest kernel/update?

Which kernel are you running?
`uname -r`

The driver should be located down:
`/var/lib/dkms/nvidia-current/<nvidia-driver-version>/<your-kernel-version>/x86_64/module/nvidia-current.ko`

There could be more than one Nvidia driver installed as well.  I have 415.27 installed with the `4.19.0-0.steamos2.3-amd64` kernel.

If there is an nvidia.ko file, you can try loading it with `insmod nvidia-current.ko` from the module directory.  Take a look at `dmesg | grep -i nvidia` after you do that to see if there are errors and confirm it loads with the lspci command above.

**Comment by stupid-genius** [comment]
Hmm, I seem to be missing the `ko`.  My versions seem to match yours though.
```
desktop@steamos:~$ uname -r
4.19.0-0.steamos2.3-amd64

root@steamos:/var/lib/dkms/nvidia-current/415.27# find . -type f -name '*.ko'
root@steamos:/var/lib/dkms/nvidia-current/415.27# ls
build  source
root@steamos:/var/lib/dkms/nvidia-current/415.27# ls build/
common	dkms.conf  Kbuild  Makefile  nvidia  NVIDIA_Changelog  nvidia-drm  nvidia-modeset
root@steamos:/var/lib/dkms/nvidia-current/415.27#
```

**Comment by racecar-driver** [comment]
[This ](https://askubuntu.com/questions/53364/command-to-rebuild-all-dkms-modules-for-all-installed-kernels)page has a quick one-liner for triggering dkms to rebuild all the modules for all the installed kernels via the startup service:
`ls /var/lib/initramfs-tools | sudo xargs -n1 /usr/lib/dkms/dkms_autoinstaller start`

Look for errors in the output for the 4.19.0 kernel building the nvidia-current.ko driver.

**Comment by stupid-genius** [comment]
That did the trick.  Thanks so much!
```
root@steamos:/var/lib/initramfs-tools# ls
4.11.0-0.steamos.57-amd64  4.11.0-0.steamos.65-amd64  4.14.0-0.steamos.81-amd64  4.16.0-0.steamos2.1-amd64  4.19.0-0.steamos2.3-amd64
root@steamos:/var/lib/initramfs-tools# cd
root@steamos:~# ls /var/lib/initramfs-tools | sudo xargs -n1 /usr/lib/dkms/dkms_autoinstaller start | tee dkms.log
dkms: running auto installation service for kernel 4.11.0-0.steamos.57-amd64:Error! echo
Your kernel headers for kernel 4.11.0-0.steamos.57-amd64 cannot be found at
/lib/modules/4.11.0-0.steamos.57-amd64/build or /lib/modules/4.11.0-0.steamos.57-amd64/source.
Error! echo
Your kernel headers for kernel 4.11.0-0.steamos.57-amd64 cannot be found at
/lib/modules/4.11.0-0.steamos.57-amd64/build or /lib/modules/4.11.0-0.steamos.57-amd64/source.
.
dkms: running auto installation service for kernel 4.11.0-0.steamos.65-amd64:Error! echo
Your kernel headers for kernel 4.11.0-0.steamos.65-amd64 cannot be found at
/lib/modules/4.11.0-0.steamos.65-amd64/build or /lib/modules/4.11.0-0.steamos.65-amd64/source.
Error! echo
Your kernel headers for kernel 4.11.0-0.steamos.65-amd64 cannot be found at
/lib/modules/4.11.0-0.steamos.65-amd64/build or /lib/modules/4.11.0-0.steamos.65-amd64/source.
.
dkms: running auto installation service for kernel 4.14.0-0.steamos.81-amd64:Error! echo
Your kernel headers for kernel 4.14.0-0.steamos.81-amd64 cannot be found at
/lib/modules/4.14.0-0.steamos.81-amd64/build or /lib/modules/4.14.0-0.steamos.81-amd64/source.
Error! echo
Your kernel headers for kernel 4.14.0-0.steamos.81-amd64 cannot be found at
/lib/modules/4.14.0-0.steamos.81-amd64/build or /lib/modules/4.14.0-0.steamos.81-amd64/source.
.
dkms: running auto installation service for kernel 4.16.0-0.steamos2.1-amd64:
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.16.0-0.steamos2.1-amd64 KVER=4.16.0-0.steamos2.1-amd64....
unset ARCH; env NV_VERBOSE=1 make modules KERNEL_UNAME=4.16.0-0.steamos2.1-amd64......
cleaning build area.....

DKMS: build completed.

wl.ko:
Running module version sanity check.
. - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.16.0-0.steamos2.1-amd64/updates/dkms/

depmod.....

Backing up initrd.img-4.16.0-0.steamos2.1-amd64 to /boot/initrd.img-4.16.0-0.steamos2.1-amd64.old-dkms
Making new initrd.img-4.16.0-0.steamos2.1-amd64
(If next boot fails, revert to initrd.img-4.16.0-0.steamos2.1-amd64.old-dkms image)
update-initramfs.....................................................

DKMS: install completed.
........
cleaning build area....

DKMS: build completed.

nvidia-current.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.16.0-0.steamos2.1-amd64/updates/dkms/

nvidia-current-modeset.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.16.0-0.steamos2.1-amd64/updates/dkms/

nvidia-current-drm.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.16.0-0.steamos2.1-amd64/updates/dkms/

nvidia-current-uvm.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.16.0-0.steamos2.1-amd64/updates/dkms/

depmod....

DKMS: install completed.
.
dkms: running auto installation service for kernel 4.19.0-0.steamos2.3-amd64:
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
unset ARCH; env NV_VERBOSE=1 make modules KERNEL_UNAME=4.19.0-0.steamos2.3-amd64....................................
cleaning build area....

DKMS: build completed.

nvidia-current.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-0.steamos2.3-amd64/updates/dkms/

nvidia-current-modeset.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-0.steamos2.3-amd64/updates/dkms/

nvidia-current-drm.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-0.steamos2.3-amd64/updates/dkms/

nvidia-current-uvm.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-0.steamos2.3-amd64/updates/dkms/

depmod....

DKMS: install completed.
.
root@steamos:~#
```

So to close the loop and add to the educational value for myself and others, if you can think of any amplifying info, that would be most appreciated.
1) Any idea what went wrong initially?
2) Did something specific point you towards the kernel drivers and `dkms`?  Or just "keep trying things till you find it"?

I hope it's another year or two before I have another issue with this machine.  Thanks, again!
