### ISSUE TITLE
Delayed steam.exe 15+ and Games launch 15+ seconds; steam.exe 140kb, windows 7 x64

### ISSUE THREAD

**Issue by Gerion7009** [ValveSoftware/SteamOS#715]
#### Problem:
started at 2018. Delayed steam.exe and Games from steam launch 15+ seconds. First fix at 2018 was set amd "use hardware acceleration" and AMD settings for steam.exe - it deduced launch time from ~40 to ~15seconds. Now 2020 "use hardware acceleration" dont give time.
#### Сurrent process
Steam delay 15+ seconds (steam.exe 140kb) and start normaly, then game start (steam.exe 130kb) 15 seconds delay and start normaly.

Task Manager cant kill steam.exe untill 15 seconds remain, at end error message: "Access to the specified device, path or file is denied"

#### Your system information
* Steam client version: last
* Opted into Steam client beta?: No
* Opted into SteamOS beta?:No

* Steam version: Windows 7 x64 (2019 q1 updated)
Windows 7 x64;  i5-4210m; 8gb ram 
Radeon R7 m265, 22.05.2019 ,  26.20.11015.5009 (and any driver from 2018 to 2020)

maximum performance windows 7
maximum perfromance AMD graphic settings
AMD graphics for Steam.exe, steamservice.exe and others steam and game*.exe
No antivirus (no before, no viruses)
All programs and games launch instant and works fine

#### Things that dont help:
1. Reinstall steam
 1.1 SteamService.exe" /repair
  1.2 Steam cache folders delete
   1.3 Steam delete caches from client
2. Own file access privileges
 2. Run as administrator
3. Firewall exception for steam.exe (disabled by service)
4. Check HDD for errors
5. Check RAM for erros
6. Windows repair
7. Run simplified:
Steam.exe" -silent -no-browser -steamos -noverifyfiles -no-cef-sandbox -vrdisable -nobigpicture -nofriendsui

**Comment by kisak-valve** [comment]
Hello @Gerion7009, this issue tracker is for the SteamOS distribution of Linux. Please use [Steam Support](https://help.steampowered.com/) for issues with the Steam for Windows client.

**Comment by Gerion7009** [comment]
@kisak-valve They dont help, i tried to ask you have solution
