### ISSUE TITLE
Client password and Steam Guard password are reset when switching between clients in a SteamOS session and a desktop session.

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/SteamOS#722]
#### Your system information

* Steam client version: 1596762082
* SteamOS version: 2.0:1:2.195
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
The client password and Steam Guard password are requested when switching between clients in a SteamOS session and a desktop session.

#### Steps for reproducing this issue:

1. Install the client in the desktop session
2. Try switching clients
3. If no password is required, try restarting your system and try again

**Comment by TTimo** [comment]
SteamOS session and desktop session run as different users. They are two completely different installs of steam.

**Comment by Vladislavuz** [comment]
> SteamOS session and desktop session run as different users. They are two completely different installs of steam.

Yes, but switching between Steam clients causes login and password reset
