### ISSUE TITLE
Black screen after last client beta update

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/SteamOS#732]
Black screen after last client beta update.

Nvidia GTX 1060
Intel core i5 7400

**Comment by jmmcass** [comment]
found same try to do restore and having connection issues

**Comment by kisak-valve** [comment]
Hello @Vladislavuz, per https://github.com/ValveSoftware/steam-for-linux/issues/7874#issuecomment-872105322, please retest this issue.

**Comment by Vladislavuz** [comment]
> Hello @Vladislavuz, per https://github.com/ValveSoftware/steam-for-linux/issues/7874#issuecomment-872105322, please retest this issue.

Problem solved. Thanks
