### ISSUE TITLE
Error processing pulseaudio update 12/19/2013

### ISSUE THREAD

**Issue by Toetje583** [ValveSoftware/SteamOS#74]
`root@steamos:/home/desktop# apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue [Y/n]? y
Setting up pulseaudio (2.0-6.1+steamos3+bsos1) ...
[....]Starting system PulseAudio Daemon:/usr/bin/pulseaudio already running.
invoke-rc.d: initscript pulseaudio, action "start" failed.
dpkg: error processing pulseaudio (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 pulseaudio
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by matcheydj** [comment]
what are the dependencies for pulse, what package manager are you using (you can use dnf or other as well) do you script-chain the pulse devices after boot, or would you like to include kernel mode audio activation?
