### ISSUE TITLE
Control the master volume

### ISSUE THREAD

**Issue by abc-mikey** [ValveSoftware/SteamOS#740]
Could we please have a master volume control?

Not everyone is using big picture mode under Linux is using a TV. Could we please just adjust the sounds levels for our sound cards? I'm sick of adjusting the volume in every game, especially because many have broken sound controls themselves.

**Comment by kisak-valve** [comment]
Hello @abc-mikey, looks like this feature request was previously evaluated at https://github.com/ValveSoftware/SteamOS/issues/146#issuecomment-39657684 and https://github.com/ValveSoftware/SteamOS/issues/146#issuecomment-42244753 and is not expected to be added to SteamOS 2.0.

**Comment by abc-mikey** [comment]
@kisak-valve  it may have been evaluated as not necessary in 2014, in 2021 it's a embarrassment. Revaluate it.
