### ISSUE TITLE
Shouldn't the code here be updated to 3.xx after release?

### ISSUE THREAD

**Issue by Daasin** [ValveSoftware/SteamOS#742]
#### Your system information: 

N/A

#### Please describe your issue in as much detail as possible: 
Not necessarily an Open-Beta but please atleast release the source code here under GPL ahead of any testing, people often try to turn to leaks and that's not ideal for anyone :/

#### Steps for reproducing this issue: 

1. To try and access SteamOS Installer on official websites but can only find out-of-date references and links to the old Debian proposal (Old 3.0) ☹️ 
2. Not any different for those that pre-ordered any of the SteamDeck versions. 
3. Nor is it currently available for devs despite the reveal that people are using it (December Update 20211120.2) and making the information public domain knowledge and therefore publicly accessible. 
 
 
![image](https://user-images.githubusercontent.com/92701426/146656133-dc18d198-9bb7-4b5e-ae10-58c6954de214.png) 
![image2](https://user-images.githubusercontent.com/92701426/146656140-dbda1d7d-97ca-40de-a88c-053faeabb3fc.png)

**Comment by Daasin** [comment]
Could this be considered now that it has likely started distribution under the terms of f-OSS Licenses used? 
 
@Plagman @MrSchism @mdeguzis

**Comment by Daasin** [comment]
> Could this be considered now that it has likely started distribution under the terms of f-OSS Licenses used? 
    
>  @Plagman @MrSchism @mdeguzis  
  
Especially with the usage of GPL Licensed components that have been redistributed, 
if it was atleast *'Source-Available'* on GitHub (or GitLab) then Devs from the community could send contributions via pull requests to help out & improve the Linux DE experience as a whole, even if under a Canonical-Styled CLA :3

**Comment by Daasin** [comment]
> Could this be considered now that it has likely started distribution under the terms of f-OSS Licenses used? 
    
   
  
 @alexvalve @mikela-valve @kisak-valve Could you guys perhaps help us get an update on this enquiry? 
 Especially with the usage of GPL Licensed components that have been redistributed,  
 atleast *'Source-Available'* on GitHub (or GitLab) then Devs from the community could send contributions via pull requests to help out & improve the Linux DE experience as a whole, 
 ***...even if under a Canonical-Styled CLA for the Steam Parts :3***

**Comment by hofq** [comment]
The Steamdeck cad Files are Hosted here, so maybe it also could show up here:

https://gitlab.steamos.cloud/explore/groups

**Comment by Daasin** [comment]
> I see you tagged me, but I don't work for Valve (would love to!), but was really involved with the community when SteamOS came out. From what I understand, shortly following official release, we should be able to use/download/check source for SteamOS 3.0 (based on Arch Linux). I haven't been able to find much else on this at the moment. I'll ping Gabe via email and see if he responds.
> 
> Edit 0: I would expect it to show up in https://repo.steampowered.com/ at some point. But I also have not seen any updates to https://store.steampowered.com/steamos page.

My apologies, I had no idea who to tag and tried to scan through past issues and pull requests 😅

**Comment by LukeShortCloud** [comment]
I've already taken SteamOS 3 packages and made my own portable, gaming optimized, operating system with Mac support.

https://github.com/LukeShortCloud/winesapOS

We could really take our project to the next level if we had access to the source code. Things like tweaking the Mesa package to include Intel OpenGL drivers and maintaining forks of SteamOS packages like linux-neptune on the AUR for all users to enjoy and benefit.

**Comment by FabioLolix** [comment]
Some sources can be found here:

* https://steamdeck-packages.steamos.cloud/archlinux-mirror/sources/holo/
* https://steamdeck-packages.steamos.cloud/archlinux-mirror/sources/jupiter/

With for example a 2.4 GiB tarball for linux-neptune-5.13.0.valve10-3.src.tar.gz, with the PKGBUILD inside the tarball

**Comment by LukeShortCloud** [comment]
@FabioLolix Thanks for sharing those links! That's really helpful and definitely a great start. The next step would be to have public git repositories so the community can more directly contribute back.

**Comment by kisak-valve** [comment]
Mildly off-topic to this issue report, but almost all community contributions should be sent to the various upstream projects instead of SteamOS.

**Comment by Daasin** [comment]
> "...almost all community contributions should be sent to the various upstream projects instead of SteamOS."
 
Was wondering if anybody could confirm any possible future plans for 2.0 code on here to be replaced with 3.0?  
_(I know Holo code is mostly available in other repo sources but wanted to ask if it will eventually be available in the same ways as the last update)_ 

And would firmware update sourcecode be available too by any chance? 😅

**Comment by FabioLolix** [comment]
> Was wondering if anybody could confirm any possible future plans for 2.0 code on here to be replaced with 3.0?

Maybe they will continue to working on their GitLab istance instead of here

https://gitlab.steamos.cloud/explore/groups


Looking at the linux-neptune pkgbuild is their private source at the moment 
```
source=(
  "$_srcname::git+ssh://git@gitlab.internal.steamos.cloud/jupiter/linux-integration.git#tag=$_tag"
```

About the firmware noticed too that was missing later yesterday

***
> almost all community contributions should be sent to the various upstream projects instead of SteamOS.

One want downstream sources to play with them

**Comment by dos1** [comment]
> The next step would be to have public git repositories

It appears that git repositories are already included in at least some of the source package tarballs.

**Comment by LukeShortCloud** [comment]
> Mildly off-topic to this issue report, but almost all community contributions should be sent to the various upstream projects instead of SteamOS.

My intent here with upstreaming is to help Valve get SteamOS 3 ready for the masses. For example, things such as enabling wider driver support in both the Mesa and Linux packages. I am not a C developer but can help with building and packaging. I've been working with many different community-lead SteamOS 3 forks (besides just my own). Would be happy to, at least, share some of our learnings and, at most, contribute directly back into SteamOS.

**Comment by Daasin** [comment]
Should this now be closed due to inactivity & no response being given by Valve?

**Comment by ruineka** [comment]
> > Was wondering if anybody could confirm any possible future plans for 2.0 code on here to be replaced with 3.0?
> 
> Maybe they will continue to working on their GitLab istance instead of here
> 
> https://gitlab.steamos.cloud/explore/groups
> 
> Looking at the linux-neptune pkgbuild is their private source at the moment
> 
> ```
> source=(
>   "$_srcname::git+ssh://git@gitlab.internal.steamos.cloud/jupiter/linux-integration.git#tag=$_tag"
> ```
> 
> About the firmware noticed too that was missing later yesterday
> 
> > almost all community contributions should be sent to the various upstream projects instead of SteamOS.
> 
> One want downstream sources to play with them

Attempting to do this with the 6.06 kernel fails using the PKGBUILD.
```
/linux-neptune-60/archlinux-linux-neptune is not a clone of ssh://git@gitlab.steamos.cloud/jupiter/linux-integration.git
    Aborting...
```

Attempting to clone the git fails with permission issues.

**Comment by GuestSneezeOSDev** [comment]
All the source code and projects can be found [here for all versions and types of steamos](https://steamdeck-packages.steamos.cloud/archlinux-mirror/) a [gnome](https://www.gnome.org/) version (unreleased and unstable) can be found [here](https://steamdeck-packages.steamos.cloud/archlinux-mirror/gnome-unstable-3.6/)  staging and testing can be found [here](https://steamdeck-packages.steamos.cloud/archlinux-mirror/testing-3.6/) and a community debug version of steamos can be found [here](https://steamdeck-packages.steamos.cloud/archlinux-mirror/community-debug-3.5/)

**Comment by Daasin** [comment]
I meant on here too 😅
We've been stuck on an old build.for a while and can't have PR's/issues of the new stuff

**Comment by mdeguzis** [comment]
@GuestSneezeOSDev just a package repo though, not a complete set I don't think that you could build into an Image.

**Comment by GuestSneezeOSDev** [comment]
it is a package repo but you can build an archiso with those packages to make your own steamos https://github.com/holoiso-eol/holoiso https://github.com/HoloISO

**Comment by GuestSneezeOSDev** [comment]
@Daasin valve is no longer making open-source projects and they have changed their licence to the steam subscriber agreement meaning they are allowed to do anything with their OS

**Comment by mdeguzis** [comment]
> @Daasin valve is no longer making open-source projects and they have changed their licence to the steam subscriber agreement meaning they are allowed to do anything with their OS

... What? It's just scripts on top of Arch Linux. The packages are all available in their repo. ChimeraOS and HoloISO would like a word. I understand it would be a heck of a lot easier if they provided an official image. It's just not their focus right now with the Steam Deck.

**Comment by GuestSneezeOSDev** [comment]
> @FabioLolix Thanks for sharing those links! That's really helpful and definitely a great start. The next step would be to have public git repositories so the community can more directly contribute back.

I know winesapOS is using arch linux now but i found this [guide](https://iliana.fyi/blog/build-your-own-steamos-updates/)
