### ISSUE TITLE
Streaming multichannel audio via remote play with SteamOS 3

### ISSUE THREAD

**Issue by Xenophobe-01** [ValveSoftware/SteamOS#743]
#### Your system information

n/a, this a general question, as I don't have SteamOS 3 yet.

#### Please describe your issue in as much detail as possible:
currently in linux streaming multichannel audio does not work properly. see https://github.com/ValveSoftware/steam-for-linux/issues/6150

will this issue be fixed in SteamOS 3.0?

#### Steps for reproducing this issue:

1. connect steam link or device with steam link app to receiver.
2. set pc and steam link/app to 5.1 or 7.1 surround sound.
3. start streaming and test the speakers with the pc's sound applet, or use pavucontrol to check the Recording tab.

**Comment by kisak-valve** [comment]
Hello @Xenophobe-01, speculatively fragmenting the discussion of this issue over multiple issue trackers is not productive.

Closing in favor of the older issue report.
