### ISSUE TITLE
[Feature Request] Provide an ISO image for easy installation on non-UEFI systems

### ISSUE THREAD

**Issue by tecnogaming** [ValveSoftware/SteamOS#75]
I understand UEFI is easy,  easy for the ones that have it.

80% of systems prior to 2012 won't be able to install SteamOS just because of this requirement alone.

What is worse, the people who try to make it work will need to fiddle with custom images and custom grub installation to make it work.

I'm writing within steamOS custom installed on a X58 motherboard with a Xeon processor, so, SteamOS is perfectly capable of running on non-UEFI systems.

As we speak, writing an ISO image to an USB is super easy and there are plenty of good utilities that does this, as Win32DiskImage so there is no point in deniying this method.

**Comment by johnv-valve** [comment]
added this quite a while ago
