### ISSUE TITLE
SteamOS3 - please include Docker or OverlayFS to make services like cups available

### ISSUE THREAD

**Issue by derpelikan** [ValveSoftware/SteamOS#754]
Docker and/or OverlayFS could be great expansion solutions for SteamOS while keeping the rootfs valid. On a failed boot, the integration could just be deactivated. Dockerd could even be deactivated in GameUI, so installed services don't interfere with the experience.
With proper Docker integration, optional services like cups could be managed by users. With full OverlayFS even pacman could be used.

**Comment by nogeenkopjethee** [comment]
Docker (or Podman) support would be nice, since you could use a tool like `toolbox` or `distrobox` to use development tools without disabling the read-only filesystem.

**Comment by SaulGoodman1337** [comment]
Yep we need this !

**Comment by dos1** [comment]
> Dockerd could even be deactivated in GameUI, so installed services don't interfere with the experience.

Docker has support for socket activation, so with:
```
sudo systemctl disable docker.service
sudo systemctl enable docker.socket
```
it will only start on demand.

**Comment by zhulik** [comment]
+1 for docker. Also it should be configured in a way that images and containers survive OS updates. Must have for linux enthusiasts, power users and developers.

**Comment by dos1** [comment]
Docker containers already survive OS updates, you just have to re-install docker itself each time you update.

**Comment by alkazar** [comment]
Podman would be a better fit than Docker because you don't need an additional service running nor root priveleges.

**Comment by emmetoneillpdx** [comment]
Just here to agree that I'd love to see Podman shipped with SteamOS3, particularly for use with [Distrobox](https://github.com/89luca89/distrobox) so that we can easily create mutable "pet containers" on top of the stable base system. This would open up a lot of possibilities for advanced Linux users on SteamOS.

(Docker would also work, but I agree that Podman is really a better fit due to being daemonless and not requiring root to use.)

**Comment by xrishox** [comment]
Please add support for podman on steamos. Podman + distrobox allows for nearly limitless expansion without people needing to unlock the base os. This would be an absolute gamechanger. I agree with the later sentiment that specifically podman would be a better fit for this rather than docker. As a bonus it would be nice to also have distrobox installed by default, but once podman is installed people could just install distrobox manually.

**Comment by xPathin** [comment]
We need this! Docker + Podman or just either support in SteamOS out of the box would be so highly appreciated.
FYI: Docker can also run rootless (https://docs.docker.com/engine/security/rootless/)

**Comment by popsUlfr** [comment]
I made an AppImage of podman if you need a portable way to containerize things: https://github.com/popsUlfr/podman-appimage

In the past I wrote about a manual fakeroot way to get another environment working on the Steam Deck: https://gitlab.com/popsulfr/steam-deck-tricks#use-podman-to-create-a-steamosarch-development-image
In the meantime I put the AppImage together to make everything much easier (includes btrfs driver support, automatically sets up the storage if it detects it's on btrfs [see steamos-btrfs project])

**Comment by bertogg** [comment]
One possible way to add services like cups without touching the rootfs is with systemd-sysext, which is already available, there are some instructions [here](https://blogs.igalia.com/berto/2022/09/13/adding-software-to-the-steam-deck-with-systemd-sysext/).

Probably Podman can also be installed using this method.

**Comment by bertogg** [comment]
FYI the latest SteamOS 3.5 preview image comes with podman and distrobox preinstalled (the usual warnings apply: preview images are unstable and untested, use at your own risk, etc.).

**Comment by zhulik** [comment]
@bertogg amazing news, thanks for letting us know!

**Comment by rafrafek** [comment]
Thank you for providing Podman!

It's currently in version 4.5.1. Is there a way to update it to 4.7 so we can use `podman compose`?

https://stackoverflow.com/a/77448532/9737275

**Comment by bertogg** [comment]
Hi @rafrafek, the packages are updated periodically so there will definitely be a new version of Podman in a future software update. I cannot really tell when that will be, though.

If you really want to have it now I suppose you can try installing Podman using Nix, the single-user installation mode should just work (https://nixos.org/download) but there might be interactions with the Podman that comes with the system, I haven't tested that.

**Comment by bertogg** [comment]
Since SteamOS 3.5 is already shipping Podman I think that we can close this issue.
