### ISSUE TITLE
Feature Request: Use LVM Groups & XDG Compliant Spec by Default.

### ISSUE THREAD

**Issue by Daasin** [ValveSoftware/SteamOS#755]
#### Your system information

* Steam client version: Beta
* SteamOS version: 3.0
* Opted into Steam client beta?: [Unable to on Desktop Mode, see previous bug report] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible: 
 
Now while I understand that the filesystem proposal has been suggested for **_previous_** versions of SteamOS (_1.0 & 2_) via https://github.com/ValveSoftware/steam-for-linux/issues/1890 & https://github.com/ValveSoftware/SteamOS/issues/61 I would like to raise the point for SteamOS _**3.0 on Modern PC's/SteamDeck**_ (_Holo_)
 
**The potential benefits of an "LVM _Group_" are already known, felxibility for users of desktop mode, rollbacks to previous snapshots/backups & security. 
 The same also applies to simple ordered structures that comply with the XDG Base Directory Spec (for Steam Flatpak Add-ons etc)** 

#### Steps for reproducing this issue:

1. N/A (_Feature requests would solve other issues & make life easier/simpler for users_)

**Comment by kisak-valve** [comment]
Hello @Daasin, there's no value in fragmenting the discussion of these issues over another issue report. Closing in favor of the older issue reports.

**Comment by Daasin** [comment]
> Hello @Daasin, there's no value in fragmenting the discussion of these issues over another issue report. Closing in favor of the older issue reports.

How about now? Fixed the issues report since this part hadn't been brought up for SteamOS yet and already causing problems 🤔
