### ISSUE TITLE
Can't close non-Steam game when two non-Steam games are open.

### ISSUE THREAD

**Issue by nogeenkopjethee** [ValveSoftware/SteamOS#758]
# What did I do?
I started the Spotify Flatpak as a non-Steam game in Gaming Mode. After this, I started up a non-Steam game (like PolyMC).

After this, I try to close Spotify from the Steam menu.

# Expected behavior
Spotify closes.

# What happens
Spotify doesn't close. Instead the app stays open or it gets stuck on the SteamOS loading screen.

I can replicate this behavior if I use the Microsoft Edge Beta Flatpak instead of Spotify.

**Comment by kisak-valve** [comment]
Hello @nogeenkopjethee, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/8474. Closing as a duplicate.
