### ISSUE TITLE
[Suggestion] Steam Deck / SteamOS 3.0: Uninstall should include a pop up asking to remove all files.

### ISSUE THREAD

**Issue by BKGaming** [ValveSoftware/SteamOS#759]
Right now if you uninstall a game a lot of left over files get left in the compdata folder taking up space. Give the end user a option to remove all related files in the associated compdata folder (on both SD card and SSD) and give them a warning that removing all files may remove saves, etc if the game doesn't support cloud saves.

**Comment by kisak-valve** [comment]
Hello @BKGaming, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/7418. Closing as a duplicate.
