### ISSUE TITLE
[Request] Support .7z archives in SteamOS 3.0

### ISSUE THREAD

**Issue by WilliamYeske** [ValveSoftware/SteamOS#761]
Ark (the KDE archive tool) optionally depends on a package called p7zip in order to add support for .7z archives. Given that these are extremely popular file types, this package should be included in SteamOS 3.0

[ark package details page](https://archlinux.org/packages/extra/x86_64/ark/) 
[p7zip package details page](https://archlinux.org/packages/extra/x86_64/p7zip/)

**Comment by bertogg** [comment]
Hi, both packages are available in recent betas.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by gunshit** [comment]
So, how can we unzip 7z files? I don't have any beta

**Comment by bertogg** [comment]
The latest stable releases of the OS come with p7zip as well, simply double click on any `.7z` file from the file manager and it will open correctly.

**Comment by gunshit** [comment]
> The latest stable releases of the OS come with p7zip as well, simply double click on any `.7z` file from the file manager and it will open correctly.

Thanks mate ^_^
