### ISSUE TITLE
`ida` from preinstalled `fbida` package cannot be run because of missing `openmotif` / `libXm.so.4`

### ISSUE THREAD

**Issue by Saancreed** [ValveSoftware/SteamOS#764]
#### Your system information

* Steam client version: 1649344803
* SteamOS version: snapshot/20220227.3
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Steam Deck's Plasma session has `ida` from `fbida` package configured as default (and the only one installed?) image viewer. However, attempting to launch it will fail because `libXm.so.4` is missing (because `openmotif` package which provides it is not installed).

#### Steps for reproducing this issue:

On Steam Deck:

1. Switch to desktop session
2. Open Konsole
3. Try to run `ida`

```
(deck@steamdeck ~)$ ida
ida: error while loading shared libraries: libXm.so.4: cannot open shared object file: No such file or directory
(127)(deck@steamdeck ~)$ pacman -F libXm.so.4
community/openmotif 2.3.8-3
    usr/lib/libXm.so.4
(deck@steamdeck ~)$ pacman -Qi openmotif
error: package 'openmotif' was not found
```

Minor suggestion: can we have `gwenview` preinstalled as an image viewer, either instead or in addition to `ida`?

**Comment by bertogg** [comment]
Hey, this has already been fixed in recent betas by replacing `ida` with `gwenview`

**Comment by kisak-valve** [comment]
Closing per the last comment.
