### ISSUE TITLE
"localhost" does not resolve for IPv4

### ISSUE THREAD

**Issue by dos1** [ValveSoftware/SteamOS#765]
On default installation on Steam Deck, `/etc/hosts` is empty, leading to troubles with applications that try to resolve `localhost` into an IPv4 address (an example of that is Frets on Fire which errors out after choosing "start game").

Adding following lines to `/etc/hosts` fixes these issues:
```
127.0.0.1 localhost
127.0.1.1 steamdeck
```

**Comment by smcv** [comment]
Using [nss_myhostname](https://www.freedesktop.org/software/systemd/man/nss-myhostname.html) would probably be a better solution to this than populating `/etc/hosts`.

**Comment by dos1** [comment]
For the reference: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1415

**Comment by dos1** [comment]
Looks like the latest Beta update on Deck includes localhost entries in /etc/hosts, workarounding above Flatpak issue.
