### ISSUE TITLE
Deck: No audio in 32-bit games using ALSA (patch included)

### ISSUE THREAD

**Issue by dos1** [ValveSoftware/SteamOS#766]
On Steam Deck, 32-bit games that use ALSA to output audio (such as _Day of the Tentacle Remastered_ or _Full Throttle Remastered_) remain silent.

Turns out that there are two reasons for that:

1. 32-bit libasound is unable to read the config files from Btrfs filesystem because of 64-bit inodes
2. ALSA `default` device is configured to use PipeWire, but there are no 32-bit PipeWire libraries installed

Point 1 can be fixed by including this patch in `lib32-alsa-lib` package: https://github.com/alsa-project/alsa-lib/pull/223

Point 2 can be fixed by installing `lib32-pipewire` by default.

With these two changes, audio starts to work with above-mentioned games on the Deck.

**Comment by dos1** [comment]
Upstream Arch report for libasound issue: https://bugs.archlinux.org/task/74583

**Comment by bertogg** [comment]
Ideally we would fix 1) by building ALSA with `-D_FILE_OFFSET_BITS=64`, this should be evaluated

**Comment by dos1** [comment]
You'd still need to patch ALSA to make it work with _FILE_OFFSET_BITS=64, because it's using `off_t` in its API which would suddenly change its size.

**Comment by bertogg** [comment]
Thanks, we're aware and this is being worked on :-)

**Comment by bertogg** [comment]
Excellent! Let us know if you find any issues

**Comment by bertogg** [comment]
This bug is fixed in the latest beta

**Comment by dos1** [comment]
I can confirm that this is now fixed in beta as well.

What's the policy on closing issues in here? Is being fixed in beta considered done, or should it wait until in reaches stable?

**Comment by jtrachtenberg** [comment]
I was able to fix this just by forcing proton 7 instead of experimental.

**Comment by dos1** [comment]
This has nothing to do with Proton, and has been already fixed in stable release.
