### ISSUE TITLE
Some titles crashing in current stable mesa on Steam Deck (20220425.5)

### ISSUE THREAD

**Issue by shyney7** [ValveSoftware/SteamOS#767]
#### Your system information

* Steam client version: 1650949507
* SteamOS version: 3.1 (20220425.5)
* Opted into Steam client beta?: No 
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

When playing native games that use mesa in conjunction with OpenGL the current mesa version is causing the games to crash.
Here is a error log:

[hs_err_pid8308.log](https://github.com/ValveSoftware/SteamOS/files/8592228/hs_err_pid8308.log)

This was fixed with the following commit:
[https://gitlab.freedesktop.org/pepp/mesa/-/commit/3cc2fc5dbdb533a12c9fd8392f45c4dfdef312cf](https://steamcommunity.com/linkfilter/?url=https://gitlab.freedesktop.org/pepp/mesa/-/commit/3cc2fc5dbdb533a12c9fd8392f45c4dfdef312cf)

Here is the opened issue:
[https://gitlab.freedesktop.org/mesa/mesa/-/issues/5754](https://steamcommunity.com/linkfilter/?url=https://gitlab.freedesktop.org/mesa/mesa/-/issues/5754)

Here are the bug reports on the developer forum of starsector (he also confirms that this must be driver issues):
* [https://fractalsoftworks.com/forum/index.php?topic=24210.0](https://steamcommunity.com/linkfilter/?url=https://fractalsoftworks.com/forum/index.php?topic=24210.0)
* [https://fractalsoftworks.com/forum/index.php?topic=24340.0](https://steamcommunity.com/linkfilter/?url=https://fractalsoftworks.com/forum/index.php?topic=24340.0)

#### Steps for reproducing this issue:

1. play games that use mesa in conjunction with OpenGL

***Solution: Update mesa driver version***

**Comment by lepwn66** [comment]
Can confirm,I am having the same problem

**Comment by Xuerian** [comment]
I'm not involved (yet), but it seems worth noting that apparently this is resolved with SteamOS 3.3: https://fractalsoftworks.com/forum/index.php?topic=24210.msg369343#msg369343

**Comment by shyney7** [comment]
> I'm not involved (yet), but it seems worth noting that apparently this is resolved with SteamOS 3.3: https://fractalsoftworks.com/forum/index.php?topic=24210.msg369343#msg369343

Yes can be closed
