### ISSUE TITLE
SteamOS-to-go. Run SteamOS from an external USB drive that you can boot up from any machine.

### ISSUE THREAD

**Issue by charlesRedwoodPlains** [ValveSoftware/SteamOS#773]
Windows has a cool little feature called Windows-to-go where a user can install Windows on a portable SSD/HDD and boot that drive on any PC just by plugging in.

This would be great for SteamOS and open up some fun for gamers when they are away from their home station.

**Comment by kisak-valve** [comment]
Hello @charlesRedwoodPlains, historically, Linux does not care about the storage medium it is installed on and this shouldn't need to be considered as an extra feature ahead of time. I'm going to close this for now, but if there's an issue after SteamOS 3 is generally available, then let me know and I'll re-open this issue report.

**Comment by charlesRedwoodPlains** [comment]
There's no effective way to create a portable bootable SteamOS installation.

Give it a try, the installer will install the os on the external drive but
it installs the bootloader on the internal drive which means the external
drive is tied to the internal drive in order to boot.
