### ISSUE TITLE
glibc needs to be updated to latest stable version (2.35)

### ISSUE THREAD

**Issue by SheridanR** [ValveSoftware/SteamOS#776]
#### Your system information

* Steam client version: 1651529636
* SteamOS version: 3.2
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I have built a binary app which links to glibc version 2.35, however my app does not run on SteamOS because the latest version of glibc included here is 2.33.

#### Steps for reproducing this issue:

1. Build and link an app to glibc on another linux distro, eg Fedora
2. Download app onto SteamOS device (eg SteamDeck)
3. Observe app does not run (in a terminal you will see a message eg `/usr/lib/i386-linux-gnu/libc.so.6: version 'GLIBC_2.35' not found`)

**Comment by SheridanR** [comment]
Since most shared libs ultimately depend on libc it is a major hassle to build an app where all libc dependencies are linked statically (or to an older version of glibc). Right now, the only practical way that I know of to do this is to build my app on a system that has version 2.33 (or older) version of glibc installed - eg in a VM of some kind. Given that glibc is consistently updated with new stable builds in early February and August every year, I don't think it should be difficult to also keep it rigorously up-to-date in SteamOS, and it would make nearly every kind of app far more portable to SteamOS.

**Comment by TTimo** [comment]
Linux binaries compiled for Steam for Linux (as is the case for any native titles shipping on Steam Deck) need to be compiled in the 'scout' runtime SDK. See https://github.com/ValveSoftware/steam-runtime for details.
