### ISSUE TITLE
[Feature] Add support for F2FS into Steam OS 3.x Linux kernel

### ISSUE THREAD

**Issue by mdedetrich** [ValveSoftware/SteamOS#777]
* Steam client version: Steam Deck Stable
* SteamOS version: 3
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Currently the linux kernel that is used by SteamOS doesn't support f2fs, i.e. if you do `ls /sys/fs` on a steam deck then `f2fs` is not listed there.

Even if its not used as a default installation, it would be great if the kernel used by SteamOS would come with support for F2FS for those wanting to use it, especially considering that F2FS is designed for flash based storage devices (i.e. nvme/sd card) and also has support for casefolding.

**Comment by bertogg** [comment]
F2FS support is available as a module, did you try `sudo modprobe f2fs` ?
