### ISSUE TITLE
DualShock 4 not working on Steam Deck Beta

### ISSUE THREAD

**Issue by Maykin-99** [ValveSoftware/SteamOS#781]
#### Your system information

* Steam client version: 1651529636
* SteamOS version: 3.2 Beta
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
DS4 Controller should work in the Beta branch. Stable works fine.

More information also available here: https://steamcommunity.com/app/1675200/discussions/1/3269060419623414682/

#### Steps for reproducing this issue:

1. Couple a DS4 Controller to the Steam Deck
2. The light bar is white (instead of blue by default) and Steam doesn't recognize it or its input

**Comment by evelikov** [comment]
Since both stable and beta are moving targets, it's worth mentioning the exact build numbers. It can be found in Settings -> System -> OS Build

**Comment by evelikov** [comment]
Currently the numbers are:
stable - 20220425.2
beta - 20220202.100

**Comment by logan2611** [comment]
Same here, it should be added that this behavior only happens over bluetooth, USB seems to work fine.

**Comment by logan2611** [comment]
DualShock controllers now work on the latest stable and beta versions of SteamOS.

**Comment by Maykin-99** [comment]
Can confirm that it now works on Beta.
