### ISSUE TITLE
Missing lib32-fontconfig breaks fonts in some 32-bit applications

### ISSUE THREAD

**Issue by dos1** [ValveSoftware/SteamOS#785]
Some applications, such as *Steam* (in desktop mode) or *The Beginner's Guide*, rely on font metrics and aliases being configured by the system. This is usually done by fontconfig - however, a 32-bit version of fontconfig isn't installed on SteamOS by default, resulting in issues like bad font selection in Steam or even text being rendered in all tofus as in The Beginner's Guide (easily visible in chapter 4) and possibly a multitude of similar issues in other 32-bit applications.

Installing `lib32-fontconfig` makes the above problems go away.

Observed on SteamOS version: 20220506.1001

**Comment by bertogg** [comment]
Thanks, I can see the problem easily with the Steam client, this will be fixed in the next release.

**Comment by dos1** [comment]
This has been fixed for a while indeed
