### ISSUE TITLE
SteamOS3: Please move functionality from .bashrc

### ISSUE THREAD

**Issue by derpelikan** [ValveSoftware/SteamOS#788]
On current SteamOS3, the .bashrc is filled with 100s of lines of vital code. This is a per-user file and modifying it is very common. On an OS that usually comes with a readonly fs to stop users from breaking things, having vital code at such a place is really intimidating. The code should be moved to another file and only be referenced from .bashrc (or handled by the init system, where possible)

**Comment by bertogg** [comment]
Hi, this has been fixed in the latest beta and all the content has been moved to a system-wide file.

Note that old `~/.bashrc` files are not modified, if you want to start again with a clean one you can use `/etc/skel/.bashrc` as a template.

**Comment by bertogg** [comment]
This has also been fixed in the latest stable release
