### ISSUE TITLE
SteamDeck: get rid of useless preinstalled applications and replace them with useful ones

### ISSUE THREAD

**Issue by zocker-160** [ValveSoftware/SteamOS#790]
#### Your system information

* Steam client version: not relevant
* SteamOS version: 3.1 (20220425.2)
* Opted into Steam client beta?: No 
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Currently SteamOS ships with preinstalled applications that take up space but are useless for probably 99% of all SteamOS users.

Affected programs are including, but not limited to:

- Qt Assistant
- Qt Designer
- Qt Linguist
- Qt QDBusViewer
- Qt V2L2 test Utilit
- Qt V2L2 video capture utility

![Screenshot_20220520_011820](https://user-images.githubusercontent.com/36563538/169420263-e0315b06-d8af-4659-b8aa-9e032f4a5315.png)

On the other hand though, SteamOS does not come with tools that are needed for **very** basic functionality expected to be present on absolutely every PC like:

- a text editor (how about Kate?)
- an image viewer (Gwenview?)
- an audio player
- a video player

also what on earth is `ida`? It does not do anything when selecting it in this menu.

![Screenshot_20220520_012339](https://user-images.githubusercontent.com/36563538/169420668-841a5917-5900-455d-8aa6-b229743dd9ef.png)

#### Steps for reproducing this issue:

1. reserve and buy a Steam Deck ( :P )
2. update to latest version
3. try to open an image / text file / audio file / video file

#### Personal Opinion

In my opinion I think this is _extremely_ important and a huge oversight from Valve, because Steam Deck is the first encounter into the Linux world for a lot of ppl and not being able to do very basic thing + ppl not knowing the names of the needed applications (Kate, Gwenview etc) will cause frustration and a very bad user experience.

**Comment by bertogg** [comment]
For the record recent beta images come with KWrite and replace ida with Gwenview

**Comment by zocker-160** [comment]
ah good to know, thanks for that info @bertogg!

I still think that removing the Qt stuff would make sense to save some space.

**Comment by arrowgent** [comment]
qt tools might be packaged depenedencies as a bundle, removing them would require removing qt dependencies.
also might be used as accessibility options

im not sure of the specifics of those applications included (mentioned) maybe they are extraneous

**Comment by zocker-160** [comment]
@arrowgent they can be uninstalled on vanilla Arch without any consequences, so I think it should be possible for Valve in SteamOS too, unless I am missing something important.

**Comment by evelikov** [comment]
Most of the Qt utilities listed are part of [qt5-tools](https://archlinux.org/packages/testing/x86_64/qt5-tools/) (weighting in at 15MiB). The package is essential for [plasma-workspace](https://archlinux.org/packages/extra/x86_64/plasma-workspace/) (think plasmashell) and its dependencies - [plasma-nm](https://archlinux.org/packages/extra/x86_64/plasma-nm/), [plasma-pa](https://archlinux.org/packages/extra/x86_64/plasma-pa/) and [systemsettings](https://archlinux.org/packages/extra/x86_64/systemsettings/) to name a few.

Removing the programs is possible but requires heavy and careful surgery - which given the size isn't worth it.

**Comment by sevmonster** [comment]
If the Qt programs bother you enough, just remove their desktop files. The only way they are going away is if Valve ships their own custom Qt5/KDE packages that strip `qt5-tools` as dependencies or remove the shortcuts/etc from `qt5-tools`.

In the grand scheme of things, even the base model Deck is not affected by the meager amount of space KDE and its dependencies take up compared to even a simple game from Steam, or the Soldier environment.

(ed. Actually, it looks like they might have already hidden the Development category from the app launcher?? at least I can't see it anymore on latest Preview build.)

As for audio player and video player, they are often so divisive that I think it better to leave it up to the end user to pick their favorite. You do not often see that kind of peculiarity with image viewers so Gwenview works fine in that regard I think.

**Comment by zocker-160** [comment]
understood and they are also preinstalling Gwenview and Kwrite, which was my main complaint, closing
