### ISSUE TITLE
Joystick option absent from controller configuration

### ISSUE THREAD

**Issue by strycore** [ValveSoftware/SteamOS#793]
#### Your system information

* Steam client version: Stable and Beta
* Opted into Steam client beta?: Yes

#### Please describe your issue in as much detail as possible:

When configuring a controller through Steam, on the joysticks, there is no option to act as an actual joystick.
Furthermore, when loading a gamepad profile the joysticks are set too "Joystick move" but when you go customize this, it gets set back to nothing.

#### Steps for reproducing this issue:

1.  Plug in a joystick
2.  Open the Controller section in Steam settings, select Desktop Configuration
3.  Configure any stick on the pad, notice that "Joystick" is absent from the list

This has been reproduced on Pop 22.04, Fedora 36 and the Steam Deck, on Steam stable and Beta.

**Comment by strycore** [comment]
Here you can see the Joystick Move options getting set to nothing because the option is not present.

https://user-images.githubusercontent.com/280336/171958331-fe082156-fde1-42e8-bea9-bd9d5534cb2d.mp4

**Comment by kisak-valve** [comment]
Hello @strycore, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/7289. Closing as a duplicate.
