### ISSUE TITLE
Betaflight HID-compliant game controller not recognized

### ISSUE THREAD

**Issue by krislabs** [ValveSoftware/SteamOS#801]
#### Your system information

* Steam client version: 1654818235
* SteamOS version: 3.2
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Betaflight 4.x HID joystick isn't recognized at all as a controller when connected via USB OTG adapter or USB hub to Steam Deck. It works fine on Windows 10/11 though.
https://github.com/betaflight/betaflight/wiki/HID-Joystick-Support
https://github.com/betaflight/betaflight/issues/9377
https://oscarliang.com/betaflight-fc-fpv-simulator/

#### Steps for reproducing this issue:

1. Go into Desktop mode.
2. Connect flight controller with HID joystick function enabled using cable and USB hub or OTG adapter.
3. Go to _Settings_ > _Input Devices_ > _Game Controller_.
4. There is no new gamepad visible in _Device:_ droplist.

**Comment by kisak-valve** [comment]
Hello @krislabs, skimming betaflight#9377, this is the wrong part of the linux ecosystem to report this issue. Instead, your feedback should be directed towards libSDL2 and figuring out why it's having a hard time with the controller before progress can be made here. Please report this issue to https://github.com/libsdl-org/SDL and/or to betaflight.

**Comment by krislabs** [comment]
I finally got it detected using some other OTG adapter (FiiO CL06). USB hub strangely didn't work even with external power. However I get no input similarly to this:
https://github.com/ValveSoftware/SteamOS/issues/800
