### ISSUE TITLE
black screen after finish install reboot

### ISSUE THREAD

**Issue by QHM-MING** [ValveSoftware/SteamOS#815]
install holoISO with KVM, after install finish I got black screen

**Comment by bertogg** [comment]
holoISO is a third-party project, I don't think this is relevant for this issue tracker.

For the record, SteamOS 3 does not generally work on a VM (not at the moment at least), but if you want to try it with _limited functionality_ you can use the desktop mode, see here for an **unofficial** tutorial: https://blogs.igalia.com/berto/2022/07/05/running-the-steam-decks-os-in-a-virtual-machine-using-qemu/
