### ISSUE TITLE
[Bug] Issues with the "Add to Steam" dolphin right-click menu functionality

### ISSUE THREAD

**Issue by popsUlfr** [ValveSoftware/SteamOS#821]
#### Your system information

* Steam client version:
  - Built: Jul 30 2022, at 04:09:05
  - Steam API: v020
  - Steam package versions: 1659369000
* SteamOS version: 3.3 20220726.100
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Yes 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Hello,

there's a kde service menu that's installed as part as the base system which allows to quickly add a non-steam game to the Steam client from the dolphin file explorer:

![Screenshot_20220808_121934_crop](https://user-images.githubusercontent.com/1030423/183400031-b90ee299-cf06-4d7a-a56b-7539c3d89b05.png)

But it has a few issues I've encountered that require user intervention for the shortcut to finally work:

* Adding an executable that is not marked as executable (`chmod +x`) results in a shortcut that points to the temporary `.desktop` file that is stored in `/tmp` which will not be available on subsequent boots. (usually .exe files that one wishes to execute through proton do not need to be marked as executable)

![Screenshot_20220808_122122_crop](https://user-images.githubusercontent.com/1030423/183400565-2219dfa0-65d7-4e8a-8aa0-f5d4ec478f32.png)

* Marking the executable as *executable* resolves this.
* Now the successful shortcut will have weird extraneous quotes `"` added
* If the path to the executable contains spaces, it will be cut off short

![Screenshot_20220808_122401_crop](https://user-images.githubusercontent.com/1030423/183401168-191deb9c-8656-4c32-80c7-8d5287fa147b.png)

**Comment by bertogg** [comment]
The problem with the spaces in the filename is that the generated desktop file contains quotes and triggers this bug: https://github.com/ValveSoftware/steam-for-linux/issues/8164

See also https://github.com/ValveSoftware/SteamOS/issues/830

**Comment by bertogg** [comment]
The problem with non-executable files seems to me like a bug in the Steam client or in the "Add to Steam" Dolphin action. At the very least it should fail with an error.

However I don't know if there's a general solution because depending on the program that you're adding you would need a different interpreter, `.exe` files are not the only ones that you can open, there are also shell scripts, Python files or even native Linux binaries.

**Comment by bertogg** [comment]
Hi @popsUlfr , the latest preview release (20221010.1000) should handle the problems that you report. If you try it and still have issues please let me know. Thanks!

**Comment by popsUlfr** [comment]
@bertogg Thanks for looking into this. I'm on the preview channel and I am up to date but the issues are all still present.

**Comment by bertogg** [comment]
> The OS Build version says 20221003.100, do I need to unlock Advanced Update Channels and switch to the Main channel ?

Yes, it's the main channel. You can also wait until the changes reach beta, but I don't know how long that can take.

> I don't think Steam should be smart about this, just blindly create a shortcut to the pointed file. If the file does not have execute permissions, then trying to start it will simply fail (user error). But a user could have made a custom compatibility tool that can interpret the file or a windows executable that can be started with a proton compatibility tool.

In this new version .exe files are added as-is whether they have the executable bit or not. Linux native binaries still require executable permissions, and you'll see an error message if they don't have them.

**Comment by popsUlfr** [comment]
Ok, I switched to main and can confirm that these issues are fixed in `20221010.1000` ! Thank you. :+1:

**Comment by bertogg** [comment]
Thanks for testing it!
