### ISSUE TITLE
[Bug] Unable to close non-Steam applications when multiple are running in "Gaming Mode"

### ISSUE THREAD

**Issue by wesleyote** [ValveSoftware/SteamOS#823]
#### Your system information

* Steam client version: 1659369000
* SteamOS version: 20220729.1000
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Expected behavior:
The application closes when pressing its corresponding "Exit game" button in the Steam menu and confirming.

Actual behavior:
The application remains open and all running applications now have a grey, unpressable "Exiting game..." button.

#### Steps for reproducing this issue:

1. Enter Desktop Mode.
2. Download two Flatpak applications from the Discover store. For example, Firefox and Discord.
3. Enter Steam and navigate to Games > Add a Non-Steam Game to My Library... > Select the two Flatpaks > ADD SELECTED PROGRAMS.
4. Return to Gaming Mode.
5. Launch both applications so that both are running and visible in the Steam menu.
6. Close one using its "Exit game" button.

**Comment by kisak-valve** [comment]
Hello @wesleyote, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/8474. Closing as a duplicate.
