### ISSUE TITLE
[Feature Request/Adjustment: Boot] Allow more options for the Steamdeck in the UEFI (or BIOS) Menus 

### ISSUE THREAD

**Issue by Daasin** [ValveSoftware/SteamOS#824]
#### Your system information

* Steam client version: Latest Beta as of August 10th
* SteamOS version: 3
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Literally as stated in title, ideally should have same configurability as PC Motherboard Vendors allow via updates. 

#### Steps for reproducing this issue:

1. 
2.  N/A
3.

**Comment by kisak-valve** [comment]
Hello @Daasin, as a generic and non-specific request for more settings that can potentially put the hardware in a suboptimal configuration, this feature request isn't viable.

If there's a specific UEFI setting that is needed, then the hardware devs can ponder that separately.
