### ISSUE TITLE
Some flatpak apps won't run from Steam

### ISSUE THREAD

**Issue by missionfloyd** [ValveSoftware/SteamOS#830]
#### Your system information

* Steam client version: 1660688177
* SteamOS version: 3.3.1 Build 20220817.1
* Opted into Steam client beta?: no
* Opted into SteamOS beta?: no
* Have you checked for updates in Settings > System?: yes

#### Please describe your issue in as much detail as possible:
Take [Mednaffe](https://steamcommunity.com/linkfilter/?url=https://flathub.org/apps/details/com.github.AmatCoder.mednaffe), for instance. This works fine when run from the terminal.
```
"/usr/bin/flatpak" run --command=mednafen com.github.AmatCoder.mednaffe "/home/deck/Roms/Saturn/Sonic R/Sonic R (USA, Brazil).cue"
```
But it won't run when added as a non-steam game, whether in game mode or desktop. No errors, just nothing. The non-flatpak Mednafen binary does work, however.

Here's the log from trying to run it.
```
[2022-08-16 16:35:43] Game 12367352156997550080 adding PID 1967 as a tracked process "/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=2879498563 -- "/usr/bin/flatpak" run --command=mednafen com.github.AmatCoder.mednaffe "/home/deck/Roms/Saturn/Sonic R/Sonic R (USA, Brazil).cue""
[2022-08-16 16:35:43] Game 12367352156997550080 adding PID 1968 as a tracked process
[2022-08-16 16:35:43] Game 12367352156997550080 no longer tracking PID 1968, exit code -1
[2022-08-16 16:35:43] Game 12367352156997550080 no longer tracking PID 1967, exit code 0
```

Similarly, [Flycast](https://flathub.org/apps/details/org.flycast.Flycast) doesn't work when launched from Steam, either,
```
"/usr/bin/flatpak" run org.flycast.Flycast -config window:fullscreen=yes "/home/deck/Roms/Dreamcast/Sonic Adventure (USA).cue"
```
but it does if you do it this way.
```
org.flycast.Flycast -config window:fullscreen=yes "/home/deck/Roms/Dreamcast/Sonic Adventure (USA).cue"
```
and for some reason. once the latter is run, the former suddenly works. I noticed the same thing with [MAME](https://flathub.org/apps/details/org.mamedev.MAME).

This workaround doesn't work with the Mednaffe command above because it needs to pass the `--command=mednafen` argument to flatpak.

I've tried re-imaging my Steam Deck, didn't help.

Edit: More apps that refuse to run from Steam.
[Nestopia](https://flathub.org/apps/details/ca._0ldsk00l.Nestopia)
[DOSBox Staging](https://flathub.org/apps/details/io.github.dosbox-staging)
[DOSBox-X](https://flathub.org/apps/details/com.dosbox_x.DOSBox-X)

This problem severely impacts the Steam Deck's usability.

[Others](https://steamcommunity.com/app/221410/discussions/0/3272436686701284923/) have reported this problem as well.

**Comment by missionfloyd** [comment]
I got it so spit out an error.
```
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
error: Invalid byte sequence in conversion input
```

**Comment by bertogg** [comment]
Hello, I can run Mednaffe, but I did find a problem.

I went to the desktop and added a launcher like this (`foobar.desktop`):

```
[Desktop Entry]
Name=Foo Bar on the SNES
Exec=/usr/bin/flatpak run --command=mednafen com.github.AmatCoder.mednaffe /home/deck/Roms/foobar.smc
Type=Application
Encoding=UTF-8
```
Then opened Steam, added that as a non-Steam game, went back to Gaming Mode and ran the game. **This works fine**.

However I see that if the `Exec` line has quotes then this doesn't work, e.g from your example:

```
Exec="/usr/bin/flatpak" run --command=mednafen com.github.AmatCoder.mednaffe "/home/deck/Roms/Saturn/Sonic R/Sonic R (USA, Brazil).cue"
```

What happens if you select the game on Steam, click the settings button, then select Properties -> Shortcut -> Launch options? Do you see the full Flatpak command-line options?

**Comment by missionfloyd** [comment]
I'm using [Steam ROM Manager](https://github.com/SteamGridDB/steam-rom-manager) for this, not Add to Steam.

The Steam shortcut does contain the full command, with quotes. I have other flatpak apps (Dolphin, DuckStation, xemu) added exactly the same way, and they do work.

**Comment by bertogg** [comment]
Ok but what do you see when you go to the game and select Settings -> Properties? Can you paste the exact contents of "Target", "Start In" and "Launch Options"?

**Comment by missionfloyd** [comment]
Target: `"/usr/bin/flatpak"`
Start in: `/usr/bin`
Launch Options: `run --command=mednafen com.github.AmatCoder.mednaffe "/home/deck/Roms/Saturn/Sonic R/Sonic R (USA, Brazil).cue"`

I've also tried putting the hole command in "Target".

Another one that doesn't work.
Target: `"/usr/bin/flatpak"`
Start in: `/usr/bin`
Launch Options: `run org.flycast.Flycast -config window:fullscreen=yes "/home/deck/Roms/Dreamcast/Sonic Adventure (USA).cue"`

A couple that do.
Target: `"/usr/bin/flatpak"`
Start in: `/usr/bin`
Launch Options: `run org.DolphinEmu.dolphin-emu "/home/deck/Roms/Dolphin/GZLE01.iso"`

Target: `"/usr/bin/flatpak"`
Start in: `/usr/bin`
Launch Options: `run org.duckstation.DuckStation "/home/deck/Roms/PS1/Metal Gear Solid (USA).m3u"`

**Comment by bertogg** [comment]
Does it work if you use file names without spaces or other strange characters?

```
$ cat sonic.desktop 
[Desktop Entry]
Type=Application
Name=Sonic
Exec=/usr/bin/flatpak run --command=mednafen com.github.AmatCoder.mednaffe /home/deck/Roms/Sonic/sonic.cue
```

This works just fine for me after I add it to Steam, I don't need to tweak anything.

**Comment by tlneondo** [comment]
I have also noticed that, specifically, a Flatpak application will not run if the Steam entry's name has been changed. Whereas if it is added and left alone, things will tend to work.

**Comment by missionfloyd** [comment]
Target: `/usr/bin/flatpak`
Start in: `/usr/bin`
Launch Options: `run --command=mednafen com.github.AmatCoder.mednaffe /home/deck/Roms/Saturn/Sonic/Sonic.cue`

Doesn't make a difference. That wouldn't be it anyway, I have others (see above) with spaces, quotes, and parentheses that work fine.
