### ISSUE TITLE
[Steam Deck] On-screen keyboard misses keystrokes

### ISSUE THREAD

**Issue by missionfloyd** [ValveSoftware/SteamOS#831]
#### Your system information

* Steam client version: 1660688177
* SteamOS version: 3.3.1 Build 20220817.1
* Opted into Steam client beta?: no
* Opted into SteamOS beta?: no
* Have you checked for updates in Settings > System?: yes

#### Please describe your issue in as much detail as possible:
In desktop mode, when entering text with the OSK, I have to type very slowly and meticulously, otherwise it misses keystrokes.

Seems to work okay in game mode.

#### Steps for reproducing this issue:

1. Go to desktop mode.
2. Open Konsole.
3. Open the OSK with STEAM+X.
4. Type something.

**Comment by RodoMa92** [comment]
Same identical issue here. Touchpad work correctly, but using the touchscreen cause half of the input to be ingnored (the device vibrate confirming the input, but no text input appears anywhere).

**Comment by missionfloyd** [comment]
Looks like it's been [fixed](https://store.steampowered.com/news/app/1675200?emclan=103582791470414830&emgid=3308480236507403332).
