### ISSUE TITLE
Cannot use d-pad and A button anymore in EFI loaders

### ISSUE THREAD

**Issue by lwbt** [ValveSoftware/SteamOS#832]
#### Your system information

* Steam client version: 1660688177
* SteamOS version: 3.3.1
* BIOS Version: F7A0105
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Expected behavior: Boot into the EFI loader of a different operating system and move around with d-pad, select options with the `A` button. This has worked before (regression).

Actual behavior: The menu appears to be stuck. An external USB keyboard is required to get past the menu and into to other operating systems.

#### Steps for reproducing this issue:

1. Connect an external storage device with an EFI binary which displays a menu. (I'm using Grub to start Windows 2 Go and Ubuntu among a variety of other tools like PassMark MemTest. Systemd Boot and Syslinux may also be affected)
2. Start your Steam Deck while holding the volume minus (`-`) button.
3. Select the external drive to boot from and wait until the EFI loader has been loaded.
4. Try to navigate in the menu. 

#### Background information

Under System > Updates > Software Updates > (Y) Patch Notes an entry published on July 20 reads:

> Steam Deck OS Stable Update: nothing to see here
>
> [...] updated with a hotfix to enable compatibility with future system and **input** firmware [...]

The functionality worked before and stopped working after this update.

If there is a more appropriate place to file bugs for specific components of SteamOS or the Steam Deck platform (firmware, I guess), please let me know.

**Comment by fledermaus** [comment]
Hi - thanks for the report - this is being looked into.

**Comment by lwbt** [comment]
From my point of view it works again with recent versions from the stable branch on Steam Deck/SteamOS.

You may close this issue.

**Comment by kisak-valve** [comment]
Hello @lwbt, glad to hear that this is behaving for you. Closing per the last comment.
