### ISSUE TITLE
qt-wayland missing so can't launch OBS Studio from game scope

### ISSUE THREAD

**Issue by samrocketman** [ValveSoftware/SteamOS#842]
#### Your system information

* Steam client version: any
* SteamOS version: latest on Deck
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

Launch OBS studio from desktop mode and it can stream.

Launch OBS studio from game mode and it refuses to launch.

I wrote a bash script as a wrapper for launching to capture logs and it doesn't launch due to missing qt[5 or 6?]-wayland

#### Steps for reproducing this issue:

1. Install OBS through discover
2. Add OBS as non-steam game to steam
3. Logout or reboot to get back to gamescope
4. Launch OBS

It immediately fails to launch

**Comment by ebassi** [comment]
A couple of quick questions:

- from which software repository did Discover install OBS?
- if OBS wasn't installed from Flathub, does installing it from Flathub work as expected?

**Comment by bertogg** [comment]
This has been fixed in the latest preview image (20221025.1000) and there's no need to edit the properties anymore, this issue can be closed.

**Comment by samrocketman** [comment]
Nice! I look forward to trying it; thank you!
