### ISSUE TITLE
[Feature Request] Add a proper way to close a window opened by desktop application running in game mode

### ISSUE THREAD

**Issue by KrisCris** [ValveSoftware/SteamOS#845]
#### Your system information

* Steam client version: 1662598759
* SteamOS version: 3.3.1
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

On Steam Deck, I would add some desktop applications to the Steam library so that I can run it without going to desktop mode.

Some applications may have secondary windows, e.g. settings. Once they are opened, I am unable to close them since game mode hides the title bar. 

Even though I am able to switch between windows by pressing the Steam button, some applications may be designed to only save changes on window-closed.

I am not asking to bring back the title bar, but at least I hope we can close a window from where we do the window switch.

#### Steps for reproducing this issue:

1. Add a desktop application to the steam library
2. open it in game mode
3. open a secondary window, like settings
4. try to close the window

**Comment by missionfloyd** [comment]
> I am not asking to bring back the title bar, but at least I hope we can close a window from where we do the window switch.

This already works. Press X to close the window.

**Comment by KrisCris** [comment]
> You already can. Press X to close the window.

Thanks!!
