### ISSUE TITLE
[SteamDeck] On-screen keyboard key selection skipping rows of letters only while docked

### ISSUE THREAD

**Issue by Shaunathanz** [ValveSoftware/SteamOS#851]
#### Your system information

* Steam client version: 1660688177
* SteamOS version: 3.3.1
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
When tilting the analog stick of a connected controller in a vertical direction I expect the key selector to shift up / down a row of keyboard keys. What happens is that the selector skips a row, which makes the keyboard unusable unless you’re using the Steam Deck trackpads to select keys.

#### Steps for reproducing this issue:

1. Connect the Steam Deck to an external display (4k@60Hz tested in gaming mode)
2. Bring up on-screen keyboard anywhere
3. Use the analog stick or d-pad on the Steam Deck or an external controller to vertically navigate the rows of the keyboard

**Comment by robbybutterton** [comment]
I also have this issue.

**Comment by Shaunathanz** [comment]
Sounds like this is fixed on beta & preview branches but I can't verify myself
