### ISSUE TITLE
[Steam Deck] Allow USB drives to be used in Game Mode

### ISSUE THREAD

**Issue by missionfloyd** [ValveSoftware/SteamOS#852]
#### Your system information

* Steam client version: 1660688177
* SteamOS version:  20220817.1
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
When connecting a USB drive, the SD card icon appears the top of the screen, suggesting that it can be used for Steam games. Clicking it takes us to the Format SD Card option on settings.
![20220918203231_1](https://user-images.githubusercontent.com/4073789/190942973-b908018d-3cf0-4474-baff-6c8d331709fd.png)

Selecting Format will, predictably, format the SD card.
![20220918203240_1](https://user-images.githubusercontent.com/4073789/190943268-eab1f3f9-d6f7-4548-8b94-5ee3c6707fca.png)

Or at least attempt to and fail, if there's no card inserted.
![20220918203247_1](https://user-images.githubusercontent.com/4073789/190943313-737329eb-6d95-4caa-bb60-7425e944af1d.png)

Ideally, it should allow the user to select which external drive/partition to format, and allow for multiple to be mounted. This would be useful when used with a dock, or as a way to offload games to a large external drive to avoid having to redownload them in the future (as with Xbox Series X/S and PS5).

**Comment by bertogg** [comment]
Yeah, that "Format SD card" button is only formatting the card inserted in the SD slot of the Steam Deck. I don't think the icon should appear if you connect a USB drive.

**Comment by bertogg** [comment]
The latest beta image (build 20221111.100) allows you to use an external drive, although you have to format it yourself in your computer:

https://store.steampowered.com/news/app/1675200/view/3383920059429575957

**Comment by bertogg** [comment]
SteamOS 3.5 allows mounting and formatting external USB drives so this issue can be closed.
