### ISSUE TITLE
Client/Beta preview: Controller update service running every boot

### ISSUE THREAD

**Issue by parkerlreed** [ValveSoftware/SteamOS#859]
#### Your system information

* Steam client version: 1663888700
* SteamOS version: 20220922.00
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Every boot on preview is running the jupiter-controller-update service and taking nearly 30s to do so

```
(1)(deck@steamdeck build)$ systemd-analyze blame | head -5
28.334s jupiter-controller-update.service
 1.979s ldconfig.service
 1.800s systemd-random-seed.service
 1.050s dracut-pre-mount.service
  625ms initrd-switch-root.service
(deck@steamdeck build)$ systemctl status jupiter-controller-update.service 
○ jupiter-controller-update.service - Jupiter Controller Firmware Update Service
     Loaded: loaded (/usr/lib/systemd/system/jupiter-controller-update.service; disabled; vendor preset: disabled)
     Active: inactive (dead) since Mon 2022-09-26 13:40:09 EDT; 1min 53s ago
    Process: 892 ExecStart=/usr/bin/jupiter-controller-update (code=exited, status=0/SUCCESS)
   Main PID: 892 (code=exited, status=0/SUCCESS)
        CPU: 1.619s

Sep 26 13:40:09 steamdeck jupiter-controller-update[1043]: Waiting for app to enumerate: -
Sep 26 13:40:09 steamdeck jupiter-controller-update[1043]: Waiting for app to enumerate: \
Sep 26 13:40:09 steamdeck jupiter-controller-update[1043]: Waiting for app to enumerate: |
Sep 26 13:40:09 steamdeck jupiter-controller-update[1043]: Waiting for app to enumerate: /
Sep 26 13:40:09 steamdeck jupiter-controller-update[1043]: Waiting for app to enumerate: |
Sep 26 13:40:09 steamdeck jupiter-controller-update[1043]: SUCCESS
Sep 26 13:40:09 steamdeck jupiter-controller-update[892]: Firmware updated to 1663179557
Sep 26 13:40:09 steamdeck systemd[1]: jupiter-controller-update.service: Deactivated successfully.
Sep 26 13:40:09 steamdeck systemd[1]: Finished Jupiter Controller Firmware Update Service.
Sep 26 13:40:09 steamdeck systemd[1]: jupiter-controller-update.service: Consumed 1.619s CPU time.
```

#### Steps for reproducing this issue:

1. Opt into preview
2. Observe longer boot times with jupiter-controller-update

**Comment by parkerlreed** [comment]
Boot plot from systemd-analyze

![boot](https://user-images.githubusercontent.com/841440/192346075-6c9ca46b-8849-477a-b147-6a8e544f8057.png)

**Comment by parkerlreed** [comment]
Full update service output from journalctl

https://gist.github.com/parkerlreed/052ef0d407d7ac4a0b5fa13145eea733

**Comment by rawdatafeel** [comment]
Your system information

    Steam client version: x
    SteamOS version: x
    Opted into Steam client beta?: Yes
    Opted into SteamOS beta?: Yes
    Have you checked for updates in Settings > System?: Yes

Full update service output from journalctl

https://gist.github.com/rawdatafeel/68f42eb0538e811020104993fc6f4e1d

**Comment by parkerlreed** [comment]
@rawdatafeel So yours is booting fine? No long controller update?

**Comment by rawdatafeel** [comment]
> @rawdatafeel So yours is booting fine? No long controller update?

No update from what I can tell, but I still have an abnormally long bootup time

Output from systemd-analyze blame 
https://gist.github.com/rawdatafeel/3466053cc8a46c6b2651490bc8b7765f

**Comment by parkerlreed** [comment]
> Your system information
> 
> ```
> Steam client version: 1663888700
> SteamOS version: 20220914.1000
> Opted into Steam client beta?: Yes
> Opted into SteamOS beta?: Yes
> Have you checked for updates in Settings > System?: Yes
> ```
> 
> Full update service output from journalctl
> 
> https://gist.github.com/rawdatafeel/68f42eb0538e811020104993fc6f4e1d

I now realize this one is also showing the long behavior, just not verbose for some reason.

**Comment by parkerlreed** [comment]
Even while booted I can repeatedly run it and it just doesn't update

```
(B)(root@steamdeck deck)# time /usr/bin/jupiter-controller-update
PTS: 1663179565, STS: 1663179565
[
  {
    "path": "/dev/hidraw3",
    "vendor_id": 10462,
    "product_id": 4613,
    "serial_number": "MEDA21408252",
    "release_number": 256,
    "manufacturer_string": "Valve Software",
    "product_string": "Steam Deck Controller",
    "usage_page": 65535,
    "usage": 1,
    "interface_number": 2,
    "build_timestamp": 1663179565,
    "secondary_build_timestamp": 1663179565,
    "is_bootloader": false
  }
]
UPDATE: Type 1 device is running build '1663179565', updating to build 1663179557
Found candidate device, build timestamp 1663179565, BL false, BL_Type 1, HYB false
Updating Type 1 System
2022-09-26 14:20:23,701 - __main__ - INFO - Looks like we are running an app. Resetting into bootloader
Switching to ISP mode: |                                                                                                                                                                                                                                                                                                    
Erasing: |                                                                                                                                                                                                                                                                                                                  
Programming: [##############################################################################################################################################################################################################################################################################################] 174.9 KiB 100%
Waiting for app to enumerate: |                                                                                                                                                                                                                                                                                             
SUCCESS
Firmware updated to 1663179557

real    0m24.211s
user    0m1.230s
sys     0m0.358s
```

**Comment by parkerlreed** [comment]
Manually pulled the updated jupiter-hw-support from the repo, extracted, changed the controller update script to point to the relative firmware files.

No difference. Tries to update to the same build but seemingly never does even though it prints SUCCESS.

**Comment by rkarstens** [comment]
Please provide the output of journalctl for the subsequent boots. And a copy of the /usr/bin/jupiter-controller-update script fro this image.  

 I tested 3x types of units Type I, II, and III and the issue only originally occurred on types I and II.  The problem was that the expected build timestamp did not match that of the FW image it loaded.  I have corrected that.

That said, the build timestamp running 565 is the correct one and the script file (listed above) that is checked into jupiter-hw-support on branch jupiter-3.3.2 has the correct values. This commit is tagged and is referenced by the PKGBUILD file for HW support on the beta branch of the "holo" repo.  This is all easily verified.

So, all should be behaving properly AFAICT.  So, please provide follow-on details.

**Comment by parkerlreed** [comment]
journalctl --boot=0

https://gist.github.com/682067530145260f0035b032203f26b8

boot=-1

https://gist.github.com/604ae59bba0580549a18c34f5cee5b5d

Controller update script https://gist.github.com/27e69579e064e33e3a676d5b92e9b066

**Comment by rkarstens** [comment]
Yeah that’s not the updated script. Dunno.

**Comment by parkerlreed** [comment]
jupiter-hw-support-3.3.2.20220926.1-1 is available as a pacman update but not applied. I assume this is the fix but I assume is not advised to install it manually.

The one shipped on the current preview is upiter-hw-support-3.3.2.20220922.1-1-

**Comment by parkerlreed** [comment]
> Manually pulled the updated jupiter-hw-support from the repo, extracted, changed the controller update script to point to the relative firmware files.
> 
> No difference. Tries to update to the same build but seemingly never does even though it prints SUCCESS.

An update to this. I erroneously downloaded the 0922 which was already installed. I will manually try the 0926 and report back

**Comment by parkerlreed** [comment]
Yes the 0926 package fixes the check. Thanks for the confirmation and will await a preview update. Thank you.

```
(deck@steamdeck bin)$ sudo ./jupiter-controller-update 
PTS: 1663179565, STS: 1663179565
[
  {
    "path": "/dev/hidraw3",
    "vendor_id": 10462,
    "product_id": 4613,
    "serial_number": "MEDA21408252",
    "release_number": 256,
    "manufacturer_string": "Valve Software",
    "product_string": "Steam Deck Controller",
    "usage_page": 65535,
    "usage": 1,
    "interface_number": 2,
    "build_timestamp": 1663179565,
    "secondary_build_timestamp": 1663179565,
    "is_bootloader": false
  }
]
NO UPDATE: Type 1 device is running latest build 1663179565
```

**Comment by NoCodeLeftBehind** [comment]
I also have this slow boot issue with the Steam Deck preview channel build of 0922 due to the controller firmware being flashed at every boot. It appears the problem is that the 0922 jupiter-controller-update script that was installed with the preview identifies the current firmware for device types D20 and D21 as 1663179557 when the latest is actually 1663179565 (for those 2 types but not RA). So, when the script determines it needs to install the included "new" firmware, it really only installs the included 565 firmware binary, then on next boot does the same again because the installed 565 version still doesn't match the script's "current" and expected 557.

What is the best way for an end user to fix this while awaiting a new preview release?   Install the fixed "jupiter-hw-support-3.3.2.20220926.1-1" from pacman (a user above advises we should not)? Or, simply edit the lines at the top of the installed /usr/bin/jupiter-controller-update script to identify 1663179565 as the current firmware for device types D20 and D21?

**Comment by rkarstens** [comment]
I did exactly what you suggest while debugging this.  Change the TIMESTAMP lines below as indicated.  You'll need to clear the steamos-readonly flag on the file and use root permissions though.


```
# D21 Date 14-Sep-2022
CURRENT_D21_FIRMWARE_TIMESTAMP=**1663179565**
CURRENT_FIRMWARE_FILE_D21=/usr/share/jupiter_controller_fw_updater/D21_APP_REL_63221B25.bin

# D20 Date 14-Sep-2022
CURRENT_D20_FIRMWARE_TIMESTAMP=**1663179565**
CURRENT_FIRMWARE_FILE_D20=/usr/share/jupiter_controller_fw_updater/D20_APP_REL_63221B25.bin
```

**Comment by parkerlreed** [comment]
> (a user above advises we should not)

Because most users even on preview are not going to understand/want to unlock read write rootfs. That's why I did my testing manually downloading the package and modifying the file paths in the script. 

If you are comfortable with unlocking rootfs and updating, then yes installing the updated package would work (Or the manual script above one comment above)

**Comment by james2432** [comment]
I also have this. I'm only on the preview channel, 

``` 1min 18.022s jupiter-controller-update.service
      1.593s systemd-random-seed.service
      1.281s systemd-resolved.service
      1.141s dracut-pre-mount.service
       689ms initrd-switch-root.service
       427ms sdcard-mount@mmcblk0p1.service
       265ms user@1000.service
       251ms dracut-pre-udev.service
       188ms iwd.service
       178ms dracut-pre-pivot.service
       173ms jupiter-biosupdate.service
       167ms dracut-initqueue.service
       161ms dracut-cmdline.service
       129ms initrd-parse-etc.service
       118ms systemd-udev-trigger.service
       112ms upower.service
       106ms udisks2.service
```


```○ jupiter-controller-update.service - Jupiter Controller Firmware Update Service
     Loaded: loaded (/usr/lib/systemd/system/jupiter-controller-update.service; disabled; vendor preset: disabled)
     Active: inactive (dead) since Thu 2022-09-29 18:45:49 EDT; 11min ago
    Process: 897 ExecStart=/usr/bin/jupiter-controller-update (code=exited, status=0/SUCCESS)
   Main PID: 897 (code=exited, status=0/SUCCESS)
        CPU: 3.975s

Sep 29 18:44:33 steamdeck jupiter-controller-update[897]: Updating Hybrid SECONDARY of Type 2 System
Sep 29 18:44:41 steamdeck jupiter-controller-update[1146]: 2022-09-29 18:44:41,709 - __main__ - INFO - Uploading /usr/share/jupiter_control>
Sep 29 18:45:06 steamdeck jupiter-controller-update[1146]: SUCCESS
Sep 29 18:45:06 steamdeck jupiter-controller-update[897]: Updating PRIMARY of Type 2 System
Sep 29 18:45:10 steamdeck jupiter-controller-update[2590]: 2022-09-29 18:45:10,672 - __main__ - INFO - Uploading /usr/share/jupiter_control>
Sep 29 18:45:49 steamdeck jupiter-controller-update[2590]: SUCCESS
Sep 29 18:45:49 steamdeck jupiter-controller-update[897]: Firmware updated to 1663179557
Sep 29 18:45:49 steamdeck systemd[1]: jupiter-controller-update.service: Deactivated successfully.
Sep 29 18:45:49 steamdeck systemd[1]: Finished Jupiter Controller Firmware Update Service.
Sep 29 18:45:49 steamdeck systemd[1]: jupiter-controller-update.service: Consumed 3.975s CPU time.```

It's running every boot and takes over a minute to startup

**Comment by james2432** [comment]
Seems the modified date doesn't match what's in the script file
![image](https://user-images.githubusercontent.com/498547/193159523-62c2d774-3e6e-4eee-adaa-a7e182f46680.png)

**Comment by rkarstens** [comment]
Correct. Executive decision to just modify the script to reflect the date reported by the FW and leave the firmware filenames (essentially moot) the same.

Rich

------- Original Message -------

**Comment by james2432** [comment]
Ok so I modified the script a bit to output the modified times of files on disk:

```
D21: 1663182784
D20: 1663179557
RA: 1663182784
```
the buildtime stamp and the secondary(from firmware) are:
```
build_timestamp: 1663179565, secondary_build_timestamp: 1663179565
```
the issue is on line 118:
```
elif [[ $bootloader_type -eq 2 ]]; then

    if [[ ${build_timestamp} -eq $CURRENT_D21_FIRMWARE_TIMESTAMP ]] && [[ ${secondary_build_timestamp} -eq $CURRENT_D21_FIRMWARE_TIMESTAMP || ${secondary_build_timestamp} -eq  $CURRENT_D20_FIRMWARE_TIMESTAMP  ]]; then
      info "NO UPDATE: Type 1/2 Device is running latest build $CURRENT_D21_FIRMWARE_TIMESTAMP"
    else
      needupdate=1
      info "UPDATE: Type 1/2 Device is running builds ($build_timestamp | $secondary_build_timestamp), updating to build ($CURRENT_D21_FIRMWARE_TIMESTAMP | $CURRENT_D21_FIRMWARE_TIMESTAMP or $CURRENT_D20_FIRMWARE_TIMESTAMP)"
    fi
```
if I replace the values of the if statement:
```
if [[ 1663179565 -eq (Script: 1663179557 File modified time: 1663182784)]] && [[ 1663179565 -eq (Script:1663179557  File Modified Time1663182784) || 1663179565 -eq  (Script: 1663179557 File Modified Time: 1663179557]]; then
```
it will always return false

So either the firmware is reporting the wrong time or the logic on line 118 is messed up because it will always be false even if you took the file modification time

**Comment by james2432** [comment]
> I did exactly what you suggest while debugging this. Change the TIMESTAMP lines below as indicated. You'll need to clear the steamos-readonly flag on the file and use root permissions though.
> 
> Note the timestamp value of **1663179565**
> 
> ```
> # D21 Date 14-Sep-2022
> CURRENT_D21_FIRMWARE_TIMESTAMP=1663179565
> CURRENT_FIRMWARE_FILE_D21=/usr/share/jupiter_controller_fw_updater/D21_APP_REL_63221B25.bin
> 
> # D20 Date 14-Sep-2022
> CURRENT_D20_FIRMWARE_TIMESTAMP=1663179565
> CURRENT_FIRMWARE_FILE_D20=/usr/share/jupiter_controller_fw_updater/D20_APP_REL_63221B25.bin
> ```

you might as well replace the RA one as well because it compares it to the build timestamp a little bit lower, i'm not sure how it's determinining the bootloader type(revivions of hardware?)

```
# D21 Date 14-Sep-2022
#CURRENT_D21_FIRMWARE_TIMESTAMP=1663179557
CURRENT_D21_FIRMWARE_TIMESTAMP=1663179565
CURRENT_FIRMWARE_FILE_D21=/usr/share/jupiter_controller_fw_updater/D21_APP_REL_63221B25.bin

# D20 Date 14-Sep-2022
#CURRENT_D20_FIRMWARE_TIMESTAMP=1663179557
CURRENT_D21_FIRMWARE_TIMESTAMP=1663179565
CURRENT_FIRMWARE_FILE_D20=/usr/share/jupiter_controller_fw_updater/D20_APP_REL_63221B25.bin

# RA Date 14-Sep-2022
#CURRENT_RA_FIRMWARE_TIMESTAMP=1663179557
CURRENT_RA_FIRMWARE_TIMESTAMP=1663179565
CURRENT_FIRMWARE_FILE_RA=/usr/share/jupiter_controller_fw_updater/RA_APP_REL_63221B25.bin
```

**Comment by rkarstens** [comment]
Only the data timestamps for D21 and D20 were off and those are the only ones that need to be changed.

The 3.3.2 Beta Candidate (now Beta) has the correct script.  (this is attached below).

The timestamp (reported by firmware) and used to compare to the timestamp variables is embedded int the firmware image and is not easily visible. 

FYI, the bootloader version is described in the USB descriptor returned by an enumerated device 0x0100, 0x0200, 0x0300, but that's not related to this.

[jupiter-controller-update.zip](https://github.com/ValveSoftware/SteamOS/files/9684416/jupiter-controller-update.zip)

**Comment by parkerlreed** [comment]
Fix is live! Thank you
