### ISSUE TITLE
SteamOS tenfoot obsolete by broken chat function

### ISSUE THREAD

**Issue by Turpster** [ValveSoftware/SteamOS#870]
#### Your system information

* Steam client version: 7/10/22
* SteamOS version: 7/10/22
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] Yes
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When entering Steam Big Picture, you can use the chat function. However, the chat function now is in a loading state endlessly.

Making all consoles of steam obsolete. Also making Big Picture as a whole obsolete as unable to communicate and invite your friends in any game. Or even to chat with them.

It is not me alone who is experiencing this issue:
https://steamcommunity.com/groups/bigpicture/discussions/1/3365901132013461070/

#### Steps for reproducing this issue:

1. Open Steam (Beta/Stable)
2. Click on Big Picture (-tenfoot)
3. Use chat function

**Comment by kisak-valve** [comment]
Hello @Turpster, this is an issue with the Steam client, not SteamOS as a platform, and you've already reported this at https://github.com/ValveSoftware/steam-for-linux/issues/8833. Please do not intentionally open duplicate issue reports.

Closing as a duplicate.
