### ISSUE TITLE
[Query] Asking whether Valve Devs even see these filed issues & response if they do

### ISSUE THREAD

**Issue by Daasin** [ValveSoftware/SteamOS#879]
#### Your system information

* Steam client version: [Latest Beta at timestamp of post]
* SteamOS version: [Latest Beta at timestamp of post]
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

#### **Please describe your issue in as much detail as possible:**
Describe what you _expected_ should happen and what _did_ happen.
> This is just to ask if SteamOS Devs see this or whether we're wasting our time with filing for issue/feature requests & asking questions. If they do see this, could they acknowledge this repo with a response? 
 
 >> _**_Another_** thing would be to enable the discussions tab in the GitHub Repo settings which is just a tickbox but allows a space for non-issue discussions that require more Back & Forth and are also more longer-term in nature._ 
 
#### **Steps for reproducing this issue:**

1. Opening repo settings tab in GitHub next to the issues tab & enabling discussions feature which is next to the 'Wiki' option. 
2. To make an initial announcement post in the discussions forum that acknowledges that this repo isn't abandoned, archived, inactive & that you've seen the issues made by the users of SteamOS 3 in the community. 
3. N/A

**Comment by kisak-valve** [comment]
Hello @Daasin, yes, issues reported here do get evaluated.

**Comment by Daasin** [comment]
By the same people who submitted the most Commits/PR's? I've never seen them respond in here before unless it was back when the Debian builds were the base of SteamOS :/ @kisak-valve

**Comment by Daasin** [comment]
By the same people who previously submitted the most Commits/PR's? I've never seen them respond in here before unless it was back when the Debian builds were the base of SteamOS :/ 
Like @Plagman or @mdeguzis
