### ISSUE TITLE
External Display - Bug with the Steam Menu and Quick Action Menu.

### ISSUE THREAD

**Issue by SentaiBrad** [ValveSoftware/SteamOS#885]
#### Your system information

* Steam client version: 1666399660
* SteamOS version: 3.3.2
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] Yes
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When in game mode using an external display, I expect that Steam will display its Left Steam Menu properly when pressing (in this case) the PS Button, and I expect (in this case) PS Button + X to open the Quick Access Menu on the right.

What is happening, is that the left menu appears off-center slightly and down with some items running off the screen. The QAM doesn't appear at all. The rest of the screen dims a bit as if it is open, but does not display. Images of the problem are attached at the bottom.

But I have found a fix.

Under "display", I turned off "Automatically Set Resolution", and set it to 1280x800@120. After the screen refresh, both menus appear with my controller and on my external display. The kicker is, if at this point I turn back on automatic resolution (RIGHT after having just turned it off and selecting 1280x800), both menus display correctly.

![20221022_215301](https://user-images.githubusercontent.com/26223818/197374547-adf6af78-5d8b-44bd-990e-c37562c20f44.jpg)

![20221022_215316](https://user-images.githubusercontent.com/26223818/197374552-4c20159b-9fa4-4ced-88fa-8a716f2c6517.jpg)

**Comment by MadByteDE** [comment]
#### Your system information

* Steam client version: 1666399660
* SteamOS version: 3.3.2
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] Yes
* Have you checked for updates in Settings > System?: [Yes/No] Yes

Similar issue for me:
![image](https://i.imgur.com/HI524Tc.jpg)

This happens everytime after boot or after switching from desktop to gaming mode. Unplugging and re-plugging the USB-C connection fixes the issue.

- Using the official Steam Deck dock
- Using Display Port
- Default screen resolution is 2560x1440

**Comment by MadByteDE** [comment]
Cross-posted in Steam Community discussion.
https://steamcommunity.com/app/1675200/discussions/1/3490878556693817717/

**Comment by SentaiBrad** [comment]
Would also like to mention that this display bug affects applications and games as well. In particular noted here https://github.com/sonic2kk/steamtinkerlaunch/issues/640#issuecomment-1289269779

I am helping to contribute what I can to SteamTinkerLaunch, and what I originally thought was a bug with STL was directly related to the display bug here. So it's more than just the SteamOS GameMode UI.

> Cross-posted in Steam Community discussion. https://steamcommunity.com/app/1675200/discussions/1/3490878556693817717/

I appreciate you making the issue known to more folks.

**Comment by Samsagax** [comment]
Enter Developer Mode, switch off OpenGL compositor. That should fix it.

**Comment by lostgoat** [comment]
This should be fixed in the latest steam client beta.

**Comment by MadByteDE** [comment]
* Steam client version: 1666913041
* SteamOS version: 3.3.2

I re-tried the procedure to see if the issue still persists & the issue changed: Now, on boot or restart, my external monitor will stay off/dark until I re-connect the USB-C cable - so it somehow got worse.


> Enter Developer Mode, switch off OpenGL compositor. That should fix it.

@Samsagax I tried it and it helped as in the external monitor now showing the UI after boot/restart & the scaling of the Steam Menu was correct - but now the underlying UI elements won't render when any of the overlay menu's is open.

![missing UI](https://i.imgur.com/XKkIw6M.png)

**Comment by lostgoat** [comment]
> I re-tried the procedure to see if the issue still persists & the issue changed: Now, on boot or restart, my external monitor will stay off/dark until I re-connect the USB-C cable - so it somehow got worse.

This sounds unrelated to this issue. Would be best to open a new issue for that.

After replugging the USB-c cable and with the GL compositor turned on, do things work correctly?

**Comment by MadByteDE** [comment]
>After replugging the USB-c cable and with the GL compositor turned on, do things work correctly?

Yes, after re-plugging the USB-C cable after restart/boot with GL compositor ON everything works correctly.

>This sounds unrelated to this issue. Would be best to open a new issue for that.

Will do, thanks.

**Comment by lostgoat** [comment]
Closing as fixed. Thanks for the report and the info everyone.

**Comment by pacoa-kdbg** [comment]
This issue is still present when using an aspect ratio of 3:2 with resolution of 960x640.

Resolutions above 1280 work fine ( like 1440x960)
