### ISSUE TITLE
Can't switch to KDE Plasma desktop mode after "Cloud Sync fix" beta update

### ISSUE THREAD

**Issue by JLP** [ValveSoftware/SteamOS#886]
After this Steam Deck client beta update it is not possible to switch to desktop mode anymore. When you select Switch to Desktop the power menu just popsup again and the switch does not happen.
SteamOS version is from Preview channel: 3.3.2 build 20221005.1

**Comment by blakejrobinson** [comment]
To add to this, I noticed it does say 'Switching to desktop mode' briefly before the power menu pops up again (which suggests the button is doing something - it's the switching process that's not working).

**Comment by TTimo** [comment]
Thanks - this will be fixed in the next beta update.

**Comment by ahjolinna** [comment]
the new update has fixed the issue

OS Build 20221026.1000

(now just waiting for the kernel, mesa & kde update...which I hope will arrive soon™ :D )

**Comment by JLP** [comment]
I can confirm, fixed with latest update
