### ISSUE TITLE
pipewire crashes on the Main channel

### ISSUE THREAD

**Issue by popsUlfr** [ValveSoftware/SteamOS#890]
#### Your system information

* Steam client version: latest Beta
* SteamOS version: 20221028.1000
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Main channel for the system, Beta for the Steam Client
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

When opening the audio menu in the bottom right in desktop mode, pipewire crashes in a loop.
Using flatpak Discord it doesn't detect any input and output device.

#### Steps for reproducing this issue:

1. Go to desktop mode
2. Open the Audio volume Menu
3. pipewire crashes

or

1. Open Discord flatpak from gaming mode or desktop mode
2. There are no input or output devices

- [pipewire-journalctl.log](https://github.com/ValveSoftware/SteamOS/files/9893810/pipewire-journalctl.log)
- [pipewire-coredump.gz](https://github.com/ValveSoftware/SteamOS/files/9893815/pipewire-coredump.gz)

I switched to the Main channel since I've been having issues with the Beta channel and the Stable channel is missing a lot of bugfixes.

Also in the audio settings of the Deck UI, the options look different to before:
![20221029155559_1](https://user-images.githubusercontent.com/1030423/198835518-ceab8e4d-6077-4594-8c28-bbd197c3ad7c.jpg)
![20221029155634_1](https://user-images.githubusercontent.com/1030423/198835524-01e376ef-6d99-4d30-b582-80b7cb842543.jpg)

**Comment by bertogg** [comment]
Thanks for the report, this will be fixed soon

**Comment by bertogg** [comment]
This is fixed in the latest _Main_ images.

**Comment by popsUlfr** [comment]
> This is fixed in the latest _Main_ images.

I can confirm that pipewire doesn't crash anymore on **20221101.1001**. Thank you! :+1: 

Is the very verbose naming of the devices intentional ? Before it was just "Speakers" and "External device" I think.

Also while I have your intention, listening on journalctl I'm seeing that fancontrol has become very spammy. It's printing every second to the journal:

```
...
Nov 02 14:25:58 steamdeck-richter-white fancontrol.py[911]: CPU: 50.0/0  GPU: 49.0/0  SSD: 37.9/0  P_APU: 2.1/2.1  Fan[CPU]: 10/0
Nov 02 14:25:59 steamdeck-richter-white fancontrol.py[911]: CPU: 50.0/0  GPU: 49.0/0  SSD: 37.9/0  P_APU: 2.0/2.1  Fan[CPU]: 10/0
Nov 02 14:26:00 steamdeck-richter-white fancontrol.py[911]: CPU: 50.0/0  GPU: 49.0/0  SSD: 35.9/0  P_APU: 2.2/2.1  Fan[CPU]: 10/0
Nov 02 14:26:01 steamdeck-richter-white fancontrol.py[911]: CPU: 50.0/0  GPU: 49.0/0  SSD: 35.9/0  P_APU: 2.1/2.1  Fan[CPU]: 10/0
Nov 02 14:26:02 steamdeck-richter-white fancontrol.py[911]: CPU: 50.0/0  GPU: 49.0/0  SSD: 35.9/0  P_APU: 2.1/2.1  Fan[CPU]: 10/0
Nov 02 14:26:03 steamdeck-richter-white fancontrol.py[911]: CPU: 50.0/0  GPU: 49.0/0  SSD: 35.9/0  P_APU: 2.1/2.1  Fan[CPU]: 10/0
Nov 02 14:26:04 steamdeck-richter-white fancontrol.py[911]: CPU: 50.0/0  GPU: 49.0/0  SSD: 35.9/0  P_APU: 2.1/2.1  Fan[CPU]: 10/0
Nov 02 14:26:05 steamdeck-richter-white fancontrol.py[911]: CPU: 50.0/0  GPU: 49.0/0  SSD: 35.9/0  P_APU: 2.1/2.1  Fan[CPU]: 10/0
Nov 02 14:26:06 steamdeck-richter-white fancontrol.py[911]: CPU: 50.0/0  GPU: 49.0/0  SSD: 35.9/0  P_APU: 2.1/2.1  Fan[CPU]: 10/0
Nov 02 14:26:07 steamdeck-richter-white fancontrol.py[911]: CPU: 50.0/0  GPU: 49.0/0  SSD: 35.9/0  P_APU: 2.1/2.1  Fan[CPU]: 10/0
Nov 02 14:26:08 steamdeck-richter-white fancontrol.py[911]: CPU: 50.0/0  GPU: 49.0/0  SSD: 37.9/0  P_APU: 2.1/2.1  Fan[CPU]: 10/0
Nov 02 14:26:09 steamdeck-richter-white fancontrol.py[911]: CPU: 50.0/0  GPU: 49.0/0  SSD: 37.9/0  P_APU: 2.1/2.1  Fan[CPU]: 10/0
...
```

**Comment by kisak-valve** [comment]
Thanks for retesting @popsUlfr. Please open a separate issue report for the follow up issue.
