### ISSUE TITLE
[SteamDeck] TRIM is not enabled by default affecting lifespan of eMMC / SSD

### ISSUE THREAD

**Issue by rstrube** [ValveSoftware/SteamOS#898]
#### Your system information

* Steam client version: 1667866781
* SteamOS version: 3.3.2
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
The systemd timer that periodically runs TRIM on your SSD is disabled by default.  This will degrade the life of the SSD, as "wear leveling" won't work correctly.  Because the SteamDeck has either eMMC or an SSD, TRIM should be enabled by default to maximize the lifespan of the drive.

#### Steps for reproducing this issue:

1. Switch to "Desktop Mode"
2. Make sure you've set a password with `passwd`
3. Open a terminal
4. Enter: `sudo systemctl status fstrim.timer`
5. Note that the `fstrim.timer` is disabled by default

**Comment by kisak-valve** [comment]
Hello @rstrube, it looks like adjustments to this was already in the works and there's improved behavior with the [SteamOS 3.4 preview build](https://store.steampowered.com/news/app/1675200/view/3383920059429575957).

Please opt into SteamOS's beta update channel and retest.

**Comment by kisak-valve** [comment]
Closing as implemented.
