### ISSUE TITLE
"AaaaaAAaaaAAAaaAAAAaAAAAA!!! for the Awesome" with sixaxis controller: axis and buttons are mapped incorrectly

### ISSUE THREAD

**Issue by aaronp24** [ValveSoftware/SteamOS#90]
Start [AaaaaAAaaaAAAaaAAAAaAAAAA!!! for the Awesome](http://store.steampowered.com/app/15560) with a PS3 sixaxis controller attached via USB.

Expected result: the right thumb stick can be used for aiming

Observed result: the right thumb stick's Y axis controls the camera's X axis.  As far as I can tell, there's no way to control the camera's Y axis.

In addition, the Select button jumps.

**Comment by ProfessorKaos64** [comment]
If you have configured your controller int he Steam settings menu, you will need to contact the developer on the Steam discussions board or directly. If this is only partial to SteamOS/Linux, I'd imagine Valve needs more details than "it doesn't work".

**Comment by aaronp24** [comment]
Eh, I'm pretty sure I did configure it, but it was a long time ago and I've long since stopped caring.  Closing.
