### ISSUE TITLE
Wake on lan with dock turns on only deck’s display

### ISSUE THREAD

**Issue by francois-pasquier** [ValveSoftware/SteamOS#906]
#### Your system information

* Steam client version: 1666117138
* SteamOS version: 3.3.2
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
When the steam Deck is connected to an external display and to Ethernet (I.e through a dock/hub), then receiving a WOL packet should result in the external display being used instead of the deck’s.

I am pretty sure this is unintentional as manually waking the deck through the power button results in the correct behavior.

#### Steps for reproducing this issue:

1. Plug deck to a dock
2. turn on external display
3. Put deck to sleep
4. Send a wake-on-lan packet to the dock MAC address
5. See the deck display being used instead of the external display

**Comment by robled** [comment]
I've been wanting to use wake on lan with the official dock, but it doesn't work for me.  Is this supported?  Is there some sort of configuration on the deck (OS or BIOS) needed to make this work, caveats with the display notwithstanding?

**Comment by syberphunk** [comment]
I believe Wireless Wake on LAN is disabled on the WiFi driver in SteamOS - but I haven't checked details for the dock.

**Comment by robled** [comment]
Someone is [claiming](https://www.reddit.com/r/SteamDeck/comments/zwuija/comment/j28qzer/?utm_source=share&utm_medium=web2x&context=3) that the JSAUX dock supports this feature.  I checked the specs on the JSAUX dock on their site but didn't see anything about wake on LAN.  Is OP using one of those docks?

**Comment by francois-pasquier** [comment]
> Someone is [claiming](https://www.reddit.com/r/SteamDeck/comments/zwuija/comment/j28qzer/?utm_source=share&utm_medium=web2x&context=3) that the JSAUX dock supports this feature. I checked the specs on the JSAUX dock on their site but didn't see anything about wake on LAN. Is OP using one of those docks?

Yes I am using the JSAUX dock

**Comment by robled** [comment]
Thanks for the info!  I find it a bit surprising that the official dock doesn't support this but a cheaper third party dock does.

**Comment by rstanuwijaya** [comment]
I am using the JSAUX dock but have been unable to set up WOL. 

When checking using ngrep, I can receive the [magic packet](https://wiki.archlinux.org/title/Wake-on-LAN#Using_ngrep). 
```
# ngrep '\xff{6}(.{6})\1{15}' -x port 9
```

It seems like the ethernet is not powered when the deck is on sleep. Anyone can confirm?

**Comment by indykoning** [comment]
> Sorry if this is unrelated. I am using the JSAUX dock but have been unable to set up WOL.
> 
> When checking using ngrep, I can receive the [magic packet](https://wiki.archlinux.org/title/Wake-on-LAN#Using_ngrep).
> 
> ```
> # ngrep '\xff{6}(.{6})\1{15}' -x port 9
> ```
> 
> It seems like the ethernet is not powered when the deck is on sleep. Anyone can confirm?

Can confirm, i'm playing with it as well with a JSAUX dock. using the same instructions as you i enabled wol
`nmcli c modify "Wired connection 1" 802-3-ethernet.wake-on-lan magic`

Unfortunately it does not wake from suspend, when i keep the network settings open, suspend it and then start it back up i see that it's trying to connect to ethernet. Thus suggesting that it disconnects from ethernet while suspended and being unable to respond to the WOL packet.

I haven't been able to figure out how to keep ethernet connected yet.

**Comment by maxpavlov** [comment]
@indykoning how do you prevent USB from sleeping in SteamOS si that WOL will work?

**Comment by qiwichupa** [comment]
still relevant. The bug is reproduced on these versions:
- OS version: 3.5.7
- Steam version: 1702079146

**Comment by rstanuwijaya** [comment]
@francois-pasquier Any update if this issue will be fixed in the next preview/beta release?

**Comment by francois-pasquier** [comment]
> @francois-pasquier Any update if this issue will be fixed in the next preview/beta release?

I closed this issue as the official dock does not support Wake on lan and it’s been more than one year so I guess valve is not going to look into this.

**Comment by Hatsune-Cthulhu** [comment]
@francois-pasquier Why are you closing other people's issues on behalf of a company that you don't work for?

**Comment by Cyan101** [comment]
This is still an issue, WoL is supported by the deck so displays turning on should be too

**Comment by rstanuwijaya** [comment]
@francois-pasquier i think it is better to reopen the issue, otherwise others will need to open a seperate thread to track the same problem.

Valve can close the issue when the problem is resolved or when the acknowledge it's a non-fix.

**Comment by kisak-valve** [comment]
Hello, #1322 was opened as a continuation of this issue report. Please use that issue report to discuss this issue going forward.
