### ISSUE TITLE
Final fantasy 14 keyboard does not work and bugs out steam and three dot button 

### ISSUE THREAD

**Issue by Jrwcmj** [ValveSoftware/SteamOS#910]
#### Your system information

* Steam client version: 166854410
* SteamOS version: 3.3.2
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes 
Final fantasy 14 keyboard does not come up when even using steam and X or set button as show keyboard and also makes steam and three dots button slow or unresponsive 

#### Steps for reproducing this issue:

1. Launch final fantasy 14
2. Press steam and X to get keyboard up no response 
3. Press steam button takes a few attempts,
4. Add button in controller config to show keyboard 
5. Go back to game use button for show keyboard does not work 
6. Exit game 
7. Steam and button glitchy so restart steam deck 
8. Repeat with testing final fantasy 14 still not working and same issues with steam and three dots so restart steam deck again 
9. Test to see if just final fantasy 14 keyboard issue 
10. Keyboard works in another game and no steam or three dots issues

**Comment by Pobega** [comment]
I'm running into this same issue. I believe it started happening after today's update on stable channel, though I could be mistaken. I purchased the game this morning and the on-screen keyboard was working, then I got an update and can no longer login in gaming mode.

**Comment by Jrwcmj** [comment]
True was working fine till the new update for me

**Comment by Pobega** [comment]
Was able to work around the issue using XIVLauncher from Flathub (https://goatcorp.github.io/faq/steamdeck.html), but this issue is still occurring when launching the game directly.

**Comment by Jrwcmj** [comment]
I tried using an external keyboard and it worked to login and after that not issues ,must be something to do with the login launcher

**Comment by Jrwcmj** [comment]
Newest update address this issue
