### ISSUE TITLE
No audio output on SteamDeck from HDMI

### ISSUE THREAD

**Issue by dsyer** [ValveSoftware/SteamOS#916]
#### Your system information

SteamDeck

* Steam client version: 1668654410
* SteamOS version: 3.3.2
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Plug in HDMI cable connected to TV. 

Expected: Audio should come from TV and HDMI Output Device should show up in Audio settings.

Actual: Audio output stuck on built in speakers. No HDMI outputs listed in Audio settings.

#### Steps for reproducing this issue:

1. Plug in HDMI cable
2. Look at Audio settings

Steam Support have been trying to help me but they apparently only know how to do 2 things ("Battery storage mode" and "re-image the device"). This seems to me like a software problem.

**Comment by dsyer** [comment]
UPDATE: I found a solution here https://askubuntu.com/a/1316585/895838 (install PulseAudio and select HDMI output in Configuration menu). Surely that shouldn't be necessary?

**Comment by kisak-valve** [comment]
Hello @dsyer, this issue is already being tracked at #873. Closing as a duplicate.
