### ISSUE TITLE
sshd_config should include "AcceptEnv LANG LC_*"

### ISSUE THREAD

**Issue by docwhat** [ValveSoftware/SteamOS#933]
#### Your system information

* Steam client version: 1671133277
* SteamOS version: 3.4 build 20221214.100
* Opted into Steam client beta?: yes
* Opted into SteamOS beta?: yes 
* Have you checked for updates in Settings > System?: yes

#### Please describe your issue in as much detail as possible:

The `sshd` service should include `AcceptEnv LANG LC_*` in `/etc/ssh/sshd_config` to allow the locale to be set correctly when logging in.

Example without `AcceptEnv` set:

```sh
$ locale                                             
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
$ ssh steamdeck.lan locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

This is what I expected:

```sh
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
$ ssh steamdeck locale                               
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Symptoms include weird character issues and commands that use Unicode not working correctly, especially when calling directly with `ssh -t`.

**Comment by bertogg** [comment]
That's how openssh comes configured [by default](https://github.com/openssh/openssh-portable/blob/V_9_1/sshd_config), but you can edit `sshd_config` if you want.

**Comment by bertogg** [comment]
If you are using SteamOS 3.5.2 (preview branch) you can add your own config snippet to `/etc/ssh/ssh_config.d/`, so I think this issue can be closed.

**Comment by bertogg** [comment]
This is now in the SteamOS 3.5 stable releases.
