### ISSUE TITLE
Support for hid-nintendo

### ISSUE THREAD

**Issue by cybik** [ValveSoftware/SteamOS#935]
#### Your system information

* Steam client version: 1671601575
* SteamOS version: SteamOS 3.4
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Kernel 5.13 does not have hid-nintendo. Is it possible to backport it? Or is the next major SteamOS upgrade using kernel 6.0, which already has the module?

**Comment by bertogg** [comment]
Hello, the idea is to move towards 6.x, see issue #954.

**Comment by bertogg** [comment]
The images from the _main_ channel come with `hid-nintendo` already and therefore it will be available in SteamOS 3.5.

**Comment by kisak-valve** [comment]
Closing per the last comment.
