### ISSUE TITLE
compress the initramfs and the kernel with zstd or lz4

### ISSUE THREAD

**Issue by unclejack** [ValveSoftware/SteamOS#939]
dracut's default for initramfs is gzip. gzip isn't exactly fast when it comes to compression and decompression. Most other distributions have migrated away from gzip. Arch Linux is using zstd for their initramfs.

dracut has support for multiple compression programs.
```
compress="{cat|bzip2|lzma|xz|gzip|lzo|lz4|zstd|<compressor [args...]>}"
```
The kernel used by SteamOS 3.x doesn't include the more recent version of the zstd code. zstd would be the best choice for a 6.0+ kernel. lz4 would be an appropriate choice for the current 5.13 kernel. We could use lz4 now and switch to zstd when the kernel is upgraded.

What needs to be changed?
A file called /etc/dracut.conf.d/compress.conf can be created with the following content:
```
compress="lz4"
```

I've tested this change. It works on the SteamOS 3.4.2 release. The recovery initramfs was 6 MB larger than before. It should decompress a bit faster than before.

The kernel is compressed with xz. It'd be a good idea to compress it with lz4 or zstd just like the initramfs.

Compression could be improved by sorting the files to be put into the initramfs by similarity.

**Comment by bertogg** [comment]
This is fixed in the _main_ channel (using zstd).
