### ISSUE TITLE
Unable to close apps added to Steam

### ISSUE THREAD

**Issue by unclejack** [ValveSoftware/SteamOS#942]
#### Your system information

* Steam client version: 1671676017
* SteamOS version: 3.4.2
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Closing an app such as Firefox by clicking the Steam "exit game" button doesn't work. It seemed to be an issue specific to Firefox at first. I noticed the same thing also happens with other apps. The app stays in "Exiting game..." forever.

The only way to close these apps so far has been with a SteamOS reboot. Starting a single app leads to this issue again, thus requiring a reboot again. Games also seem to be affected to some extent on 3.4.2.

Some apps don't exhibit this behavior. VLC seems to exit cleanly. I've run into this issue with some Steam games as well. The only fix so far has been a reboot.

The issue seems to be related to or made worse by starting two apps. I was able to get these apps to close just fine when starting a single app after switching to desktop mode and returning to game mode.

This is the kind of bug which makes me wonder if my Steam Deck has a hardware issue or if it's just a software bug.

The issues were observed on a vanilla installation of SteamOS without any changes made to the OS' partitions. Only flatpaks have been installed.

#### Steps for reproducing this issue:

1. If the Steam Deck is already on, reboot it to have a freshly booted OS. Power it on if it's not on.
2. While in game mode, start an app added to Steam
3. Try to close the running app by choosing exit game from the Steam menu
4. The app stays in "Exiting game..." forever

If the app/game is closed by choosing exit from the app/game, the Steam logo with the spinner is displayed forever. The abort game button is also shown in the corner. The abort game button (B) does nothing.

**Comment by kisak-valve** [comment]
Hello @unclejack, this issue is already being tracked at #897. Closing as a duplicate.
