### ISSUE TITLE
On-screen keyboard hiding itself when requested to be opened

### ISSUE THREAD

**Issue by james2432** [ValveSoftware/SteamOS#970]
#### Your system information

* Steam client version: 167461648
* SteamOS version: 3.4.5
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] Yes (Preview)
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.
In game on screen keyboard will open for a fraction of a second then hide itself after hitting steam+x
#### Steps for reproducing this issue:

1. Open game (Lord of the rings Online launcher in this case)
2. Go to password field
3. Steam+X
4. Keyboard shows up then automatically hides itself

**Comment by jakobi** [comment]
Confirming this issue as of jan24 beta (both os+client on beta channel):

https://steamcommunity.com/app/1675200/discussions/1/3757725715243181071/ seems to be about this bug, and shows a work around using the quick access key, which seems to cover all use cases incl. showing the keyboard on top vs bottom.

**Comment by OysterP** [comment]
+1
Just updated tonight and experienced it on two games I've tried it on so far.

**Comment by Diliz** [comment]
Experiencing this one as well on edge and chrome in latest betas (can't connect to GeForce now and Xbox cloud with this issue)

**Comment by james2432** [comment]
Fixed for me in Jan 27th update

**Comment by kisak-valve** [comment]
Closing per the last comment.
