### ISSUE TITLE
Update to Flatpak 1.12.7 or newer

### ISSUE THREAD

**Issue by tobiasjakobi** [ValveSoftware/SteamOS#981]
#### Your system information

* Steam client version: 1675222473
* SteamOS version: holo 3.4.4
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I'm using a dedicated audio system at home. This system exposes it's audio hardware via PulseAudio on the network. Any authenticated system can use the hardware by setting the `PULSE_SERVER` environment variable. I'd like the Deck to use my audio hardware as well, in particular when docked.

Current holo stable version 3.4.4 comes with flatpak 1.12.4. This flatpak version has a bug in that it doesn't implement forwarding `PULSE_SERVER`  into the flatpak container using standard overrides.

This bug was fixed in flatpak 1.12.7:
https://github.com/flatpak/flatpak/releases/tag/1.12.7

See this pull request and bug report for details:
https://github.com/flatpak/flatpak/pull/4705
https://github.com/flatpak/flatpak/issues/3908

So at the moment I need to apply some dirty flatpak workaround by replacing the run command with some shell code.

My expectation: This should work with standard flatpak mechanisms, like an override.
Current state: Overrides don't work because flatpak is too old

Solution: Upgrade flatpak from 1.12.4 to 1.12.7 (this should be unproblematic since we only increase the patch level here, so API breaks are not to be expected)

#### Steps for reproducing this issue:

1. Provide a network-accessible PulseAudio server on your local network, let's say `myserver.local`
2. Install a environment variable override (`PULSE_SERVER=tcp:myserver.local`) for a flatpak container that can use PulseAudio (like e.g. io.mpv.Mpv)
3. Notice that the envvar override never reaches the inside of the container (e.g. mpv still plays back on the local device)

**Comment by bertogg** [comment]
This is fixed in the _main_ channel.
