### ISSUE TITLE
Triple monitor dock not working on 6.x kernels

### ISSUE THREAD

**Issue by parkerlreed** [ValveSoftware/SteamOS#986]
#### Your system information

* Steam client version: 1676336721
* SteamOS version: 20230213.1000
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes - Main 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Triple monitor setup with ThinkPad 40AS dock completely broken on 6.x kernels.

The dock uses MST and DSC to enable all three. This worked fine on 5.13 but has been non-functional ever since Main updated to 6.x.

Sometimes two monitors will appear but after trying to activate the third, no output at all.

AMDGPU driver seems to repeatedly crash and eventually gives no output at all and am forced to hard power down.

Boot log 
[boot_log.txt](https://github.com/ValveSoftware/SteamOS/files/10736631/boot_log.txt)

#### Steps for reproducing this issue:

1. Plug in dock that uses MST and DSC
2. Observe behavior

**Comment by Alia5** [comment]
Can confirm, looks also good for me
(Again, Vanilla-Arch with some jupiter packages/ unsupported; But even then :))

**Comment by RodoMa92** [comment]
From 6.1.11 now it seems to be fixed, besides the integrated display backlight not turning off yet again when the integrated panel is disabled.

**Comment by kisak-valve** [comment]
Closing per the last several comments.
