### ISSUE TITLE
[Feature Request] Add clock to performance overlay

### ISSUE THREAD

**Issue by TeamLinux01** [ValveSoftware/SteamOS#994]
Please add a clock to performance overlay level 2 and higher.

I would like to see a setting that only displays FPS, Battery level and clock as well.

**Comment by RobertAdams313** [comment]
It would be even better if they added a custom option so you can pick and choose what you want to show.

**Comment by Pimlaio3** [comment]
I still can't add because there isn't a specific guide for this [io games](https://iogames.onl)
